sentry_sdk/client.py
sentry_sdk/stripping.py

Unclear:
- strip PII in relay exclusively? (yes)
- flag to disable truncation in sdk?
- truncating middle frames like in raven here as well?
- generally, what to truncate in sdk?

[wip] basic implementation of string truncation with metadata

---

tests/integrations/django/myapp/management/commands/mycrash.py
tests/integrations/django/myapp/settings.py
tests/integrations/django/test_basic.py
tests/integrations/flask/test_flask.py

test: add tests for flask and django management cli error handling

---

sentry_sdk/_compat.py
sentry_sdk/integrations/_wsgi.py
sentry_sdk/integrations/django.py
sentry_sdk/integrations/flask.py
tests/integrations/conftest.py
tests/integrations/django/myapp/settings.py
tests/integrations/django/test_basic.py
tests/integrations/flask/test_flask.py
tests/integrations/wsgi/test_wsgi.py
tox.ini

ref: Share code from Flask/Django with WSGI middleware

---

sentry_sdk/integrations/django.py
sentry_sdk/integrations/flask.py

Reduces the chance of leakage.

feat(django,flask): Use a weakref request for the django event processor

---

sentry_sdk/consts.py
sentry_sdk/hub.py
sentry_sdk/utils.py
tests/conftest.py
tests/test_client.py

feat: Add debug flag

---

Makefile
sentry_sdk/hub.py
sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/logging.py
sentry_sdk/transport.py
sentry_sdk/utils.py
tox.ini

This improves the debug logging support

ref: Refactored debug logging

---

sentry_sdk/hub.py
tests/test_basics.py

fix: Dont crash on breadcrumb overflow

---

sentry_sdk/integrations/_wsgi.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/transport.py
tests/integrations/aws_lambda/test_aws.py
tox.ini

feat: AWS lambda support

---

.travis.yml
scripts/runtox.sh
tox.ini

Don't overwrite coverage reports with each other

fix(build): Merge coverage reports

---

sentry_sdk/utils.py
tests/test_utils.py

fix: safe_repr for cyrillic

---

sentry_sdk/integrations/flask.py
sentry_sdk/integrations/sanic.py
tests/integrations/flask/test_flask.py
tests/integrations/sanic/test_sanic.py
tox.ini

support for older versions seems nontrivial. In particular testing against 0.7 just locks up

feat: Sanic integration

---

sentry_sdk/_compat.py
sentry_sdk/api.py
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/hub.py
sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/_wsgi.py
sentry_sdk/integrations/atexit.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/dedupe.py
sentry_sdk/integrations/django.py
sentry_sdk/integrations/excepthook.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/logging.py
sentry_sdk/integrations/modules.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/scope.py
tests/conftest.py
tests/test_basics.py

ref: Integration options now live on the client

---

sentry_sdk/integrations/sanic.py
tests/integrations/sanic/__init__.py
tests/integrations/sanic/test_sanic.py

fix: Fix concurrency issues in sanic

---

sentry_sdk/utils.py
tests/integrations/django/test_basic.py
tests/integrations/flask/test_flask.py
tests/test_event.py

fix: Rename meta key to _meta

---

sentry_sdk/integrations/_wsgi.py
sentry_sdk/integrations/pyramid.py
tests/integrations/flask/test_flask.py
tests/integrations/pyramid/__init__.py
tests/integrations/pyramid/test_pyramid.py
tox.ini

feat: Pyramid integration

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery.py

fix: Add celery args to extra

---

sentry_sdk/client.py

See https://github.com/getsentry/sentry-php/issues/688

fix: Strip release

---

sentry_sdk/consts.py
sentry_sdk/transport.py

feat: ca_certs option

---

sentry_sdk/integrations/_wsgi_common.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/pyramid.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/wsgi.py
tests/integrations/wsgi/test_wsgi.py

feat: WSGI Middleware

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/modules.py
sentry_sdk/integrations/pyramid.py
sentry_sdk/integrations/rq.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/tornado.py
sentry_sdk/integrations/wsgi.py
tests/test_basics.py

This is closer to how JS behaves. Should fix #200

ref: Event processors always overwrite

---

sentry_sdk/transport.py

Use like this:
```python
from sentry_sdk.transport import HTTPTransport
class CustomHTTPTransport(HTTPTransport):
def _get_pool_options(self, *args, **kwargs):
options = HTTPTransport._get_pool_options(self, *args, **kwargs)
options['cert_file'] = '...'
sentry_sdk.init(..., transport=CustomHTTPTransport)
```
This allows you to overwrite the entire urllib3 connection pool if you feel like it.

ref: Make HTTP transport extensible

---

sentry_sdk/utils.py
tests/test_client.py

Fix https://github.com/getsentry/sentry-python/issues/243

fix: Port exception chains from raven

---

sentry_sdk/integrations/flask.py

fix: Store Flask username

---

sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/threading.py
tests/integrations/threading/test_threading.py

feat: Threading integration

---

CONTRIBUTING.md
Makefile
scripts/aws-cleanup.sh
scripts/runtox.sh
sentry_sdk/scope.py
tests/integrations/aws_lambda/test_aws.py
tox.ini

Inspired by bruno's initiative on "getting started" docs I'm writing some for Python. Adding armin because he will likely have opinions about the makefile rewrite

doc: Contributing.md

---

scripts/runtox.sh
tests/integrations/tornado/test_tornado.py

@nickbaum you seem to know what you're doing. Can you recommend something to test Tornado apps with? This solution I have right now is working fine but it seems hard to maintain

ref: Do not use test classes for tornado tests

---

scripts/runtox.sh
sentry_sdk/integrations/tornado.py
tests/conftest.py
tests/integrations/tornado/test_tornado.py

feat: Tornado formdata

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/rq.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/serverless.py
sentry_sdk/integrations/tornado.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/scope.py
tests/integrations/pyramid/test_pyramid.py

fix: Clear breadcrumbs before new tx

---

.travis.yml
azure-pipelines.yml
scripts/download-semaphore.sh
scripts/runtox.sh
tests/integrations/django/myapp/settings.py

This doesn't replace all the Travis jobs we have at the moment, but it'll probably give a good overview of how Azure Pipelines behave.
Support for Python 3.8 and PyPy will be (hopefully) soon added to the base image: https://github.com/Microsoft/azure-pipelines-tasks/pull/9866

ci: Use Azure Pipelines

---

sentry_sdk/api.py
sentry_sdk/hub.py

Type hint fixes

---

sentry_sdk/transport.py

fix: Log response body in transport

---

sentry_sdk/client.py
sentry_sdk/utils.py
tests/test_client.py

fix: Add basic breadth trimming to databags

---

sentry_sdk/utils.py
tests/utils/test_general.py

fix: in_app_exclude does not work solo

---

sentry_sdk/integrations/django/__init__.py
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py
tox.ini

fix: Capture body of Django Rest Framework apps

---

sentry_sdk/integrations/logging.py

Fix for 'data' key in logger's extra

---

sentry_sdk/integrations/wsgi.py

fix: Honor X-Real-IP

---

sentry_sdk/_compat.py
sentry_sdk/consts.py
sentry_sdk/hub.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/scope.py
sentry_sdk/tracing.py
tests/integrations/celery/test_celery.py

This is the most basic hack I could come up with that gets us into the direction
of correlating errors.  It currently uses a made up `trace` context but i think
realistically speaking we probably want to use attributes for this.

feat(tracing): Initial tracing experiments

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery.py

fix(celery): Un-break usages of apply_async

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery.py

fix(celery): Fix RecursionError

---

sentry_sdk/integrations/_wsgi_common.py
sentry_sdk/integrations/wsgi.py

fix: Remove more headers containing IP addrs

---

sentry_sdk/integrations/django/__init__.py
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py

fix: Another attempt at getting DRF body data

---

sentry_sdk/utils.py
tests/integrations/pyramid/test_pyramid.py

fix: Deal with gevent patched thread locals

---

sentry_sdk/integrations/django/__init__.py
tests/integrations/django/myapp/settings.py
tests/integrations/django/test_basic.py

fix(django): Delay patching of DRF

---

pytest.ini
sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/flask.py
sentry_sdk/tracing.py
tests/__init__.py
tests/conftest.py
tests/integrations/flask/test_flask.py
tests/integrations/logging/test_logging.py

test: Treat warnings as errors

---

sentry_sdk/integrations/stdlib.py
tests/integrations/stdlib/test_subprocess.py

fix: Do not clear environment in subprocess integration

---

sentry_sdk/hub.py
sentry_sdk/tracing.py
tests/test_tracing.py

Fix #430
@reupen could you try this one out? I assume it will fix your problem but maybe your issue with 0.10 is something entirely else

fix: Better memory usage for tracing

---

sentry_sdk/integrations/logging.py

fix: Timezone bug in logging integration

---

sentry_sdk/client.py
tests/test_client.py

fix: Infinite recursion when capturing event during serialization

---

sentry_sdk/tracing.py

fix: Convert assertion into warning

---

sentry_sdk/integrations/stdlib.py
tests/integrations/stdlib/test_subprocess.py

Avoiding parsing arguments for now because that really backfired in the
past and it's probably not that useful.

feat(subprocess): Instrument more methods

---

sentry_sdk/integrations/asgi.py

fix: Do not attempt to access headers for all asgi requests

---

sentry_sdk/integrations/aiohttp.py

feat: Add trace propagation to aiohttp integration

---

sentry_sdk/integrations/django/middleware.py
tests/integrations/django/myapp/settings.py
tests/integrations/django/test_basic.py

fix: Fix crash on Django function-based middleware

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/asgi.py

fix: Make patched channels asgi app awaitable, fix integraton-disabled codepath

---

.travis.yml
sentry_sdk/utils.py
test-requirements.txt

It took me 10 minutes to find out what the problem was, so this adds a message for other users

fix: add an error message for a valueerror

---

tests/integrations/aws_lambda/test_aws.py

test: add tests for cw logs

---

sentry_sdk/integrations/logging.py
tests/test_transport.py

fix: Fix infinite loop in transport

---

sentry_sdk/hub.py
tests/test_basics.py

Fix bug in _update_scope()

---

sentry_sdk/integrations/pyramid.py
tox.ini

This is needed for APM and also fixes #683

fix(pyramid): Set transaction name eagerly

---

sentry_sdk/api.py

fix: Fix type annotation of capture-exception

---

sentry_sdk/integrations/redis.py
tests/integrations/rediscluster/__init__.py
tests/integrations/rediscluster/test_rediscluster.py
tox.ini

In addition to the redis and rb clients try to patch also the rediscluster library which does not use the already patched clients.

feat(redis): Patch rediscluster if present

---

mypy.ini
sentry_sdk/integrations/pure_eval.py
test-requirements.txt
tests/integrations/pure_eval/__init__.py
tests/integrations/pure_eval/test_pure_eval.py
tox.ini

Part of #748 
Redoing #750 from scratch using an integration. Wasn't worth rebasing from master.
There's a bunch of duplicate code between this and the executing integration that I'll refactor out after they both merge. Don't want to deal with it now, I'll get conflicts.

Extract additional expression values with pure_eval

---

setup.py

Add setup.py extra for pure_eval

---

sentry_sdk/integrations/django/middleware.py

fix(django): Patch __self__ onto middlewares

---

sentry_sdk/serializer.py
tests/test_serializer.py

fix: Serialize sets into JSON

---

.flake8

.flake8: Don't set --max-complexity if you don't care about code complexity

---

sentry_sdk/integrations/chalice.py
tox.ini

This is a suggestion fix for the chalice integration.

fix(chalice): Enable support for Chalice 1.20

---

tests/test_client.py

While working on adding tests for an other feature, I stumbled on those tests and found it hard to check which cases were tested among the 16 present tests.
Hopefully it's easier to read in the new version.

tests: parametrize proxy tests

---

.vscode/settings.json

VSCode can't seem to resolve the env without this.

fix(dev): Set VSCode Python path

---

sentry_sdk/client.py
sentry_sdk/utils.py

This now reads git info and a bunch of environment variables to determine
release information.  It also defaults the env to production if a release
is set.

feat: Automatically determine release and environment

---

sentry_sdk/integrations/pure_eval.py
tests/integrations/pure_eval/test_pure_eval.py

Use asttokens less to account for nodes that don't get position information

---

sentry_sdk/integrations/logging.py
tests/integrations/logging/test_logging.py

Fix https://github.com/getsentry/sentry-python/issues/904

fix: Handle exc_info=0

---

sentry_sdk/integrations/django/asgi.py

Fixes https://github.com/getsentry/sentry-python/issues/911

Fix patching of AsgiHandler in Django Channels >= 3.0

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py
tests/tracing/test_sampling.py

Things were already getting a bit unwieldy, and I'm about to add more tracing helpers, which would just make it worse.
No other changes besides moving stuff around.
(Tests aren't automatically running, I suppose because this is a PR to a branch rather than master, but I did run them locally, and all was good.)

chore(tracing): Split tracing utils into separate module

---

sentry_sdk/integrations/asgi.py

This pull requests decodes the headers before creating a transaction. See issue #983

Decode headers before creating transaction

---

CHANGELOG.md

Release: 0.20.2
- fix for Wheel file missing in PyPi release

release: 0.20.2

---

CHANGELOG.md

Release 0.20.3 
- Adds scripts that support auto instrumentation of no code AWS lambda python functions

release: 0.20.3

---

sentry_sdk/integrations/django/__init__.py

Use path_info instead of path

---

.github/workflows/ci.yml
CHANGELOG.md

In this PR,
- Added Change log for major release 1.0.0

Release: 1.0.0

---

setup.cfg
setup.py

Get rid of setup.cfg by moving the only option to setup.py

---

sentry_sdk/_types.py

Fixes getsentry/sentry-python#1090

Update traces_sampler declaration to concrete types

---

sentry_sdk/transport.py
sentry_sdk/worker.py

Introduce standard hook for capturing all events dropped within
transport

fix(transport): Unified hook for capturing metric about dropped events

---

sentry_sdk/integrations/httpx.py
setup.py
tests/integrations/httpx/__init__.py
tests/integrations/httpx/test_httpx.py
tox.ini

feat(integration): Add Httpx Integration

---

sentry_sdk/integrations/asgi.py
tests/integrations/asgi/test_asgi.py

Closes getsentry/sentry-python#1154

Add real ip detection to asgi integration

---

CHANGELOG.md
sentry_sdk/consts.py

This enables client reports out of the box.

feat: Turn on client reports by default

---

sentry_sdk/consts.py

Fix "shutdown_timeout" parameter typing

Fix "shutdown_timeout" typing

---

.github/workflows/jira.yml

Adds the JIRA integration to the WEBBACKEND project

chore: add JIRA integration

---

.github/workflows/ci.yml
CHANGELOG.md
docs/conf.py
sentry_sdk/consts.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/falcon.py
setup.py
test-requirements.txt
tests/integrations/django/myapp/custom_urls.py
tests/integrations/django/myapp/middleware.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py
tests/integrations/falcon/test_falcon.py
tox.ini

Adding Python 3.10 to our test suite
Refs GH-1273

build(tests): Python 3.10 support

---

CONTRIBUTING.md
README.md
tox.ini

- moved sections around for more clarity
- added some links 
- moved version policy to CONTRIBUTING.md
- Added "how to create a release" section.

Update contribution guide

---

.github/ISSUE_TEMPLATE/config.yml

----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.

chore(issues): add link to Sentry support

---

tox.ini

see 
https://github.com/dsoftwareinc/fakeredis-py/issues/3

chore(tests): Pin fakeredis<1.7.4

---

sentry_sdk/utils.py

Removed (unused) sentry_timestamp header

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/envelope.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/profiler.py
sentry_sdk/tracing.py

Changed the output data format for the profiler, and added ability for the profiler to send profiles to Sentry

Profiling new data format

---

mypy.ini
sentry_sdk/integrations/fastapi.py
sentry_sdk/integrations/starlette.py
setup.py

Some small changes inspired by Sebastian

Update to FastAPI

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/transactions.py
tests/integrations/django/test_basic.py
tests/integrations/django/test_transactions.py

Send correct "url" source if Django resolver fails to resolve

---

sentry_sdk/integrations/starlette.py

Fix typo in starlette attribute check

---

README.md

doc(readme): add Starlette and FastAPI links

---

sentry_sdk/profiler.py

Should always check if the transaction is sampled before deciding to profile to avoid profiling when it's not necessary.

fix(profiling): Check transaction sampled status before profiling

---

sentry_sdk/consts.py

fix(profiling): Profiler mode type hints

---

.github/workflows/ci.yml

Committed via https://github.com/asottile/all-repos

Update actions/upload-artifact to v3.1.1

---

sentry_sdk/consts.py
sentry_sdk/transport.py
tests/test_client.py

Expose proxy_headers as top level config and use in ProxyManager

---

sentry_sdk/integrations/sqlalchemy.py

Handle `"rc"` in SQLAlchemy version.

---

tox.ini

Remove sanic v22 pin

---

tox.ini

Sort all the integrations in tox.ini alphabetically to make it easier to find stuff in this too big file.

Sorted integrations alphabetically

---

docs-requirements.txt
linter-requirements.txt
sentry_sdk/tracing.py

Bringing some of our dependencies up to date.

Update test/linting dependencies

---

codecov.yml

Right now it is more annoying than helpful.

Removed code coverage target

---

sentry_sdk/integrations/asyncio.py
tests/integrations/asyncio/test_asyncio.py

Returning the tasks result.

---

sentry_sdk/tracing_utils_py2.py
sentry_sdk/tracing_utils_py3.py
tests/tracing/test_decorator_py2.py
tests/tracing/test_decorator_py3.py

Just better naming for some vars

Better naming

---

sentry_sdk/integrations/atexit.py

Fixes https://github.com/getsentry/sentry-python/issues/2027

Fix atexit message

---

tox.ini

See: https://github.com/pydantic/pydantic/issues/545

Pinned version of dependency that broke the build

---

sentry_sdk/integrations/huey.py
tests/integrations/huey/test_huey.py

fix(huey): Fix TaskLockedException handling

---

sentry_sdk/integrations/loguru.py
tests/integrations/loguru/test_loguru.py

More convenient setting message format.

feat(loguru): add message format configuration arguments

---

sentry_sdk/hub.py
sentry_sdk/scope.py
tests/integrations/flask/test_flask.py

Add "replay" context to event payload

---

CONTRIBUTING.md

Clarified the procedure for running tests

---

sentry_sdk/client.py
sentry_sdk/hub.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/tracing_utils.py
sentry_sdk/utils.py
tests/test_client.py
tests/test_utils.py
tests/tracing/test_misc.py

Resolves @sl0thentr0py's [comment](https://github.com/getsentry/sentry-python/pull/2297/files#r1288387953) on a previous PR

Moved is_sentry_url to utils

---

scripts/runtox.sh
sentry_sdk/integrations/django/__init__.py
tests/integrations/django/test_basic.py
tests/integrations/threading/test_threading.py

... and not the db. (On Mysql and SQLite this is unfortunately not possible because not exposed by the client libs)
Fixes #2303

In Postgres take the connection params from the connection 

---

sentry_sdk/integrations/_asgi_common.py

Don't fail when upstream scheme is unusual

---

docs/api.rst
docs/apidocs.rst
docs/index.rst
docs/integrations.rst

List user facing functions and also have a list of most used classes.

Updated Apidocs

---

sentry_sdk/integrations/rq.py

RQ changed how the set jobs to failed. Dealing with this.

---

sentry_sdk/tracing_utils.py

Use in app filepath instead of absolute path

---

sentry_sdk/integrations/django/__init__.py

Context: https://github.com/getsentry/sentry-python/issues/2551#issuecomment-1853878170
Closes https://github.com/getsentry/sentry-python/issues/2551

fix(django): Fix psycopg2 detection

---

CHANGELOG.md
docs/conf.py
sentry_sdk/consts.py
sentry_sdk/integrations/opentelemetry/span_processor.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py
setup.py
tests/integrations/asyncpg/test_asyncpg.py
tests/integrations/django/test_db_query_data.py
tests/integrations/opentelemetry/test_span_processor.py
tests/integrations/sqlalchemy/test_sqlalchemy.py

Periodically merging `master` into `sentry-sdk-2.0`.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before …

Sync `sentry-sdk-2.0` with `master`

---

CHANGELOG.md
docs/conf.py
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/integrations/gcp.py
sentry_sdk/metrics.py
sentry_sdk/tracing_utils.py
sentry_sdk/utils.py
setup.py
tests/integrations/asyncpg/test_asyncpg.py
tests/integrations/django/test_db_query_data.py
tests/integrations/sqlalchemy/test_sqlalchemy.py
tests/test_metrics.py
tests/test_profiler.py
tests/test_utils.py
tests/utils/test_general.py

Merge master to sentry-sdk-2.0

---

CHANGELOG.md
docs/conf.py
sentry_sdk/consts.py
sentry_sdk/integrations/pyramid.py
setup.py
tests/integrations/aws_lambda/client.py
tests/integrations/aws_lambda/test_aws.py
tests/integrations/threading/test_threading.py
tox.ini

Sync with main branch

---

.craft.yml

Fixed regex to parse version in lambda package file

---

tests/tracing/test_decorator.py

Fork `test_tracedecorator_async`

---

sentry_sdk/client.py

ref: Remove unnecessary try/except for `collections.abc` import

---

sentry_sdk/integrations/clickhouse_driver.py
sentry_sdk/integrations/pymongo.py

Speedrunning through the remaining integrations 🏃🏻‍♀️  
Closes https://github.com/getsentry/sentry-python/issues/2815
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our …

ref(integrations): Use new scopes API in pymongo, clickhouse integration

---

sentry_sdk/integrations/flask.py
tests/integrations/flask/test_flask.py

Speedrunning through the remaining integrations 🏃🏻‍♀️
Closes https://github.com/getsentry/sentry-python/issues/2811
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our …

ref(flask): Use new scopes API in Flask

---

sentry_sdk/types.py

To make strict mypy setups of our customers happy.

Explicit reexport of types

---

sentry_sdk/integrations/bottle.py

Relates https://github.com/getsentry/sentry-python/issues/2812
--- …

ref(bottle): Use new scopes API

---

sentry_sdk/integrations/pyramid.py

Relates https://github.com/getsentry/sentry-python/issues/2812
--- …

ref(pyramid): Use new scopes API

---

sentry_sdk/integrations/spark/spark_driver.py
sentry_sdk/integrations/spark/spark_worker.py

ref(spark): Use new scopes API

---

sentry_sdk/integrations/trytond.py

ref(trytond): Use new scopes API

---

sentry_sdk/integrations/gcp.py

ref(gcp): Use new scopes API

---

sentry_sdk/integrations/chalice.py

ref(chalice): Use new scopes API

---

sentry_sdk/integrations/grpc/aio/client.py
sentry_sdk/integrations/grpc/aio/server.py
sentry_sdk/integrations/grpc/client.py
sentry_sdk/integrations/grpc/server.py
tests/integrations/grpc/test_grpc.py

ref(grpc): Use new scopes API

---

sentry_sdk/integrations/_wsgi_common.py

ref(wsgi): Use new scopes API

---

sentry_sdk/integrations/asyncio.py

ref(asyncio): Use new scopes API

---

sentry_sdk/integrations/executing.py

ref(executing): Use new scopes API

---

sentry_sdk/integrations/serverless.py
tests/integrations/serverless/test_serverless.py

ref(serverless): Use new scopes API

---

tests/integrations/sqlalchemy/test_sqlalchemy.py

ref(sqlalchemy): Use new scopes API in tests

---

sentry_sdk/tracing.py

ref https://github.com/getsentry/sentry-docs/issues/5082

docs: Document arguments for `Span`

---

sentry_sdk/crons/decorator.py
tests/test_crons.py

Sync 2.0 with `master`

---

CHANGELOG.md
CONTRIBUTING.md
codecov.yml
devenv-requirements.txt
sentry_sdk/_types.py
sentry_sdk/consts.py
sentry_sdk/crons/api.py
sentry_sdk/crons/decorator.py
sentry_sdk/envelope.py
sentry_sdk/integrations/celery/beat.py
sentry_sdk/integrations/celery/utils.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/signals_handlers.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/strawberry.py
sentry_sdk/metrics.py
sentry_sdk/profiler.py
sentry_sdk/transport.py
sentry_sdk/utils.py
tests/integrations/django/myapp/signals.py
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py
tests/integrations/strawberry/test_strawberry.py
tests/test_metrics.py
tests/test_transport.py

Sync `2.0` with `master`

---

sentry_sdk/metrics.py

ref(metrics): Fix comment typo

---

scripts/runtox.sh
tests/integrations/celery/test_celery.py

Might make stuff slightly faster.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before running sensitive …

feat(tests): Parallelize tox

---

sentry_sdk/ai/monitoring.py

This functionality was requested by early users of the AI monitoring feature.

Add tags + data passing functionality to @ai_track

---

setup.py

Fixed grpcio extras to work as described in the docs

---

tests/integrations/langchain/test_langchain.py
tox.ini

Updated deps for latest langchain version

---

README.md

Give kudos to our amazing contributors!
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before running …

Added contributor image to readme

---

.github/workflows/test-integrations-ai.yml
scripts/split-tox-gh-actions/split-tox-gh-actions.py

Separating our AI integrations from the Data Processing group into their own group.

ref(ci): Create a separate test group for AI

---

tox.ini

tests: Test with Django 5.1 RC

---

sentry_sdk/api.py
sentry_sdk/integrations/asgi.py
sentry_sdk/integrations/opentelemetry/potel_span_processor.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/scope.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py

Centralize the default case, external APIs just take it optionally.

Cleanup origin handling and defaults

---

.coveragerc36

Fixed config for old coverage versions

---

sentry_sdk/tracing.py

This should be the correct version (if we have no security release until next week :-) )

Fixed deprecation message

---

tox.ini

pyspark 4.0.0dev2 is available. Test with it.

tests: Test with pyspark prerelease

---

MIGRATION_GUIDE.md
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/gcp.py
tests/integrations/gcp/test_gcp.py

* add initial span attrs and get rid of custom sampling context
* add one extra span attr to aws too
* update tests

Use span attrs in GCP sampling context

---

tox.ini

Run `generate-test-files.sh` (this will be automated at some point)

chore(tests): Regenerate tox.ini

---

tox.ini

feat(tests): Update tox.ini

---

.github/CODEOWNERS

meta: Add CODEOWNERS

---

CHANGELOG.md

fixed code snippet

---

scripts/populate_tox/populate_tox.py
tox.ini

- try to refetch data if PyPI returns an error
- if we fail after 3 tries, fail the whole script (it doesn't make sense to run it without access to up-to-date PyPI data)

toxgen: Retry & fail if we fail to fetch PyPI data

---

sentry_sdk/integrations/logging.py

The way the code was written before this change made it look like log records from the `warnings` module were always being handled by a separate code path. In fact, this separate path is only used for Python 3.10 and below.
This change makes it clear that the branch is version specific. That way, when we eventually stop supporting 3.10, it is clear that we can delete this separate block.
Depends on:
- #4292
- #4291

ref(logging): Clarify separate warnings case is for Python <3.11

---

tox.ini

tests: Update tox.ini

---

docs/conf.py
sentry_sdk/consts.py
setup.py

For testing purposes I set the next major version of the SDK.

Set SDK version

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/boto3.py
sentry_sdk/integrations/httpx.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/tracing.py
sentry_sdk/utils.py

Add thread info to HTTP breadcrumbs

---

requirements-docs.txt

Underlying issue fixed upstream

apidocs: Remove snowballstemmer pin

---

sentry_sdk/consts.py
tests/integrations/aws_lambda/utils.py

CI failures are unrelated, I'm fixing them elsewhere

fix(typing): Add before_send_log to Experiments

---

tox.ini

tests: Regenerate toxgen

---

tests/test_client.py

don't think this one is needed at all
part of #4538

Remove forked marker in client uwsgi test

---

sentry_sdk/utils.py

fix: Fix `abs_path` bug in `serialize_frame`

---

tox.ini

tests: tox.ini update

---

.github/workflows/test-integrations-ai.yml
.github/workflows/test-integrations-cloud.yml
.github/workflows/test-integrations-common.yml
.github/workflows/test-integrations-dbs.yml
.github/workflows/test-integrations-flags.yml
.github/workflows/test-integrations-gevent.yml
.github/workflows/test-integrations-graphql.yml
.github/workflows/test-integrations-misc.yml
.github/workflows/test-integrations-network.yml
.github/workflows/test-integrations-tasks.yml
.github/workflows/test-integrations-web-1.yml
.github/workflows/test-integrations-web-2.yml
scripts/split_tox_gh_actions/templates/test_group.jinja

was deprecated
https://github.com/codecov/codecov-action?tab=readme-ov-file#migration-guide

Fix plugins key codecov
