getsentry/sentry-python

sentry_sdk/integrations/_wsgi.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/flask.py
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py
tests/integrations/flask/test_flask.py

feat: PoC for data_info field

---

sentry_sdk/client.py
sentry_sdk/transport.py
tests/test_client.py

Main issue was that we didn't wait n seconds until the the task queue was worked off, but more or less exactly until the last item was popped (but there was still code afterwards)
Other than that this seems to work: Set drain_timeout up to 10 seconds, install a proxy that will make your request timeout and you will see.

feat: register atexit handler

---

sentry_sdk/_compat.py
sentry_sdk/api.py
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/hub.py
sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/atexit.py
sentry_sdk/scope.py
sentry_sdk/transport.py
sentry_sdk/utils.py
sentry_sdk/worker.py
tests/conftest.py
tests/integrations/excepthook/test_excepthook.py
tests/test_client.py

This uses the same logic as the old raven python background worker which is to block in the atexit running thread on the lock the background worker has. This way the demon thread can be kept alive a while longer to orderly start the shutdown.

ref: Use atexit only in init

---

sentry_sdk/transport.py
sentry_sdk/worker.py

This solves the case where joining on a thread can have bad consequences on shutdown. If shutdown is disabled with wait 0 it doesn't try to do anything crazy now.

feat: Disable thread joining on transport shutdown if timeout is 0

---

sentry_sdk/__init__.py
sentry_sdk/api.py
sentry_sdk/client.py
sentry_sdk/debug.py
sentry_sdk/hub.py
sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/_wsgi.py
sentry_sdk/integrations/atexit.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/dedupe.py
sentry_sdk/integrations/django.py
sentry_sdk/integrations/excepthook.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/logging.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/scope.py
sentry_sdk/transport.py
sentry_sdk/utils.py
sentry_sdk/worker.py

This cleans up imports and debug logging slightly.  This is mostly done for consistency
and because I had circular import errors in a PR i'm working on.

feat: refactored debug logging and imports

---

.craft.yml
.gitignore
.travis.yml
Makefile
README.md

...so they can later be published by "craft".

docs: Build docs on Travis

---

.craft.yml

@untitaker Before the next release, please check that your `craft` version is at least `0.5.1`.

ci: Add "registry" target to Craft config

---

sentry_sdk/client.py
sentry_sdk/consts.py

The attribute is unused by Sentry.

ref: Remove repos interface

---

sentry_sdk/utils.py
tests/test_utils.py

Raven behavior for comparison: https://github.com/getsentry/raven-python/blob/719be9afae528962e683d086f9c2ceeda07f881b/raven/utils/stacks.py#L275-L282

fix: Make filename relative to sys.path

---

sentry_sdk/integrations/aws_lambda.py

The call to logger.warn causes `DeprecationWarning` when not running in an AWS environment (e.g. local testing environments). `logger.warning` has always been the preferred and documented logger method, and in Python 3.3 and above, `logger.warn` is deprecated.

changed logger.warn to logger.warning to remove DeprecationWarning

---

MANIFEST.in
README.md

- Used a MANIFEST.in file to include the LICENSE file in PyPI sdist, as required by the BSD license.
- Corrected README to say BSD not MIT, so it matches the LICENSE file and setup.py.

Include LICENSE in sdist and clarify in README

---

sentry_sdk/hub.py
tests/test_basics.py

fix: Dont crash when client is bound inside of push_scope

---

sentry_sdk/integrations/logging.py
tests/integrations/logging/test_logging.py

In Raven, you could do this:
```
logger.warning('things happened', extra={'stack': True})
```
And the stack would be collected. This adds back that feature.

Add the stack option back to the Logging integration

---

sentry_sdk/integrations/aiohttp.py
tests/integrations/aiohttp/__init__.py
tests/integrations/aiohttp/conftest.py
tests/integrations/aiohttp/test_aiohttp.py
tox.ini

feat: aiohttp-server integration

---

sentry_sdk/_compat.py
sentry_sdk/integrations/wsgi.py
tests/integrations/conftest.py
tests/integrations/django/test_basic.py
tests/integrations/flask/test_flask.py
tests/integrations/wsgi/test_wsgi.py

This will make WSGI apps more tolerant against:
* WSGI servers streaming responses from a different thread/from different threads than the one that called `start_response`
* `close` not being called
* WSGI servers streaming responses interleaved from the same thread
I have no idea or opinion about performance impact but I don't think it's much?

fix: Push scope for each response chunk

---

sentry_sdk/client.py
sentry_sdk/integrations/pyramid.py
sentry_sdk/scope.py
tests/integrations/pyramid/test_pyramid.py

fixes https://github.com/getsentry/sentry-python/issues/208
I think this is the simplest and most comprehensive fix but let me know what you think.
I looked at fixing it directly in `capture_internal_exceptions` but it felt super awkward. It looked like this, with the import inside to avoid recursive imports between `utils.py` and `hub.py`. This PR does not suffer from that issue and will only avoid creating events while processing one.
```diff
diff --git a/sentry_sdk/utils.py b/sentry_sdk/utils.py
index 6388f96..fadd4bc 100644
--- a/sentry_sdk/utils.py
+++ b/sentry_sdk/utils.py
@@ -39,12 +39,24 @@ def _get_debug_hub():
@contextmanager
def capture_internal_exceptions():
+    from .api import configure_scope
+
+    # avoid any code inside generating new events
+    with configure_scope() …
```

fix event recursion

---

sentry_sdk/utils.py
tests/integrations/django/myapp/views.py

Fixes #238
Not sure if this is the best way to show it, i think it is better than showing just empty list. But maybe there could be some better way to show that exception occured during traversal.
There is more general problem that it is probably good to not iterate over queryset, so DB is not queried. Any ideas on how to do that?

Handle iteration errors during frame traversal

---

sentry_sdk/integrations/tornado.py
tox.ini

Tornado 6 will remove old coroutine support in respect to standard async/await syntax.
Current TornadoIntegration is not working with Tornado 6 (current alpha release is 6.0a1):
```
[D 190129 13:19:21 logger:68] Started GET /status
/Users/belk/.venv/lib/python3.7/site-packages/sentry_sdk/integrations/tornado.py:57: RuntimeWarning: coroutine 'RequestHandler._execute' was never awaited
result = yield from old_execute(self, *args, **kwargs)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[E 190129 13:19:21 base_events:1608] Exception in callback _HandlerDelegate.execute.<locals>.<lambda>(<Future finis...e generator")>) at /Users/belk/.venv/lib/python3.7/site-packages/tornado/web.py:2329
handle: <Handle _HandlerDelegate.execute.<locals>.<lambda>(<Future finis...e …
```

Add tornado 6 support

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery.py
tox.ini

fix: Ignore Celery's retry exceptions

---

sentry_sdk/integrations/aiohttp.py
tests/integrations/aiohttp/test_aiohttp.py

The replaced _handle method of aiohttp.web.Application is a coroutine
itself. So it has to await the call to the original handle otherwise its
never awaited.
This fixes #260
Signed-off-by: Jan Losinski <losinski@wh2.tu-dresden.de>

Add missing await in AioHttpIntegration.

---

sentry_sdk/client.py
sentry_sdk/integrations/logging.py
tests/test_client.py

Currently, `sentry_sdk` is ignoring the `with_locals` option when collecting stacktrace info.
This makes events collect local variables, which in our case creates huge events which are dropped by sentry.
This PR passes the client options to `current_stacktrace` to avoid the problem.
Related to #268

Stacktrace: Pass with_locals parameter.

---

sentry_sdk/integrations/_wsgi_common.py
tests/integrations/flask/test_flask.py
tests/integrations/pyramid/test_pyramid.py

It should be evaluated as empty JSON object/array
Note that according to RFC 4627 top level elements can be empty objects or arrays

fix: Wsgi - valid JSONs ([], {}) are evaluated as raw data

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/gnu_backtrace.py
tests/integrations/test_gnu_backtrace.py

Value proposition: ClickHouse sends us error messages with stacktrace information. Ideally we would parse this stacktrace information into actual stacktraces. Here is an integration for exactly that. The testcase is ripped straight from https://sentry.io/organizations/sentry/issues/856036064
ClickHouse calls [`backtrace_symbols`](https://linux.die.net/man/3/backtrace_symbols). It already returns a formatted string/list of strings. ClickHouse then parses this string and [replaces symbols with demangled versions](https://github.com/yandex/ClickHouse/blob/1e22b308d9cd974803920c90d968ca89ad36c84f/dbms/src/Common/StackTrace.cpp). I didn't bother with parsing addresses and offsets as I don't see much value in that information (not sure if it's used in grouping) and some of those return …

feat: Add integration for parsing GNU-style backtrace dumps

---

Makefile
sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/sanic.py
sentry_sdk/utils.py
test-requirements.txt
tests/integrations/aiohttp/test_aiohttp.py
tests/integrations/sanic/test_sanic.py
tox.ini

Ok, found a workaround for [this](https://github.com/getsentry/sentry-python/issues/289) issue. All tests are passed for py3.7 and py3.6.

use contextvars backport for aiohttp and sanic support in py3.6

---

sentry_sdk/integrations/celery.py
tests/conftest.py
tests/integrations/celery/test_celery.py
tests/integrations/rq/test_rq.py

Patch celery such that it flushes the client when shutting down a worker.
Fix #285

fix(celery): flush queue on worker exit

---

sentry_sdk/utils.py
tests/integrations/wsgi/test_wsgi.py

* affects only python3 because items() in python3 doesn't return list
* note that this situation is actually a simplified example how environ is treated in Bottle framework

fix: `RuntimeError: dictionary changed size during iteration` raised within extract_locals

---

sentry_sdk/integrations/bottle.py
tests/integrations/bottle/test_bottle.py
tox.ini

I found out that a sentry record is created when a Bottle redirect is performed.
This MR should fix that.
I also included a small tox.ini update.

Bottle redirect fix

---

sentry_sdk/integrations/django/__init__.py
tests/integrations/django/test_basic.py

fix(django/sql): Run cursor.mogrify as fallback to regular formatting

---

sentry_sdk/integrations/__init__.py

fix: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str' when Python with -O flag
ref #327

fix: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'str' when Python with -O flag

---

sentry_sdk/integrations/falcon.py
setup.py
tests/integrations/falcon/test_falcon.py
tox.ini

Adds support for the [Falcon web framework](https://github.com/falconry/falcon). Any feedback or suggestions would be greatly appreciated.

feat(integration): Add Falcon integration

---

sentry_sdk/integrations/celery.py

fix: Ignore Celery exceptions used for control flow

---

CHANGES.md
sentry_sdk/integrations/excepthook.py
tests/integrations/excepthook/test_excepthook.py

```
from sentry_sdk.integrations.excepthook import ExcepthookIntegration
'https...',
integrations=[ExcepthookIntegration(always_run=True)]
)
```
Fix https://github.com/getsentry/sentry-python/issues/360

Added the always_run option in excepthook integration

---

sentry_sdk/integrations/wsgi.py
tests/integrations/wsgi/test_wsgi.py

Neither SystemExit nor KeyboardInterrupt subclass Exception, so we must
explicitly handle these two exception classes in addition to Exception in the
WSGI middleware.
This is notably a direct port from raven-python:
- https://github.com/getsentry/raven-python/blob/master/raven/middleware.py
- https://github.com/getsentry/raven-python/blob/master/tests/middleware/tests.py
Fixes: GH-379
There are notably 3 places an exception could be raised, but it looks like we're only
testing one case. If we want to test the other two, would appreciate advice 🙏🏾.

fix(wsgi): Log SystemExit (with non-zero exit code) and KeyboardInterrupt

---

sentry_sdk/integrations/pyramid.py
tests/integrations/pyramid/test_pyramid.py

ref(pyramid): Errorhandlers now swallow events

---

MANIFEST.in
setup.py

The `typedpkg` example in the PEP is a little misleading unfortunately.
I tested that it is now properly included and properly picked up by mypy.

Fix py.typed not being included in distribution

---

sentry_sdk/utils.py

fix: Honor __tracebackhide__ even if frame has name

---

examples/basic.py
mypy.ini
sentry_sdk/api.py
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/debug.py
sentry_sdk/hub.py
sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/atexit.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/bottle.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/excepthook.py
sentry_sdk/integrations/falcon.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/gnu_backtrace.py
sentry_sdk/integrations/pyramid.py
sentry_sdk/integrations/rq.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/threading.py
sentry_sdk/integrations/tornado.py
sentry_sdk/scope.py
sentry_sdk/serializer.py
sentry_sdk/transport.py
sentry_sdk/utils.py
tox.ini

The first commit fixes #386.
The second commit is a bug fix that mypy found.
The third commit adds a basic example as requested in https://github.com/getsentry/sentry-python/issues/386#issuecomment-499010982.
The fourth commit improves the typings a bit by enabling some more strict mypy options and fixing the errors. I imagine it's quite hard to review so I can leave it off if that's preferable.

Improve typings some

---

sentry_sdk/integrations/logging.py

Using this function will block regular event recording as well as breadcrumb recording.

fix(docs): Fix docstring in `ignore_logger`

---

sentry_sdk/integrations/celery.py

I have not tested this change but did something similar that the existing typing in `DjangoIntegration`.

Add typings for CeleryIntegration.__init__

---

sentry_sdk/utils.py

Replace some Anys with proper types.

feat: Improve type annotations in utils.py

---

CHANGES.md

Not a lot of Python projects seem to have this because everybody just
assumes semver until stuff starts breaking.

doc: Have a versioning policy

---

sentry_sdk/integrations/logging.py
tests/integrations/logging/test_logging.py

If I pass dict with int keys in extra keyword argument
```
logger.warning('test', extra={1:1})
```
I'll get an exception and event will not be sent.

fix: Allow int keys in extra dict

---

tests/integrations/django/myapp/asgi.py
tests/integrations/django/myapp/manage.py
tests/integrations/django/myapp/routing.py
tests/integrations/django/myapp/settings.py
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/myapp/wsgi.py

See #419 
Needs a test that invokes the ASGI app. We should pull sentry-asgi into here as well.

[wip] test: Add Django channels to Django example app

---

sentry_sdk/integrations/asgi.py
tests/conftest.py
tests/integrations/asgi/__init__.py
tests/integrations/asgi/test_asgi.py
tests/integrations/django/channels/__init__.py
tests/integrations/django/channels/test_channels.py
tests/integrations/django/myapp/asgi.py
tests/integrations/django/test_channels.py
tox.ini

Diff to sentry-asgi:
<details><summary>click me</summary>
```diff
diff --git a/../sentry-asgi/sentry_asgi/middleware.py b/sentry_sdk/integrations/asgi.py
index 37d1117..4c40750 100644
--- a/../sentry-asgi/sentry_asgi/middleware.py
+++ b/sentry_sdk/integrations/asgi.py
@@ -1,35 +1,44 @@
import functools
import urllib
-import sentry_sdk
-from sentry_sdk.utils import event_from_exception, exc_info_from_error
+from sentry_sdk._types import MYPY
+from sentry_sdk.hub import Hub, _should_send_default_pii
+from sentry_sdk.integrations._wsgi_common import _filter_headers
+from sentry_sdk.utils import transaction_from_function
+if MYPY:
+    from typing import Dict
+
+
+class SentryAsgiMiddleware:
+    __slots__ = ("app",)
-class SentryMiddleware:
def __init__(self, app):
self.app = app
async def …
```

feat: ASGI middleware

---

sentry_sdk/integrations/celery.py

fix(celery): Add functools.wraps to wrapped Task methods

---

sentry_sdk/consts.py
sentry_sdk/integrations/logging.py

The sdk supports disabling the LoggingIntegration by passing `None` as
arguments; however, the current types require ints.
This behavior is noted in the docs:
https://docs.sentry.io/platforms/python/logging/#options
```
sentry_sdk.init(integrations=[LoggingIntegration(level=None, event_level=None)])
```
edit: when adding `# type: ignore` I found a second issue with the argument `integrations` which mypy recommended as typing as `Sequence` instead of `List`. This fixed the type error.

fix: types for logging integration args

---

sentry_sdk/utils.py
test-requirements.txt
tests/utils/test_contextvars.py

The `_` in `_threading` seems like a mistake and always returns False.
Removing it leads to the detection working properly:
```py
Python 3.7.4 (default, Jul 16 2019, 07:12:58)
[GCC 9.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gevent.monkey
>>> gevent.monkey.is_object_patched('_threading', 'local')
False
>>> gevent.monkey.is_object_patched('threading', 'local')
False
>>> gevent.monkey.patch_all()
True
>>> gevent.monkey.is_object_patched('_threading', 'local')
False
>>> gevent.monkey.is_object_patched('threading', 'local')
True
```

Fix detection of gevent threading.local monkey-patch

---

sentry_sdk/integrations/threading.py
tests/integrations/threading/test_threading.py

Fixes #423 
According to the [Python Data Model](https://docs.python.org/3.7/reference/datamodel.html?#index-35), the code below will cause a reference cycle between  `__self__` and `__dict__`.
```
class Test:
def start(self, *a, **kw):
self.run()
def run(self):
...
old_start = Test.start
def _wrap_run(old_run):
def run(*a, **kw):
result = old_run(*a, **kw)
return result
return run
def test_start(self, *a, **kw):
self.run = _wrap_run(self.run)
return old_start(self, *a, **kw) 
Test.start = test_start
if __name__ == "__main__":
tmp = Test()
tmp.start()
```
The references graph like this::
Meantime [Python Standard Library - concurrent.futures](https://github.com/python/cpython/blob/3.7/Lib/concurrent/futures/process.py#L584) used thread to manage tasks queue, therefore when sentry patched …

:bug: [#423] fix reference cycle

---

sentry_sdk/integrations/stdlib.py
tests/integrations/stdlib/test_subprocess.py

Parsing args and kwargs like that seems like a rabbit hole, but there's no other way to instrument this that I am aware of.
Fix #436.

fix: Fix a bunch of bugs in subprocess integration

---

sentry_sdk/utils.py

fix: Remove duplicate function

---

.travis.yml
sentry_sdk/integrations/beam.py
tests/integrations/beam/test_beam.py
tox.ini

Beam integration requires #439. New files include `beam.py`, `test_beam.py` and test additions to tox.

Beam integration

---

sentry_sdk/hub.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/tracing.py
tests/integrations/celery/test_celery.py
tests/integrations/flask/test_flask.py
tests/integrations/redis/test_redis.py
tests/test_tracing.py

* Add indicator of failed transactions for both celery and wsgi. This is a context field that will later be promoted as tag or somehow indexed separately.
* Rename `error: bool` to `status: str`

feat: Add status to transactions

---

tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py

test(django): Add tests for permission denied handling

---

sentry_sdk/worker.py
test-requirements.txt
tests/conftest.py
tests/test_transport.py
tests/utils/test_contextvars.py

fix(transport): Detect eventlet's Queue monkeypatch and work around it

---

sentry_sdk/integrations/redis.py
sentry_sdk/tracing.py
tests/integrations/redis/test_redis.py
tests/integrations/stdlib/test_subprocess.py

fix: Add breadcrumb description

---

sentry_sdk/integrations/beam.py
tox.ini

https://getsentry.atlassian.net/browse/SFD-14
This patch fixes the previously disabled beam tests. Running the tests with beam v2.12 and v2.13 was seen to be fine, the tests were experiencing issues with `beam-master`.
```
tests/integrations/beam/test_beam.py:182: in test_invoker_normal
invoker = init_beam(fn)
tests/integrations/beam/test_beam.py:169: in inner
pardo = ParDo(fn)
sentry_sdk/integrations/beam.py:60: in sentry_init_pardo
old_init(self, fn, *args, **kwargs)
.tox/py3.7-beam-master/lib/python3.7/site-packages/apache_beam/transforms/core.py:1117: in __init__
self._signature = DoFnSignature(self.fn)
.tox/py3.7-beam-master/lib/python3.7/site-packages/apache_beam/runners/common.py:232: in __init__
self.process_method = MethodWrapper(do_fn, 'process') …
```

fix: Beam Integration Tests 

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/middleware.py
tests/integrations/django/test_basic.py

feat: Spans for Django middleware calls

---

sentry_sdk/integrations/asgi.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/scope.py
tests/integrations/django/channels/test_channels.py
tests/integrations/django/myapp/asgi.py

feat: Automatically instrument ASGI HTTP requests in Django Channels

---

sentry_sdk/consts.py
sentry_sdk/hub.py
sentry_sdk/tracing.py
tests/integrations/django/test_basic.py
tests/integrations/sqlalchemy/test_sqlalchemy.py
tests/test_tracing.py

We have memory usage issues for very large queries, because large params are held in memory (spans or breadcrumb buffer). Do not capture SQL params for now.

fix: Do not capture SQL params for now

---

sentry_sdk/serializer.py

Refactor MetaNode and merge it into Serializer. 40% speedup for some
random microbenchmark, lol

ref(serializer): Make trimming faster by a few ms

---

sentry_sdk/hub.py
sentry_sdk/integrations/_wsgi_common.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/logging.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/tracing.py
tests/conftest.py
tests/integrations/bottle/test_bottle.py
tests/integrations/celery/test_celery.py
tests/integrations/django/test_basic.py
tests/integrations/falcon/test_falcon.py
tests/integrations/flask/test_flask.py
tests/integrations/pyramid/test_pyramid.py
tests/integrations/stdlib/test_httplib.py
tests/integrations/stdlib/test_subprocess.py
tests/test_tracing.py

fix: Actually run tests for fast_serialize

---

sentry_sdk/integrations/aiohttp.py
tests/integrations/aiohttp/test_aiohttp.py

Partially fixes https://github.com/getsentry/sentry-python/issues/220
In case if the request body has been read at least once, we have it in the `request._read_bytes` attribute. It allows us simply access it from non-async code.

feat: aiohttp request body

---

sentry_sdk/serializer.py
sentry_sdk/utils.py
tests/test_serializer.py
tests/utils/test_general.py

Fixes #550
The serializer was returning lists of integers when attempting to serialize `bytes`. On top of that, the behavior of `sentry_sdk.utils.safe_repr` was decoding non-printable characters, and generally not behaving as expected. 
Both issues were fixed for Python 3. `safe_repr` still has the bug in Python 2, but the solution for that will not be straightforward.

Fixed the serialization of byte-string objects in Python 3

---

sentry_sdk/integrations/tornado.py
tests/integrations/tornado/test_tornado.py

fix: Do not unnecessarily ignore tornado.application logger

---

sentry_sdk/integrations/asgi.py

fix: Make ASGI middleware inspectable for ASGI version

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/asgi.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/tracing.py
tests/integrations/celery/test_celery.py
tests/integrations/flask/test_flask.py
tests/test_tracing.py

schema def here: https://github.com/getsentry/semaphore/pull/326

ref: Update transaction status to match final protocol

---

sentry_sdk/integrations/logging.py
sentry_sdk/serializer.py
sentry_sdk/tracing.py

Please answer question in [Issue 567](https://github.com/getsentry/sentry-python/issues/567) to fix failing tests

fix skipped None

---

sentry_sdk/tracing.py
tests/test_tracing.py

Correction based on what I see on the JS SDK:
https://github.com/getsentry/sentry-javascript/blob/01cac4ff6c09d7cf4b5e9d6cf595b095a8d036f3/packages/apm/src/span.ts#L202-L207
------
The incorrect mapping (red arrows) I found from my local development. The blue arrow is the supposedly correct mapping.

fix(apm): Continuation of a trace from another span should use its span id as the parent span id

---

sentry_sdk/integrations/aiohttp.py
tests/integrations/aiohttp/test_aiohttp.py

This PR disables capturing of `asyncio.CancelledError` in `AioHttpIntegration`.
`aiohttp` will raise `asyncio.CancelledError` if clients interrupt request ([ref.](https://aiohttp.readthedocs.io/en/stable/web_advanced.html#web-handler-cancellation)) and this behaviour is considered normal.
In the meanwhile, such aborted requests are getting captured:

Fix 'asyncio.CancelledError' capturing for 'AioHttpIntegration'

---

sentry_sdk/utils.py

@rhcarvalho and I were guessing at how the code actually worked. It seemed like it only did so accidentally because the import of `aiocontextvars` has the side effect of monkeypatching `contextvars` (the PyPI package, not the stdlib module!) which is one of its dependencies.

fix: Make contextvars-detection more readable

---

sentry_sdk/integrations/wsgi.py

fix(wsgi): Avoid adding extra parameters if not necessary

---

sentry_sdk/worker.py

fix: Enforce max queue length in transport

---

sentry_sdk/integrations/sqlalchemy.py

fix: Fix deprecation warning in sqlalchemy integration

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery.py

Reference to issue: https://github.com/getsentry/sentry-python/issues/552
The task id is very useful for debugging celery tasks. I add it by using `set_tag`.

improvement: add celery task_id into tags

---

sentry_sdk/integrations/aws_lambda.py

As discussed on discord, this adds an additional "extra" for cloudwatch logs URL, log group, and log stream.
Not sure what if any tests are required for this change. Thoughts?

feat: add cloudwatch logs URL to lambda additional data

---

docs-requirements.txt
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/bottle.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/falcon.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/rq.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/integrations/tornado.py
tests/integrations/flask/test_flask.py
tests/test_basics.py

The idea is that you can write `init(_experiments={"auto_enabling_integrations": True})` to get maximal instrumentation.
Unsolved questions:
* How to opt out of integrations?

feat: Auto-enabling integrations behind feature flag

---

sentry_sdk/tracing.py

In summary, care must be taken when computing durations. Monotonic
clocks are not subject to system clock adjustments or system clock skew.
The difference between any two chronologically recorded time values is
guaranteed to never be negative.
The same guarantee above does not exist for the difference between two
calls to datetime.now() and friends.
More details and rationale see PEP 418.
Resources:
PEP 418 -- Add monotonic time, performance counter, and process time functions
https://www.python.org/dev/peps/pep-0418/
PEP 564 -- Add new time functions with nanosecond resolution
https://www.python.org/dev/peps/pep-0564/
---
**Know limitation**
At present, we only address timestamp computation within a single span.
A more complete patch should compute all durations in a transaction using a …

fix: Use monotonic clock to compute durations

---

sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/pyramid.py
sentry_sdk/integrations/tornado.py
sentry_sdk/integrations/wsgi.py

Turns out some users manually set user.id and other fields in the scope,
and those values get overwritten by integrations.
Glanced over places where we could be inadvertently overwriting user
data and changed to use setdefault to avoid overwriting existing values.

fix: Do not overwrite User data if already set

---

sentry_sdk/api.py
sentry_sdk/hub.py
sentry_sdk/scope.py
tests/test_scope.py

This is a draft of the proposal for explicit scope passing.

feat(scopes): Explicit scopes

---

docs-requirements.txt
sentry_sdk/_types.py
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/envelope.py
sentry_sdk/hub.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/scope.py
sentry_sdk/serializer.py
sentry_sdk/sessions.py
sentry_sdk/transport.py
sentry_sdk/utils.py
sentry_sdk/worker.py
tests/conftest.py
tests/integrations/flask/test_flask.py
tests/test_sessions.py

Initial work to support envelopes in parts of the system.

feat: Add envelope abstraction and session tracking

---

sentry_sdk/client.py
sentry_sdk/hub.py
sentry_sdk/integrations/atexit.py
sentry_sdk/scope.py
sentry_sdk/sessions.py

This lets you suspend and resume automated session tracking. It also ends the current session automatically in the atexit integration.

feat(sessions): Improved control over sessions

---

sentry_sdk/tracing.py
tests/test_tracing.py

In the product side we don't really want people to search by this tag as it is far more expensive than the `transaction.status` property which is indexed separately. By not emitting this tag and only including it in the trace context we won't end up with poor performing tags for users to click on.

fix(tracing) Omit the top level status tag

---

sentry_sdk/transport.py

The quota system no longer supports absolute timestamps.

feat(transport): Remove absolute time stamps

---

sentry_sdk/transport.py
tests/test_transport.py

Also fix a bug where missing categories ("123::project") would not
enforce a rate limit for all categories, as they were parsed as category
"" instead of category None.

fix: Test transport rate limits parsing and enforcement

---

sentry_sdk/integrations/aiohttp.py

aiohttp integration currently re-create a task to encapsulate the request
handler.
But:
- aiohttp already does it.
- contextvars created in it can't be read by aiohttp.
It's an issue for users custom logger.
Fix #670

fix: Preserve contextvars in aiohttp integration

---

sentry_sdk/_compat.py

The usage of the word 'enable' twice makes it sound strange.

Clarify console warning

---

sentry_sdk/tracing.py
tests/test_tracing.py

Do not crash if nested spans/transactions specify sampled argument.

fix: Allow nested spans to override sampled argument

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/asgi.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/asgi.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/tornado.py
sentry_sdk/utils.py
test-requirements.txt
tests/integrations/asgi/test_asgi.py

Found multiple issues with the asgi middleware:
* lack of warning if contextvars are broken -- as part of that I refactored/unified the error message we give in such situations, also added more information as gevent just recently released a version that deals with contextvars better
* exposed methods that were meant for overriding.. but all that is done in there can be done in event processors, so we make them private
Fix #630
Fix #700 
Fix #694

ref: Refactor ASGI middleware and improve contextvars error message

---

mypy.ini
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/asgi.py
sentry_sdk/integrations/django/middleware.py
sentry_sdk/utils.py
tests/integrations/django/asgi/test_asgi.py
tox.ini

* Django 3.1a1 adds more parameters to `load_middleware` which we do not really care about.
* Django 3.1a1 starts executing exception handlers in a random thread/with the wrong context. Turns out they have their own implementation of context local that is necessary to be able to find the right hub. See also https://github.com/getsentry/sentry-docs/pull/1721
More support is required for supporting async middlewares once Django 3.1 comes out but this should unbreak basic usage of the sdk.
Fix #704

fix(django): Support for Django 3.1

---

sentry_sdk/integrations/pyramid.py

When Pyramid can't match the route `request.matched_route` is set to `None`. The patched call view is throwing an AttributeException trying to set the transaction name.

Pass when exception is raised trying to set the transaction name

---

sentry_sdk/api.py
sentry_sdk/integrations/serverless.py

By [construction](https://github.com/getsentry/sentry-python/blob/6e378f18919a834d3de50b6f981e332b5094ad83/sentry_sdk/hub.py#L133-L142), Hub.current is never None, such that the expression
Hub.current is not None
always evaluates to True.
This commit simplifies all uses of Hub.current, and in particular
chooses to write `return Hub.current.method(...)` for every method, even
when the method returns None. The intent is to make it easier to keep
the static API matching the Hub behavior. Without this, if a method
returns anything other than None the static API would silently drop it,
leading to unnecessary debugging time spent trying to identify the
culprit.

ref: Remove Hub.current is not None checks

---

sentry_sdk/client.py
tests/test_tracing.py

Transactions should be sampled independent of error events. We should never "roll the dice" twice to decide when to send a transaction to Sentry.
This was probably fixed in the JS SDK as part of https://github.com/getsentry/sentry-javascript/pull/2600.
See [diff](https://github.com/getsentry/sentry-javascript/pull/2600/files#diff-377e14ef259b8bd726753063b8658e97).

fix: Do not double sample transactions

---

sentry_sdk/client.py
tests/test_tracing.py

This matches the behavior with JS and [the specs](https://develop.sentry.dev/sdk/unified-api/tracing).
The change in JS was introduced in https://github.com/getsentry/sentry-javascript/pull/2600.
See notes under "Few other fixes".

fix: Do not call before_send for transactions

---

sentry_sdk/tracing.py
tests/integrations/django/test_basic.py
tests/integrations/stdlib/test_subprocess.py

This matches the [JS implementation](https://github.com/getsentry/sentry-javascript/blob/a6b67abd9b2dabee0f9d61f822c97657b0496bfc/packages/apm/src/transaction.ts#L14-L35), and without it we cannot use the span recorder of a span to find its parent transaction (required to implement #734).

ref: Store tracked spans on start not finish

---

CHANGES.md
sentry_sdk/integrations/redis.py

When we deal with multikey commands (e.g. DEL), it's sometimes still useful to have the key as a tag. To make it less ambiguous, let's add the tag only if the command has one argument.

feat(redis): Add tags for more commands

---

sentry_sdk/client.py
tests/conftest.py
tests/test_tracing.py

This matches [what the JS SDK does](https://github.com/getsentry/sentry-javascript/pull/2553) and what the Tracing dev docs indicates.
Related: https://github.com/getsentry/sentry-python/pull/730

feat: Send transactions in envelopes

---

sentry_sdk/scope.py
tests/test_tracing.py

Specially when trying to add spans to automatically instrumented transactions, users need access to the current transaction.
This gives direct access no matter how deep the code is in the transaction/span tree.
This replicates a similar feature in JS: https://github.com/getsentry/sentry-javascript/pull/2668.

feat: Access transaction in current scope

---

sentry_sdk/hub.py
tests/test_basics.py
tests/test_client.py

ref: Use Hub.scope and Hub.client when appropriate

---

setup.py

https://pypi.org/project/beam/
https://pypi.org/project/apache-beam/
tox.ini gets this right, I guess nothing tests the setup extra.

beam extra should install apache-beam

---

sentry_sdk/api.py
sentry_sdk/hub.py
sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/asgi.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/rq.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/scope.py
sentry_sdk/tracing.py
tests/integrations/celery/test_celery.py
tests/integrations/sqlalchemy/test_sqlalchemy.py
tests/integrations/stdlib/test_subprocess.py
tests/test_tracing.py

This aligns the tracing implementation with the current JS tracing implementation, up to a certain extent.
Hub.start_transaction or start_transaction are meant to be used when starting transactions, replacing most uses of Hub.start_span / start_span.
Spans are typically created from their parent transactions via transaction.start_child, or start_span relying on the transaction being in the current scope.
It is okay to start a transaction without a name and set it later.
Sometimes the proper name is not known until after the transaction has started.
We could fail the transaction if it has no name when calling the finish method. Instead, set a default name that will prompt users to give a name to their transactions. This is the same behavior as implemented in JS.

feat: Introduce Transaction and Hub.start_transaction

---

sentry_sdk/envelope.py
sentry_sdk/transport.py
sentry_sdk/utils.py

This shrinks event sizes a bit, even when gzip'ed.
The compact representation is documented in the json module.
Alternatively, we can also look into using a custom encoder (that could
also handle datetime objects, instead of the current manual
serialization of those).
In the absence of proper benchmark data, consider a random transaction
event t:
```py
>>> len(json.dumps(t)), len(json.dumps(t, separators=(',', ':')))
(82174, 78516)
```
That is 95.5% of the original size.
With gzip compression:
```py
>>> len(gzips(json.dumps(t))), len(gzips(json.dumps(t, separators=(',', ':'))))
(13093, 12988)
```
That is 99.2% of the original size.

feat: Use most compact JSON encoding

---

sentry_sdk/client.py

Exceptions that are fatal but handled are probably log messages. Log messages are not really crashes. If we capture crashes as log messages only, we should fix that first by writing more integrations or fixing bugs in existing ones.

fix(sessions): Only crash session if the error is unhandled, not if it is fatal

---

sentry_sdk/integrations/flask.py
tests/integrations/flask/test_flask.py

Pushing the scope has little value even for the one usecase it was designed for (cli apps), as those run in their own processes anyway.

fix(flask): Remove double-scope

---

tests/conftest.py
tests/test_client.py

@untitaker how's this?
Based on https://github.com/getsentry/sentry-python/pull/749#issuecomment-656827764

Use sentry_init fixture in tests instead of using Hub directly

---

sentry_sdk/integrations/aws_lambda.py
sentry_sdk/utils.py
tests/integrations/aws_lambda/test_aws.py

Changes:
1) Added a new wrapper decorator for post_init_error method to capture initialization error for AWS Lambda integration.
2) Modified _wrap_handler decorator to include code which runs a parallel thread to capture timeout error.
3) Modified _make_request_event_processor decorator to include execution duration as parameter.
4) Added TimeoutThread class in utils.py which is useful to capture timeout error.

Capturing Initialization and Timeout errors for AWS Lambda Integration 

---

sentry_sdk/client.py
sentry_sdk/serializer.py
tests/integrations/sqlalchemy/test_sqlalchemy.py

For database auto-instrumented spans, the description contains potentially long SQL queries that are most useful when not truncated.
Because arbitrarily large events may be discarded by the server as a protection mechanism, we dynamically limit the description length, preserving the most important descriptions/queries.
**Performance impact**
Preliminary CPU profiling using [1] suggests that uuid4() dominates the execution time for code sending many transactions sequentially.
Preliminary memory profiling using [2] and looking at the max RSS of a benchmark script suggests that the max RSS has no significant change (JSON encoding in CPython is implemented in C).
In any case, we mitigate any increase in memory usage and run time for the majority of cases by avoiding any extra work when the …

feat: Avoid truncating span descriptions

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/views.py
tests/conftest.py
tests/integrations/django/test_basic.py
tests/integrations/sqlalchemy/test_sqlalchemy.py

This adds spans around URL resolving and the view itself.

feat(django): Instrument views as spans

---

sentry_sdk/integrations/gcp.py
test-requirements.txt
tests/integrations/gcp/test_gcp.py
tox.ini

Changes:
1) Added new GCP Integration for Google Cloud Functions.
2) Added event processor for this integration.
3) Added code for sending timeout warning.
4) Added automation test cases for the integration.
5) Modified tox.ini file for running automation test cases for GCP Integration.
6) Added code to capture timeout warning as well.

Added a new integration for Google Cloud Functions and automation test case framework

---

sentry_sdk/integrations/aws_lambda.py

We use UTC throughout the SDK, the Lambda integration was the only
exception, now fixed.
Explicitly setting the timezone to UTC fixes a problem when loading the
AWS CloudWatch Logs console, where using local time is unreliable.

fix: Use UTC time in AWS Lambda integration

---

sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/gcp.py

Changes:
1) Converted local time format to UTC time format for AWS Lambda integration, and verified it on cloudwatch logs.
2) Added code for timeout_warning parameter in class GcpIntegration.
Fix #796

Fix for timeout warning parameter for GCP integration & UTC time zone for AWS integration

---

sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/gcp.py
tests/integrations/gcp/test_gcp.py
tox.ini

1) Changed test_gcp.py file to include unit tests and removed automation tests.
2) Modified tox.ini as per above changes.
3) Modified Google cloud logs url to include utc time.

fix: Refactor testsuite for GCP and fix some bugs

---

sentry_sdk/integrations/pure_eval.py
tests/integrations/pure_eval/test_pure_eval.py

Part of #805 
The idea here is to prioritise values which appear closer to the executing statement. The dict of values is ordered so that trimming removes lower priority values later on.
However this doesn't work in python 3.5 because the ordered dict is actually converted to a regular dict which loses the order:
https://github.com/getsentry/sentry-python/blob/4d91fe0944009a6e02450214f663037dc1ce056c/sentry_sdk/serializer.py#L286-L288
It seems that my options are:
1. Remove the above line and fix the errors that arise.
2. Keep the dict ordered when making the copy.
3. Preemptively trim in the pure_eval integration so order no longer matters.
What do you think @untitaker ?

Order variables by closeness to executing statement in pure_eval

---

.travis.yml
tox.ini

Xenial is already the default dist on Travis CI.  (bionic and focal are also available)
Py39 in allow_failures mode until the GA release in one month.  https://devguide.python.org/#status-of-python-branches
Note: Python 3.4 is end of life and 3.5 will be end of life in two weeks.  https://devguide.python.org/devcycle/#end-of-life-branches
Also fixes:

Travis CI: Test on Python 3.9 release candidate 1

---

sentry_sdk/integrations/asgi.py
tests/integrations/asgi/test_asgi.py

When the exception bubbles up we deduplicate it based on object identity, so this should be fine
Fix #816

fix: Allow ASGI middleware to capture exceptions in nested call

---

sentry_sdk/envelope.py
sentry_sdk/transport.py
tests/conftest.py
tests/test_client.py
tests/test_transport.py

While working on https://github.com/getsentry/sentry-python/pull/825 I found a bug that caused us to use the "default" item type for transaction events. The bug happened because there were mismatched expectations as to what Item.get_event should return if the content is a transaction event.
Will add an explicit test later.

fix(transport): Use correct data category for transaction events

---

.travis.yml
sentry_sdk/integrations/celery.py
sentry_sdk/tracing.py
tests/conftest.py
tests/integrations/celery/test_celery.py
tox.ini

* Work around https://github.com/celery/celery/issues/4875 which causes us to lose transaction events. Fix #824 
* Rewrite celery testsuite to use redis backend and test transactions too. This is better because it works on more celery versions (memory backend is often broken). However, this still does not trigger the bug, so I guess for this to be properly tested we'd need to install rabbitmq into CI? No thanks

fix(celery): Fix dropped transactions under Celery 4.2+

---

sentry_sdk/serializer.py
tests/test_client.py

We already had safeguards for this situation, but only for local variables, not tags and extra.

fix(serialization): Do not crash if tag is nan

---

sentry_sdk/transport.py
tests/test_client.py

This would match `http_proxy`/`https_proxy` support and was actually supported in the old raven-python client.
Given the lack of a standard on `no_proxy` interpretation (with/without asterisk, with IP CIDR, etc), I went with a first basic implementation that should cover the most frequent usecase.

Add basic support for no_proxy environment variable

---

sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/gcp.py
tests/integrations/aws_lambda/test_aws.py
tests/integrations/gcp/test_gcp.py

1) Added code to capture transactions related to performance monitoring for AWS & GCP integrations.
2) Added test cases as per above changes.

Capturing Performance monitoring transactions for AWS and GCP

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/views.py
tests/integrations/django/myapp/settings.py

fix(django): Do not patch resolver_match

---

pytest.ini

This adds a pytest marker similar to `it.only` in jest.

feat(test): Add `only` pytest marker

---

sentry_sdk/client.py
sentry_sdk/consts.py
tests/integrations/flask/test_flask.py
tests/test_basics.py

We want to make auto enabling integrations the new default.

feat: Auto enable integrations=true

---

sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/gcp.py
sentry_sdk/utils.py

1) Added code to stop thread in aws_lambda.py & gcp.py.
2) Modified logic of run() function of class TimeoutThread to stop the thread and raise ServerlessTimeoutWarning exception, conditionally.
Fixes #846.

Fix incorrect timeout warnings in AWS Lambda and GCP integrations

---

mypy.ini
sentry_sdk/integrations/flask.py

Fixes https://github.com/getsentry/sentry-python/issues/858

fix: Import blinker check

---

pytest.ini
sentry_sdk/integrations/flask.py
sentry_sdk/scope.py
sentry_sdk/tracing.py
tests/conftest.py
tests/integrations/stdlib/test_httplib.py
tests/tracing/test_integration_tests.py
tests/tracing/test_misc.py

A bunch of comments and docstrings which got added while I was working on https://github.com/getsentry/sentry-python/pull/863. Also adds data to both the `Span` and `Transaction` reprs, and changes a handful of variable names to be more accurate. No behavior changes.

ref(tracing): Pre-`traces_sampler` documentation additions

---

tox.ini

The newest `pytest-django` drops support for older versions of `python`, `django`, and `pytest`. This should hopefully fix CI until we can think about upgrading.

fix(dev): Pin `pytest-django` version

---

sentry_sdk/integrations/django/asgi.py
sentry_sdk/integrations/django/views.py
tests/integrations/django/asgi/test_asgi.py
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py

Special handling for async views such that the function wrapper is also async. Need to split across files to preserve syntax compatible with Python 2.
Fix #849

fix: Fix crash with Django 3.1 async views

---

setup.py

These appear on the sidebar and provide neat, somewhat standard shortcuts to useful places. cf. [scout-apm](https://pypi.org/project/scout-apm/) , as defined in https://github.com/scoutapp/scout_apm_python/blob/631f2432f643d256ad5ab7ff6b8f7b95b14231f5/setup.py#L44

Add documentation and changelog links on PyPI

---

test-requirements.txt
tests/conftest.py
tox.ini

Extracted from https://github.com/getsentry/sentry-python/pull/863.

feat(dev): Add fixtures for testing `traces_sampler`

---

sentry_sdk/attachments.py
sentry_sdk/client.py
sentry_sdk/envelope.py
sentry_sdk/scope.py
tests/conftest.py
tests/test_basics.py

Initial work in progress support for attachments.
Example integration that uploads stdout/stderr as attachments is here: https://gist.github.com/mitsuhiko/16815c06341370c90030b520984e6ee2

feat(attachments): Add basic support for attachments

---

test-requirements.txt

See https://github.com/eventlet/eventlet/issues/660.
Until that gets addressed, this pins us at a version we know doesn't break py2.7 tests.

fix(dev): Pin `eventlet` version

---

sentry_sdk/consts.py
sentry_sdk/serializer.py
tests/test_client.py

In [this commit](https://github.com/getsentry/sentry-python/commit/16aaed1fdaa08e9ee177d89d6d2938acbdeff8aa#diff-c935006d78056bc518dd6e898d31d972c130c63119df74edf122e2cf4a5733bcL315), the structure of the `"breadcrumbs"` entry of an event was changed such that they were no longer stored at `event["breadcrumbs"]` but instead were stored at `event["breadcrumbs"]["values"]`. The `_is_databag()` helper function wasn't adjusted accordingly, however, resulting in `MAX_DATABAG_BREADTH` being applied to the list of breadcrumbs rather than the data inside each breadcrumb itself. In practice, this meant that no event could have more than 10 breadcrumbs.
This fixes the check in `_is_databag()` to look one level deeper for breadcrumbs. It also adds a more specific assert statement to the max breadth …

fix(serialization): Adjust breadcrumb check for new structure

---

sentry_sdk/_types.py
sentry_sdk/consts.py
sentry_sdk/tracing.py

This adds (but doesn't yet use) the types and attributes necessary for adding the `traces_sampler` option which is specced [here](https://develop.sentry.dev/sdk/unified-api/tracing). Extracted from the larger PR on that topic, https://github.com/getsentry/sentry-python/pull/863.
- Types for the `traces_sampler` itself (the function and its input)
- A new attribute on the `Transaction` class tracking the parent sampling decision separately from the sampling decision of the transaction itself, since part of the `traces_sampler` spec is that there needs to be a difference between an inherited decision and an explicitly set decision.

feat(tracing): Add types for `traces_sampler` implementation

---

sentry_sdk/tracing.py
sentry_sdk/utils.py
tests/tracing/test_sampling.py

This adds (but doesn’t yet use) some helper functions/methods which will be used in the implementation of the new `traces_sampler` option. It includes:
- a function to determine if tracing is enabled
- a function to validate sample rates returned from `traces_sampler`
- a `to_json` method in the `Transaction` class building upon the one already in the `Span` class
While creating `transaction.to_json`, I also removed the unused `client` parameter in `span.to_json`.

[WIP] feat(tracing): Add helper functions for new `traces_sampler` option

---

sentry_sdk/tracing.py
tests/tracing/test_misc.py

This adds a pointer to the `Span` class which points the the `Transaction` instance from which the span is descended. (It doesn't do anything with it yet, though - that will come in a subsequent PR which allows unsampled transactions living on the scope to be found.)

feat(tracing): Make spans point to their transactions

---

sentry_sdk/scope.py
tests/tracing/test_sampling.py

Currently, when trying to find the transaction on the scope (if any), we look for a span on the scope (which could be the transaction itself, or could be one of its descendants) and grab the first span in its span recorder. This works, but has the disadvantage that it can only find transactions with `sampled = True`, since transactions with `sampled = False` don't have a span recorder.
This changes the getter to use the current span's transaction pointer (added in https://github.com/getsentry/sentry-python/pull/870) to find the transaction instead.

fix(tracing): Make unsampled transactions findable on the scope

---

test-requirements.txt

eventlet recursion on py2.7 fixed in 0.29.1 https://github.com/eventlet/eventlet/issues/660
dnspython was pinned in eventlet since 0.26.1

unpin eventlet and dnspython

---

sentry_sdk/api.py
sentry_sdk/consts.py
sentry_sdk/hub.py
sentry_sdk/tracing.py
sentry_sdk/utils.py
tests/conftest.py
tests/integrations/sqlalchemy/test_sqlalchemy.py
tests/tracing/test_integration_tests.py
tests/tracing/test_sampling.py

This adds a `traces_sampler` option to the SDK, allowing dynamic sampling and filtering of transactions, as outlined [here](https://develop.sentry.dev/sdk/unified-api/tracing).
The one piece of that spec that this doesn't yet implement is pulling in default sampling context values from various frameworks/integrations, which will happen in subsequent PRs.

Add `traces_sampler` option

---

tests/conftest.py
tests/test_conftest.py

Adds the ability to test against partial objects. Also adds tests for previously-added matcher fixtures.

feat(dev): Add object matcher pytest fixture

---

sentry_sdk/__init__.py
sentry_sdk/api.py

Mypy does not support runtime-calculated `__all__`, so duplicate symbols
from `sentry_sdk.api.__all__` to top-level `__init__.py`.
Fixes #375.
Tested with mypy 0.790.

Fix mypy hinting of toplevel sentry_sdk module

---

sentry_sdk/integrations/aiohttp.py
tests/integrations/aiohttp/test_aiohttp.py

Following up on https://github.com/getsentry/sentry-python/pull/863, this adds the request object to the data automatically passed to `traces_sampler` when using the AIOHTTP integration.

feat(tracing): Add aiohttp request object to sampling context

---

tox.ini

This may end up being a bug on our end, in that the way that we're using `channels`/`asgiref` no longer matches their API, but as a temporary measure, this pins `channels` to a version which lets CI pass. 
See https://github.com/django/channels/issues/1549.

fix(dev): Pin `channels` for django tests

---

sentry_sdk/api.py
sentry_sdk/scope.py

fix https://github.com/getsentry/sentry-python/issues/899

fix: Correct types on set_context

---

README.md
setup.py

https://pypi.org/project/sentry-sdk/ is currently a bit too spartan and requires the user to do extra clicks to determine if they want to install or upgrade this package.
This PR proposes to replace the current one-liner with the markdown content from `README.md`.

Replace PyPI page with README.md

---

sentry_sdk/integrations/asgi.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/rq.py
sentry_sdk/integrations/wsgi.py
tests/integrations/asgi/test_asgi.py
tests/integrations/celery/test_celery.py
tests/integrations/rq/test_rq.py
tests/integrations/wsgi/test_wsgi.py

Following up on https://github.com/getsentry/sentry-python/pull/863, this adds useful information to the data automatically passed to `traces_sampler` when using the asgi, celery, rq, and wsgi integrations.

feat(tracing): Add more sampling context for asgi, celery, rq, and wsgi

---

sentry_sdk/integrations/aws_lambda.py
tests/integrations/aws_lambda/test_aws.py

Per https://docs.aws.amazon.com/lambda/latest/dg/python-handler.html, the `event` argument passed to the lambda function handler can be any jsonifiable type - string, int, list, etc - rather than just the dictionary we've previously assumed it to be. (This is particularly relevant for batch requests, which come in as a list of event dictionaries.)
When faced with such an `event`, our current integration crashes, because it tries to run `.get()` on it. This fixes that, by introducing the following behavior:
- If `event` is a list, tag the transaction as a batch and with the batch size.
- If `event` is a list, take the first entry as representative for the purposes of grabbing request data.
- If `event` (or the representative) isn't a dictionary, handle it gracefully and move on without …

fix(aws): Don't crash if `event` isn't a single dict

---

sentry_sdk/_compat.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/gcp.py
tests/conftest.py
tests/integrations/aws_lambda/client.py
tests/integrations/aws_lambda/test_aws.py
tests/integrations/gcp/test_gcp.py

Another follow-up to https://github.com/getsentry/sentry-python/pull/863. This adds sampling context from the AWS and GCP integrations.
In addition, this PR includes two changes to support testing of these changes - fixes to the `DictionaryContaining` and `ObjectDescribedBy` matchers, and closing of resources opened by tests to suppress unnecessary warnings.

feat(tracing): Add sampling context from AWS and GCP

---

sentry_sdk/consts.py
sentry_sdk/transport.py
sentry_sdk/worker.py

This adds a configurable transport queue size to the options.

feat: Expose transport queue size to options and bump queue size

---

sentry_sdk/integrations/aws_lambda.py
setup.py

Fixes #944 
Since the `headers` property is present and set to `None`, the `.get` default value is ignored.
We need an explicit check on `None` for this one.
~I would advise checking other places in `sentry_sdk/integrations/aws_lambda.py` where the default value is expected to be an empty dictionary. This kind of error is frequent when working with Lambda/ApiGateway.~ Fixed.

fix: Fix header extraction for AWS Lambda/ApiGateway

---

sentry_sdk/integrations/flask.py
test-requirements.txt
tests/conftest.py
tests/integrations/django/myapp/routing.py
tests/utils/test_general.py
tox.ini

* eventlet is broken all the time in newer Python versions
* Channels 3.0 needs some adjustments.
* unpin pytest to satisfy conflicts between Python 3.9 and Python 2.7 environments

fix(ci): unpin pytest, stop testing eventlet

---

sentry_sdk/utils.py

This was an unintentional behavior. It should in fact use the full git sha as release name.
This fixes #908

Use full git sha as release name

---

sentry_sdk/api.py
sentry_sdk/hub.py
sentry_sdk/integrations/chalice.py

A **kwargs argument should be hinted as `T`, instead of `Dict[str, T]`.
The dict wrapping is already implied by the type system.
See: https://mypy.readthedocs.io/en/stable/getting_started.html?highlight=kwargs#more-function-signatures

Fix multiple **kwargs type hints

---

sentry_sdk/integrations/aws_lambda.py

Fix for https://github.com/getsentry/sentry-python/issues/972

AWS Lambda integration fails to detect the aws-lambda-ric 1.0 bootstrap

---

sentry_sdk/integrations/aws_lambda.py

Fix for https://github.com/getsentry/sentry-python/issues/974

Fix unbound local crash on handling aws lambda exception

---

sentry_sdk/client.py
sentry_sdk/utils.py

The SDK spec ([here](https://develop.sentry.dev/sdk/overview/)) doesn't list a release condition on the default environment value.
Specifically:
> The following items are expected of production-ready SDKs:
> [...]
> Additionally, the following features are highly encouraged:
> - [...]
> - Send an `environment` on each event. If none was detected or set by the user, `production` should be used.

fix(environment): Remove release condition on default

---

CONTRIBUTING.md

This commit adds more instructions on how to install the sdk from source. It will be more clear to someone who is new to python.

Make pytest run instruction clear in contribution guide

---

test-requirements.txt
tests/integrations/django/test_transactions.py
tox.ini

Two fixes to CI, both caused by dependencies dropping support for specific things we use.
1. Our celery tests depend on the `newrelic` package, which just hit v6, [dropping support for py3.5 in the process](https://docs.newrelic.com/docs/release-notes/agent-release-notes/python-release-notes/python-agent-600154). Fortunately, since the celery tests are the only thing which uses the package, it was possible to move it out of the general test requirements and into celery-specific requirements in tox, allowing py3.5 to use a different veresion of `newrelic` than other Python versions.
2. Since version 2.0 (4 years ago), Django's `url` function has really [just been an alias](https://github.com/django/django/commit/df41b5a05d4e00e80e73afe629072e37873e767a#diff-318c25772a3e40b833969d2d1c3e1a6f9 …

fix(ci): Fix `py3.5-celery` and `*-django-dev`

---

sentry_sdk/consts.py
sentry_sdk/tracing.py

This PR partially reverts https://github.com/getsentry/sentry-python/pull/948 and https://github.com/getsentry/sentry-python/commit/6fc2287c6f5280e5adf76bb7a66f05f7c8d18882, to restore the ability to disable tracing, which allows it to truly be opt-in [as per the spec](https://develop.sentry.dev/sdk/performance/#sdk-configuration).
Note that this does not change the behavior that PR was made to reinstate - the model wherein the front end makes sampling decisions, the backend has `traces_sample_rate` set to `0`, and the result is that the backend samples according to the front end decision when there is one, but otherwise does not send transactions. (That PR modified a test to test for that exact scenario, and it still passes.)

ref(tracing): Restore ability to have tracing disabled

---

sentry_sdk/client.py
sentry_sdk/envelope.py
sentry_sdk/hub.py
sentry_sdk/scope.py
sentry_sdk/session.py
sentry_sdk/sessions.py
tests/test_envelope.py
tests/test_sessions.py

This changes the SessionFlusher to pre-aggregate sessions according to https://develop.sentry.dev/sdk/sessions/#session-aggregates-payload instead of sending individual session updates.
The current implementation will *always* aggregate sessions, as the SDK currently lacks the possibility to chose between application-mode or request-mode sessions.

feat: Support pre-aggregated sessions

---

.github/workflows/ci.yml
Makefile
scripts/build-awslambda-layer.py

In order to get the Python SDK on an AWS Lambda function, a layer where Python is installed must be added to that function. The layer requires a ZIP file to be uploaded, containing the Python binaries installed (i.e. the Python SDK and the required additional modules installed). The `scripts/build-awslambda-layer.py` generates that ZIP file. The script is also run in the CI, so it will be available as an artifact.

feat: Build dist ZIP for AWS Lambda layers

---

tox.ini

Django dropped support for `Python3.7`. This PR removes `Python3.7` from `django-dev`. Fixes master.

fix: Remove Python3.7 from Django

---

.github/workflows/ci.yml
Makefile

CI runs on master, release branches and PRs; however, the `dist` job only runs on release branches. At the moment there's no other way of building distribution packages (such as the serverless `zip` dist), which may be needed in some cases. This PR removes the `dist` job execution requirement and is run when CI is run.

ci: Run `dist` job always when CI is run

---

.craft.yml

Adds the `aws-lambda-layer` target for Craft.

feat: Add `aws-lambda-layer` craft target

---

.github/workflows/release.yml

Addresses @HazAT's comment here: https://sentry.slack.com/archives/C01C205FUAE/p1613045701031000

ci(release): Update release to use v1.1 of action

---

.github/workflows/ci.yml
.gitignore
scripts/build-awslambda-layer.py

`/dist` is used by twine, so the serverless dist package shouldn't be in the same directory. This PR fixes the issue where `twine` tries to upload the serverless package.

ref: Change serverless dist destination path to `/dist-serverless`

---

CONTRIBUTING.md
setup.py

Renamed in getsentry/sentry-python#1008

Fix link to changelog

---

scripts/build-awslambda-layer.py

Handles the case where the destination directory does not exist.

fix: Create dist directory if it does not exist

---

sentry_sdk/integrations/django/asgi.py
tests/integrations/django/asgi/test_asgi.py
tests/integrations/django/myapp/middleware.py

fix(django): Fix middleware issue not handling async middleware functions

---

.craft.yml
scripts/build-awslambda-layer.py

At the moment there is an issue when releasing the Python SDK, where PyPI tries to upload the serverless dist package. https://github.com/getsentry/sentry-python/pull/1012 tried to address this issue, incorrectly. This PR sets a filter in the PyPI craft target in `.craft.yml`; and reverts the destination directory to `/dist`, where the distribution files are placed.

fix(release): Include in PyPI artifact filter for Craft

---

scripts/init_serverless_sdk.py
tests/integrations/aws_lambda/client.py

This PR is a minor fix to the environment variables names in the `scripts/init_serverless_sdk.py`
- Added `SENTRY_` prefix to all environment variables
- Added `SENTRY_TRACES_SAMPLE_RATE` environment variable to initialization of sentry_sdk

Fix(serverless): Add "SENTRY_" prefix to env variables in serverless init script + added traces_sample_rate

---

sentry_sdk/hub.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/stdlib.py
tests/conftest.py
tests/integrations/stdlib/test_httplib.py
tests/integrations/stdlib/test_subprocess.py
tests/tracing/test_integration_tests.py

Currently, there are situations in which a trace ends up looking not like this (as it should):
but instead looks like this:
This happens because we currently create the outgoing tracing headers based not on the span representing the outgoing request but on whatever span is on the scope, which is most often the transaction itself. There are situations in which this is necessary (if there is no child span to tie to*), but in situations where it's not, we should be correctly associating child transactions with their parent spans, not their ancestor transactions.
\*It's a separate question whether, in the one place there isn't a span ([here](https://github.com/getsentry/sentry-python/blob/1279eeca6763e119d97da5da8318f48a04d3adef/sentry_sdk/integrations/rq.py#L99-L107), the `rq` integration), …

fix(tracing): Get HTTP headers from span rather than transaction if possible

---

sentry_sdk/integrations/flask.py
tests/integrations/flask/test_flask.py

This PR fixes the bug that transactions were missing data/body because weakref to the request object was garbage collected before the request object made into the event_processor
- Removed weakref to request object when passed to the event_processor_factory
Ref: https://app.asana.com/0/1142928854421177/1199663160066590

bug(flask): Transactions missing body

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/wsgi.py
tests/integrations/django/test_basic.py

This PR, 
- Changes the `SentryWsgiMiddleware` to accept a `use_x_forwarded_for` arg that defaults to False. It acts as a flag that if enabled  allows for checking if the `HTTP_X_FORWARDED_HOST` and if it is present in the `environ`, it is used to generate the request URL rather than using the `HTTP_HOST` for it
- Modified the Django integration's initialization of `SentryWsgiMiddleware` to pass the value of `settings.USE_X_FORWARDED_HOST`

fix(django):  Added SDK logic that honors the `X-Forwarded-For` header

---

tests/integrations/django/test_basic.py

This PR modified a test that used to import django settings and manipulate it and now just uses pytest settings fixture

fix(django): Modified test to use settings fixture rather than using django settings

---

sentry_sdk/worker.py

When we fail to flush all events, or when the queue overflows, this
should be an error event.
I have some concerns about when the user uses things like logly, which
are known for sending out blocking HTTP requests from within their log
handler. However I believe they don't register that handler for all
loggers.

fix(worker): Log data-dropping events with error

---

scripts/build_awslambda_layer.py
scripts/init_serverless_sdk.py
sentry_sdk/integrations/logging.py
tests/integrations/logging/test_logging.py

Fixes #511 
This implementation uses [fnmatch](https://docs.python.org/3/library/fnmatch.html) since the `glob` module only matches existing files.
`fnmatch` also works on python 2.7 and later, so this should work with all python versions supported by the SDK.

feat: Support wildcards in ignore_logger

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/tornado.py
tests/integrations/tornado/test_tornado.py

feat: Support tracing on Tornado

---

CHANGELOG.md

Since we're on major version 1, I think the docs should recommend that version.

Minor tweak of recommended version to pin in changelog

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/flask.py
tox.ini

Fix a bunch of issues with CI that prevent me from releasing
* django main branch has changed how classbased views work, slightly, view_func is now some sort of closure
* spark is unmaintained so we can do nothing but remove it from CI for now
* Flask has a RC-version released so it generally feels safer to allow those weird versions to be used with the SDK

chore: Fix CI failures

---

sentry_sdk/integrations/rq.py
tests/integrations/rq/test_rq.py

Fixes https://github.com/getsentry/sentry-python/issues/1074
Sentry reports all errors from RQ even if it is still retrying the job. 
This changes checks to ensure that retries have been exhausted, ie. the job has failed and will be moved to the failed jobs queue, before capturing the exception. 
Changes:
integrations/rq.py
- only call _capture exception if job.is_failed is true, indicating it is moving to the failed jobs registry
- add ignore_logger('rq.worker') so the exception does not get captured via the logging integration 
tests/integrations/rq/test_rq.py
- Add a failing test case for redis version 1.5 and above (where Retry was introduced) to ensure only one exception is captured in the event of a retry

fix(rq): Only capture exception if RQ job has failed (ignore retries)

---

scripts/build_awslambda_layer.py
tests/integrations/aws_lambda/client.py

This PR provides :
- Fix for AWS Function Handler name to be in the format of `filename.function-name` because
passing paths (what we have now) as function name is giving us import errors from AWS Lambda
- Added the initialisation script for AWS Lambda function handler name to path `init_serverless_sdk.sentry_lambda_handler`
Current Behavior:
Handler name: `sentry_sdk.integrations.init_serverless_sdk.sentry_lambda_handler`
Response from AWS 
```
Response
{
"errorMessage": "Unable to import module 'sentry_sdk.integrations.init_serverless_sdk': No module named 'init_serverless_sdk'",
"errorType": "Runtime.ImportModuleError",
"stackTrace": []
}
```
Note: Unable to replicate in backend tests that actually create real lambda functions and layers. Only able to replicate this behavior on the AWS …

fix(aws-lambda): Change lambda function handler name to 'x.y'

---

scripts/init_serverless_sdk.py

I think this is the culprit of broken AWS API Gateway <-> AWS Lambda when the Sentry Lambda Layer is enabled.
(Have not tested myself)

fix(serverless): Return value from original handler

---

scripts/build_awslambda_layer.py
tests/integrations/aws_lambda/client.py

Reverts getsentry/sentry-python#1107

Revert "fix(aws-lambda): Change lambda function handler name to 'x.y'"

---

sentry_sdk/tracing.py

Zero is a valid sample rate, which will turn on tracing.

fix(docs): Correct docstring on `has_tracing_enabled`

---

tests/integrations/django/test_basic.py
tox.ini

This PR fixes failing CI due to : 
- `trytond` failing dependency because it uses deprecated methods in Wekzeug and so pinning `werkzeug` to version `<2.0`
- Introduction of explicit database access requirement due to an experimental feature in `pytest-django` version `4.3`

fix(ci): Fix failing CI dependencies due to Werkzeug and pytest_django

---

sentry_sdk/integrations/bottle.py

This PR bring support dev branch integration.
Simply strip -dev suffix.
https://github.com/bottlepy/bottle/blob/master/bottle.py#L20
`>>> tuple(map(int, "0.13-dev".split(".")))
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '13-dev'
`

fix(integration): Discard `-dev` when parsing required versions for bottle

---

sentry_sdk/integrations/aws_lambda.py

The AWSLambdaIntegration adds the cloudwatch URL in the context but the domain is hardcoded and doesn't work for China regions.

Support China domain in lambda cloudwatch logs url

---

sentry_sdk/worker.py

Set daemon attribute instead of using setDaemon method that was deprecated in Python 3.10

---

scripts/init_serverless_sdk.py
tests/integrations/aws_lambda/client.py
tests/integrations/aws_lambda/test_aws.py
tests/integrations/django/myapp/settings.py

This PR:-
- Fixes bug that would technically fail if the initial handler for a lambda function by adding support for  `x.y.z` rather than just `x.y`
- Adds support for initial handler dir paths in the format of `x/y.z`
Ref: https://sentry.zendesk.com/agent/tickets/49603

fix(aws-lambda): Fix bug for initial handler path

---

docs/conf.py

This PR adds explicit imports for sphinx packages due to circular dependency bug introduced in sphinx 4.x
Ref: https://github.com/sphinx-doc/sphinx/issues/9243

fix(docs): Add sphinx imports to docs conf to prevent circular deps

---

sentry_sdk/integrations/sanic.py
tests/integrations/sanic/test_sanic.py
tox.ini

This PR:
- Adds support for latest Sanic versions >= 21.3 because it was initially broken due to breaking changes after LTS of 20.12
Note/Todo:
- There **MIGHT** be missing support for new added functionality in version 21.3 that should be integrated in future work
- This PR is merely there to not break support for what we already have
Fixes: #1066, #1128

feat(integration): Add support for Sanic >=21.3

---

sentry_sdk/utils.py

🐛 Fix detection of contextvars compatibility with Gevent 20.9.0+
This is described in https://github.com/getsentry/sentry-python/issues/1063, and this PR would fix it (it should at least).
The current implementation checks if Gevent patched contextvars, but:
> Gevent 20.9.0 depends on Greenlet 0.4.17 which natively handles switching context vars when greenlets are switched.
> Older versions of Python [older than 3.7] that have the backport installed will still be patched.
Ref: https://github.com/gevent/gevent/blob/83c9e2ae5b0834b8f84233760aabe82c3ba065b4/src/gevent/monkey.py#L604-L609
This PR updates the implementation to check the version of Gevent and Python to account for that.
I'm migrating a code base with a couple of apps from Flask to FastAPI. During the migration both Flask and …

🐛 Fix detection of contextvars compatibility with Gevent 20.9.0+

---

sentry_sdk/api.py
sentry_sdk/scope.py

Switch from using (Dict[str, Any]) -> None to
(Optional[Dict[str, Any]]) -> None for the `set_user` function's type
hints.
Fixes https://github.com/getsentry/sentry-python/issues/1164

fix(mypy): Use correct typings for set_user

---

sentry_sdk/client.py
sentry_sdk/integrations/httpx.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/scope.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py

Mostly docstrings and comments. Also a stray, no-longer-necessary variable initialization and a few log statements. Pulled from an upcoming PR in order to make it less noisy.

chore(tracing): Pre-lazy-tracestate cleanup

---

sentry_sdk/client.py
sentry_sdk/scope.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py
tests/tracing/test_http_headers.py

Three small changes here, mostly unrelated. Probably easiest to look at this commit by commit.
- Correct return type of `compute_tracestate_entry` to correctly return `None` when we're missing a client or DSN.
- Let transactions (effectively) point to themselves as the "containing transaction." In order to avoid a circular reference, this is handled through a new property on both spans and transactions. As a result of this change, we can eliminate a good deal of type-checking that we've been doing up until now.
- Switch `tracestate` creation to be lazy. Rather than always creating a value in the transaction constructor, we now wait until we need it - either for an outgoing HTTP header or for the envelope header when sending the transaction event.

ref(tracing): Various tweaks to tracestate header handling

---

sentry_sdk/tracing_utils.py
tests/tracing/test_http_headers.py

This adds user data (specifically `id` and `segment`) and transaction name to the `tracetate` value. 
Doing this has two known limitations, which, though we've discussed them, I'm adding here for posterity:
1) Adding this data puts us over the character limit for tracestate values [listed in the W3C spec](https://www.w3.org/TR/trace-context/#value) (256 characters). For reference:
Tracestate data:
```
{
"trace_id": "12312012123120121231201212312012",
"environment": "dogpark",
"release": "off.leash.park",
"public_key": "dogsarebadatkeepingsecrets",
"user": {"id": 12312013, "segment": "bigs"},
"transaction": "/interactions/other-dogs/new-dog/"
}
```
`tracestate`  with without either: 196 characters
`tracestate` with user data: 256 characters
`tracestate` with transaction name: 264 …

feat(tracing): Add user data/transaction name to tracestate value

---

.github/workflows/black.yml
.github/workflows/ci.yml

GitHub is retiring `ubuntu-16.04` as a platform for GitHub Actions later this month.
This moves all but our Python 3.4 tests to `ubuntu-latest` (which is currently `20.04`). GitHub doesn't host a `py3.4` binary on `latest`, so those tests are now run on `18.04`.

chore(ci): Update GHA jobs to run on `ubuntu-latest`

---

CHANGELOG.md
sentry_sdk/hub.py
tests/test_basics.py

This fixes the logic to not set the last event id for transactions which was not intended.

fix: no longer set the last event id for transactions

---

sentry_sdk/tracing.py
tests/integrations/sqlalchemy/test_sqlalchemy.py
tests/tracing/test_misc.py

_Background for anyone not familiar with Python's internal workings (skip ahead if you that's not you):_
_Python handles memory deallocation through a combination of reference counting and cyclic garbage collection, the former taking way fewer resources than the latter. Having circular references forces the cyclic garbage collector to run, since anything involved in a reference cycle will never have a refcount of 0, even once everything _outside_ of the cycle is done with all of its members. The `gc` module used in the test mentioned below is a window specifically into the cyclic garbage collector part of the memory deallocation system, and its `collect` method returns the number of objects it was forced to deal with. See https://devguide.python.org/garbage_collector/ and …

fix(tracing): Break `transaction` / `span` circular references before garbage collection

---

.vscode/settings.json
scripts/init_serverless_sdk.py
sentry_sdk/_types.py
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/envelope.py
sentry_sdk/tracing.py
sentry_sdk/transport.py
tests/test_transport.py

This adds support for client reports to the python SDK. This will cause the SDK to send a report once every 30 seconds or once a minute. After 30 seconds it will attempt to attach the report to a scheduled envelope if there is one, after 60 seconds it will send it as a separate envelope. Attempts of sending are only made as a byproduct of attempted event / envelope sending or an explicit flush.
The feature can be turned off via the `send_client_reports` option which is on by default.
Refs: https://github.com/getsentry/relay/pull/1074

feat(transport): Client Report Support

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/hub.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/httpx.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/scope.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py
sentry_sdk/utils.py
tests/integrations/sqlalchemy/test_sqlalchemy.py
tests/test_envelope.py
tests/tracing/test_http_headers.py
tests/tracing/test_integration_tests.py
tests/tracing/test_misc.py
tests/tracing/test_sampling.py
tests/utils/test_general.py

This PR introduces handling of the `tracestate` header, as described in the [W3C Trace Context spec](https://www.w3.org/TR/trace-context/#tracestate-header) and our own [corresponding spec](https://develop.sentry.dev/sdk/performance/trace-context/).
Key features:
- Deprecation of `from_traceparent` in favor of `continue_from_headers`, which now propagates both incoming `sentry-trace` and incoming `tracestate` headers.
- Propagation of `tracestate` value as a header on outgoing HTTP requests when they're made during a transaction.
- Addition of `tracestate` data to transaction envelope headers.
Supporting changes:
- New utility methods for converting strings to and from base64.
- Some refactoring vis-à-vis the links between transactions, span recorders, and spans. See …

feat(tracing): Add `tracestate` header handling

---

CHANGELOG.md
sentry_sdk/consts.py

Since we don't do beta releases in this SDK turn this of for one release so we can test this before enabling it by default.

feat: disable client reports by default

---

CHANGELOG.md
tox.ini

I'm not fully convinced that we should run everything on the latest branches.
It can be noisy and block our release process, while providing is with nothing else than a warning that upstream might be broken.

misc(test): Dont run tests on -dev branches and add latest versions of Django and Flask

---

.github/workflows/release.yml

Upgrade to latest version of `getsentry/action-prepare-release` (from 1.1 to 1.3+)
Noticed getsentry/publish#556 is using the old version of our release action so bumping it here.

ci(release): Use the latest version of publish

---

sentry_sdk/tracing.py
tests/tracing/test_integration_tests.py

In `__exit__` method, we call `self.finish` first, and then we restore the previous span to the scope. Because of that, in some circumstances, it can happen, that `start_child` will be called on the Transaction which `_span_recorder` has been already deleted from the instance, making the call below blow up without a proper check.
In our case, we performed db calls through our options cache inside the custom transport - https://github.com/getsentry/sentry/blob/14dc81c124e4ab4d86967c14e44a7bb8af8ca742/src/sentry/utils/sdk.py#L278-L280

fix(tracing): Fix race condition between finish and start_child

---

sentry_sdk/transport.py

Previously the envelope was modified in place which meant that an envelope could not be easily sent to multiple transports. Now the http transport makes a copy of the envelope before modifying it.

fix: Ensure that an envelope is cloned before it's modified

---

.craft.yml

From [AWS docs](https://docs.aws.amazon.com/lambda/latest/dg/lambda-python.html):
> End of support for the Python 2.7 runtime started on July 15, 2021.
Since Python 2.7 is no longer supported, there's no point in having it as a compatible runtime for the created layers. Removing this version means new layers created by Craft on releases won't have it as a compatible runtime; so it doesn't affect existing layers.

build(craft): Remove Python 2.7 support for AWS Lambda layers

---

sentry_sdk/integrations/sanic.py
tests/integrations/sanic/test_sanic.py

This PR allows for Sanic v21.9 style error handlers to operate and provide full access to handling Blueprint specific error handlers.
---
> The ErrorHandler.lookup now requires two positional arguments:
[Source](https://sanicframework.org/en/guide/release-notes/v21.9.html#what-to-know)
See also: https://github.com/sanic-org/sanic/pull/2259
---
_UPDATE_: 
Fixes https://github.com/getsentry/sentry-python/issues/1240
Fixes https://github.com/sanic-org/sanic/issues/2250

Refactor Sanic integration for v21.9 support

---

.craft.yml
sentry_sdk/integrations/aws_lambda.py
tests/integrations/aws_lambda/test_aws.py

- Added AWS Lambda Python 3.9 runtime support
- Ignore mypy module check
- Fixed check bug and added python3.9 runtime to tests
- Revert comment
- run black on aws_lambda.py and test
- add python3.9 as compatible runtime in .craft.yml

feat(aws-lambda): Add Python 3.9 support

---

tox.ini

Version 8.11.0 of more-itertools drops Python 3.5 support. This pins
the library to <8.11.0 so that we still run tests.

fix(tests): Pin more-itertools in tests for Python 3.5 compat

---

sentry_sdk/integrations/django/__init__.py
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py

Here's a screenshot of a trace where Django opens a new connection
fixes #1249

record span and breadcrumb when Django opens db connection

---

CHANGELOG.md

To match at least a > 1.0.0 world as the description

CHANGELOG: update requirements example

---

CHANGELOG.md
sentry_sdk/integrations/django/transactions.py
tox.ini

Upstream django [CVE fix](https://github.com/django/django/compare/2.2.24...2.2.25#diff-ecd72d5e5c6a5496735ace4b936d519f89699baff8d932b908de0b598c58f662L233) caused master tests to fail.
This patches our url resolver regex substition to account for \A and \Z metacharacters.

fix(django): Fix django legacy url resolver regex substitution

---

CHANGELOG.md
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py
tests/tracing/test_sampling.py

Spurious client report outcomes were recorded before even if `traces_sample_rate` and `traces_sampler` were both `None` in the config.
Fixes https://getsentry.atlassian.net/browse/WEB-279

fix(client-reports): Record lost `sample_rate` events only if tracing is enabled

---

sentry_sdk/client.py
tests/conftest.py
tests/integrations/gcp/test_gcp.py
tests/test_basics.py

Record client reports of `event_processor` type when dropped.
Closes https://github.com/getsentry/sentry-python/issues/1210
and https://getsentry.atlassian.net/browse/WEB-341

feat(client-reports): Record event_processor client reports

---

sentry_sdk/integrations/__init__.py
sentry_sdk/integrations/quart.py
setup.py
tests/integrations/quart/__init__.py
tests/integrations/quart/test_quart.py
tox.ini

This is based on the Flask integration but includes background and
websocket exceptions, and works with asgi. 
Note I think the background task exception monitoring and Quart-Auth integration make this more useful than the ASGI middleware alone.
If this is welcomed I'm happy to write the tests (based on the Flask ones).

Add a Quart integration

---

sentry_sdk/integrations/sanic.py
tests/integrations/sanic/test_sanic.py

The previous version of the SDK had a workaround for v21.9. That is no longer needed in v21.12 and should not be triggered. By doing so, it calls the `__exit__` method of the `Hub` twice causing the error in #1290.
Ref https://github.com/sanic-org/sanic/issues/2297
Closes #1290

Sanic v21.12 support

---

mypy.ini
sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery.py

I have a use case for Celery [abstract
tasks](https://docs.celeryproject.org/en/latest/userguide/application.html#abstract-tasks)
to handle exceptions for an entire Celery app in a common way. Handled
exceptions should be swallowed in the abstract task and never make it to
Sentry.
Prior to this change, the Celery integration always instruments
`task.run` and incorrectly instruments `task.__call__` (`task(...)` is
equivalent to `type(task).__call__(...)`, not `task.__call__(...)`).
After this change, we'll use the same logic as Celery to decide whether
to instrument `task.__call__` or `task.run`. That change allows abstract
tasks to catch/raise exceptions before the Sentry wrapper.

Support Celery abstract tasks

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/middleware.py
tests/integrations/django/myapp/custom_urls.py
tests/integrations/django/myapp/middleware.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py

Django middlewares sometimes [can override `request.urlconf`](https://github.com/django-tenants/django-tenants/blob/eee77af68004745ed104b63ed69995789e3a6b32/django_tenants/middleware/main.py#L73) for the current request which it has a [contract](https://github.com/django/django/blob/main/django/core/handlers/base.py#L283-L288) for using subsequently as the source of truth for url related operations.
As a result, we also need to respect the overwritten `urlconf` in our transaction name resolving.
I finally went with an `_after_get_response` solution. The resolution is repeated code but runs only if `urlconf` is overwritten. I wanted to touch as little of existing logic as possible.
For reference, I went back and forth several times between doing it in a couple of other places.
* …

feat(django): Pick custom urlconf up from request if any

---

sentry_sdk/integrations/falcon.py
tests/integrations/falcon/test_falcon.py

fix(python): Capture only 5xx HTTP errors in Falcon Integration

---

sentry_sdk/integrations/django/__init__.py
tests/integrations/django/myapp/custom_urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py

The fix in https://github.com/getsentry/sentry-python/pull/1308 only worked for transactions and not for exceptions since exceptions will nope out before `_after_get_reponse` runs in most cases. This generalizes the solution to also run in `_got_request_exception`.
https://getsentry.atlassian.net/browse/WEB-530

fix(django): Attempt custom urlconf resolve in got_request_exception as well

---

sentry_sdk/tracing_utils.py

Granted, this is a bit of an edge-case, but I'll explain the rationale.
In our Django application, we define `MERCURIAL_TAG` in our settings. To compute this we subprocess out to `hg`. As you can imagine, this is quite expensive and has a significant impact on application startup time. So we've wrapped this in `django.utils.functional.lazy()` so that it's only evaluated when it's needed, not every time the app starts or every time a uwsgi worker is recycled.
The issue is, we primarily use this setting by passing it to `sentry_sdk.init()`. When the Sentry SDK goes to report an error, `compute_tracestate_value()` calls `json.dumps()` which blows up with a whole stack of `TypeError: Object of type __proxy__ is not JSON serializable` as the `_got_request_exception` signal fires over and over. …

Provide default argument to json.dumps in compute_tracestate_value

---

sentry_sdk/serializer.py
tests/test_serializer.py

Based on the discussion in https://github.com/getsentry/sentry-python/pull/1300 and https://github.com/getsentry/sentry-python/issues/1296.
We do a lot of truncation magic in our serializer to not send huge payloads.
In the process, we ignore if a user/framework sets a custom `__repr__` on a class.
This PR lets users add a `sentry_repr` that will short circuit our truncation logic and pick the user defined repr.
We cannot just go with checking if `__repr__` is overridden because we still want to preserve the truncation behavior for classes out there in the wild like [`QueryDict`](https://docs.djangoproject.com/en/2.2/ref/request-response/#django.http.QueryDict).
Some notes from the TSC:
* for now this is python only because python is the only SDK with an elaborate serializer
* and in …

feat(serializer): Allow classes to short circuit serializer with `sentry_repr`

---

test-requirements.txt

`pytest` version 7.0.0 was released on last friday and it does not work with our test suite. So I pinned the pytest version in our test suite to use the "old" one until pytest fixes the problems with 7.0.0 release.

Pinning test requirements versions

---

.pre-commit-config.yaml
linter-requirements.txt
test-requirements.txt

To speed up development and prevent a lot of front and back with the CI linter, I added a pre-commit hook, so before one can commit something the linting (black, flake8 and mypy) will run locally to format and lint the changed files.

feat(tooling): Enabled local linting

---

examples/tracing/templates/index.html
sentry_sdk/integrations/flask.py
tests/integrations/flask/test_flask.py

To setup distributed tracing links between a Flask app and a front-end app, one needs to figure out how to get the current hub, safely get the traceparent and then properly pass it into a template and then finally use that properly in a `meta` tag. [The guide](https://docs.sentry.io/platforms/javascript/performance/connect-services/) is woefully inadequate and error-prone so this PR adds a built-in helper `sentry_trace()` to the Flask integration to simplify this linking.
I'll follow up with documentation updates once the approach here is approved.

feat(flask): Add `sentry_trace()` template helper

---

.github/ISSUE_TEMPLATE/bug.yml

Adding Github [issue form](https://docs.github.com/en/communities/using-templates-to-encourage-useful-issues-and-pull-requests/syntax-for-issue-forms) for bugs.
**Preview**: 
https://github.com/getsentry/sentry-python/blob/217d337a41feeb516893626be6c4abbc32cbc48e/.github/ISSUE_TEMPLATE/bug.yml

chore: add bug issue template

---

sentry_sdk/serializer.py
tests/test_serializer.py

The addition of `sentry_repr` in #1322 breaks `MagicMock` since it creates attrs on the fly.
This converts it to a dunder magic method `__sentry_repr__`.
See [here](https://github.com/python/cpython/blob/main/Lib/unittest/mock.py#L639-L640) that mock doesn't mess with custom magics and the following test code:
```bash
In [22]: from unittest import mock
In [23]: m = mock.Mock()
In [24]: m
Out[24]: <Mock id='140712474488560'>
In [25]: type(m)
Out[25]: unittest.mock.Mock
In [26]: getattr(m, "foo")
Out[26]: <Mock name='mock.foo' id='140712490825808'>
In [27]: getattr(m, "__foo__")
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [27], in <module>
----> 1 getattr(m, "__foo__")
File …
```

fix(serializer): Make sentry_repr dunder method to avoid mock problems

---

sentry_sdk/scope.py

fixes #1155, not sure why we have this discrepancy between getter and setter behaviour in the first place

fix(perf): Fix transaction setter on scope to use containing_transaction

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/tracing_utils.py

Fix issue from issue #1132 when we get race condition in multithreading with generator based context manager. The generator is not thread safe!

(fix) Change context manager type to avoid race in threads

---

sentry_sdk/integrations/asgi.py
tests/integrations/asgi/test_fastapi.py
tox.ini

✨ Add support for setting transaction name to `path` in FastAPI
This is related to https://github.com/getsentry/sentry-python/issues/829 and https://github.com/getsentry/sentry-python/issues/1165
This would work with FastAPI `0.74.1` that I just released 5 minutes ago.
Most of the functionality is already tested by the Starlette tests. I added a FastAPI test only to test the new `transaction_style="url"`. But I'm not sure if that's desired. If it is, FastAPI would have to be added to the testing dependencies here, but I'm not even sure where, I suspect somewhere in the Tox configs, but I don't really know much about Tox :grimacing: , so I'll wait for feedback first.

✨ Add support for setting transaction name to path in FastAPI

---

sentry_sdk/utils.py

Its usage was removed in 211f7f4 (in 2019-08-09).

Remove obsolete MAX_FORMAT_PARAM_LENGTH

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/tracing_utils.py

* Revert https://github.com/getsentry/sentry-python/pull/1368 since it caused a regression for measuring db span times (https://github.com/getsentry/sentry-python/issues/1385)
* Use context instead of connection in sqlalchemy integration
*  The connection is reused across threads while the context is specific to the query in question.
* Also fix `handle_error` to use the correct `execution_context` where we attach our span context manager.

fix(sqlalchemy): Use context instead of connection in sqlalchemy integration

---

sentry_sdk/client.py

As requested by @mitsuhiko this PR shall serve as basis for discussing the ordering of event drop mechanisms and its implications.
We are planning for `sample_rate` to update the session counts despite dropping an event (see https://github.com/getsentry/develop/pull/551 and https://github.com/getsentry/develop/issues/537). Without changing the order of filtering mechanisms this would mean any event dropped by `sample_rate` would update the session even if it would be dropped by `ignore_errors` which should not update the session counts when dropping an event. By changing the order we would first drop `ignored_errors` and only then check `sample_rate`, so session counts would not be affected in the case mentioned before. The same reasoning could probably be applied to `event_processor` and …

Change ordering of event drop mechanisms

---

setup.py
tox.ini

There is a problem with the newly introduced version constraint for Flask:
https://github.com/getsentry/sentry-python/issues/1391
In this PR we try to fix this.

WIP: try to remove Flask version contraint

---

Makefile
linter-requirements.txt
mypy.ini
sentry_sdk/hub.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/excepthook.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/gcp.py
sentry_sdk/integrations/logging.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/integrations/threading.py
sentry_sdk/integrations/tornado.py
sentry_sdk/utils.py
tox.ini

Fixes https://github.com/getsentry/sentry-python/issues/1415
and https://github.com/getsentry/sentry-python/issues/1081

chore: Bump mypy and fix abstract ContextManager typing

---

docs/conf.py

Noticed while reading the documentation. Of course, with monospaced typewriters two space made sense, but it's 2022.
----
By submitting this pull request, I confirm that Sentry can use, modify, copy, and redistribute this contribution, under Sentry's choice of terms.

conf.py: removed double-spaces after period

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/stale.yml

Restrict the GitHub token permissions only to the required ones; this way, even if the attackers will succeed in compromising your workflow, they won’t be able to do much.
- Included permissions for the action. https://github.com/ossf/scorecard/blob/main/docs/checks.md#token-permissions
https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs
[Keeping your GitHub Actions and workflows secure Part 1: Preventing pwn requests](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)
Signed-off-by: naveen <172697+naveensrinivasan@users.noreply.github.com>

chore: Set permissions for GitHub actions

---

scripts/init_serverless_sdk.py

https://getsentry.atlassian.net/browse/WEBBACKEND-143

feat(extension): Replace original DSN host/port with localhost:3000

---

sentry_sdk/_types.py
sentry_sdk/consts.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py
tests/tracing/test_misc.py

I went with  `set_measurement(name, value, unit)` (singular) instead of `set_measurements` as in JS since I think this is more convenient for the end user. Otherwise they need to build the  name -> unit/value dict themselves.
This should be merged once [develop](https://github.com/getsentry/develop/pull/515#discussion_r819587128) is synced and the changes in relay have been made to support units for `measurements`.

feat(measurements): Add experimental set_measurement api on transaction

---

sentry_sdk/integrations/logging.py
tests/integrations/logging/test_logging.py

See https://github.com/getsentry/sentry-python/issues/1443

Use logging levelno instead of levelname.  Levelnames can be overridden

---

.github/workflows/ci.yml

Refactoring the build process of the AWS Lambda Layer broke the preparations of deploying the Python packages. This fixes it.

Fix Deployment

---

docs/conf.py
sentry_sdk/client.py
sentry_sdk/scope.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py
tests/integrations/stdlib/test_httplib.py
tests/tracing/test_baggage.py
tests/tracing/test_integration_tests.py

* `Baggage` class implementing sentry/third party/mutable logic with parsing from header and serialization
* Parse incoming `baggage` header while starting transaction and store it on the transaction
* Extract `dynamic_sampling_context` fields and add to the `trace` field in the envelope header while sending the transaction
* Propagate the `baggage` header (only sentry fields / no third party as per spec)
[DSC Spec](https://develop.sentry.dev/sdk/performance/dynamic-sampling-context/)
fixes #1476

Dynamic Sampling Context / Baggage continuation

---

sentry_sdk/tracing_utils.py
tests/tracing/test_baggage.py

We are seeing baggage headers coming in with a single comma. This is obviously invalid but Sentry should error out.

Skip malformed baggage items

---

tests/tracing/test_misc.py

There is a small typo in tests/tracing/test_misc.py.
Should read `collector` rather than `collecter`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: fix simple typo, collecter -> collector

---

sentry_sdk/tracing.py

Clearly the intent was to call the function, but previously the `freeze` method was dead code.
I have not verified that this actually works correctly, however.

fix: properly freeze Baggage object

---

.github/workflows/ci.yml
README.md

Travis CI is no longer being used and has been replaced by GitHub Actions.
The ci.yml workflow contains the main tests, so show that status in the README.

Replace Travis CI badge with GitHub Actions badge

---

sentry_sdk/hub.py

We will drop support for 3.4 and 3.5 in a breaking major 2.0.0.
This adds a deprecation warning for the same.
Fixes #1535

Add deprecation warning for 3.4, 3.5

---

setup.py

Fixes #1544
In [one of our previous commits](https://github.com/getsentry/sentry-python/commit/b7c0dc412a1505fff382732f567952c8a9572b60#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7R43) we mistakenly added a quote that was confusing conda.

chore: remove quotes

---

sentry_sdk/integrations/starlette.py

Fixes https://github.com/getsentry/sentry-python/issues/1550
If the header type is not consistent with the body, the SDK currently throws internally.
before
```
(venv) ➜  fastapi git:(main) ✗ curl -X 'POST' \
'http://localhost:8000/token' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d 'grant_type=&username=johndoe&password=secret&scope=&client_id=&client_secret='
Internal Server Error
```
after
```
(venv) ➜  fastapi git:(main) ✗ curl -X 'POST' \
'http://localhost:8000/token' \
-H 'accept: application/json' \
-H 'Content-Type: application/json' \
-d 'grant_type=&username=johndoe&password=secret&scope=&client_id=&client_secret='
{"detail":[{"loc":["body","username"],"msg":"field required","type":"value_error.missing"},{"loc":["body","password"],"msg":"field …
```

Wrap StarletteRequestExtractor in capture_internal_exceptions

---

sentry_sdk/client.py

We noticed that an error occurs when a profile is being uploaded and there is no release set (the error can only occur when profiling is enabled). This PR stops the error from occurring.

Handle no release when uploading profiles

---

sentry_sdk/integrations/redis.py
tests/integrations/redis/test_redis.py
tests/integrations/rediscluster/test_rediscluster.py

Add automatic instrumentation of [redis pipelining](https://redis.io/docs/manual/pipelining/) for both `redis` and `rediscluster`. 
Note: This does not add instrumentation for [`StrictRedisCluster`](https://github.com/Grokzen/redis-py-cluster/blob/master/docs/release-notes.rst#200-aug-12-2019).

feat(redis): Add instrumentation for redis pipeline

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/rq.py
sentry_sdk/integrations/starlette.py
sentry_sdk/integrations/tornado.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/tracing.py
sentry_sdk/utils.py
tests/integrations/celery/test_celery.py
tests/integrations/tornado/test_tornado.py
tests/tracing/test_integration_tests.py

Fixes #1557 
see https://github.com/getsentry/develop/pull/667
`unknown` is only supposed to be inferred by relay as a default and not
set by any SDKs.
Additionally, fix some of the other cases where `start_transaction` was
being called without a source in integrations.

Remove TRANSACTION_SOURCE_UNKNOWN and default to CUSTOM

---

sentry_sdk/integrations/redis.py
tests/conftest.py
tests/integrations/rediscluster/test_rediscluster.py
tests/integrations/sanic/test_sanic.py

fixes #1553
#1504 added parallelization for tox but we have some tests that have global side effects and thus will flake when run concurrently.
* Fixed Sanic tests starting on the same fixed port for older versions 0.8.x and 18.x
* Fixed `rediscluster` test side-effect by resetting integrations list to ensure our monkeypatching happens after the test fixture monkeypatching

Fix side effects for parallel tests

---

sentry_sdk/integrations/redis.py
tests/integrations/rediscluster/test_rediscluster.py
tox.ini

Currently  Sentry uses [`redis-py-cluster==2.1.0`](https://github.com/getsentry/sentry/blob/fd84edc46ad29083c7fe69ff48a159f1ae8ea85a/requirements-frozen.txt#L91) which does not expose the `ClusterPipeline` as a top level object. The fix was introduced in version `2.1.1` and another fix in `2.1.2` see https://github.com/Grokzen/redis-py-cluster/blob/master/docs/release-notes.rst
And getting following error 
```python
09:05:04 [INFO] sentry.plugins.github: apps-not-configured
Traceback (most recent call last):
File "/Users/olksdr/dev/sentry/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 123, in setup_once
_patch_rediscluster()
File "/Users/olksdr/dev/sentry/.venv/lib/python3.8/site-packages/sentry_sdk/integrations/redis.py", line 88, in _patch_rediscluster …
```

fix(redis): import redis pipeline using full path

---

setup.py

For some reason, `poetry` will run the solver at least twice if python version are above 3.6, each with a different constraint for urllib3. This add a significant slowdown on our end in some project.

Add more version constraints

---

sentry_sdk/hub.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py
tests/integrations/sqlalchemy/test_sqlalchemy.py
tests/integrations/stdlib/test_httplib.py
tests/tracing/test_integration_tests.py

Baggage creation for head of trace

---

sentry_sdk/client.py
sentry_sdk/profiler.py

Previously, the only scheduling mechanism was via `signals.SIGPROF`. This was limited to UNIX platforms and was not always consistent. This PR introduces more ways to schedule the sampling. They are the following:
- `_SigprofScheduler` uses `signals.SIGPROF` to schedule
- `_SigalrmScheduler` uses `signals.SIGALRM` to schedule
- `_SleepScheduler` uses threads and `time.sleep` to schedule
- `_EventScheduler` uses threads and `threading.Event().wait` to schedule

feat(profiling): Introduce different profiler schedulers

---

.flake8
.pre-commit-config.yaml
linter-requirements.txt
sentry_sdk/_compat.py
sentry_sdk/api.py
sentry_sdk/hub.py
sentry_sdk/integrations/serverless.py
sentry_sdk/integrations/starlette.py
sentry_sdk/profiler.py
sentry_sdk/utils.py
tests/conftest.py
tests/integrations/aiohttp/test_aiohttp.py
tests/integrations/aws_lambda/test_aws.py
tests/integrations/django/test_basic.py
tests/test_envelope.py

noqa removal was automated via [yesqa](https://github.com/asottile/yesqa)

ref: upgrade linters to flake8 5.x

---

tests/integrations/asgi/__init__.py
tests/integrations/asgi/test_asgi.py
tests/integrations/starlette/test_starlette.py
tox.ini

Rewrote tests to not use Starlette (or any other framework) for testing the `SentryAsgiMiddleware`.

New ASGIMiddleware tests

---

sentry_sdk/profiler.py

Because more time may have elapsed between 2 samples due to us calling the sampling function and other threads executing, we need to account for it in the sleep or the time between samples will often be greater than the expected interval. This change ensures we account for this time elapsed and dynamically adjust the amount of time we sleep for between samples.

fix(profiling): Dynamically adjust profiler sleep time

---

sentry_sdk/integrations/django/signals_handlers.py
tests/integrations/django/test_basic.py

Making sure signal name can also be set when partials are used as signal in  old Django versions in old Python versions.
Fixes #1640

Fix for partial signals in old Django and old Python versions.

---

sentry_sdk/utils.py
tests/integrations/bottle/test_bottle.py
tests/integrations/falcon/test_falcon.py
tests/integrations/flask/test_flask.py
tests/integrations/pyramid/test_pyramid.py
tests/integrations/sqlalchemy/test_sqlalchemy.py

Our python sdk is the only sdk which sends truncated desc from the sdk side. This effects our ability to cleanly detect perf issues, but in general we should probably aim for more consistency. This bumps the max limit by a moderate amount (again, other sdk's are already sending unbounded data). We could potentially go higher (`2048`?). Partially put this up for RFC, but if this is fine then I'll fix tests where required and merge it in.

ref(perf-issues): Increase max string size for desc

---

.github/workflows/test-integration-aiohttp.yml
.github/workflows/test-integration-asgi.yml
.github/workflows/test-integration-aws_lambda.yml
.github/workflows/test-integration-beam.yml
.github/workflows/test-integration-boto3.yml
.github/workflows/test-integration-bottle.yml
.github/workflows/test-integration-celery.yml
.github/workflows/test-integration-chalice.yml
.github/workflows/test-integration-django.yml
.github/workflows/test-integration-falcon.yml
.github/workflows/test-integration-fastapi.yml
.github/workflows/test-integration-flask.yml
.github/workflows/test-integration-gcp.yml
.github/workflows/test-integration-httpx.yml
.github/workflows/test-integration-pure_eval.yml
.github/workflows/test-integration-pyramid.yml
.github/workflows/test-integration-quart.yml
.github/workflows/test-integration-redis.yml
.github/workflows/test-integration-rediscluster.yml
.github/workflows/test-integration-requests.yml
.github/workflows/test-integration-rq.yml
.github/workflows/test-integration-sanic.yml
.github/workflows/test-integration-sqlalchemy.yml
.github/workflows/test-integration-starlette.yml
.github/workflows/test-integration-tornado.yml
.github/workflows/test-integration-trytond.yml
scripts/split-tox-gh-actions/ci-yaml.txt

This will save us some CI minutes when new commits are pushed to the same PR over and over again.
Fixes #1644

Cancel old CI runs when new one is started.

---

tox.ini

New versions of dependencies of Celery have been released that break our test suite. #1656

Fix Celery tests

---

sentry_sdk/integrations/_wsgi_common.py
sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/gcp.py
sentry_sdk/integrations/starlette.py
sentry_sdk/utils.py
tests/integrations/bottle/test_bottle.py
tests/integrations/django/test_basic.py
tests/integrations/flask/test_flask.py
tests/integrations/pyramid/test_pyramid.py
tests/integrations/starlette/test_starlette.py

We did read the whole request body to figuring out the size of the content. This is not optimal at all. Now we read the "content-length" request header and if this header is not there, we just do not touch the request body (because in ASGI the request body is a stream and if it is consumed it can not be accessed again.)
Fixes #1646 
Fixes #1631
Fixes #1595
Fixes #1573

Use content-length header in ASGI instead of reading request body

---

sentry_sdk/client.py
sentry_sdk/profiler.py
sentry_sdk/tracing.py

Attaching thread metadata to the profiles will allow the UI to render a thread name in the thread selector.

feat(profiling): Attach thread metadata to profiles

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/utils.py
tests/test_basics.py

Currently the Python sdk reports always the name `sentry.python` as its name. For consistent sdk naming and better data analysis of events we want to have also include the framework in the SDK name. Like `sentry.python.django`.
Fixes #1497

Include framework in SDK name

---

tests/conftest.py
tests/integrations/wsgi/test_wsgi.py
tests/test_profiler.py

This introduces some basic tests to the setup of the profiler.

test(profiling): Add basic profiling tests

---

sentry_sdk/profiler.py
tests/test_profiler.py

Currently, we use `code.co_name` for the frame name. This does not include the name of the class if it was a method. This tries to extract the qualified name for each frame where possible.
- methods: *typically* have `self` as a positional argument and we can inspect it to extract the class name
- class methods: *typically* have `cls` as a positional argument and we can inspect it to extract the class name
- static methods: no obvious way of extract the class name

feat(profiling): Extract qualified name for each frame

---

sentry_sdk/profiler.py

This is fixing a mistake from #1676, and adding a sample at the start of the profile instead of waiting 1 interval before getting the first sample.

fix(profiling): Need to sample profile correctly

---

sentry_sdk/profiler.py
tests/test_profiler.py

Standardizing the names of the keys in the frames across SDKs so we're going to rename them.

ref(profiling): Rename profiling frame keys

---

.github/workflows/ci.yml

Stumbled upon this when going through the dependabot PRs.

Remove unused node setup from CI.

---

Makefile
tests/integrations/django/myapp/routing.py
tox.ini

From Channels 4.0.0 on it has no ASGI handling included but utilizes Django's own  ASGI handling.

Use Django internal ASGI handling from Channels version 4.0.0.

---

sentry_sdk/integrations/stdlib.py
tests/integrations/stdlib/test_httplib.py

Modifies behavior of putrequest to check for None on real_url prior to using it.
Fixes GH-1678

fix(integrations): Fix http putrequest when url is None

---

sentry_sdk/integrations/starlette.py
tests/integrations/starlette/test_starlette.py

We wrapped the `receive()` callback of all ASGI middleware to create spans when they where executed. 
The `receive()` callback is used to receive message from the server.
But we forgot to return the value that the original `receive()` callback returns. So basically swallowing the return of the server.
Refs #1696

The wrapped receive() did not return anything.

---

sentry_sdk/integrations/starlette.py
tests/integrations/starlette/test_starlette.py

Make sure receive/send callbacks can also be `functools.partial` objects (or other objects that are not having a `__name__`)
Refs #1697

Bug fixes for FastAPI and Sentry SDK 1.10.0

---

sentry_sdk/profiler.py
tests/test_profiler.py

We noticed that generating the sample format at the end of a profile can get rather slow and this aims to improve what we can here with minimal changes. A few things we took advantage of to accomplish this:
- Turning the extracted stack into a tuple so it is hashable so it can be used as a dictionary key. This let's us check if the stack is indexed first, and skip indexing the frames again. This is especially effective in profiles where it's blocking on a network request for example, since there will be many identical stacks.
- Using the hash of the stack as the dictionary key. Hashing the entire stack can be an expensive operation since a stack can have up to 128 frames. Using it as a dictionary key means it needs to be rehashed each time. To avoid this, we pre-hash the stack and use the …

perf(profiling): Tune the sample profile generation code for performance

---

scripts/init_serverless_sdk.py
sentry_sdk/integrations/pure_eval.py

goes with https://github.com/getsentry/action-build-aws-lambda-extension/pull/6
and https://github.com/getsentry/sentry-javascript/pull/6093

Move relay to port 5333 to avoid collisions

---

.github/workflows/test-integration-pymongo.yml
linter-requirements.txt
sentry_sdk/integrations/pymongo.py
setup.py
tests/integrations/pymongo/__init__.py
tests/integrations/pymongo/test_pymongo.py
tox.ini

Adds breadcrumbs and performance traces for PyMongo queries using an
official monitoring API. Integration is similar to the one available in
OpenTelemetry, tags set to values recommended for attributes by OT as
specified in `Span Operations` guidelines.
PyMongo version selection explanation:
* 3.1 - introduction of monitoring API. Only Python 2.7 and 3.6
supported.
* 3.12 - latest 3.x release, support for 2.7, 3.6-3.9 (3.7-3.9 added in
various minor releases between 3.1 and 3.12).
* 4.0 - no support for 2.7, added support for 3.10.
* 4.1 - no support for 3.6.0-3.6.1.
* 4.2 - no support for any 3.6.
Uses `MockupDB` for tests (Python implementation of MongoDB protocol server). `mongomock` is a reimplementation of the `MongoClient` and doesn't support tracing. This way we get real world like …

feat(pymongo): add PyMongo integration

---

sentry_sdk/_compat.py
sentry_sdk/integrations/django/signals_handlers.py
test-requirements.txt
tests/integrations/django/test_basic.py

Our Django signals integrations added a lot of overhead in some cases. 
See: https://github.com/getsentry/sentry-python/issues/1721
This code runs now over an order of magnitude faster for getting the name of a partials.

Performance optimizations

---

sentry_sdk/profiler.py

The sleep scheduler is the most reliable of the available schedulers, make it the default.

ref(profiling): Use sleep scheduler by default

---

sentry_sdk/profiler.py

We currently error if profiling is already setup which can be error prone depending on the end user's setup. This change ensures that we only setup profiling once and once setup, it's reused.

ref(profiling): Do not error if already setup

---

sentry_sdk/integrations/django/signals_handlers.py

When using the newest version of the Python SDK on the sentry backend we get the following error:
```
tests/getsentry/billing/test_staged.py:838: in test_apply_inplace_trigger_post_save
subscription = self.create_subscription(
...
/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/signals_handlers.py:56: in wrapper
signal_name = _get_receiver_name(receiver)
/usr/local/lib/python3.8/site-packages/sentry_sdk/integrations/django/signals_handlers.py:28: in _get_receiver_name
name = "partial(<function " + receiver.func.__name__ + ">)"  # type: ignore
/usr/local/lib/python3.8/unittest/mock.py:639: in __getattr__
raise AttributeError(name)
E   AttributeError: __name__
```
This change gets the `__name__` attribute in a very defensive way, to not raise any errors what so ever.

Fix signals problem on sentry.io

---

sentry_sdk/profiler.py
tests/test_profiler.py

Methods may be inherited from a parent class. If multiple classes inherit from the same class and uses the inherited method, we'd want it to report the parent class's name instead of the individual child classes since they'd have the same filename and lineno of the parent class and not the children.

fix(profiling): Resolve inherited method class names

---

.vscode/settings.json
sentry_sdk/consts.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/tracing.py

No behavior change, just cleaning up.
Preparation for otel.

Add constants for sentry-trace and baggage headers

---

sentry_sdk/tracing.py

* When creating a Span/Transaction a `start_timestamp` can be given. 
* When a Span/Transaction is finished a `end_timestamp` can be given.
Both default to "now" in UTC.

Add API to set custom Span timestamps

---

sentry_sdk/profiler.py
tests/test_profiler.py

Hashing the stack is an expensive operation and the same stack is used for parallel transactions happening on various threads. Instead of hashing it each time it's used.

ref(profiling): Eagerly hash stack for profiles

---

sentry_sdk/client.py
sentry_sdk/profiler.py
sentry_sdk/scope.py

Upto this point, simply taking the current thread when the transaction/profile was started was good enough. When using ASGI apps with non async handlers, the request is received on the main thread. This is also where the transaction or profile was started. However, the request is handled on another thread using a thread pool. To support this use case, we want to be able to set the active thread id on the scope where we can read it when we need it to allow the active thread id to be set elsewhere.

feat(profiling): Introduce active thread id on scope

---

.github/workflows/test-integration-opentelemetry.yml
sentry_sdk/integrations/opentelemetry/__init__.py
sentry_sdk/integrations/opentelemetry/consts.py
sentry_sdk/integrations/opentelemetry/propagator.py
sentry_sdk/integrations/opentelemetry/span_processor.py
sentry_sdk/tracing.py
setup.py
tests/integrations/opentelemetry/__init__.py
tests/integrations/opentelemetry/test_propagator.py
tests/integrations/opentelemetry/test_span_processor.py
tests/tracing/test_noop_span.py
tox.ini

Adding basic OpenTelementry (OTel) support to the Sentry SDK:
* Adding a OTel `SpanProcessor` that can receive spans form OTel and then convert them into Sentry Spans and send them to Sentry.
* Adding a OTel `Propagator` that can receive and propagate trace headers (Baggage) to keep distributed tracing intact.

Basic OTel support

---

CONTRIBUTING.md

`.venv` is what we use in Makefile, and also `.env` is not in `.gitignore` at the moment.

doc: Use .venv (not .env) as a virtual env location in CONTRIBUTING.md

---

sentry_sdk/consts.py
sentry_sdk/integrations/django/views.py
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py

Response rendering can be a source of slow performance in Django, especially with Django rest framework and serializers. This change adds a span to track this.
related: #1250

add span for response rendering

---

sentry_sdk/profiler.py
tests/test_profiler.py

This contains some small tweaks to speed up the profiler.
- changed from a namedtuple to a regular tuple as namedtuples were much slower but the tradeoff here is that it's more legible
- moved away from `os.path.abspath` as it was doing some extra operations that were unnecessary for our use case
- use the previous sample as a cache while sampling

perf(profiling): Performance tweaks to profile sampler

---

sentry_sdk/_compat.py
sentry_sdk/serializer.py
tests/test_serializer.py

Both `bytearray` and `memoryview` built-in types weren't explicitly mentioned in the serializer logic, and as they are subtyping Sequence, this led their instances to be enumerated upon, and to be output as a list of bytes, byte per byte.
In the case of `memoryview`, this could also lead to a segmentation fault if the memory referenced was already freed and unavailable to the process by then.
By explicitly adding them as seralizable types, bytearray will be decoded as a string just like bytes, and memoryview will use its __repr__ method instead.
Close GH-1829
-----
I noticed Python 2.7 was still supported, so I also attempted to add the fix for this version.
However `bytearray` and `memoryview` were introduced by Python 2.7, so this PR introduces code that is not supported by Python 2.6 …

fix(serializer): Add support for `bytearray` and `memoryview` types

---

sentry_sdk/tracing.py
tests/tracing/test_noop_span.py

When using otel as the instrumentor, the NoOpSpan needs to update the scope when it's used as a context manager. If it does not, then this differs from the usual behaviour of a span and the end user may start seeing an unexpected `None` on the scope.

fix(otel): NoOpSpan updates scope

---

codecov.yml
sentry_sdk/_types.py
sentry_sdk/client.py
sentry_sdk/consts.py
tests/test_basics.py

Callback function that is called for all transactions (in opposite to `before_send` which is only called for issue events)
Fixes #1738

Add `before_send_transaction`

---

sentry_sdk/integrations/asgi.py

By changing the order in the condition, we can avoid the call to `_get_installed_modules` at import time (which imports `pkg_resources`) when the `mechanism_type` is set to `"starlette"`.
I have validated the change using `PYTHONPROFILEIMPORTTIME=1`.
Tell me if such a change requires a link to an issue or some testing.

Avoid import of pkg_resource with Starlette integration

---

sentry_sdk/integrations/opentelemetry/span_processor.py
tests/integrations/opentelemetry/test_span_processor.py

fixes https://github.com/getsentry/sentry-python/issues/1846

fix(opentelemetry): Use dict for sentry-trace context instead of tuple

---

sentry_sdk/integrations/starlette.py

When the `StarletteIntegration` is used in a FastAPI app, as instructed in [the docs](https://docs.sentry.io/platforms/python/guides/fastapi/), the `AuthenticationMiddleware` and `ExceptionMiddleware` get patched every time `add_middleware` or `add_exception_handler` is called, since these methods call `build_middleware_stack`, where patched `Middleware` instances are repatched without checking if they were already patched.
If these functions are called enough times, Python registers this as infinite recursion (as we've discovered).
The changes look broad, but amount to the addition of two `if not_yet_patched` checks and indentation.

Fix middleware being patched multiple times when using FastAPI

---

sentry_sdk/_compat.py
sentry_sdk/profiler.py
tests/test_profiler.py

The `get_frame_name` implementation works well for <3.11 but 3.11 introduced a `co_qualname` that works like our implementation of `get_frame_name` and handles some cases better.

feat(profiling): Use co_qualname in python 3.11

---

sentry_sdk/profiler.py
sentry_sdk/utils.py
tests/utils/test_general.py

Currently, the SDK marks all frames as in_app when it can't find any in_app frames. As we try to move some of this detection server side, we still want to allow the end user to overwrite the decision client side. So we'll leave in_app as `None` to indicate the server should decide of the frame is in_app.

fix(profiling): Default in_app decision to None

---

sentry_sdk/client.py
sentry_sdk/scope.py

These logger statements probably made sense at an earlier state of the SDK, but now events are sufficiently complex that logging the whole dict makes no sense and cause issues such as the linked issue when large bytes payloads are included.
Fixes #1856

Don't log whole event in before_send / event_processor drops

---

sentry_sdk/hub.py
sentry_sdk/integrations/asgi.py
sentry_sdk/integrations/django/asgi.py
sentry_sdk/integrations/django/views.py
sentry_sdk/integrations/fastapi.py
sentry_sdk/integrations/starlette.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/profiler.py
sentry_sdk/tracing.py
tests/integrations/django/asgi/test_asgi.py
tests/integrations/fastapi/test_fastapi.py
tests/integrations/starlette/test_starlette.py
tests/test_profiler.py

Up to now, we've only been profiling WSGI + ASGI transactions. This change will enable profiling for all transactions.

feat(profiling): Enable profiling on all transactions

---

sentry_sdk/integrations/flask.py

This line seems like a copy/paste error, introduced in 41120009fa7d6cb88d9219cb20874c9dd705639d.
The email address is already set a few lines above for "email".
Unless I'm missing some very clever fallback magic, considering the `try/catch` around this, I think this is a mistake and the email address should not be used as username.

Do not overwrite default for username with email address in Flask-Login integration

---

sentry_sdk/integrations/fastapi.py

When loading FastAPI integration also check if `StarletteIntegration` can actually be loaded. (Because Starlette is a requirement for FastAPI)
Fixes #1603

Fix check for Starlette in FastAPI integration

---

sentry_sdk/profiler.py

As pointed out in https://github.com/getsentry/sentry-python/issues/1813#issuecomment-1406636598, gevent patches the `time` module and `time.sleep` will only release the GIL if there no other greenlets ready to run. This ensures that we always use the builtin `time.sleep` and not the patched version provided by `gevent`.

fix(profiling): Always use builtin time.sleep

---

sentry_sdk/profiler.py
sentry_sdk/tracing.py
tests/integrations/django/asgi/test_asgi.py
tests/integrations/fastapi/test_fastapi.py
tests/integrations/starlette/test_starlette.py
tests/integrations/wsgi/test_wsgi.py
tests/test_profiler.py

Single sample profiles are dropped in relay so there's no reason to send them to begin with. Save the extra bytes by just not sending it.

ref(profiling): Do not send single sample profiles

---

sentry_sdk/utils.py
tests/integrations/wsgi/test_wsgi.py
tests/test_basics.py

see [JS implementation](https://github.com/getsentry/sentry-javascript/blob/e497bcda305a9c248dcdc78f48fe548cc58f8233/packages/utils/src/misc.ts#L99)

Mechanism should default to true unless set explicitly

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/profiler.py
sentry_sdk/utils.py
tests/integrations/django/test_basic.py
tests/test_client.py
tests/utils/test_general.py

How the `in_app` flag is set in stack trace frames (in `set_in_app_in_frames()`):
- If there is already `in_app` set, it is left untouched.
- If there is a `module` in the frame and it is in the `in_app_includes` -> `in_app=True`
- If there is a `module` in the frame and it is in the `in_app_excludes` -> `in_app=False`
- If there is an `abs_path` in the frame and the path is in `/side-packages/` or `/dist-packages/` -> `in_app=False`
- If there is an `abs_path` in the frame and it starts with the current working directory of the process -> `in_app=True`
- If nothing of the above is true, there will be no `in_app` set.
Fixes #1754 
Fixes #320

Better setting of in-app in stack frames

---

sentry_sdk/profiler.py
sentry_sdk/tracing.py
sentry_sdk/utils.py

We want the profile to be as closely aligned with the transaction's timestamps as possible to make aligning the two visualizations as accurate as possible. Here we change the transaction's internal `_start_timestamp_monotonic` to be in nanoseconds derived from each of the possible clocks we use in the various python versions. This allows us to use the `start_timestamp` of the transaction as the timestamp of the profile, and we can use the `_start_timestamp_monontonic` as the anchor for all the relative timestamps in the profile.

ref(profiling): Use the transaction timestamps to anchor the profile

---

LICENSE
README.md
setup.py

The license of our SDKs should be MIT.
https://open.sentry.io/licensing/
Part of https://github.com/getsentry/team-ospo/issues/56.

Switch to MIT license

---

.vscode/settings.json
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/signals_handlers.py
tests/integrations/django/test_basic.py

Adds an option `signals_spans` to the DjangoIntegrations that works the same as `middleware_spans` so the tracing of Django signals can be turned of.
Also I cleaned up the tests a bit.
Fixes #1893

Make Django signals tracing optional

---

sentry_sdk/integrations/flask.py

As explained in [this bug report](https://github.com/getsentry/sentry-python/issues/1936), recent versions of werkzeug [introduced](https://github.com/pallets/werkzeug/pull/2355) the behaviour to `get_json` where it will throw an error when content_type isn't set.

fix(integration): fix FlaskIntegration for Werkzeug > 2.1.0

---

sentry_sdk/integrations/quart.py
tests/integrations/quart/test_quart.py

Following up to #1824 to set the active thread id for quart.

feat(profiling): Set active thread id for quart

---

tests/conftest.py
tests/integrations/stdlib/test_httplib.py

Changed tests to not make actual HTTP requests. And because we monkey patch very low level HTTP libs of Python it is hard to mock them, because most of the time our monkey patches are overwritten by the mock. So I created an actual HTTP server to make requests to.
Fixes #1920

Start a real http server instead of mocking libs

---

sentry_sdk/__init__.py
sentry_sdk/api.py
tests/test_api.py

Idea originated in this comment of a code review: https://github.com/getsentry/sentry-python/pull/1089#discussion_r1133985202

Added top level api to get current span and transaction

---

tox.ini

The newer versions of fakeredis does not install `async-timeout` which it needs.

fix(tests): Bad arq dependency in tests

---

sentry_sdk/profiler.py
tox.ini

We've received report that occasionally, there's `AttributeError` on `f_back`. It's unclear what exactly causes this issue because the source of the frame is from a system libray. This avoids the `AttributeError` by wrapping the line in question with a `try ... except ...`. And whenever it does encounter this error, we should continue with what frames we have.
Closes #1958

fix(profiling): Handle non frame types in profiler

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/scrubber.py
sentry_sdk/serializer.py
tests/test_scrubber.py

Add a new `EventScrubber` class that scrubs certain potentially sensitive interfaces with a `DEFAULT_DENYLIST`. The default scrubber is automatically run if `send_default_pii = False`.
```python
from sentry_sdk.scrubber import EventScrubber, DEFAULT_DENYLIST
denylist = DEFAULT_DENYLIST + ["my_sensitive_var"]
send_default_pii=False,
event_scrubber=EventScrubber(denylist=denylist),
)
```
As outlined in https://github.com/getsentry/rfcs/blob/main/text/0062-controlling-pii-and-credentials-in-sd-ks.md
closes #1897 
docs: https://github.com/getsentry/sentry-docs/pull/6489

Implement EventScrubber

---

sentry_sdk/tracing_utils.py
tests/tracing/test_baggage.py

Forward all baggage items that are prefixed with `sentry-`.
Refs https://github.com/getsentry/team-webplatform-meta/issues/41

ref: Forward all `sentry-` baggage items

---

sentry_sdk/client.py
sentry_sdk/consts.py
tests/test_basics.py
tox.ini

Have a list of functions that can be passed to "sentry_sdk.init()". When the SDK starts it goes through the list and instruments all the functions in the list. 
```python
functions_to_trace = [
{"qualified_name": "tests.test_basics._hello_world_counter"},
{"qualified_name": "time.sleep"},
{"qualified_name": "collections.Counter.most_common"},
]
dsn="...",
traces_sample_rate=1.0,
functions_to_trace=functions_to_trace,
)
```
Fixes #1963 
Docs: https://github.com/getsentry/sentry-docs/pull/6520
Fixes https://github.com/getsentry/team-webplatform-meta/issues/19

Centralized way to configure custom instrumentation

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery_beat_crons.py

- Small update to support Celery 4 and 5
- Changed the name of the schedule shelf file that we patch to have the suffix `-patched-by-sentry-sdk` instead of `.new` so in case there is an error with this new shelf file somewhere the users know that it is patched by the sentry sdk.
- Additionally some minor tweaks to make code more readable

Auto monitoring beat update

---

sentry_sdk/profiler.py
sentry_sdk/utils.py
tests/test_profiler.py

This change adds additional performance improvements to the profiler after observing the following:
- extracting the full frame information is expensive, but we only need to do it once since the subsequent occurrences can reuse previous results
- the abs_path + lineno is sufficient to uniquely identify a frame, so use that as the frame key

perf(profiling): Additionl performance improvements to the profiler

---

sentry_sdk/client.py
tests/conftest.py
tests/integrations/gcp/test_gcp.py
tests/test_client.py

When tracing is enabled we can safely send all events to `/envelope`. The dynamic sampling context (DSC) is sent with all envelopes.
The legacy `/store` endpoint will be removed in the future.
Fixes #2008

Send all events to /envelope endpoint when tracing is enabled

---

sentry_sdk/integrations/redis.py
sentry_sdk/tracing_utils.py
tests/integrations/redis/test_redis.py

This PR updates handling of data in the redis SDK:
- Arguments of the redis AUTH command is never collected (because it contains username and password)
- When `send_default_pii=False` the arguments of all redis commands are redacted (except the first parameter, because it is always the "key" and thus important for debugging
- Span descriptions and breadcrumb message are truncated to a max size of 1024 (the max size can be configured in a new argument to `RedisIntegration(max_data_size=30)` (if `max_data_size` is set to a falsie value (0 or None) then no truncation is done)

Better handling of redis span/breadcrumb data

---

sentry_sdk/integrations/celery.py

Somehow it can happen that `task.request.get("headers", {})` returned `None`.

Made code more resilient.

---

.github/workflows/ci.yml
linter-requirements.txt
mypy.ini
sentry_sdk/integrations/asyncio.py
sentry_sdk/integrations/celery.py
sentry_sdk/integrations/django/signals_handlers.py
sentry_sdk/integrations/socket.py
sentry_sdk/integrations/tornado.py
sentry_sdk/integrations/wsgi.py
sentry_sdk/profiler.py
sentry_sdk/tracing.py
sentry_sdk/utils.py
tox.ini

I had to remove and/or add some `# type:ignore` type hints because `mypy` does different things in Python 3.9 (the version we run it in earlier) and Python 3.11 (the version we run it in now)

Upgraded linting tooling 

---

sentry_sdk/integrations/redis.py
tests/integrations/redis/test_redis.py
tests/integrations/rediscluster/test_rediscluster.py

Dependent on https://github.com/getsentry/sentry-python/pull/2037
Extracted from https://github.com/getsentry/sentry-python/pull/2035

feat(redis): Add `db.system` to redis db spans

---

sentry_sdk/profiler.py

We've noticed some edge cases where the api doesn't return the expected `FrameType` or is missing some attributes. There isn't much we can do about this other than to handle the error and drop the sample.
Closes #2022

fix(profiling): Handle potential attribute errors in profiler

---

sentry_sdk/integrations/django/__init__.py
test-requirements.txt
tests/integrations/django/test_basic.py
tox.ini

ref https://github.com/getsentry/team-webplatform-meta/issues/60
So worked out when testing locally + the types seem to enforce this, and it works on all django versions, so I think this is good to go.

feat(django): Add `db.system`

---

mypy.ini
sentry_sdk/_lru_cache.py
sentry_sdk/profiler.py
tests/test_lru_cache.py
tests/test_profiler.py

The profiler can capture frames from it's own thread. When it does so, it holds on to a reference to the frame in the previous sample. One of the frames it holds on it is a frame from the profiler itself, which prevents the references to other frames to other frames from being freed. A consequence of this is that the local variables of those frames are not able to be freed either. This change ensures we do not keep a reference to the profiler around in order to prevent this issue.
Closes #1980

fix(profiling): Do not keep reference to frame

---

sentry_sdk/client.py

Fixes https://github.com/getsentry/sentry-python/issues/1979

Handle event being None before before_send_(transaction)

---

sentry_sdk/crons/api.py
tests/test_crons.py

This fixes a regression introduced in 1.18 which caused monitor
check-ins without a `monitor_config` to be rejected by relay.
Fixes https://github.com/getsentry/sentry-python/issues/2052

fix(crons): Do not send monitor_config when unset

---

setup.py

urllib3 released a major which breaks with openssl on some AWS runtimes and some other setups (#2051)
Pin for now and we can investigate changes needed separately.
fixes #2051 
(for now)

Pin urllib3 to <2.0.0 for now

---

sentry_sdk/integrations/boto3.py
sentry_sdk/integrations/httpx.py
sentry_sdk/integrations/stdlib.py
tests/integrations/httpx/test_httpx.py
tests/integrations/requests/test_requests.py
tests/integrations/stdlib/test_httplib.py

~Blocked on https://github.com/getsentry/sentry-python/pull/2053 merging, so draft for now.~
As per https://develop.sentry.dev/sdk/performance/span-data-conventions/, we want to rename `method` being set on spans to `http.method`. This better aligns with otel, and also removes ambiguity when operating in Relay.

feat: Use `http.method` instead of `method`

---

sentry_sdk/integrations/sqlalchemy.py
tests/integrations/sqlalchemy/test_sqlalchemy.py

There are cases where `engine.name` in sqlalchemy is not a string (see https://github.com/getsentry/sentry-python/issues/2071). 
Fixes https://github.com/getsentry/sentry-python/issues/2071

Handle sqlalchemy engine.name being bytes

---

setup.py

The original contribution by @jsmitka included a bug fix that has in the mean time also been implemented by us (I was just to slow in merging the PR).

Added test from contributor

---

sentry_sdk/integrations/starlette.py

Fixes https://github.com/getsentry/sentry-python/issues/2062

Handle non-int exc.status_code in starlette

---

sentry_sdk/integrations/threading.py
tests/integrations/threading/test_threading.py

Should fix compatibility with OpenCensus threading integration 
fixes #2076

Use functools.wrap for ThreadingIntegration patches to fix attributes

---

sentry_sdk/integrations/django/caching.py

Dogfooding (or at least trying to) in our own project already found a problem: 
https://github.com/getsentry/sentry/actions/runs/4893658363/jobs/8736882698?pr=48624#step:5:345
This fixes it that args can also be a list of lists.

Fix: Handle a list of keys (not just a single key) in Django cache spans

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery_beat_crons.py

We can not use a `perf_counter` when dealing with duration's of Celery tasks, because the start of a Celery tasks and the finish are recorded in different processes.
Start happens in the Celery Beat process, the end in the Celery Worker process.
Fixes #2078

Fix: Duration in Celery Beat tasks monitoring

---

sentry_sdk/consts.py
sentry_sdk/integrations/django/caching.py
tests/integrations/django/test_basic.py

- Fix problem when the cache key is given with kwargs (instead of positional args)
- Using the more specific `cache.get_item` span `op` because we only patch the getting cache functions.
Fixes #2085

Django caching span fixes

---

sentry_sdk/consts.py
sentry_sdk/integrations/pymongo.py
sentry_sdk/integrations/redis.py
tests/integrations/redis/test_redis.py
tests/integrations/rediscluster/test_rediscluster.py

Add `db.operation` to Redis and MongoDB spans.

---

.github/workflows/test-integration-loguru.yml
linter-requirements.txt
sentry_sdk/integrations/logging.py
sentry_sdk/integrations/loguru.py
setup.py
tests/integrations/loguru/__init__.py
tests/integrations/loguru/test_loguru.py
tox.ini

Actually, this is the solution in comments under #653 adapted to codebase and tested as well.
https://github.com/getsentry/sentry-python/issues/653#issuecomment-788854865
I also changed `logging` integration to use methods instead of functions in handlers, as in that way we can easily overwrite parts that are different in `loguru` integration. It shouldn't be a problem, as those methods are private and used only in that file.
Please let me know if I missed something, or you have more ideas how to test this.
Fixes #653.

Add `loguru` integration

---

.github/workflows/ci.yml
.github/workflows/test-integration-loguru.yml
Makefile
linter-requirements.txt
scripts/aws-delete-lamba-layer-versions.sh
scripts/aws-deploy-local-layer.sh
scripts/build_aws_lambda_layer.py
scripts/init_serverless_sdk.py
sentry_sdk/integrations/logging.py
sentry_sdk/integrations/loguru.py
setup.py
tests/integrations/loguru/__init__.py
tests/integrations/loguru/test_loguru.py
tox.ini

we're reverting back to the older setup since the whole 'relay as AWS extension' experiment didn't really work out.
* remove gh action that bundles relay
* remove port override in DSN
* zip in place as part of `make build_aws_lambda_layer`
part of https://github.com/getsentry/team-webplatform-meta/issues/58

Remove relay extension from AWS layer

---

sentry_sdk/client.py
sentry_sdk/serializer.py
tests/integrations/bottle/test_bottle.py
tests/integrations/flask/test_flask.py
tests/integrations/pyramid/test_pyramid.py
tests/test_serializer.py

We've received quite some feedback regarding our automatic request body trimming making it harder to debug issues. This PR changes the behavior of our serializer so that we don't apply our `MAX_DATABAG_BREADTH` and `MAX_DATABAG_DEPTH` limits if the SDK has been initialized with `request_bodies="always"`.
Fixes https://github.com/getsentry/sentry-python/issues/1041

Do not truncate body if `request_bodies` is `"always"`

---

sentry_sdk/utils.py
tests/test_utils.py

- Added `include_source_context` option to `serialize_frame` function to allow users to opt-out of getting source context.
This is my very first open-source contribution. Please let me know if I missed something.
Fixes #2017

Ref: Add `include_source_context` option in utils

---

sentry_sdk/integrations/asyncio.py

fixes #2093 
I'll add a test case if the user comes up with a sample task that fails for him

Fix __qualname__ missing attribute in asyncio integration

---

sentry_sdk/integrations/flask.py
setup.py

Fixes a `DeprecationWarning` when using Flask v2.3.0 or later (actually, it breaks completely with `flask==2.3.0`, but that's down to a mistake in the Flask project. Some tests are failing for me locally, but the same tests are failing on the `master` branch so hopefully that's just something peculiar to my machine.
See [Flask's release notes](https://flask.palletsprojects.com/en/2.3.x/changes/#version-2-3-0) for more context.

Import Markup from markupsafe

---

sentry_sdk/consts.py
sentry_sdk/utils.py
tests/test_client.py

The possibility to omit source context was added in https://github.com/getsentry/sentry-python/pull/2020, this PR surfaces it as a client option.
https://github.com/getsentry/sentry-python/issues/2017

Surface `include_source_context` as a client option

---

sentry_sdk/integrations/redis.py

...not the module, if there is one present.
https://github.com/getsentry/sentry-python/issues/1402

Make sure we're importing `redis` the library

---

sentry_sdk/integrations/django/__init__.py
tests/integrations/django/test_basic.py

Users were telling us that the cache spans are adding to much overhead onto their servers, so we are disabling cache spans by default and make them opt-in.

This disables Django Cache spans by default.

---

sentry_sdk/integrations/modules.py
tests/integrations/modules/test_modules.py
tests/integrations/pyramid/test_pyramid.py

Let's not use `pkg_resources` and avoid a `DeprecationWarning` if `importlib.metadata` is available.
Fixes https://github.com/getsentry/sentry-python/issues/2048

Prefer importlib.metadata over pkg_resources if available

---

sentry_sdk/integrations/_wsgi_common.py
sentry_sdk/integrations/asgi.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/fastapi.py
sentry_sdk/integrations/gcp.py
sentry_sdk/integrations/starlette.py
sentry_sdk/utils.py
tests/integrations/fastapi/test_fastapi.py
tests/integrations/flask/test_flask.py
tests/integrations/starlette/test_starlette.py
tests/test_scrubber.py

In some cases we were attaching parts of the original request to the event with live references on them and ending up modifying the underlying headers or request data when we scrubbed the event. Now we make sure to only attach a copy of the request to the event. We also do the same for frame vars.
See:
- https://github.com/getsentry/sentry-python/issues/2109
- https://github.com/getsentry/sentry-python/issues/2114

Work with a copy of request, vars in the event

---

sentry_sdk/crons/api.py
sentry_sdk/integrations/celery.py
sentry_sdk/tracing_utils.py
sentry_sdk/utils.py
tests/integrations/celery/test_celery_beat_crons.py
tests/test_utils.py

Adds a `exclude_beat_tasks` option to `CeleryIntegration` where users can exclude Celery Beat tasks from being auto-instrumented.
Fixes #2119

Celery beat exclude option

---

sentry_sdk/consts.py

This updates the type of the `functions_to_trace` param to match the latest changes.
The expected format introduced [here](https://github.com/getsentry/sentry-python/pull/1960) is:
```
functions_to_trace = [
{"qualified_name": "tests.test_basics._hello_world_counter"},
{"qualified_name": "time.sleep"},
{"qualified_name": "collections.Counter.most_common"},
]
```
But the current type is `List[str]`

fix: functions_to_trace typing

---

tests/integrations/modules/test_modules.py

Current logic in `test_installed_modules` does not properly handle
distributions with underscores. On my machine I get the following error
while running tests:
```
tests/integrations/modules/test_modules.py:60: in test_installed_modules
assert installed_modules == pkg_resources_modules
E   AssertionError: assert {'aiven-clien...'22.2.0', ...} == {'aiven-clien...'22.2.0', ...}
E     Omitting 93 identical items, use -vv to show
E     Left contains 1 more item:
E     {'tomli_w': '1.0.0'}
E     Right contains 1 more item:
E     {'tomli-w': '1.0.0'}
E     Use -v to get more diff
```
This change fixes distribution name normalization by applying the code
from PEP-0503 (https://peps.python.org/pep-0503/#normalized-names).

Fix distribution name normalization (PEP-0503)

---

docs/conf.py
sentry_sdk/integrations/cloud_resource_context.py
sentry_sdk/integrations/opentelemetry/span_processor.py
sentry_sdk/transport.py
setup.py
tests/integrations/cloud_resource_context/test_cloud_resource_context.py

Reverts getsentry/sentry-python#2069
Resolves #2070
this shouldn't have been pinned in the first place.  the actual failure was unrelated to sentry.  _they_ should have pinned in their app -- a library should not make this decision for its users

Revert "Pin urllib3 to <2.0.0 for now"

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/arq.py
sentry_sdk/integrations/boto3.py
sentry_sdk/integrations/bottle.py
sentry_sdk/integrations/chalice.py
sentry_sdk/integrations/falcon.py
sentry_sdk/integrations/flask.py
sentry_sdk/integrations/rq.py
sentry_sdk/integrations/sanic.py
sentry_sdk/integrations/sqlalchemy.py
sentry_sdk/utils.py
tests/test_utils.py

This now uses the PEP 440 reference implementation [1] to parse version strings. 
Fixes #1095 
Fixes #1941 
1: https://peps.python.org/pep-0440/#appendix-b-parsing-version-strings-with-regular-expressions

Better version parsing

---

sentry_sdk/integrations/boto3.py
sentry_sdk/integrations/httpx.py
sentry_sdk/integrations/stdlib.py
tests/conftest.py
tests/integrations/boto3/test_s3.py
tests/integrations/httpx/test_httpx.py
tests/integrations/requests/test_requests.py
tests/test_utils.py

Follow up to https://github.com/getsentry/sentry-python/issues/2160
Our URL parsing and sanitizing can fail. If it does, the error must never break the user's application.
This PR:
- wraps all calls to `parse_url` in `capture_internal_exceptions` and skips setting any parsed URL related data on the span (affects the `stdlib`, `boto3`, `httpx` integrations)
- adds more test cases for the `sanitize_url` function with `split=True`

Wrap `parse_url` calls in `capture_internal_exceptions`

---

sentry_sdk/profiler.py
tests/test_profiler.py

Wrapper functions can take on the same name as the wrapped function. This means that if a decorator is used to wrap different functions, even though the filename and line number will be the same for all instances of the frame, the function name can vary. Add the function name to the cache to avoid these cache collisions.

fix(profiler): Add function name to profiler frame cache

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery_beat_crons.py

In Celery you can run task in intervals shorter than one minute. Sentry crons does not support this, so in a case where a sub-minute interval is specified, just print a warning and do not set a schedule configuration.
Fixes #2168

Do not support sub-minute cron intervals

---

sentry_sdk/integrations/opentelemetry/propagator.py
sentry_sdk/integrations/opentelemetry/span_processor.py
tests/integrations/opentelemetry/test_propagator.py
tests/integrations/opentelemetry/test_span_processor.py

This builds on top of #1995, while also applying the same fix to `SentrySpanProcessor`.

fix: fix propagation of OTEL NonRecordingSpan

---

tests/integrations/sqlalchemy/test_sqlalchemy.py
tox.ini

Make sure our SQLAlchemy integration works with SQLAlchemy 1.4 and 2.0.
Fixes #2174

Support for SQLAlchemy 2.0

---

sentry_sdk/integrations/celery.py
sentry_sdk/integrations/httpx.py
tests/integrations/celery/test_celery.py
tests/integrations/httpx/test_httpx.py

If there's custom data in the `baggage` header of an outgoing request, we should preserve it when adding our custom sentry tracing baggage items.
Closes https://github.com/getsentry/sentry-python/issues/2190

Do not overwrite existing baggage on outgoing requests

---

sentry_sdk/api.py
sentry_sdk/hub.py

Use new top level api in trace_propagation_meta and also move the functions into the Hub, so they can be used in the Hub. (following the pattern of other top level API)
Refs #2186

Use new top level api in `trace_propagation_meta`

---

.github/workflows/ci.yml
docs-requirements.txt
docs/conf.py

This should be a quick fix to address some visual overlapping issues that we currently have (see screenshot https://github.com/getsentry/sentry-python/issues/2196).

Change API doc theme

---

sentry_sdk/integrations/aiohttp.py
tests/integrations/aiohttp/test_aiohttp.py

Adds instrumentation of client requests for aiohttp. See https://docs.aiohttp.org/en/stable/client_advanced.html#client-tracing for aiohttp documentation on tracing hooks for client requests.
This change could arguably go in a separate AioHttpClientIntegration but will leave that for discussion.

feat(aiohttp): add instrumentation of client requests

---

sentry_sdk/profiler.py
tests/test_profiler.py

To help understand the client discard in profiles better.

feat(profiling): Add client reports for profiles

---

sentry_sdk/integrations/aiohttp.py
tests/integrations/aiohttp/test_aiohttp.py

Do not override custom baggage when using `aiohttp` as a client.
Closes #2211

Append to existing aiohttp baggage

---

docs/api.rst
sentry_sdk/api.py
sentry_sdk/client.py
sentry_sdk/hub.py
sentry_sdk/integrations/logging.py
sentry_sdk/tracing.py

- Support autocompletion for the most commonly used args/kwargs of the top level API and remove some arg duplication. Couldn't get this done for everything and for all args/kwargs, but it should be an improvement compared to now. Step by step.
- Also added `Span` and `Transaction` to the docs. (For some reason, autodocumenting the `tracing.py` module doesn't do anything so had to add the classes explicitly.)
- Expanded some docstrings, too.
Fixes https://github.com/getsentry/sentry-python/issues/2199
Fixes https://github.com/getsentry/sentry-python/issues/2196

Allow (some) autocompletion for top-level API

---

scripts/runtox.sh
sentry_sdk/integrations/django/templates.py
tests/integrations/django/myapp/templates/trace_meta.html
tests/integrations/django/myapp/urls.py
tests/integrations/django/myapp/views.py
tests/integrations/django/test_basic.py

Adding `sentry_trace_meta` to template context so meta tags including Sentry trace information can be rendered using `{{ sentry_trace_meta }}` in the Django templates

Add Django template tag for adding sentry tracing information

---

sentry_sdk/api.py
sentry_sdk/hub.py
sentry_sdk/tracing.py

The `partial` hack enabled us to have nicer sphinx docs, but broke any autocompletion in PyCharm.

Revert `partial` hack, but keep docs

---

tests/integrations/starlette/test_starlette.py
tox.ini

Update our test matrix to support current Starlette versions. (only testing every other version, because otherwise it would be too much versions to test)

Support newest starlette versions

---

sentry_sdk/integrations/aiohttp.py

fix(aiohttp): Handle explicitly passing `None` for `trace_configs`

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/monitor.py
sentry_sdk/tracing.py
sentry_sdk/transport.py
sentry_sdk/worker.py
tests/test_monitor.py

* Monitor class performs health checks in a thread every 10s
* if not healthy, we downsample / halve in steps till healthy again
* exposed as experimental `enable_backpressure_handling`
related to #2095 and https://github.com/getsentry/team-webplatform-meta/issues/50

Backpressure prototype

---

sentry_sdk/hub.py
sentry_sdk/tracing.py

If OpenTelementry is enabled, the `sentry-trace` headers should not be applied by Sentry intregration, but only by the OTel propagator.
Fixes #1940

Prevent adding `sentry-trace` header multiple times

---

sentry_sdk/tracing_utils.py
tests/tracing/test_misc.py

Do not add trace headers to requests to Sentry

---

sentry_sdk/integrations/modules.py
tests/integrations/modules/test_modules.py

In rare cases, `importlib.metadata` values may contain `None`, see
https://github.com/python/cpython/issues/91216
and
https://github.com/python/importlib_metadata/issues/371
The fix skips all distributions with incomplete metadata.

Skip distributions with incomplete metadata

---

sentry_sdk/tracing_utils.py
tests/integrations/aiohttp/test_aiohttp.py
tests/integrations/celery/test_celery.py
tests/integrations/httpx/test_httpx.py
tests/integrations/stdlib/test_httplib.py
tests/test_api.py
tests/tracing/test_integration_tests.py

Add Sampling Decision to Trace Envelope Header

---

sentry_sdk/integrations/celery.py
sentry_sdk/scope.py

When tasks are started by Celery Beat they should not inherit the trace from the starting code (which is Celery Beat) but get their own trace.

Make sure each task that is started by Celery Beat has its own trace.

---

tox.ini

We don't have workflows testing on 3.4 anymore.

Remove py3.4 from tox.ini

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/integrations/_wsgi_common.py
sentry_sdk/serializer.py
sentry_sdk/utils.py
test-requirements.txt
tests/integrations/bottle/test_bottle.py
tests/integrations/flask/test_flask.py
tests/integrations/pyramid/test_pyramid.py
tests/test_client.py
tests/test_serializer.py

Hi!
This PR fixes https://github.com/getsentry/sentry-python/issues/926
~🎗️ Question: Where can I update the Sentry's documentation for this change? https://docs.sentry.io/platforms/python/configuration/options/#request-bodies~

ref(integrations): Rename `request_bodies` to `max_request_body_size`

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery_beat_crons.py

This adds both the name of the problematic monitor and a suggestion of how to fix the problem to the error message about crons with < 1 min intervals.

ref(crons): Add information to short-interval cron error message

---

sentry_sdk/integrations/aiohttp.py
sentry_sdk/integrations/httpx.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/scrubber.py
sentry_sdk/utils.py
tests/conftest.py
tests/integrations/aiohttp/test_aiohttp.py
tests/integrations/httpx/test_httpx.py
tests/integrations/requests/test_requests.py
tests/integrations/stdlib/test_httplib.py
tests/test_utils.py

Inspect requests done with our HTTP client integrations (`stdlib`, `httpx`, `aiohttp`), identify GraphQL requests, and capture a specialized error event if the response from the server contains a non-empty `errors` array.
Closes https://github.com/getsentry/sentry-python/issues/2198

Capture GraphQL client errors

---

sentry_sdk/integrations/redis/__init__.py

In https://github.com/getsentry/sentry-python/pull/2038 we didn't add `db.system` to all the redis spans. This PR adds `db.system` span data to the redis spans we missed.
resolves https://www.notion.so/sentry/db-system-value-is-missing-in-Redis-spans-1c381ac16d724a58bbefd98481c93545

feat(redis): Add db.system to remaining redis spans

---

tox.ini

The dependency resolution for some of our chalice tests had a hard time identifying a good version of botocore (a chalice dependency) to install. Pinning it now.
Taking this out of https://github.com/getsentry/sentry-python/pull/2274

Fix chalice tests

---

sentry_sdk/client.py
tests/test_crons.py
tests/tracing/test_sampling.py

Always sample checkin regardless of sample_rate

---

sentry_sdk/integrations/stdlib.py
tests/integrations/requests/test_requests.py

For capturing GraphQL responses we're `read()`ing the `HTTPResponse` returned by `http.client.HTTPConnection.getresponse`, which exhausts the payload and it can't be read again by client applications. The original workaround for this was saving the payload in a `BytesIO` and aliasing `HTTPResponse.read` to the `BytesIO`'s `read`. This works when using http.client directly, but stops working with `urllib3`, which tries to determine whether there's anything left to read by checking if the response is closed, which in turn checks the internal `fp` file object. By the time we've `read()` the response, `fp` is `None`, and the response appears closed. This PR patches `fp` to point to the `BytesIO` saved response.
Fixes https://github.com/getsentry/sentry-python/issues/2285

Fix GraphQL integration swallowing responses

---

sentry_sdk/client.py
sentry_sdk/hub.py
sentry_sdk/integrations/stdlib.py
sentry_sdk/tracing_utils.py
tests/integrations/stdlib/test_httplib.py
tests/test_client.py
tests/tracing/test_misc.py

Stop recording spans for internal web requests to Sentry

---

sentry_sdk/client.py
sentry_sdk/consts.py
tests/test_monitor.py

closes https://github.com/getsentry/sentry-python/issues/2095

Enable backpressure handling by default

---

setup.py

Long overdue, but here it is.
We're been already running our test suite on 3.11 since January of this year.
Closes https://github.com/getsentry/sentry-python/issues/1950

Officially support Python 3.11

---

sentry_sdk/integrations/arq.py
tests/integrations/arq/test_arq.py

The arq settings class doesn't necessarily have to have both `functions` and `cron_jobs` attributes. Additionally it is possible to configure functions and cron jobs by passing them as a keyword argument to `create_worker`, this is now handled.
Fixes #2305
Fixes #2306

fix(arq): Fix attribute error on settings, support worker args

---

sentry_sdk/scope.py

The docstrings themselves don't really add much value but including them makes the methods appear in our [apidocs](https://getsentry.github.io/sentry-python/api.html).
Fixes https://github.com/getsentry/sentry-python/issues/2309

Make `Scope.update_from_*` appear in apidocs

---

sentry_sdk/monitor.py
sentry_sdk/tracing.py
tests/test_monitor.py

`1/2**10` is already `0.001` so downsampling more than that is fairly redundant, fixes the `OverflowError`.
fixes https://github.com/getsentry/sentry-python/issues/2340

Backpressure: only downsample a max of 10 times

---

sentry_sdk/integrations/flask.py
tox.ini

Fixing deprecated version attribute

---

.github/dependabot.yml
linter-requirements.txt
tests/integrations/celery/test_celery.py
tests/integrations/logging/test_logging.py
tests/integrations/stdlib/test_httplib.py
tests/integrations/wsgi/test_wsgi.py
tests/test_crons.py

Removed the pins to some of our linting tools to make sure we have the newest tools. (But pinning `flake8` because later versions dropped Python 2 support)
Also fixed some problems the new tools showed.
Also made sure that dependabot does not bug us about `flake8` and `jsonschema` anymore.

Updated linting tooling

---

CHANGELOG.md
sentry_sdk/hub.py
sentry_sdk/tracing.py
sentry_sdk/tracing_utils.py

Added some docstrings and also did some minor cleanup for better readability of the code.

Documenting Spans and Transactions

---

sentry_sdk/integrations/falcon.py
tests/integrations/falcon/test_falcon.py

Fixes #1946 and supersedes #2346

Prevent Falcon integration from breaking ASGI apps

---

sentry_sdk/client.py
sentry_sdk/integrations/opentelemetry/__init__.py

Always importing the experimental integration module that requires a higher version of the `opentelemetry-distro` package causes [packaging issues on some systems](https://github.com/getsentry/sentry-python/pull/2349) where the newer OTel packages don't exist.

Remove OpenTelemetry integration from integration __init__.py

---

sentry_sdk/consts.py
sentry_sdk/transport.py
tests/test_transport.py

This allows us to disable compression which might in some cases cause some unwanted overhead.

feat(transport): Added configurable compression levels

---

sentry_sdk/metrics.py

Modelled after the similar behavior in Relay. However unlike shifting on a per-project basis, we shift randomly per application start.
Refs relay https://github.com/getsentry/relay/blob/c8601c825402ee1eaf015c6ce4b7aca715627cf5/relay-metrics/src/aggregation.rs#L385-L400

feat(metrics): Shift flushing by up to a rollup window

---

sentry_sdk/__init__.py

Currently, using the decorator form of `trace` like this (as mentioned in the docs [here](https://docs.sentry.io/platforms/python/performance/instrumentation/custom-instrumentation/#using-a-decorator-1)):
```python
@sentry_sdk.trace
def do_stuff():
```
causes mypy to throw a `Module "sentry_sdk" does not explicitly export attribute "trace"  [attr-defined]` error. This adds `trace` to the top-level `__init__.py`'s `__all__` so mypy sees it as being officially exported and stops throwing the error.

fix(tracing) : Add `trace` to `__all__` in top-level `__init__.py`

---

.github/workflows/test-integration-celery.yml
.github/workflows/test-integration-falcon.yml
.github/workflows/test-integration-requests.yml
tox.ini

- Run our `requests` and `falcon` test suites on newer Python versions, too.
- Run the `celery` test suite for Celery 5.3.

Run more `requests`, `celery`, `falcon` tests

---

sentry_sdk/__init__.py
sentry_sdk/_compat.py
sentry_sdk/client.py
sentry_sdk/db/explain_plan/__init__.py
sentry_sdk/hub.py
sentry_sdk/integrations/aws_lambda.py
sentry_sdk/integrations/gcp.py
sentry_sdk/integrations/logging.py
sentry_sdk/session.py
sentry_sdk/tracing.py
sentry_sdk/transport.py
tests/test_transport.py

Replacing `datetime.utcnow()` due to deprecation as discussed in #2407

Removing utcnow method deprecated at python3.12

---

sentry_sdk/metrics.py
tests/test_metrics.py

This strengthens the recursion protection to cover two more cases:
* `before_emit_metric` in itself reporting a metric. This was previously not protected
* A transport emitting metrics. This is technically never a recursion case in the SDK, but it leads to a never ending stream of metrics
Refs https://github.com/getsentry/sentry/pull/57791

feat(metrics): Stronger recursion protection

---

sentry_sdk/metrics.py
tests/test_metrics.py

This simplifies the noop behavior for the recursion detection:
* background thread now always sets `in_metrics`
* force flush now marks `flush` as noop which sets `in_metrics`
In either case `_flush` is called and is then protected if it were to call into `add` or `flush`.

feat(metrics): Make a consistent noop flush behavior

---

sentry_sdk/integrations/django/transactions.py
tests/integrations/django/test_transactions.py

We implemented [support](https://github.com/getsentry/sentry-python/issues/1527) for more complex Django CMS URL patterns in https://github.com/getsentry/sentry-python/pull/1773, however this led to [a regression](https://github.com/getsentry/sentry-python/issues/2392) in how we capture multiple named groups in a URL pattern.
This PR reverts the Django CMS change and adds test cases that'll allow us to spot the regression should it happen again.
I'll include some rationale behind why I'm reverting the change vs. trying to make it work for both the Django CMS-style and multiple placeholder URL patterns in [the issue where we track this regression](https://github.com/getsentry/sentry-python/issues/2392).
Closes https://github.com/getsentry/sentry-python/issues/2392

Capture multiple named groups again

---

sentry_sdk/integrations/asyncpg.py
sentry_sdk/integrations/clickhouse_driver.py
sentry_sdk/integrations/gql.py

mypy 1.6.0 came out yesterday and the lint step is now [failing on master](https://github.com/getsentry/sentry-python/actions/runs/6479197446/job/17592281998).

Fix mypy errors

---

test-requirements.txt

Bump to the last version that supports 2.7 and add a reminder to revisit this if we drop py2.7 support.

Bump `pytest-localserver`, add comment

---

sentry_sdk/client.py
sentry_sdk/consts.py
tests/test_client.py

Introducing new `SENTRY_DEBUG` environment variable that can be used to set the `debug` option in `sentry_sdk.init()`.

Make `debug` option also configurable via environment

---

CONTRIBUTING.md
sentry_sdk/consts.py
sentry_sdk/transport.py
tests/test_transport.py

Increasing the HTTP pool size to better handle the requests. Also not reading the response saves some CPU cycles because TLS stuff uses CPU.
This does not fix all CPU spikes, but instead of spikes happening every 1 in 3-4 times it only happens 1 in 7-8 times with my test script. 
FIxes #2384

Mitigate CPU spikes when sending lots of events with lots of data

---

.craft.yml

Set the compatible runtimes in the Sentry AWS Lambda Layer to also include Python 3.10 and 3.11.
Related PRs in `sentry`:
* https://github.com/getsentry/sentry/pull/58321
* https://github.com/getsentry/sentry/pull/58320
Related docs update:
* https://github.com/getsentry/sentry-docs/pull/8246
Merge this, before merging the PRs in `sentry`.

Update compatible runtimes for AWS Lambda layer

---

sentry_sdk/client.py
sentry_sdk/consts.py
tests/test_client.py

Now, it is possible for Python SDK users to dynamically sample errors using the `error_sampler` option, similar how they are able to sample transactions dynamically with the `traces_sampler` option.
In other words, the new `error_sampler` is to the `sample_rate` as the existing `traces_sampler` is to the `traces_sample_rate`.
Fixes #2440

feat(api): Added `error_sampler` option

---

sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/transactions.py
tests/integrations/django/test_transactions.py

TL;DR: Our way of [parsing](https://github.com/getsentry/sentry-python/blob/085595b5f02931a3268c2de2a58b6986f3766d75/sentry_sdk/integrations/django/transactions.py#L48) named group regexes out of Django URL patterns is [not ideal](https://github.com/getsentry/sentry-python/issues/2392#issuecomment-1755797139). If someone is using (Django 2.0+) `<converter:parameter>` `path` patterns, we can parse those directly without turning them into regexes first and potentially hitting our limitations there.
When instrumenting Django for performance monitoring, the Sentry Python SDK will by default name the transactions based on the URL pattern rule that was used to serve the request.
There are two main ways of creating a URL pattern in Django: by using regexes in the rule directly, or (since Django …

Fix parsing of Django `path` patterns

---

.github/workflows/test-common.yml
sentry_sdk/integrations/logging.py
tox.ini

Add 3.12 to the test matrix and make a tiny change to the logging integration (3.12 added `taskName` to [LogRecord attributes](https://docs.python.org/3/library/logging.html#logrecord-attributes), we're now ignoring that as we do the rest).
Split off from https://github.com/getsentry/sentry-python/pull/2408.

Run common test suite on Python 3.12

---

sentry_sdk/integrations/redis/__init__.py

Should fix test failure in getsentry/getsentry#11960

Handle missing `connection_kwargs` in `patch_redis_client`

---

sentry_sdk/metrics.py
sentry_sdk/monitor.py
sentry_sdk/profiler.py
sentry_sdk/sessions.py
tests/test_monitor.py
tests/test_profiler.py
tests/test_sessions.py
tests/test_transport.py

In Python 3.12 when you try to start a thread during shutdown a `RunTimeErrror` is raised. Handle this case with grace

Handle failure during thread creation

---

setup.py

Closes https://github.com/getsentry/sentry-python/issues/2480

Add Python 3.12 to `classifiers`

---

sentry_sdk/integrations/django/__init__.py

Also probe for the psycopg3 parameters function, to not fall back to `get_connection_params()` when using psycopg3. This should improve performance for psycopg3 Django projects.
Fixes #2303

Probe for psycopg2 and psycopg3 parameters function.

---

tests/integrations/django/test_basic.py

removing redundant code in Django tests

removing redundant code in Django tests

---

sentry_sdk/integrations/celery.py
tests/integrations/celery/test_celery_beat_crons.py

Read timezone for Crons monitors from `celery_schedule` if existing

---

sentry_sdk/tracing.py

`datetime.utcfromtimestamp` and `datetime.utcnow` are [deprecated](https://docs.python.org/3/whatsnew/3.12.html) in Python 3.12.

Replace deprecated datetime functions

---

tests/integrations/flask/test_flask.py
tox.ini

* run test suite for Flask 3.0
* fix `request.get_json()` in the tests (Flask/Werkzeug 3.0 now throws an `UnsupportedMediaType` exception if the `Content-Type` isn't `application/json`)

Test with Flask 3.0

---

sentry_sdk/integrations/grpc/aio/server.py
tests/integrations/grpc/test_grpc_aio.py

The new aio integration for gRPC creates new Sentry events for each and every exception raised by the server. This becomes a problem if the user's server code uses `context.abort()` (like mine does!). [From the documentation](https://grpc.github.io/grpc/python/grpc_asyncio.html#grpc.aio.ServicerContext.abort):
> Raises an exception to terminate the RPC with a non-OK status.
Imagine this server code:
```py
async def GetUser(self, request, context):
user = self._users.find_by_id(request.id)
if not user:
await context.abort(grpc.StatusCode.NOT_FOUND)
return GetUserResponse(user=user)
```
`AbortError` is raised from `await context.abort()` every time a user is not found which, with the new Sentry integration, will also send an error event to Sentry every time a user is not found. This is …

Make async gRPC less noisy

---

test-requirements.txt
tox.ini

Our integrations tests run with the latest `pytest` out of the box. The `common`/`gevent` tests have issues with it (it doesn't play nicely with `pytest-forked`), so those will have to stay on `pytest<7` for a bit longer.

Run integration tests with newest `pytest`

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/spotlight.py
tests/test_spotlight.py

Add Spotlight option to SDK:
```python
spotlight=True,
)
spotlight='https://mycustom.ur',
)
```

feat: Send to Spotlight sidecar

---

sentry_sdk/_types.py
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/metrics.py
tests/test_metrics.py

DDM wants to show code locations with metrics. Locations are semi-static information: they change infrequently, so they don't need to be reported with every data point.
Sentry expects locations to be reported at least once per day. With backdating of metrics, the timestamp used to report the location is the metric bucket's timestamp rounded down to the start of the day (UTC timezone).
The metrics aggregator keeps a cache of previously reported locations. When a location is seen for the first time on a day, it is added to a list of pending locations. On the next flush cycle, all pending locations are sent to Sentry in the same envelope as the metric buckets.
See: https://github.com/getsentry/relay/pull/2751
Epic: https://github.com/getsentry/sentry/issues/60260

feat: Code locations for metrics

---

sentry_sdk/integrations/logging.py

Fixes https://github.com/getsentry/sentry-python/issues/802

Prevent global var from being discarded at shutdown

---

sentry_sdk/utils.py

Closes https://github.com/getsentry/sentry-python/issues/2531

Fix `parse_version` `NameError`

---

sentry_sdk/metrics.py
tests/test_metrics.py

The product is going to show source context with code locations on metrics. This
PR adds source context to the code location submission payload in the same
format that stack frames use.
Relay supports this with https://github.com/getsentry/relay/pull/2781.

feat(metrics): Add source context to code locations

---

.github/workflows/test-integration-aws_lambda.yml
scripts/split-tox-gh-actions/templates/check_permissions.jinja

The AWS Lambda test suite is failing on master. It runs a script to check whether a PR author has the right permissions to run the test suite, but the event that triggers the workflow is not a PR being opened/updated, but rather pushing to a repo branch.
In the patch here we treat the two possible event types differently:
* on `push`, we skip the permissions check entirely since the `push` event is only emitted on changes to repo branches (and we only limit it to `master` and `release/` branches), which can only be triggered by people with write permissions
* on `pull_request_target`, we run the permissions check as before

Skip permissions step on `push` events

---

CHANGELOG.md
sentry_sdk/metrics.py
tests/test_metrics.py

This corrects the reporting for context managers using `timing`. It does not address the code locations for `@timing` which are currently pointing to the call site instead of the function itself. That's tricker to fix because by the time we take the measurement the stack is unwound and before the measurement the function is not yet invoked.  We could work around this, but it's pretty ugly and does not really fit into how that system works at the moment.
Fixes #2550

feat(metrics): Improve code location reporting

---

sentry_sdk/integrations/aws_lambda.py
tests/integrations/aws_lambda/test_aws.py

When a lambda is triggered by an AWS EventBridge pipe the record contains an explicit "header" key with an empty list. This breaks the assumption that headers is always a dict or None. Update the AwsLambdaIntegration to explicitly verify that header is a dict before passing it on to the `continue_trace` function.
Fixes GH-2545

fix(integrations): Fix Lambda integration with EventBridge source

---

tox.ini

Django 5.0 stable has been released, let's run our test suite against it instead of the RC.

Update Django version in tests

---

sentry_sdk/metrics.py
tests/test_metrics.py

Fixes a bug where only the last tag combination for a metric summary was emitted. This now correctly emits arrays as intended by the RFC.

feat(summary): Fixed the incorrect emission of span metric summaries

---

sentry_sdk/client.py
sentry_sdk/hub.py
sentry_sdk/scope.py

Moved some functionality from Hub to Scope or Client:
- moved `add_breadcrumb` from Hub to Scope
- moved session functions from Hub to Scope
- moved `get_integration1` from Hub to Client.
This is preparation work for refactoring how we deal with Hubs and Scopes in the future.
Each commit is moving one function, so it should be easy to review commit by commit.

(1) Move `add_breadcrumb` and session function from Hub to Scope

---

sentry_sdk/utils.py
tests/test_utils.py

Our release checking can fail because `os.path.devnull` is not there/is not properly accessible on some setups.
Closes https://github.com/getsentry/sentry-python/issues/1496
Closes https://github.com/getsentry/sentry-python/issues/2334
---
Before running sensitive test suites, please carefully check the PR. …

Handle `os.path.devnull` access issues

---

sentry_sdk/integrations/aiohttp.py

Fixed typing in `aiohttp` integration.

Fixed typing in aiohttp

---

sentry_sdk/utils.py
tests/test_utils.py

We introduced a small regression in https://github.com/getsentry/sentry-python/pull/2557/files. Instead of only allowing truthy releases, we [are now allowing all non-`None` releases](https://github.com/getsentry/sentry-python/pull/2557#issuecomment-1853486609), which includes empty strings. Changing this back to the original behavior.

fix(utils): Filter out empty string releases

---

MIGRATION_GUIDE.md

Adding a migration guide that we can update with each change merged into 2.0 to avoid having to document everything at the end.

[2.0] Add a migration guide

---

sentry_sdk/_types.py
sentry_sdk/envelope.py

Looks like we're using a wrong data category for cron client reports. Should be `monitor`.
Closes https://github.com/getsentry/sentry-python/issues/2589

fix(crons): Change `data_category` from `check_in` to `monitor`

---

sentry_sdk/integrations/arq.py
tests/integrations/arq/test_arq.py

Arq is broken if the integration is missing because the context is not being passed, here is my tiny fix and a test
---

Arq integration ctx

---

sentry_sdk/hub.py
sentry_sdk/scope.py

Moved some functionality from Hub to Client:
- moved `start_transaction` from Hub to Scope
- moved `start_span` from Hub to Scope
- moved `continue_trace` from Hub to Scope
This is preparation work for refactoring how we deal with Hubs and Scopes in the future.
Depends on: https://github.com/getsentry/sentry-python/pull/2558 (please review the linked one first)

(4) Move transaction/span related functions from Hub to Scope

---

docs/api.rst
docs/apidocs.rst
sentry_sdk/api.py
sentry_sdk/client.py
sentry_sdk/scope.py

Second step in adding new global apis (and apidocs)

[Experiment] New scope step2

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/enforce-license-compliance.yml
.github/workflows/test-integrations-aws-lambda.yml
.github/workflows/test-integrations-cloud-computing.yml
.github/workflows/test-integrations-common.yml
.github/workflows/test-integrations-data-processing.yml
.github/workflows/test-integrations-databases.yml
.github/workflows/test-integrations-graphql.yml
.github/workflows/test-integrations-miscellaneous.yml
.github/workflows/test-integrations-networking.yml
.github/workflows/test-integrations-web-frameworks-1.yml
.github/workflows/test-integrations-web-frameworks-2.yml
linter-requirements.txt
scripts/split-tox-gh-actions/templates/base.jinja

Some CI checks aren't running on the `sentry-sdk-2.0` branch (and PRs against it) yet (see e.g. https://github.com/getsentry/sentry-python/pull/2596).
* Run all relevant workflows on `sentry-sdk-2.0`
* Fix lint step failures caused by a dependency update
---
Before running sensitive test suites, please …

Run more CI checks on 2.0 branch

---

sentry_sdk/tracing_utils.py
tests/integrations/asyncpg/test_asyncpg.py
tests/integrations/django/test_db_query_data.py
tests/integrations/sqlalchemy/test_sqlalchemy.py

If we send a relative path, make sure there is no leading path separator.

Fix relative path in db query source 

---

sentry_sdk/integrations/opentelemetry/span_processor.py
tests/integrations/opentelemetry/test_span_processor.py

Get correct datetime including timezone from timestamp

Fix timestamp in transaction created by OTel

---

.github/workflows/test-integrations-aws-lambda.yml
.github/workflows/test-integrations-cloud-computing.yml
.github/workflows/test-integrations-common.yml
.github/workflows/test-integrations-data-processing.yml
.github/workflows/test-integrations-databases.yml
.github/workflows/test-integrations-miscellaneous.yml
.github/workflows/test-integrations-networking.yml
.github/workflows/test-integrations-web-frameworks-1.yml
.github/workflows/test-integrations-web-frameworks-2.yml
MIGRATION_GUIDE.md
scripts/split-tox-gh-actions/split-tox-gh-actions.py
scripts/split-tox-gh-actions/templates/check_required.jinja
scripts/split-tox-gh-actions/templates/test_group.jinja
tox.ini

- remove special treatment for Python 2.7 from CI YAML generation
- remove Python 2.7, 3.5 test environments from `tox.ini`
- remove tests for framework versions that don't support at least Python 3.6
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using …

[2.0] Drop Python 2.7, 3.5 from CI (1)

---

sentry_sdk/tracing.py

Type hints for `sentry_sdk.trace` decorator function now indicate that the decorator returns a function with the same signature as it was called with. Previously, the type hints indicated that the decorator could return `Any`, which caused users to lose type hints for decorated functions.
Before this change:
After this change:
Fixes GH-2460

ref(api): Improve `sentry_sdk.trace` type hints

---

docs/conf.py
sentry_sdk/integrations/django/__init__.py
sentry_sdk/integrations/django/signals_handlers.py
tests/integrations/logging/test_logging.py
tests/test_client.py
tests/test_metrics.py
tests/test_transport.py
tests/tracing/test_baggage.py
tests/tracing/test_integration_tests.py
tests/utils/test_general.py

Removes `# -*- coding: utf-8 -*-` and friends.
Requires https://github.com/getsentry/sentry-python/pull/2640
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy …

[2.0] Remove `# coding: utf-8`

---

tests/integrations/django/myapp/views.py

We hid some Python 2 incompatible code behind an `exec`; removing that here.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all …

Drop `exec` for Python 2 incompatible code

---

tests/integrations/celery/test_celery.py
tests/integrations/django/test_basic.py
tests/integrations/flask/test_flask.py
tests/integrations/starlette/test_starlette.py
tests/integrations/stdlib/test_httplib.py
tests/test_api.py
tests/test_utils.py
tests/tracing/test_baggage.py
tests/tracing/test_integration_tests.py

We were sorting key-values in couple places to account for random order. Remove this where possible.
Left at least one `sorted` as is (`test_celery.py`) since this seems to still require manual sorting.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests …

Remove sorting where order is now stable

---

scripts/split-tox-gh-actions/split-tox-gh-actions.py

Moved `redis` and `redis-cluster` to the `Databases` test suite. Makes more sense there.

Moved redis related tests to databases

---

.pre-commit-config.yaml
sentry_sdk/integrations/arq.py
sentry_sdk/integrations/huey.py
sentry_sdk/integrations/opentelemetry/integration.py
sentry_sdk/scope.py
sentry_sdk/serializer.py
sentry_sdk/tracing.py
tests/integrations/asyncpg/test_asyncpg.py
tests/integrations/aws_lambda/client.py
tests/integrations/clickhouse_driver/test_clickhouse_driver.py
tests/integrations/django/myapp/custom_urls.py
tests/integrations/django/myapp/settings.py
tests/integrations/django/myapp/urls.py
tests/integrations/gcp/test_gcp.py
tests/integrations/starlette/test_starlette.py
tests/test_profiler.py

The lint CI step on new/updated PRs was [failing](https://github.com/getsentry/sentry-python/actions/runs/7667138132/job/20896357477?pr=2675) because a [recently released version of black](https://github.com/psf/black/releases/tag/24.1.0) introduced some formatting changes. Applying them here.
---
Before …

style: Reformat with black==24.1.0

---

.pre-commit-config.yaml
docs/apidocs.rst
scripts/split-tox-gh-actions/split-tox-gh-actions.py
sentry_sdk/api.py
sentry_sdk/client.py
sentry_sdk/hub.py
sentry_sdk/integrations/arq.py
sentry_sdk/integrations/django/middleware.py
sentry_sdk/integrations/django/transactions.py
sentry_sdk/integrations/huey.py
sentry_sdk/integrations/opentelemetry/integration.py
sentry_sdk/scope.py
sentry_sdk/serializer.py
sentry_sdk/tracing.py
sentry_sdk/utils.py
tests/integrations/asyncpg/test_asyncpg.py
tests/integrations/aws_lambda/client.py
tests/integrations/clickhouse_driver/test_clickhouse_driver.py
tests/integrations/django/myapp/custom_urls.py
tests/integrations/django/myapp/settings.py
tests/integrations/django/myapp/urls.py
tests/integrations/gcp/test_gcp.py
tests/integrations/starlette/test_starlette.py
tests/test_client.py
tests/test_profiler.py
tests/utils/test_contextvars.py

Verifying that merging master into sentry-sdk-2.0 was done correctly

---

sentry_sdk/_compat.py
sentry_sdk/integrations/gcp.py
sentry_sdk/tracing_utils.py
tests/integrations/asyncpg/test_asyncpg.py
tests/integrations/cloud_resource_context/test_cloud_resource_context.py
tests/integrations/django/test_db_query_data.py
tests/integrations/sqlalchemy/test_sqlalchemy.py
tests/test_utils.py

We were sometimes not adding query source to DB spans that took much longer than `db_query_source_threshold_ms`.
The SDK was considering some long spans to be too short because we were using `timedelta.microseconds` to find out the span duration. `timedelta.microseconds` doesn't return the whole duration in microseconds, just the microsecond part:
```python
>>> from datetime import timedelta
>>> t = timedelta(days=50, microseconds=10)
>>> t.microseconds
10
>>> t / timedelta(microseconds=1)
4320000000010.0
```
---
Running the test suite on your PR might require maintainer approval. Some tests (AWS Lambda) additionally require a maintainer to add a special …

fix(query-source): Fix query source duration check

---

sentry_sdk/consts.py
sentry_sdk/tracing_utils.py
tests/integrations/asyncpg/test_asyncpg.py
tests/integrations/django/test_db_query_data.py
tests/integrations/sqlalchemy/test_sqlalchemy.py

Once we've dogfooded query source in Sentry, turn it on by default.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code …

Enable DB query source by default

---

sentry_sdk/utils.py
tests/utils/test_general.py

There were at least two things wrong with our [`strip_string`](https://github.com/getsentry/sentry-python/blob/2f05ccbae7298978d2f1a8774a07386a018bcce9/sentry_sdk/utils.py#L1121) implementation:
* https://github.com/getsentry/sentry-python/issues/2612: It could lead to `UnicodeDecodeError`s on Python 2 if a non-unicode string (i.e., `bytes` in Python 2) was provided. When encoding such a (byte) string, Python 2 will first try to coerce it to a unicode string, using `ascii` to decode, leading to a `UnicodeDecodeError` if the byte string contains anything beyond ascii.
* https://github.com/getsentry/sentry-python/issues/2634: We found out how many bytes should be stripped from the string, but were then actually stripping that many characters/code points, not bytes.
This PR addresses both …

fix(utils): Fix `UnicodeDecodeError` on Python 2

---

sentry_sdk/client.py
sentry_sdk/utils.py
tests/test_metrics.py

[Enabling metrics by default](https://github.com/getsentry/sentry-python/pull/2685) leads to a deadlock when `gevent` is installed.
For now, we will disable metrics when `gevent` is used. In the next step, [we'll make metrics work with `gevent`](https://github.com/getsentry/sentry-python/issues/2689).
--- …

Disable metrics if `gevent` is used

---

.github/workflows/test-integrations-databases.yml
.github/workflows/test-integrations-web-frameworks-2.yml
scripts/split-tox-gh-actions/split-tox-gh-actions.py

The generation script -- when run with `--fail-on-changes` -- was supposed to raise an error if it detected that the integration test YAML files have changed but haven't been committed. The check is based on a hash of the contents of the YAML files, but there was a typo in the file names to consider (`integration` -> `integrations`), so it wasn't actually looking at any files and was always trivially true.
Now it'll properly complain if changes are made to `tox.ini` or to some of the constants in the splitting script that result in new YAML files, but those are not part of the commit.
--- …

fix(ci): Fix yaml generation script

---

sentry_sdk/integrations/sqlalchemy.py

In an application that is executing sqlalchemy cursors on a thread concurrently with another thread calling `sentry_sdk.init` it is possible for `_after_cursor_execute` to be called on a cursor that never had `_before_cursor_execute` called.
```
File "site-packages/sentry_sdk/integrations/sqlalchemy.py", line 98, in _after_cursor_execute
span = context._sentry_sql_span
^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'PGExecutionContext_psycopg2' object has no attribute '_sentry_sql_span'
```

Guard against sentry initialization mid sqlalchemy cursor

---

sentry_sdk/utils.py

Commit 8c24d33f causes a performance regression when PYTHONPATH is long, because it traverses PYTHONPATH for every distribution found (importlib.metadata.version traverses PYTHONPATH searching for a matching distribution for every call)
In our case we have an environment containing ~500 paths, and containing ~100 distributions, and where the first call to sentry_sdk.utils.package_version causes ~150k filesystems operations taking 10-20 seconds.
This commit uses the version from the distribution found when iterating all distributions, instead of calling importlib.metadata.version for each, which fixes the performance issue for us.
Note that if multiple copies of a distribution with different versions exist in PYTHONPATH the existing _generate_installed_modules will return the name and …

Fix performance regression in utils._generate_installed_modules

---

sentry_sdk/integrations/sqlalchemy.py
tests/integrations/sqlalchemy/test_sqlalchemy.py

Fixes https://github.com/getsentry/sentry-python/issues/2700
--- …

fix(sqlalchemy): Guard against `engine.url` being `None`

---

.github/workflows/test-integrations-aws-lambda.yml
scripts/split-tox-gh-actions/templates/check_permissions.jinja

Fixing a typo.
The AWS Lambda test suite will fail on this PR because it's running against `pull_request_target`, but it should work once we merge this.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after …

fix(ci): Fix AWS Lambda workflow

---

sentry_sdk/client.py
sentry_sdk/consts.py

Metrics are [broken under uWSGI](https://github.com/getsentry/sentry-python/issues/2699). Take the feature down for uWSGI until we figure out a fix.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any …

Turn off metrics for uWSGI

---

sentry_sdk/transport.py

Found one more compat import.
---

ref(transport): Remove compatibility import

---

sentry_sdk/metrics.py
tests/test_metrics.py

The recent metrics-on-by-default switch is causing issues for folks on uWSGI in prefork mode.
In other places where we use threads we always create the thread on demand, but in the metrics code we create a thread right away (so presumably before the process is forked). This PR aligns the behavior.
Additionally, add a small check like we have in the profiler for potential race conditions when spawning the flusher thread.
---
Sensitive test suites require …

fix(metrics): Only start thread on demand

---

MIGRATION_GUIDE.md
sentry_sdk/tracing_utils.py
tests/test_envelope.py

Closes https://github.com/getsentry/sentry-python/issues/2718
--- …

Remove `user.segment`

---

tests/integrations/aws_lambda/test_aws.py

Python 3.7 is not supported anymore by Lambda, so removed it and added 3.12

Update runtime version for AWS Lambda tests

---

sentry_sdk/integrations/aiohttp.py
tests/integrations/aiohttp/test_aiohttp.py

In the aiohttp integration we explicitly set the URL to `None` if we fail to parse it and then anyway try to access the parsed components. 
Fixes https://github.com/getsentry/sentry-python/issues/2728
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using …

fix(aiohttp): `parsed_url` can be `None`

---

MIGRATION_GUIDE.md
sentry_sdk/consts.py
sentry_sdk/profiler.py

`_experiments` options technically don't need deprecating since we explicitly say that they can change at any point, but I've seen many people actually use these profiler options, so let's give them a heads up before removing them.
---
Before running sensitive test suites, please carefully check the PR. Then, …

Deprecate profiler `_experiments` options

---

MIGRATION_GUIDE.md
sentry_sdk/metrics.py

This is technically a breaking change, so in 2.0 it goes.
--- …

Fix typo in method name

---

sentry_sdk/_compat.py
sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/hub.py
sentry_sdk/profiler.py
sentry_sdk/worker.py
tests/test_client.py

* remove special treatment for uWSGI -- turn metrics on by default everywhere
* remove the experimental `force-enable-metrics` flag
* add a warning if uWSGI is not run with the necessary flags
* move the existing uWSGI warning check from the worker to the client
TODO (separate docs PR): Call this out in the docs for wsgi framework integrations.
See https://github.com/getsentry/sentry-python/issues/2699#issuecomment-1944336675
Closes https://github.com/getsentry/sentry-python/issues/2699
---
Running the test suite on your PR might require maintainer approval. Some tests (AWS Lambda) additionally require a maintainer to add a special label to run and will fail …

ref(uwsgi): Warn if uWSGI is set up without proper thread support

---

sentry_sdk/integrations/clickhouse_driver.py

Release 0.2.7 of clickhouse-driver treats insert queries differently than before, leading to us not capturing breadcrumbs for them anymore. We need to wrap the newly introduced `receive_end_of_insert_query` just like we do `receive_end_of_query`.
---
Before running sensitive test suites, please carefully check …

feat(clickhouse): Support `clickhouse-driver==0.2.7`

---

MIGRATION_GUIDE.md
README.md

Small update to the migration guide and readme.
* sort migration guide items from more important/affecting more users to less important (e.g. internal API changes)
* add a note to migration guide about dropping support for the `/store` endpoint
* update readme with a link to the migration guide on docs.sentry.io
* note: this is not updated on the docs side yet, will be done in https://github.com/getsentry/sentry-docs/pull/9182 -- the plan is to merge `sentry-sdk-2.0` to `master` and the docs PR at roughly the same time)
* remove private module changes from migration guide

docs: Update readme, migration guide

---

sentry_sdk/client.py
sentry_sdk/metrics.py
tests/test_metrics.py
tox.ini

Make metrics work with `gevent` (again) **and** play nicely with the rest of the SDK.
* use the `gevent`-patched `threading.Event` instead of the original unpatched one to avoid greenlets waiting on the event blocking execution
* use a greenlet (a patched `threading.Thread`) instead of a native thread for the flusher
* don't support metrics on Python 3.6 and lower if `gevent` is used due to broken context vars
Mixing thread-based and greenlet-based primitives might lead to deadlocks in apps running in `gevent` mode.
Likely fixes https://github.com/getsentry/sentry-python/issues/2748
--- …

fix(metrics): Fix metrics compatibility with `greenlet`/`gevent`

---

sentry_sdk/scrubber.py
tests/test_scrubber.py

Should fix #2743
I added a "recursive" flag (default: False) to the EventScrubber that will scrub sensitive PII in dicts and lists recursively if set to True. Also added a test which uses a EventScrubber with recursive=True to scrub an event and check if it finds the sensitive stuff in deeply nested dicts/lists. Hope this is how you wanted it :)
---
Sensitive test suites require maintainer review to ensure that tests do not compromise our secrets. This review …

refactor: Add recursive scrubbing to EventScrubber with tests

---

sentry_sdk/scrubber.py

The new comment explains what the method does, allowing developers to more quickly understand the method's purpose.

docs: Add documentation comment to `scrub_list`

---

sentry_sdk/metrics.py
tests/test_metrics.py

[According to our spec](https://develop.sentry.dev/sdk/metrics/#normalization) invalid tag values should be replaced with no string.
> Tag Values: regex [^\w\d_:/@\.{}\[\]$-]+ with no replacement character.
I cross checked with [PHP](https://github.com/getsentry/sentry-php/blob/6f8cce5441da92829e84c3c2549625860f11787f/src/Serializer/EnvelopItems/MetricsItem.php#L59) and [JS](https://github.com/getsentry/sentry-javascript/blob/2a8ef4094ff283a207d3522db3e4c3357d73bb30/packages/core/src/metrics/utils.ts#L65): both of them also use no replacement character.

fix(metrics): Replace invalid tag values with an empty string instead of _

---

sentry_sdk/metrics.py
tests/test_metrics.py

see https://github.com/getsentry/develop/pull/1171
and https://github.com/getsentry/relay/pull/3174

fix(docs): allow empty character in metric tags values

---

.github/workflows/release.yml

See https://github.com/getsentry/publish?tab=readme-ov-file#merge-target
We need this for releases from the 2.0 branch that should then be merged back to 2.0 instead of master.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The …

Allow to configure merge target for releases

---

sentry_sdk/client.py
sentry_sdk/consts.py
sentry_sdk/transport.py
tests/test_transport.py

The urllib3 defaults for `socket_options` work fine most of the time, but there are environments and setups where they need tweaking (e.g., enabling keep-alive). One can create a custom transport with this, but given how often users need to tweak these, it makes sense to promote this to an `init` option.
Docs: https://github.com/getsentry/sentry-docs/pull/9332
Closes https://github.com/getsentry/sentry-python/issues/2391
---
Sensitive test suites require …

feat(transport): Expose `socket_options`

---

sentry_sdk/integrations/grpc/__init__.py
tests/integrations/grpc/test_grpc_aio.py
tox.ini

From https://github.com/getsentry/sentry-python/issues/2721#issuecomment-1969084637
This PR pins `grpcio` versions instead of `grpcio-tools`, as well as restructures test matrix and fixes an issue in grpc integration with `grpcio < 1.40` exposed by the fixed tests.
- `grpcio` versions for each "major" (1.xx.y) were bumped to the latest in the respective "major", e.g. `~=1.30.0` => `~=1.39.0`.
This was done to work around [various](https://github.com/grpc/grpc/pull/28398) [build](https://github.com/grpc/grpc/issues/25112) and [runtime](https://github.com/grpc/grpc/issues/27888) issues present in earlier versions.
- max python version for `grpcio` < 1.40 (< 1.42 actually) was lowered to cpy3.9 due to https://github.com/grpc/grpc/issues/27888
There is an unresolved issue with …

Pin `grpcio` versions in CI

---

sentry_sdk/scope.py

The example in the `use_scope` comment appears to have been copied directly from the `new_scope` example verbatim.
This change fixes the example, so the example demonstrates how to call `use_scope` rather than how to call `new_scope`.
@antonpirker, please make sure that I got the usage in the example correct; I think this is how `use_scope` is used but I'm less than 100% sure.

docs(scope): Correct `use_scope` comment

---

tests/integrations/aws_lambda/client.py

Our Lambda tests rely on parsing the stdout output of Lambda functions and only the last X bytes we can parse. So I removed those print statements because it can be that they are to long and then we can not parse the important parts of the stdout output.

Removed print statements because it messes with the tests

---

tests/integrations/aws_lambda/test_aws.py

We rely on the log output of our AWS Lambda tests to determine whether the tests have been successful: we log envelope and event contents and then check whether the log output looks as expected.
AWS Lambda has recently started logging a new warning when a function throws an unhandled exception. This is a scenario we're testing in some of our test cases.
The problem is that the log output is limited to the last 4kB and the new warning takes up a lot of space, so some of our events/envelopes will not fit anymore.
xfailing the tests here so that our release is not blocked now, but we'll need a proper solution, see https://github.com/getsentry/sentry-python/issues/2795
---
Please add tests to validate your changes, and lint your code using `tox …

ref(awslambda): xfail broken tests for now

---

sentry_sdk/api.py
sentry_sdk/hub.py
sentry_sdk/scope.py
sentry_sdk/tracing.py

This PR adds be type hints for the **kwargs that can be passed to sentry_sdk.start_transaction, thereby clearly documenting the parameters that can be passed directly in the code.
Ref https://github.com/getsentry/sentry-docs/issues/5082
- We intend to add to the docs page at least the most useful arguments defined in the TransactionKwargs type that this PR introduces.
This PR replaces #2787

ref(api): Type hinting for start_transaction kwargs

---

sentry_sdk/scrubber.py

This change improves the typing of the `scrub_dict` method.
Previously, the `scrub_dict` method's type hints indicated that only `dict[str, Any]` was accepted as the parameter. However, the method is actually implemented to accept any object, since it checks the types of the parameters at runtime. Therefore, `object` is a more appropriate type hint for the parameter.
#2753 depends on this change for mypy to pass

ref: Improve scrub_dict typing

---

sentry_sdk/integrations/huey.py
tests/integrations/huey/test_huey.py

This PR enables passing `sentry-trace` and `baggage` headers to background tasks using the Huey task queue.
This allows easily correlating what happens inside a background task with whatever transaction (e.g. a user request in a Django application) queued the task in the first place.
Periodic tasks do not get these headers, because otherwise each execution of the periodic task would be tied to the same parent trace (the long-running worker process).
--- …

feat(integrations): Propagate sentry-trace and baggage to huey tasks

---

sentry_sdk/integrations/openai.py
sentry_sdk/tracing.py
tests/integrations/openai/test_openai.py

Some data (like newer OpenAI versions' outputs) comes in some proprietary format (like pydantic) - this adds a way to recursively convert messy input data into clean json-formattable data.

Add a method for normalizing data passed to set_data

---

sentry_sdk/integrations/opentelemetry/span_processor.py
tests/integrations/opentelemetry/test_span_processor.py

OTel spans that are handled in the Sentry span processor can never be finished/closed. This leads to a memory leak. This change makes sure that open spans will be removed from memory after 10 minutes to prevent memory usage from growing constantly. 
Fixes #2722

Discard open spans after 10 minutes

---

tests/integrations/openai/test_openai.py

This will prevent the streaming reponse OpenAI tests to fail.

Fixed OpenAI tests

---

sentry_sdk/types.py

End-users may need to use the `Event` type for their type hinting to work following the `Event` type changes. However, we define `Event` in a private module `sentry_sdk._types`, which provides no stability guarantees.
Therefore, this PR creates a new public module `sentry_sdk.types`, where we re-export the `Event` type, and explicitly make it available as public API via `sentry_sdk.types.Event`. The new `sentry_sdk.types` module includes a docstring to inform users that we reserve the right to modify types in minor releases, since we consider types to be a form of documentation (they are not enforced by the Python language), but that we guarantee that we will only remove type definitions in a major release.

Re-export `Event` in `types.py`
