tests/integrations/gql/test_gql.py
These two tests are failing in #2454, blocking that PR from being merged. The tests appear to be broken, and since they appear to be unnecessary (we don't have similar tests for other integrations), we should delete them. See https://github.com/getsentry/sentry-python/pull/2454#issuecomment-2003248637 for a more detailed explanation.
=> test(gql): Delete problematic tests

Makefile, sentry_sdk/scope.py
This PR makes sure all apidocs are recreated always (by deleting an eventually existing `docs/_build` folder) and also adds some minor changes to `set_level` and `set_tag` to make the types of parameters clear. 
This is related to this Docs PR: https://github.com/getsentry/sentry-docs/issues/5432
=> Small APIdocs improvement

sentry_sdk/client.py, sentry_sdk/hub.py
Moved functionality from `_should_send_default_pii()` in Hub into `should_send_default_pii` on the Client.
Fixes #2819
=> Moved should_send_default_pii into client

sentry_sdk/integrations/celery.py, setup.py, tests/integrations/celery/test_celery_beat_crons.py
This add support for celery-redbeat (resolves #2616). Thanks to https://github.com/getsentry/sentry-python/issues/2616#issuecomment-1875438310
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code …
=> feat(integrations): Add support for celery-redbeat cron tasks

sentry_sdk/integrations/aws_lambda.py, tests/integrations/aws_lambda/test_aws.py
`aws_event` in our wrapper [can be an empty list](https://github.com/getsentry/sentry-python/issues/2847), but we assume that there's always at least one element in it.
Fixes https://github.com/getsentry/sentry-python/issues/2847
---
Before running sensitive test suites, please carefully check the PR. Then, …
=> fix(awslambda): aws_event can be an empty list

sentry_sdk/integrations/logging.py
Use new scopes API in LoggingIntegration. I also tested these changes manually: https://sentry-sdks.sentry.io/issues/5083315970/?project=4505239425777664&query=is%3Aunresolved&referrer=issue-stream&statsPeriod=1h&stream_index=1&utc=true
Fixes GH-2852
=> ref(logging): New scopes API in LoggingIntegration

sentry_sdk/integrations/ariadne.py
=> ref: Ariadne integration new scope API

sentry_sdk/consts.py, sentry_sdk/transport.py, tests/test_transport.py
In case folks are experiencing network issues between the SDK and Sentry, we in general recommend tweaking socket_options directly with a predefined set of settings. This seems to alleviate the issue most of the time, but feels rather low-level and hacky.
Node has a separate [keepAlive transport option](https://docs.sentry.io/platforms/node/configuration/options/#transport-options). We could do something similar: an option that sets the socket options to [what we usually recommend](https://github.com/getsentry/sentry-python/releases/tag/1.41.0), while keeping the `socket_options` option around as well for users who need more control over things.
Docs: https://github.com/getsentry/sentry-docs/pull/9498
Closes https://github.com/getsentry/sentry-python/issues/2837
---
Thank you for …
=> feat: Add optional `keep_alive`

sentry_sdk/integrations/redis/__init__.py, sentry_sdk/integrations/redis/asyncio.py
Update our redis integration to use the new scopes API.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before …
=> ref(redis): Use new scopes API

sentry_sdk/integrations/asyncpg.py, sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/django/asgi.py, sentry_sdk/integrations/django/caching.py, sentry_sdk/integrations/django/middleware.py, sentry_sdk/integrations/django/signals_handlers.py, sentry_sdk/integrations/django/templates.py, sentry_sdk/integrations/django/views.py, sentry_sdk/integrations/sqlalchemy.py, sentry_sdk/tracing_utils.py, tests/integrations/django/myapp/views.py
Needed to change all three of those integrations at the same time, because they use the same helper functions that had a `hub` as a parameter.
Fixes #2809 (Django)
Relates to #2815 (Database integrations)
=> Use new scopes API in Django, SQLAlchemy, and asyncpg integration.

sentry_sdk/integrations/celery.py, tests/integrations/celery/test_celery_beat_crons.py
=> Use new scopes API in Celery integration.

sentry_sdk/integrations/openai.py
=> Use new scopes API in OpenAI integration.

MIGRATION_GUIDE.md
Added some more parameters we changed in functions that are not public api, but still maybe someone uses them.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy …
=> Updated migration guide

sentry_sdk/consts.py, sentry_sdk/profiler.py, sentry_sdk/tracing.py, sentry_sdk/utils.py, tests/conftest.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/asyncpg/test_asyncpg.py, tests/integrations/boto3/test_s3.py, tests/integrations/celery/test_celery.py, tests/integrations/clickhouse_driver/test_clickhouse_driver.py, tests/integrations/django/test_basic.py, tests/integrations/grpc/test_grpc.py, tests/integrations/grpc/test_grpc_aio.py, tests/integrations/httpx/test_httpx.py, tests/integrations/redis/asyncio/test_redis_asyncio.py, tests/integrations/redis/cluster/test_redis_cluster.py, tests/integrations/redis/cluster_asyncio/test_redis_cluster_asyncio.py, tests/integrations/rediscluster/test_rediscluster.py, tests/integrations/requests/test_requests.py, tests/integrations/socket/test_socket.py, tests/integrations/stdlib/test_httplib.py, tests/integrations/stdlib/test_subprocess.py, tests/integrations/strawberry/test_strawberry_py3.py, tests/test_profiler.py, tests/test_scrubber.py, tests/test_utils.py
As per getsentry/rfcs#75 getsentry/rfc#75, this adds the thread data to the spans. This will be needed for the continuous profiling mode in #2830.
=> feat(profiling): Add thread data to spans

sentry_sdk/integrations/quart.py
Relates https://github.com/getsentry/sentry-python/issues/2812
--- …
=> ref(quart): Use new scopes in Quart integration

MIGRATION_GUIDE.md
We're deprecating hub-based API with 2.0. Add this to the migration guide.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all …
=> ref(docs): Deprecate old hub API in migration guide

sentry_sdk/integrations/falcon.py, tests/integrations/falcon/test_falcon.py
Relates https://github.com/getsentry/sentry-python/issues/2812
--- …
=> ref(falcon): Use new scopes API

sentry_sdk/integrations/asgi.py
=> ref(asgi): Use new scopes API

sentry_sdk/integrations/starlette.py, tests/integrations/starlette/test_starlette.py
=> ref(starlette): Use new scopes API

sentry_sdk/integrations/huey.py
=> ref(huey): Use new scopes API

sentry_sdk/integrations/pure_eval.py
=> ref(pure-eval): Use new scopes API

tests/integrations/threading/test_threading.py
=> ref(threading): Use new scopes API in tests

tests/integrations/django/test_basic.py, tests/integrations/falcon/test_falcon.py, tests/integrations/flask/test_flask.py, tests/integrations/quart/test_quart.py, tests/integrations/tornado/test_tornado.py
Putting these in one PR because even though it spans different integrations, it's the same changes.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring …
=> ref(integrations): Use new scopes API in web framework tests

sentry_sdk/integrations/arq.py, tests/integrations/arq/test_arq.py
=> ref(arq): Use new scopes API

sentry_sdk/utils.py, tests/test_utils.py, tests/tracing/test_decorator.py
`ensure_integration_enabled` and `ensure_integration_enabled_async` can now decorate functions that return `None` without an original function.
=> ref: `ensure_integration_enabled` without original function

sentry_sdk/integrations/starlite.py
=> ref(starlite): Use new scopes API

sentry_sdk/integrations/beam.py
=> ref(beam): Use new scopes API

sentry_sdk/types.py
Explicitly reexport types to make strict mypy setups happy. This backports #2866 to 1.x.
Fixes GH-2910
=> ref: Explicit reexport of types (backport to 1.x)

sentry_sdk/types.py
Set types in `sentry_sdk.types` to `None` at runtime. This allows the types to be imported from outside `if TYPE_CHECKING` guards.
Fixes GH-2909
=> ref: Define types at runtime

sentry_sdk/integrations/socket.py
Another forgotten integration.
Not using the `ensure_integration_enabled` decorator here by choice as it leads to some pretty intimidating mypy errors. 😬 
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed …
=> ref(socket): Use new scopes API

MIGRATION_GUIDE.md, sentry_sdk/integrations/tornado.py, tests/integrations/tornado/test_tornado.py, tox.ini
Forgot to give the Tornado integration the new scopes treatment -- fixing that now.
This integration is a bit special because trying to update it to the new API leads to the tests failing with
```
ValueError: <Token var=<ContextVar name='isolation_scope' default=None at 0x1049e8c70> at 0x104ecf080> was created in a different Context
```
when trying to restore the old isolation and current contexts at the end of `with isolation_scope()`. Digging deeper, I came across a [Tornado issue](https://github.com/tornadoweb/tornado/issues/2731). There's a fix in Tornado 6 and also in our case, everything seems to work on 6.0 up, so I'm dropping support for older Tornado to make sure contextvars work correctly. [6.0](https://github.com/tornadoweb/tornado/releases/tag/v6.0.0) itself is already 5 years …
=> ref(tornado): Use new scopes API

sentry_sdk/api.py
Adds the `instrumenter` argument to `sentry_sdk.start_transaction`. Should unblock #2865.
=> ref: Correct `api.start_transaction` method signature

sentry_sdk/crons/_decorator.py, sentry_sdk/crons/_decorator_py2.py, sentry_sdk/crons/decorator.py, tests/crons/test_crons.py, tests/crons/test_crons_async_py3.py
Our `monitor` decorator/context manager is not async friendly. If you wrap an async function in it, `monitor` will only wrap the creation of the coroutine, rather than its execution, which means it'll exit early. It won't capture the actual duration of the execution of the function, and the cron run will always be reported as success.
To better illustrate, try this out:
```python
import asyncio
sentry_sdk.init(...)
@sentry_sdk.monitor(monitor_slug='my-slug')
async def my_cron():
print('running...')
await asyncio.sleep(1)
raise ValueError
asyncio.run(my_cron())
```
If you execute this, you'll see multiple fishy things:
* the cron will be green even though it throws an exception
* even if it takes >= 1s to execute, the time reported will be ~0ms
* the "running..." message …
=> fix(crons): Make `monitor` async friendly

MIGRATION_GUIDE.md, sentry_sdk/tracing.py
This has been deprecated for 4 years, so I suppose we can remove it now in `2.0`.
Removing the `__new__` method also fixes our API docs for the `Span` and `Transaction` constructors. The `__new__` method causes the API docs to show both classes as only taking opaque `**kwargs`, like so:
Following this change, the arguments are displayed correctly in the API docs:
Partially addresses https://github.com/getsentry/sentry-docs/issues/5082
=> ref: Remove deprecated `Transaction` creation method

sentry_sdk/tracing.py
This change moves the `Transaction` constructor's parameter doctsring from the `__init__` method to the class's docstring. This way, the API docs display the parameter descriptions under the class. When the docstring is defined on `__init__`, the parameter descriptions are missing from the API docs.
This change also documents the `kwargs` parameter in the API docs.
Before the change:
After the change:
Partially addresses https://github.com/getsentry/sentry-docs/issues/5082
=> docs: Move transaction __init__ doc comment content

sentry_sdk/api.py, sentry_sdk/hub.py, sentry_sdk/scope.py, sentry_sdk/tracing.py
Repeating the doc comments also on the kwargs typed dicts enables better hinting in VSCode. See example below.
Before:
After:
I wish there was a way to do this without simply repeating the documentation both on the classes and in the Kwargs typeddicts, but this is the best way I found.
ref: https://github.com/getsentry/sentry-docs/issues/5082
=> docs: Document Transaction and Span kwargs typed dicts

sentry_sdk/api.py, sentry_sdk/hub.py, sentry_sdk/scope.py
This PR adds documentation for all `start_transaction` parameters. It also proposes removing the `StartTransactionKwargs` typeddict, instead placing the `custom_sampling_context` parameter directly on the method and deleting the `client` parameter, which appears not to be used.
ref https://github.com/getsentry/sentry-docs/issues/5082
=> ref: Improve `start_transaction` docs

sentry_sdk/api.py
Although the `@scopemethod` decorator should take care of adding this documentation comment to `start_transaction`, the decorator does not appear to work when hovering over the `sentry_sdk.start_transaction` function in VSCode. Adding the doc comment explicitly allows the documentation to be shown when hovering in VSCode, but it does not change the output of our API docs, which still uses the `@scopemethod` output.
This is the final PR in this repository that addresses https://github.com/getsentry/sentry-docs/issues/5082; the last step to closing that issue will be to add a link in the docs to `start_transaction` in our API docs. We can only do this once 2.0 is released.
=> docs: Document top-level `start_transaction` function

sentry_sdk/types.py, tests/test_types.py
Change `Event`'s runtime value to `typing.Any`, since the previous value of None caused the expression `Event | None` to result in a `TypeError` at runtime, even when the `Event | None` expression was used as a type hint. Also, add a test to make sure we don't reintroduce this bug.
Fixes GH-2926
=> fix(types): Fixed `Event | None` runtime `TypeError`

sentry_sdk/crons/decorator.py, tests/crons/test_crons.py, tests/crons/test_crons_async_py3.py
Allow to pass `monitor_config` to the `monitor` decorator/context manager.
Also adds some tests for https://github.com/getsentry/sentry-python/issues/2927 -- it was already possible to pass the new params since we just take the `monitor_config` as is.
Docs PR: https://github.com/getsentry/sentry-docs/pull/9597
Relates https://github.com/getsentry/sentry-python/issues/2927
Closes https://github.com/getsentry/sentry-python/issues/2925
Closes https://github.com/getsentry/sentry-python/issues/2770
---
Running the test suite on your PR might require maintainer approval. Some tests (AWS Lambda) additionally require a maintainer to add a special label to run and …
=> feat(crons): Allow to upsert monitors

sentry_sdk/transport.py, tests/test_transport.py
This adds the handling of rate limits for the new `metric_bucket` category, including handling the metric namespace.
Closes https://github.com/getsentry/sentry-python/issues/2921
=> feat(metrics): Implement metric_bucket rate limits

sentry_sdk/integrations/sanic.py
in Sanic, for some exceptions, quiet variables are set to True (https://github.com/hamedsh/sanic/blob/b8ec9ed3e6f63f4c61fd45d3e09cfc9457a53b82/sanic/exceptions.py#L9) these kinds of exceptions, do not exist in the stderr, but exist in the sentry panel. 
by this modification, these kinds of exceptions will not sent to the sentry hub.
=> Update sanic integration

CONTRIBUTING.md, devenv-requirements.txt
This is a quick fix for #2760. 
Ideally we'd do away with constraints duplication/introduction in `tox.ini`, but I don't see a way to do so without much more invasive changes, and I would prefer to not make those before discussing approaches.
---
Before running sensitive test suites, please carefully check the …
=> Add devenv-requirements.txt and update env setup instructions

sentry_sdk/metrics.py
Add a comment on why we only add 1 for the LocalMetricsAggregator.
#skip-changelog
=> chore: Add info on set local aggregator behaviour

sentry_sdk/utils.py
Supress command prompt window poppiing up in windows. 
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before …
=> Supress command prompt window poppiing up in windows. 

sentry_sdk/crons/_decorator.py
=> fix(crons): Fix type hints for monitor decorator

sentry_sdk/crons/_decorator.py
Instead, these should be imported from `collections.abc`
Depends on #2944
=> ref(crons): Remove deprecated `typing` imports

sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/django/signals_handlers.py, tests/integrations/django/myapp/signals.py, tests/integrations/django/myapp/urls.py, tests/integrations/django/myapp/views.py, tests/integrations/django/test_basic.py
This PR adds a way to exclude sentry-sdk from attaching to certain Django signals. This can be used to work around performance issues when sentry attaches to performance sensitive signals like `pre_init` and `post_init`. 
You pass a list of Django signals that you don't want Sentry to attach to:
```python
import django.db.models.signals
...
integrations=[
DjangoIntegration(
...
signals_denylist=[
django.db.models.signals.pre_init, 
django.db.models.signals.post_init,
],
),
],
)
```
This potentially fixes #1826 or #1739, and https://github.com/jazzband/django-model-utils/pull/556.
---
Running the test suite on your PR might …
=> feat(integrations): add django signals_denylist to filter signals that are attached to by signals_span

tests/integrations/asgi/test_asgi.py, tests/integrations/asyncio/test_asyncio.py, tests/integrations/celery/test_celery.py, tests/integrations/falcon/test_falcon.py, tests/integrations/fastapi/test_fastapi.py, tests/integrations/flask/test_flask.py, tests/integrations/huey/test_huey.py, tests/integrations/quart/test_quart.py, tests/integrations/starlette/test_starlette.py, tests/test_basics.py, tests/tracing/test_noop_span.py
The test output is too big already -- we don't need to be debug logging on `sentry_sdk.init`s in the tests. (Unless it's actually part of the test.)
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any …
=> ref(tests): Remove `debug=True` from tests

sentry_sdk/profiler.py
Closes https://github.com/getsentry/sentry-python/issues/2948
--- …
=> fix(profiler): Accessing `__class__` might throw a `ValueError`

sentry_sdk/consts.py, sentry_sdk/metrics.py, tests/test_metrics.py
Closes https://github.com/getsentry/sentry-python/issues/2956
--- …
=> feat(metrics): Add value, unit to before_emit_metric

sentry_sdk/_types.py, sentry_sdk/crons/api.py, sentry_sdk/crons/decorator.py, sentry_sdk/integrations/celery.py
Better type hinting for monitor configs.
Closes https://github.com/getsentry/sentry-python/issues/2930
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring …
=> feat(typing): Make monitor_config a TypedDict

sentry_sdk/metrics.py, tests/test_metrics.py
See https://develop.sentry.dev/sdk/metrics/#normalization
Closes https://github.com/getsentry/sentry-python/issues/2937
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our …
=> feat(metrics): New normalization of keys, values, units

sentry_sdk/_types.py, sentry_sdk/envelope.py, sentry_sdk/transport.py
The event category for emitted metrics is `metric_bucket` and not `statsd`.
=> fix(metrics): Change `data_category` from `statsd` to `metric_bucket`

MIGRATION_GUIDE.md
More details, examples, background info.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring maintainers to review all code revisions before running …
=> [2.0] Tweak migration guide

MIGRATION_GUIDE.md
=> docs: Update migration guide wording

tests/integrations/celery/test_celery.py
This fixes our tests that rely on the `newrelic` package. In their version `v9.9.0` they removed a function that we called so we had to update our tests.
=> Make it work with old and new newrelic versions

sentry_sdk/integrations/celery/__init__.py, tests/integrations/celery/test_celery.py, tests/integrations/celery/test_update_celery_task_headers.py
This fixes the accumulating baggage headers when dogfooding SDK 2.0 on `sentry.io`. 
This reverts the refactoring of header manipulation that was added in `rc4` back to what is present in current `master`.
This PR uses the working code from `master` (that is also in `rc3`) and then extracts the header manipulating code into `_update_celery_task_headers()` to make it more readable and also testable. 
This PR adds a couple of tests to make sure we do not change the behavior by accident in the future. 
(This does not fix https://github.com/getsentry/sentry-python/issues/2916 but it uncovered the root cause. The fix is in a follow up PR: https://github.com/getsentry/sentry-python/pull/3001)
=> Fix duplicate baggage headers in Celery integration introduced in SDK 2.0

sentry_sdk/integrations/celery/__init__.py
In the original implementation of celery trace propagation we had code to only create a span for the task if it was NOT started by Celery Beat (because there is no transaction created in the beat process, so also not span should be created).
See this code: https://github.com/getsentry/sentry-python/blob/master/sentry_sdk/integrations/celery.py#L187-L200
Turns out this has never worked and `task_started_from_beat` has always been `False` meaning a span was ALWAYS created.
(This did never break anything or caused any troube. When looking into a transaction less future this is also absolutely fine.)
So this PR restores now the original behavior by always creating a span.
=> Restore original behavior by always creating a span

sentry_sdk/tracing.py, tests/tracing/test_misc.py
=> Fix transaction discarded debug messages

tests/integrations/django/myapp/settings.py
Should reduce collisions of different test runs having the same database name.
=> Use `pid` for test database name in Django tests

sentry_sdk/scope.py, sentry_sdk/tracing_utils.py, tests/integrations/celery/test_celery.py, tests/integrations/rq/test_rq.py, tests/test_api.py, tests/test_propagationcontext.py
Create a class for the `PropagationContext`. Make the class generate the UUIDs lazily.
Fixes https://github.com/getsentry/sentry-python/issues/2827
=> Refactoring propagation context

sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/arq.py, sentry_sdk/integrations/asyncpg.py, sentry_sdk/integrations/django/asgi.py, sentry_sdk/integrations/fastapi.py, sentry_sdk/integrations/graphene.py, sentry_sdk/integrations/httpx.py, sentry_sdk/integrations/quart.py, sentry_sdk/integrations/redis/asyncio.py, sentry_sdk/integrations/sanic.py, sentry_sdk/integrations/starlette.py, sentry_sdk/integrations/starlite.py, sentry_sdk/integrations/strawberry.py
Quick fix for https://github.com/getsentry/sentry-python/issues/3021. Removing the decorator gets rid of the issue.
We should follow up and fix the decorator later, e.g. here: https://github.com/getsentry/sentry-python/issues/2892
Closes https://github.com/getsentry/sentry-python/issues/3021
---
Before running …
=> fix(integrations): Do not use convenience decorator

sentry_sdk/__init__.py, sentry_sdk/api.py, sentry_sdk/scope.py, tests/test_api.py, tests/test_scope.py
`Scope.set_tags` allows multiple tags to be set at the same time by passing the tags to update as a dictionary (or other `Mapping` type).
Closes GH-1344
=> feat(scope): New `set_tags` function

README.md
We're currently linking to the Migration landing page, which is also fine, but it's better to link to the specific migration guides directly.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code …
=> fix(docs): Link to respective migration guides directly

tests/integrations/trytond/test_trytond.py, tox.ini
Remove the pin on super old `werkzeug` versions. Latest `trytond` release doesn't work with `werkzeug` that old.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy …
=> fix(tests): Fix trytond tests

sentry_sdk/_types.py, sentry_sdk/tracing.py
This functionality is already in other SDKs, and will be used in future AI features.
=> feat(perf): Add ability to put measurements directly on spans.

sentry_sdk/integrations/django/asgi.py, tests/integrations/django/asgi/test_asgi.py
Upgrading a Django ASGI application to Python 3.12 broke because of the integration not being able to identify that the middleware being called was async.
This is due to Python 3.12 replacing setting `_is_coroutine = asyncio.coroutines._is_coroutine` with `inspect.markcoroutinefunction`
This ports the fix from `asgiref` to make sure sentry_sdk can support multiple python versions.
I thought about importing it from `asgiref`, but not sure how the maintainers feel about requiring it as a dependency (although it is already a django's dependency)
=> fix: fix Django ASGI integration on Python 3.12

.github/workflows/test-integrations-data-processing.yml, mypy.ini, scripts/split-tox-gh-actions/split-tox-gh-actions.py, sentry_sdk/consts.py, sentry_sdk/integrations/__init__.py, sentry_sdk/integrations/huggingface_hub.py, sentry_sdk/integrations/langchain.py, setup.py, tests/integrations/huggingface_hub/__init__.py, tests/integrations/huggingface_hub/test_huggingface_hub.py, tox.ini
Adds integration for Huggingface Hub.
=> Huggingface Hub integration

sentry_sdk/integrations/quart.py
The Quart integration was completely broken prior to this commit, as it caused every request to fail with a 500 error. The reason was that we were using the non-async `ensure_integration_enabled` decorator on the async `sentry_patched_asgi_app` function. This commit fixes the issue by removing the use of that decorator, instead replacing it with a manual check for the integration being enabled.
Fixes GH-3040
=> fix(quart): Fix Quart integration

sentry_sdk/_types.py
=> Made MeasurementValue.unit NotRequired

sentry_sdk/integrations/__init__.py, sentry_sdk/integrations/anthropic.py
Auto-enable the Anthropic integration, and put all anthropic-related imports in `try` for safety.
=> misc(ai-monitoring): Auto-enable Anthropic integration + gate imports

sentry_sdk/scope.py
The `Scope.get_client` method is typed as returning `sentry_sdk.client.BaseClient`, but because `sentry_sdk.client` was not imported, the type was resolved as `Any`. This change imports `sentry_sdk.client` to fix the type hints.
=> ref(scope): Fix `get_client` typing

sentry_sdk/consts.py, sentry_sdk/integrations/celery/__init__.py, tests/integrations/celery/test_celery.py
Send the queue name to Sentry for Celery tasks using the default exchange. The queue name is sent as span data with the key `messaging.destination.name`.
Closes GH-2961
=> feat(celery): Send queue name to Sentry

sentry_sdk/consts.py, sentry_sdk/integrations/celery/__init__.py, tests/integrations/celery/test_celery.py
Depends on:
- #2971
- #2984
Closes #2974
=> Set task ID on span (Celery integration)

sentry_sdk/consts.py, sentry_sdk/integrations/celery/__init__.py, tests/integrations/celery/test_celery.py
Depends on:
- #3015
- #2971
- #2984
ref #2951
=> feat(celery): Set "messaging.system" on span

sentry_sdk/consts.py, sentry_sdk/integrations/celery/__init__.py, tests/integrations/celery/test_celery.py
=> feat(celery): Send Celery retry count

sentry_sdk/tracing.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/celery/test_update_celery_task_headers.py, tests/integrations/httpx/test_httpx.py, tests/tracing/test_propagation.py
This change ensures that we only propagate trace headers from spans that are within a transaction. This fixes a bug where any child transactions of a span created outside a transaction are missing a dynamic sampling context and are part of a trace missing a root transaction (because the root is the span).
Fixes #3068
=> fix(tracing): Only propagate headers from spans within transactions

.github/workflows/ci.yml, Makefile
We used a very old verison of `virtualenv` to create virtual environments for apidocs generation. Switching to pythons `venv` module because it can do everything we wand and it can create virtual environments running Python 3.11+ (which the old version of virtualenv could not)
Fixes #3076
=> Use pythons venv instead of virtualenv to create virtual envs

tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/aws_lambda/test_aws.py
Recently `flake8` started to fail with `N803` errors in some places where it had previously passed. This PR adds `# noqa` comments to suppress these errors.
Unblocks #3079
=> ref: Fix N803 flake8 failures

sentry_sdk/consts.py, sentry_sdk/integrations/celery/__init__.py, tests/integrations/celery/test_celery.py
=> feat(celery): Queues module producer implementation

sentry_sdk/integrations/celery/__init__.py
From @JoshFerge "[Throws errors] millions of times a minute".  If its null we can't do anything with it so let's check first.
=> fix: Add conditional check for delivery_info's existence

sentry_sdk/integrations/clickhouse_driver.py
We started auto-enabling the ClickHouse integration in 2.0+. This led to it getting auto-enabled also for folks using ClickHouse with Django via `django-clickhouse-backend`, but it turns out that the integration doesn't work properly with `django-clickhouse-backend` and leads to `AttributeError: 'Connection' object has no attribute '_sentry_span'`.
This PR patches the integration to restore previous behavior -- i.e., the ClickHouse integration will not work with `django-clickhouse-backend`, but it will also not blow up.
Fixes https://github.com/getsentry/sentry-python/issues/3088
Follow up in https://github.com/getsentry/sentry-python/issues/3095
---
Running …
=> fix(clickhouse): `_sentry_span` might be missing

sentry_sdk/integrations/cohere.py
=> Fix `cohere` testsuite for new release of `cohere`.

sentry_sdk/integrations/excepthook.py
By patchinng `sys.excepthook` and retaining the original name, `exceptiongroup` is crashing. This is why I changed it to patch exceptgroup and have a new name for the patched function. 
Fixes #3097
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using …
=> Do not crash exceptiongroup backport

sentry_sdk/integrations/redis/utils.py, tests/integrations/redis/test_redis_cache_module.py
In some cases it can happen that the array of redis keys to get can be byte arrays and not string. Make sure we can deal with all kinds of keys, no matter if byte array or string.
Fixes: #3100
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using …
=> Handle also byte arrays keys

sentry_sdk/integrations/django/transactions.py, tests/integrations/django/test_transactions.py
`pattern.pattern._route` for i18n'd Django routes is a proxy object rather than a string. This causes an exception in the resolver, leading to the transaction not getting a proper name but rather falling back to the default `Generic WSGI request`.
The string representation of the proxy object is the actual desired endpoint route, so let's use that.
Closes https://github.com/getsentry/sentry-python/issues/3094
---
Sensitive test suites require maintainer review …
=> fix(django): Proper transaction names for i18n routes

sentry_sdk/integrations/grpc/aio/server.py, tests/integrations/grpc/test_grpc_aio.py
Add a `None` check in gRPC AIO interceptor.
Address issue: https://github.com/getsentry/sentry-python/issues/3108
`grpc.aio.ServerInterceptor` should expect the continuation to return `None` if the RPC isn't handled. Checking the return of continuation is not `None` before getting the `handler_factory` prevents an `AttributeError`
References
1. gRPC Python Docs on return types for interceptors, https://grpc.github.io/grpc/python/grpc_asyncio.html#grpc.aio.ServerInterceptor
2. Example implementation: https://github.com/d5h-foss/grpc-interceptor/blob/master/src/grpc_interceptor/server.py#L48-L57
---
Running the test suite on your PR might require maintainer …
=> Add None check for grpc.aio interceptor

tests/integrations/anthropic/test_anthropic.py
[Anthropic 0.27.0](https://github.com/anthropics/anthropic-sdk-python/compare/v0.26.2...v0.27.0) contains two changes that broke our tests:
* `Delta` is now in a different module
* `ContentBlock` is now a `Union`. Prior to 0.27 it was an alias for `TextBlock`, so now we use `TextBlock` directly.
---
Before …
=> fix(tests): Adapt to new Anthropic version

sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/celery/beat.py, sentry_sdk/scope.py, tests/integrations/celery/test_update_celery_task_headers.py
Making it:
- to be less error prone
- correctly propagate trace information to Celery tasks started by Celery beat.
Small docs update to make it clear how trace propagation in Celery works:
https://github.com/getsentry/sentry-docs/pull/10161
=> Refactored the Celery Beat integration.

sentry_sdk/scope.py, tests/test_basics.py, tests/test_scope.py
This PR supersedes #3114; it is based on #3114, but includes the changes requested during review of #3114.
Fixes GH-3113
=> fix(scope): Copy `_last_event_id` in `Scope.__copy__`

sentry_sdk/integrations/django/caching.py, sentry_sdk/integrations/redis/modules/caches.py, sentry_sdk/integrations/redis/utils.py, tests/integrations/django/test_cache_module.py, tests/integrations/redis/test_redis_cache_module.py, tests/integrations/redis/test_redis_cache_module_async.py
Make sure the `cache.key` span data field in cache spans is always an array, with one or more fields. (Compared to the description of the cache spans that is a comma separated string of the keys.)
See spec here: https://develop.sentry.dev/sdk/performance/modules/caches/
Fixes https://github.com/getsentry/sentry-python/issues/3117
=> Made `cache.key` span data field a list

sentry_sdk/integrations/redis/utils.py, tests/integrations/redis/test_redis_cache_module.py
Fixes https://github.com/getsentry/sentry-python/issues/3130
--- …
=> fix(cache): Fix _key_as_string

sentry_sdk/integrations/redis/modules/caches.py, tests/integrations/redis/test_redis_cache_module.py
When multiple keys are used, cache_prefixes should kick in if any of the keys is prefixed with any of the prefixes.
Fixes https://github.com/getsentry/sentry-python/issues/3127
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The …
=> fix(redis): Support multiple keys with cache_prefixes

sentry_sdk/scope.py, tests/test_scope.py
This PR includes a change that was split off from #3114.
=> fix(scope): Clear last_event_id on scope clear

sentry_sdk/tracing.py, tests/tracing/test_misc.py
This change should prevent confusion like what led to #2990 being opened.
=> Warn when transaction entered without calling `start_transaction`

sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/celery/beat.py, sentry_sdk/scope.py, tests/integrations/celery/test_update_celery_task_headers.py
Reverts getsentry/sentry-python#3105
=> Revert "Refactored the Celery Beat integration."

sentry_sdk/tracing.py, tests/profiler/test_continuous_profiler.py, tests/test_new_scopes_compat_event.py
The thread data was added to the profile context in #2830. It should live in the trace context to align with other SDKs.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our …
=> fix(profiling): Move thread data to trace context

sentry_sdk/crons/__init__.py
Mypy with `no_implicit_reexport = true` does not see the symbols in `sentry_sdk.crons` as exported.
```
my_file.py:10: error: Module "sentry_sdk.crons" does not explicitly export attribute "monitor"  [attr-defined]
```
Adding the `X as X` to the imports marks the symbol as exported and silences the error.
An alternative approach would be to list the symbols in `__all__`. I'm happy to rework this if you'd prefer that.
https://mypy.readthedocs.io/en/stable/command_line.html#cmdoption-mypy-no-implicit-reexport
I've not audited other parts of the library for this; this just fixes the one module that I'm hitting issues with.
=> Explicitly export cron symbols for typecheckers

sentry_sdk/profiler/__init__.py
These symbols were never explicitly part of the public API, but they were also not explicitly marked as private, so out of abundance of caution we kept them around as importable straight from `sentry_sdk.profiler` when reorganizing modules in the scope of https://github.com/getsentry/sentry-python/pull/2830. However, since they were never meant to be public, we want to remove them from the implicitly public API, so we deprecate them here.
This also needs to be called out in the changelog.
=> Add deprecation comment for profiler internals

sentry_sdk/consts.py, sentry_sdk/integrations/celery/__init__.py, tests/integrations/celery/test_celery.py, tests/integrations/celery/test_update_celery_task_headers.py
=> Add Celery receive latency

.github/workflows/test-integrations-data-processing.yml, scripts/split-tox-gh-actions/split-tox-gh-actions.py, scripts/split-tox-gh-actions/templates/test_group.jinja, sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/celery/beat.py, sentry_sdk/scope.py, tests/integrations/celery/integration_tests/__init__.py, tests/integrations/celery/integration_tests/test_celery_beat_cron_monitoring.py, tests/integrations/celery/test_celery.py, tests/integrations/celery/test_update_celery_task_headers.py
This reverts commit d818e8f08625dbc44bac95598293e86cfac9e8a1.
This reverts the revert that was done to mitigate the regression error with Crons not being sending ok/error checkins.
We have a fix ready in https://github.com/getsentry/sentry-python/pull/3155 that fixes that regression that will be merge into this PR.
---
Sensitive test suites require maintainer review to ensure that tests do not compromise our secrets. This review must be repeated after any code …
=> Reapply "Refactor the Celery Beat integration (#3105)" (#3144)

tests/integrations/django/asgi/test_asgi.py, tests/integrations/django/myapp/urls.py, tests/integrations/django/myapp/views.py
Cleaning up the ASGI tests for Django. Making sure it is always `wait()`ed for the application to finish and also made the tests a bit more readable and removed some useless asserts.
Fixes #3142
=> Cleaning up ASGI tests for Django

sentry_sdk/tracing_utils.py, tests/test_basics.py, tests/tracing/test_decorator.py
Fixes https://github.com/getsentry/sentry-python/issues/3177
--- …
=> fix(tracing): Keep original function signature when decorated

sentry_sdk/integrations/pymongo.py, tests/integrations/pymongo/test_pymongo.py
The query command is already included as the first key within the command JSON, so query spans would end up looking like this:
Our Node SDK, which uses OTel under the hood now, formats queries differently; it doesn't include the command name at the front, example:
We also already include the command within the `db.operation` tag, so there's no confusion or loss of details here. This change will ensure consistent behaviour between our other SDKs!
=> ref(pymongo): Remove redundant command name in query description

sentry_sdk/integrations/openai.py
There might be cases where there is an internal error and the function would return None
=> fix(llm-monitoring): If there is an internal error, still return a value

.github/workflows/test-integrations-data-processing.yml, scripts/split-tox-gh-actions/split-tox-gh-actions.py, tox.ini
😬 
The testsuite is there, but Spark is completely missing from `tox.ini` and it's also not run in CI.
=> fix(tests): Add Spark testsuite to tox.ini and to CI

sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/django/asgi.py
Small bugfix that can occur if you have a modern Django installation without channels installed. 
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed after any code changes to enforce our policy requiring …
=> Do not raise error when channels is not installed

setup.py
c06bf06a set the minimum version to 6, but setup.py was not updated to match.
=> build: Update tornado version in setup.py to match code check.

sentry_sdk/integrations/opentelemetry/span_processor.py
We snuck in a functional change in https://github.com/getsentry/sentry-python/pull/3168 that led to a regression. Fixing this.
Fixes https://github.com/getsentry/sentry-python/issues/3216
=> fix(otel): Fix missing baggage

requirements-testing.txt
[ipdb](https://pypi.org/project/ipdb) is not used by testing suite. To avoid installing extra dependencies, remove it from requirements file. Developers who find ipdb helpful can install the package themselves.
The change was initially driven by the fact that `ipdb` was not installable on Fedora 41 because of its missing Python 3.13 support, which made the Sentry SDK build fail due to unsatisfied build requirements.
---
Sensitive test suites require maintainer …
=> build: Remove `ipdb` from test requirements

sentry_sdk/transport.py, tests/test_transport.py
Also, add deprecation warnings for `HttpTransport.hub_cls`.
Fixes #3232
=> ref(transport): Stop using `Hub` in `HttpTransport`

sentry_sdk/integrations/stdlib.py, tests/integrations/stdlib/test_subprocess.py
During the arguments modification to `subprocess.Popen.__init__`, an explicitly empty environment of `{}` is incorrectly confused with a `None` environment. This causes sentry to pass the entire environment of the parent process instead of sending just the injected environment variables.
Fix it by only replacing the environment with `os.environ` if the variable is None, and not just falsy.
=> fix(integrations): don't send full env to subprocess

sentry_sdk/consts.py, sentry_sdk/tracing.py, tests/profiler/test_continuous_profiler.py
Relay expects this with an underscore instead of a dot.
=> fix(profiling): profiler_id uses underscore

sentry_sdk/transport.py, sentry_sdk/types.py
Done to more clearly define event data categories, in preparation for https://github.com/getsentry/sentry-python/issues/3229.
=> ref(transport): Improve event data category typing

tests/test_basics.py
Fix `tests/test_basic.py::test_event_processor_drop_records_client_report` so that the test is idempotent on failure. Previously, the test was only idempotent on success; if the test failed, it would cause many other unrelated tests to fail with it.
=> test: Fix non-idempotent test

tests/conftest.py, tests/profiler/test_transaction_profiler.py, tests/test_basics.py, tests/test_monitor.py
`capture_record_lost_event_calls` replaces the `capture_client_reports` fixture. The fixture records calls to `Transport.record_lost_event` by noting the arguments passed to each call.
This change is being introduced in preparation for #3244, which changes `Transport.record_lost_event`'s signature and behavior.
=> test: Introduce `capture_record_lost_event_calls` fixture

tests/test_transport.py
Make the `report["discarded_events"]` assertion logic (in `test_data_category_limits_reporting`) not rely on the ordering of events or any sorting logic. Done in preparation of #3244, where the sorting logic cannot be relied on anymore, since the same number of spans will be discarded as transactions.
=> test(transport): Non-order-dependent discarded events assertion

tests/tracing/test_sampling.py
Replace custom `record_lost_event` call capturing logic in `test_sampling.py` with the `capture_record_lost_event_calls` Pytest fixture. This change will simplify implementation of #3244.
=> test(sampling): Replace custom logic with `capture_record_lost_event_calls`

sentry_sdk/_types.py, sentry_sdk/client.py, sentry_sdk/tracing.py, sentry_sdk/transport.py, tests/conftest.py, tests/profiler/test_transaction_profiler.py, tests/test_basics.py, tests/test_client.py, tests/test_monitor.py, tests/test_transport.py, tests/tracing/test_sampling.py
Resolves https://github.com/getsentry/sentry-python/issues/3229
Resolves #3248
**Note to reviewers:** I have attempted to split the commits up into logical units, so you may wish to review the changes commit-by-commit.
=> feat(tracing): Record lost spans in client reports

sentry_sdk/consts.py, sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/arq.py, sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/huey.py, sentry_sdk/integrations/opentelemetry/span_processor.py, sentry_sdk/integrations/pymongo.py, sentry_sdk/integrations/sqlalchemy.py, sentry_sdk/tracing.py, tests/tracing/test_integration_tests.py
Having the Sentry span statuses in a class and introducing `get_span_status_from_http_code()`. This will be used in our new OpenTelementry instrumentation. 
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will be removed …
=> Improved handling of span status

sentry_sdk/tracing_utils.py
Get the client via `sentry_sdk.get_client()` instead.
Prerequisite for #3265
=> ref: Stop using `Hub` in `tracing_utils`

sentry_sdk/_types.py, sentry_sdk/integrations/sanic.py, sentry_sdk/utils.py
Previously, we defined `ExcInfo` as `tuple[Type[BaseException] | None, BaseException | None, TracebackType | None]`, when in fact, the correct type is the narrower `tuple[Type[BaseException], BaseException, TracebackType | None] | tuple[None, None, None]`.
This change makes [b0b5ecc](https://github.com/getsentry/sentry-python/pull/3264/commits/b0b5ecc28a10f43eac970a322ae314f5e898881b)  (included in #3264) possible; previously, we would have gotten a mypy error when passing the ExcInfo tuple to `logger.error`
=> ref(types): Correct `ExcInfo` type

sentry_sdk/debug.py, sentry_sdk/hub.py, sentry_sdk/scope.py, sentry_sdk/utils.py, tests/conftest.py
=> ref: Remove Hub from `capture_internal_exception` logic

sentry_sdk/tracing.py, tests/tracing/test_deprecated.py
Rename `Transaction.finish` method's `hub` parameter to `scope` (in a backwards-compatible manner), and update the method so that it is using `Scope` API under the hood as much as possible.
Prerequisite for #3265
=> ref(tracing): Remove `Hub` in `Transaction.finish`

sentry_sdk/debug.py
Previous name said that this filter was "hub-based," when the logic in reality is not related to hubs. So, we should rename the filter to something more sensible.
=> ref(debug): Rename debug logging filter

sentry_sdk/hub.py
We don't use this function, and since it is marked as a private method, that means we can delete it.
=> ref(hub): Delete `_should_send_default_pii`

sentry_sdk/hub.py
Use `Scope` APIs only in implementation for `sentry_sdk.init`, rather than `Hub` APIs.
=> ref(init): Stop using `Hub` in `init`

sentry_sdk/profiler/transaction_profiler.py, tests/profiler/test_transaction_profiler.py
=> ref(profiling): Deprecate `hub` in `Profile`

sentry_sdk/consts.py, sentry_sdk/hub.py
The current type hint suggests that all the parameters can be passed as positional arguments, when this is not the case. Only the `dsn` can be passed as a positional argument; the rest must be passed as keyword arguments.
This PR makes the type hint reflect the reality of what parameters can be passed to `sentry_sdk.init`.
=> docs(init): Fix `sentry_sdk.init` type hint

sentry_sdk/consts.py
All the versions we now support include `inspect.getfullargspec`, so we no longer need the backwards-compatible fallback.
=> ref(consts): Remove Python 2 compatibility code

sentry_sdk/integrations/openai.py
`tiktoken.get_encoding` makes a HTTP connection if the encoding doesn't already exist.
If a user has OpenAI, sentry, and tiktoken all installed, this line would make a HTTP request at import time.
=> fix(openai): Lazy initialize tiktoken to avoid http at import time

sentry_sdk/integrations/pymongo.py, tests/integrations/pymongo/test_pymongo.py
MongoDB queries were being sent as invalid JSON, since the keys and values were surrounded by single quotes instead of double quotes. Relay cannot parse the queries unless they are sent as valid JSON. This PR converts MongoDB queries into a JSON string before sending it on the span, so that Relay may properly parse it and extract metrics.
=> feat(pymongo): Send query description as valid JSON

sentry_sdk/integrations/langchain.py, sentry_sdk/integrations/openai.py, tests/integrations/langchain/test_langchain.py, tests/integrations/openai/test_openai.py
Tiktoken encodings sometimes make network requests, or do other stateful things. We can't guarantee what happens when you call tiktoken, so let's make it explicitly opt-in to users.
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. …
=> feat(openai): Make tiktoken encoding name configurable + tiktoken usage opt-in

sentry_sdk/integrations/wsgi.py, tests/integrations/wsgi/test_wsgi.py
URLs generated using Sentry's WSGI Middleware should include SCRIPT_NAME in the event's url
Fixes https://github.com/getsentry/sentry-python/issues/2576
Noticed that the problem described in the above issue wasn't specific to Django per se but general to all WSGI applications which is why I have made modifications to the SentryWsgiMiddleware class that should resolve this issue for Django and other integrations as well. As far as I can tell this problem should not arise for ASGI applications as the root_path is accounted for.
Running the test suite on your PR might require maintainer approval. Some tests (AWS Lambda) additionally require a maintainer to add …
=> fix(wsgi): WSGI integrations respect SCRIPT_NAME env variable

sentry_sdk/__init__.py, sentry_sdk/_init_implementation.py, sentry_sdk/hub.py
Now that the `Hub`-based API is deprecated, `sentry_sdk.init` should no longer be in `hub.py`. Since it is kind of its own thing, it makes sense to implement `init` in its own file.
Closes #3233
=> ref(init): Move `sentry_sdk.init` out of `hub.py`

tests/new_scopes_compat/test_new_scopes_compat_event.py
Benefits of unhardcoding integration list and disabling auto integrations:
1. It becomes possible to successfully run tests in environments where certain extra auto integrations get enabled.
2. There is no need to update hardcoded list when new default integrations are introduced.
The origin of this change is a patch that I had to apply while packaging for Fedora: https://src.fedoraproject.org/rpms/python-sentry-sdk/blob/30f00540cd30328d578dfb84625226dcc7f28969/f/python-sentry-sdk.spec#_52 (https://src.fedoraproject.org/rpms/python-sentry-sdk/blob/30f00540cd30328d578dfb84625226dcc7f28969/f/0002-tests.test_new_scopes_compat_event-compatibility.patch). The patch was necessary because all possible optional dependencies for optional integrations are pre-installed as system packages, so that …
=> ref(tests): Unhardcode integration list

sentry_sdk/integrations/opentelemetry/potel_span_processor.py, tests/integrations/opentelemetry/test_potel.py
* spans started with sentry only
* spans started with otel only
* mixed api usage
=> Basic test cases for potel

sentry_sdk/utils.py
The `_partialmethod` attribute of methods wrapped with `partialmethod()`
was renamed to `__partialmethod__` in CPython 3.13:
https://github.com/python/cpython/pull/16600
---
Before running sensitive test suites, please carefully check the PR. Then, apply the `Trigger: tests using secrets` label. The label will …
=> fix(utils): Handle `partialmethod` in `qualname_from_function` (CPython 3.13)

sentry_sdk/utils.py, tests/test_client.py
Starting from Python 3.13, `frame.f_locals` is not `dict` anymore, but `FrameLocalsProxy`, that cannot be copied using `copy.copy()`. In Python 3.13 and later, it should be copied using a method `.copy()`. The new way of copying works the same as the old one for versions of Python prior to 3.13, according to the documentation (both copying methods produce a shallow copy).
Since Python 3.13, `FrameLocalsProxy` skips items of `locals()` that have non-`str` keys; this is a CPython implementation detail. Disable `test_non_string_variables` test on Python 3.13.
See:
https://peps.python.org/pep-0667/
https://github.com/python/cpython/issues/118921
https://github.com/python/cpython/pull/118923
https://docs.python.org/3.13/whatsnew/3.13.html#porting-to-python-3-13 …
=> fix(tests): Fix exception on copying `frame.f_locals` (Python 3.13)

sentry_sdk/integrations/strawberry.py, tests/integrations/strawberry/test_strawberry.py
The Strawberry integration is creating spans at the moment, but they're all grouped under the same `/graphql` transaction coming from the web framework integration. This has significant effect on the usefulness of tracing.
In this PR, we use the operation name to update the name of the transaction so that each unique operation becomes its own event group.
Closes https://github.com/getsentry/sentry-python/issues/3285
=> feat(strawberry): Use operation name as transaction name

tests/integrations/asyncpg/test_asyncpg.py, tests/integrations/django/myapp/settings.py, tests/integrations/django/test_basic.py
Allow passing an arbitrary port via the `SENTPY_PYTHON_TEST_POSTGRES_PORT` environmental variable.
Fedora's RPM macro `%postgresql_tests_run` which starts PostgreSQL dynamically selects PostgreSQL port to prevent start failures when running multiple PostgreSQL servers on the same default port [1].
This issue is not specific to Fedora. In case there is some application running on the same machine with port `5432` opened, such as PostgreSQL instance with the default port, this will result in failure to start the PostgreSQL server, resulting in an inability to run these tests.
This change allows running these tests in environments where PostgreSQL has a non-default port and where other applications (including a PostgreSQL instance with the default port) have opened port `5432`, while at the …
=> test: Allow passing of PostgreSQL port

sentry_sdk/scope.py
The removed `if` statement is identical to the `if` statement immediately before. It does not seem that the code before the second `if` can modify `transaction.sampled`, so it should be safe to combine the two `if` blocks into a single block under the first `if` statement.
=> ref(scope): Remove apparently unnecessary `if`

sentry_sdk/integrations/pymongo.py, tests/integrations/pymongo/test_pymongo.py
Another PR to iron out some inconsistencies between the Python and Node SDKs. OTel attaches MongoDB tags directly on the span data, rather than in the `tags` databag. This change is necessary so that Relay can parse MongoDB spans in Python for metrics extraction.
Relevant MongoDB data is set directly as span data
Relevant MongoDB data is set in the `tags` databag
=> feat(pymongo): Set MongoDB tags directly on span data

tests/test_utils.py
Use non-cached `_generate_installed_modules`, instead
=> test: fix test_installed_modules

sentry_sdk/api.py, sentry_sdk/scope.py, sentry_sdk/tracing.py
Adjust docstrings of all non-deprecated functions which take an `instrumenter` parameter to state that `instrumenter` is only meant to be used by the SDK, and that it is deprecated for client code. The docstrings also inform users that `instrumenter` will be removed in the next major release.
=> docs: Clarify that `instrumenter` is internal-only

tests/integrations/cloud_resource_context/test_cloud_resource_context.py
This test has flaked multiple times on #3311 (see [here](https://github.com/getsentry/sentry-python/actions/runs/10007814703?pr=3311))
=> test: fix flaky test

.github/ISSUE_TEMPLATE/config.yml
With the sub-issues beta, it appears that I am no longer able to open blank issues by manually editing the URL to https://github.com/getsentry/sentry-python/issues/new.
While users should, of course, be encouraged to use one of the templates, blank issues are often quite helpful for internal purposes. For example, in my experience with the Sentry CLI repo where blank issues are enabled, very few (perhaps none) of the issues from external users that I have triaged have been blank issues.
=> meta: Allow blank GitHub issues

sentry_sdk/tracing.py, sentry_sdk/tracing_utils.py, tests/tracing/test_decorator.py, tests/tracing/test_misc.py
These messages might blow up in volume, as we've observed ourselves in Sentry. This might end up clogging up users' logs and increasing their spending.
WIP: look at if there's more cases where it makes sense to lower the log level
=> ref(logging): Lower logger level for some messages

sentry_sdk/envelope.py, tests/test_basics.py
=> Gracefully fail attachment path not found case

sentry_sdk/attachments.py, sentry_sdk/scope.py
Document parameters to `sentry_sdk.Scope.add_attachment` and `sentry_sdk.attachments.Attachment`.
Also, update `add_attachment`'s type hint to match the `Attachment` constructor's hint.
Fixes: #3340
Related: getsentry/sentry-docs#10844
=> docs(attachment): Document attachment parameters

tests/integrations/celery/test_celery.py
Use `Scope.get_isolation_scope` instead.
Ref #3344
=> test(celery): Stop using `configure_scope`

sentry_sdk/api.py, tests/test_api.py, tests/test_basics.py, tests/test_client.py, tests/test_sessions.py
All usages of `sentry_sdk.push_scope` in `test_sessions.py` can be
replaced with `new_scope`.
Closes: #3345
=> test(sessions): Replace `push_scope`

tests/test_basics.py
Use `Scope.get_isolation_scope` instead.
Ref #3344
=> test(basics): Stop using `configure_scope`

tests/test_client.py
Replace the only `configure_scope` usage in `test_client.py`, which
can be replaced without defeating the test's purpose, with
`Scope.get_isolation_scope`. The other `configure_scope` calls are
made either from a test which specifically tests `configure_scope`
or from a test which is always skipped.
Closes: #3344
=> test(client): Avoid `configure_scope`

sentry_sdk/api.py, tests/test_api.py, tests/test_client.py
Although `configure_scope` was meant to be deprecated since Sentry
SDK 2.0.0, calling `configure_scope` did not raise a deprecation
warning. Now, it does.
Fixes #3346
=> fix(api): `configure_scope` deprecation warning

tests/test_basics.py
Most of the `push_scope` usages in `test_basics.py` need to stay, as
they test functionality specific to `push_scope`.
However, in `test_scope_event_processor_order`, the `push_scope` can
be replaced with `new_scope`. We make this replacement here.
Ref: #3345
=> test(basics): Replace `push_scope`

sentry_sdk/api.py, tests/test_api.py, tests/test_basics.py
Although `push_scope` was meant to be deprecated since Sentry
SDK 2.0.0, calling `push_scope` did not raise a deprecation
warning. Now, it does.
Fixes #3347
=> fix(api): `push_scope` deprecation warning

.github/workflows/test-integrations-web-frameworks-1.yml, constraints.txt, tox.ini
Workaround https://github.com/pypa/setuptools/issues/4519 by constraining `setuptools72.0.0` when installing dependencies for Django tests.
=> ci: Workaround bug preventing Django test runs

.github/PULL_REQUEST_TEMPLATE.md
Moved the maintainer part to the [wiki](https://github.com/getsentry/sentry-python/wiki/AWS-Lambda-test-suite).
=> meta: Slim down PR template

README.md
See preview at https://github.com/getsentry/sentry-python/tree/ivana/readme-image (scroll down to the readme) or here:
=> meta: Use new image in readme

sentry_sdk/api.py, sentry_sdk/tracing.py
This is branched off of `ivana/potel/start-span` and rebased on latest `potel-base`. I added commit 971642baa382f5ff673a2b6fb51a370964f8e1fe to (hopefully) fix `start_transaction`.
=> Fixing `start_transaction`

sentry_sdk/api.py, sentry_sdk/integrations/opentelemetry/__init__.py, sentry_sdk/integrations/opentelemetry/consts.py, sentry_sdk/integrations/opentelemetry/contextvars_context.py, sentry_sdk/integrations/opentelemetry/integration.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/scope.py, tests/conftest.py, tests/integrations/opentelemetry/test_potel.py
* New `PotelScope` inherits from scope and reads the scope from the otel context key `SENTRY_SCOPES_KEY`
* New `isolation_scope` and `new_scope` context managers just use the context manager forking and yield with the scopes living on the above context key
* isolation scope forking is done with the `SENTRY_FORK_ISOLATION_SCOPE_KEY` boolean context key
=> New Scope implementation based on OTel Context

docs/api.rst, sentry_sdk/__init__.py, sentry_sdk/api.py, sentry_sdk/integrations/strawberry.py, tests/integrations/strawberry/test_strawberry.py, tests/new_scopes_compat/test_new_scopes_compat.py, tests/new_scopes_compat/test_new_scopes_compat_event.py, tests/test_api.py, tests/test_client.py
Also, remove any tests for `sentry_sdk.configure_scope`.
Since Strawberry's deprecated [Sentry tracing extensions](https://strawberry.rocks/docs/extensions/sentry-tracing) import `sentry_sdk.configure_scope`, importing `strawberry.extensions.tracing.SentryTracingExtension` (or `SentryTracingExtensionSync`) will result in an unhandled exception. Therefore, these imports, and any functionality associated with them, have also been removed. This itself is not a breaking change, as it is necessitated by the removal of `sentry_sdk.configure_scope`.
BREAKING CHANGE: Remove `sentry_sdk.configure_scope`.
Closes: #3402
=> feat(api): Remove `sentry_sdk.configure_scope`

sentry_sdk/client.py, sentry_sdk/integrations/pure_eval.py, sentry_sdk/scope.py, sentry_sdk/serializer.py, sentry_sdk/utils.py, tests/test_scrubber.py
Since we added the `recursive` option for the `EventScrubber` in #2755, vars nested inside could be replaced with `AnnotatedValue` and potentially break userland code.
We really shouldn't be holding references to `frame.f_locals` throughout our SDK, this has all sorts of breakage potential.
This is a bit hacky, but we'll simply call `serialize` early on `vars`. I tried patching `deepcopy` in #3392  to work with our requirements, but I was simply reimplementing most of this serialize function.
Turns out @sentrivana did the same in #2117
=> Serialize vars early to avoid living references

tests/test_sessions.py
We removed this line in #3354 since it is no longer needed, but it was apparently accidentally added back in #3357.
=> test(sessions): Remove unnecessary line

sentry_sdk/transport.py, tests/test_transport.py
This change is a prerequisite for #3404.
BREAKING CHANGE: Remove `sentry_sdk.transport.HttpTransport`'s `hub_cls` attribute.
=> feat(transport): Remove `HttpTransport` `hub_cls` attribute

sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/asgi.py, sentry_sdk/integrations/wsgi.py, sentry_sdk/sessions.py, tests/test_sessions.py
Make several changes to prepare for fully removing Hubs in the next major:
- Deprecate the Hub-based `auto_session_tracking` function, replacing it with a new Scope-based function called `track_session`
- Deprecate the scope-based `auto_session_tracking_scope` in favor of the new `track_session` function
- Change usages of `auto_session_tracking_scope` to `track_sessions`. There are no usages of `auto_session_tracking` outside of tests.
- Run all tests that were previously run against `auto_session_tracking` also against the new `track_session`. Previously, `auto_session_tracking_scope` was completely untested.
Fixes #3417
=> ref(sessions): Deprecate hub-based `sessions.py` logic

sentry_sdk/integrations/opentelemetry/__init__.py, sentry_sdk/integrations/opentelemetry/span_processor.py, sentry_sdk/integrations/opentelemetry/utils.py
"Fix" some circular imports on `ivana/potel/start-span`. This is just a quick fix. We should have a look at https://github.com/getsentry/sentry-python/issues/3407 at some point.
Picking https://github.com/getsentry/sentry-python/pull/3398 apart to have nicer reviewable PRs.
=> Fix circular imports

sentry_sdk/integrations/boto3.py, sentry_sdk/scope.py, sentry_sdk/tracing_utils.py, tests/test_api.py, tests/tracing/test_misc.py
Some random small things taken out of the monster PR to make it more readable.
* remove attribute deprecated in 1.0
* split docstring
* get rid of extra import
* fix some typos
=> Random tweaks

MIGRATION_GUIDE.md
We can polish the wording/structure/split this away from the existing migration guide etc. later -- but we should already have a place to write down changes as we're making them.
=> Start a migration guide

.github/workflows/test-integrations-cloud-computing.yml, .github/workflows/test-integrations-common.yml, .github/workflows/test-integrations-data-processing.yml, .github/workflows/test-integrations-databases.yml, .github/workflows/test-integrations-miscellaneous.yml, .github/workflows/test-integrations-networking.yml, .github/workflows/test-integrations-web-frameworks-1.yml, .github/workflows/test-integrations-web-frameworks-2.yml, setup.py, tox.ini
No `opentelemetry-distro` in a compatible version for Python 3.6.
=> Drop Python 3.6

sentry_sdk/client.py, sentry_sdk/consts.py, sentry_sdk/serializer.py, sentry_sdk/utils.py, tests/test_client.py, tests/test_serializer.py
=> Expose custom_repr function that precedes safe_repr invocation in serializer

sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/integrations/opentelemetry/span_processor.py, sentry_sdk/integrations/opentelemetry/utils.py, tests/integrations/opentelemetry/test_potel.py, tests/integrations/opentelemetry/test_utils.py
The idea is that we set the origin as a span attribute [here](https://github.com/getsentry/sentry-python/blob/76ccff531e0dad86e89380a94bcc9b1676820463/sentry_sdk/tracing.py#L1279) and then we can pick it up in the span processor, so that our instrumentation (i.e., us using `start_span` in an integration with origin provided) will still give us nice origins. Same with description.
=> Extract origin from span attributes

sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/integrations/opentelemetry/utils.py
The `convert_to_otel_timestamp` func will be used in follow up PRs
=> Tweak OTel timestamp utils

MIGRATION_GUIDE.md, sentry_sdk/api.py, sentry_sdk/scope.py, sentry_sdk/tracing.py
Move span instantiation to the scope, as it was before.
This is pretty broken atm because it expects a bunch of things to be on `POTelSpan`s that are not there (yet).
=> Create spans on scope

MIGRATION_GUIDE.md, sentry_sdk/tracing.py
Add more stubs for things expected on `Span`s, fill out some existing stubs.
We will have to clean up the inline imports at some point.
Depends on the `convert_to_otel_timestamp` util added in https://github.com/getsentry/sentry-python/pull/3436/files
=> Fill out more property/method stubs

sentry_sdk/client.py, sentry_sdk/spotlight.py, sentry_sdk/utils.py, tests/test_client.py, tests/test_utils.py
Allows setting Spotlight through `$SENTRY_SPOTLIGHT` env variable.
Part of getsentry/spotlight#482
=> feat: Add SENTRY_SPOTLIGHT env variable support

sentry_sdk/api.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/integrations/wsgi.py, sentry_sdk/tracing.py
The new `continue_trace` API will no longer return a `Transaction` entity. Instead, it will simply update the propagation context and run as a contextmanager.
(TODO) It will set a remote span on the OTEL context so that it can be picked up by `start_span` later.
closes #3458
---
working flask + sqlalchemy trace
=> Implement new continue_trace and make WSGI work

sentry_sdk/tracing_utils.py, sentry_sdk/utils.py
Preparation for:
https://github.com/getsentry/sentry-python/pull/3313
Proposed in:
https://github.com/getsentry/sentry-python/pull/3313#discussion_r1704258749
Note that the `_module_in_list` function returns `False` if `name` is `None` or `items` are falsy, hence extra check before function call can be omitted to simplify code.
---
=> chore(tracing): Refactor `tracing_utils.py`

tox.ini
starlette CI is broken with
```
module 'httpx._types' has no attribute 'URLTypes' 
```
caused by this change 
github.com/encode/httpx/pull/3245
upstream discussion: https://github.com/encode/httpx/discussions/3287
=> Pin httpx till upstream gets resolved

sentry_sdk/client.py, sentry_sdk/scrubber.py, tests/integrations/django/asgi/test_asgi.py, tests/test_scrubber.py
Implements https://github.com/getsentry/rfcs/blob/main/text/0062-controlling-pii-and-credentials-in-sd-ks.md#optional-c-add-separate-security-denylist
since we have enough users asking for it now
closes #2032
=> Add separate pii_denylist to EventScrubber and run it always

sentry_sdk/tracing.py
This was meant to be used to control whether to create an active or an inactive span, but we've since changed that to be done differently (via a context manager).
=> Remove `active` flag on `POTelSpan`

sentry_sdk/client.py, sentry_sdk/integrations/__init__.py
Previously, it was only added if the experimental `otel_powered_performance` flag was on.
We need the integration to be active to set up basic things like the tracer.
=> Add `OpenTelemetryIntegration` to `DEFAULT_INTEGRATIONS`

sentry_sdk/scope.py, sentry_sdk/tracing.py
* Do not explicitly create a `new_scope` on `start_span` -- we already do this via the OTel context hook
* Deprecate `Scope.transaction` and add `Scope.root_span` instead
* Save `span` on `scope` -- a lot of code depends on the scope having a span set
=> Improve scope-span management

sentry_sdk/envelope.py
noticed this while testing potel
=> Fix data_category for sessions envelope items

sentry_sdk/integrations/opentelemetry/consts.py, sentry_sdk/tracing.py
* add name
* actually return `op` 🙈 
Note: look like this makes tests stuck?
=> Fix some properties

sentry_sdk/integrations/dramatiq.py, sentry_sdk/integrations/logging.py, sentry_sdk/profiler/continuous_profiler.py, sentry_sdk/scope.py, sentry_sdk/scrubber.py, tests/integrations/beam/test_beam.py, tests/integrations/ray/test_ray.py
More `object`s have popped up since we last cleaned this up when we dropped Python 2.7.
=> Remove obsolete object as superclass

sentry_sdk/api.py, sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/tracing.py
This commit makes incoming distributed tracing work and finishes implementing `continue_trace`
* Updates the span processor to consider remote parents as root spans
* Adds a simpler `start_span` to `POTelScope` for now that is a simplified version of the original that just creates a `POTelSpan`
* `continue_trace` now adds a fake remote `NonRecordingSpan` with the correct `trace_id`, `parent_span_id` and `parent_sampled` fields taken from the `PropagationContext`
* fix the `trace_id` and `span_id` properties on `POTelSpan`
closes #3476
=> Set the correct SpanContext in continue_trace 

sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/scope.py
- Restore previous `tracing.Scope` to keep it free from OTel
- Add basic `start_transaction` to `PotelScope`
=> Restore original scope

sentry_sdk/integrations/_asgi_common.py, sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/asgi.py, sentry_sdk/integrations/aws_lambda.py, sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/gcp.py, sentry_sdk/integrations/huey.py, sentry_sdk/integrations/ray.py, sentry_sdk/integrations/rq.py, sentry_sdk/integrations/sanic.py, sentry_sdk/integrations/tornado.py, sentry_sdk/integrations/wsgi.py
* aiohttp
* asgi
* aws_lambda
* celery
* gcp
* huey
* rq
* sanic - this uses manual enter/exit on the contextmanager so we'll have to test properly
* tornado
* ray
closes #3484
=> Update integrations with new continue_trace callback usage

sentry_sdk/integrations/strawberry.py
Update our Strawberry integration to support the latest versions of Strawberry, following upstream breaking changes which caused our tests to fail.
Closes #3490
=> feat(strawberry): Support Strawberry 0.239.2

sentry_sdk/scope.py
Fixes event processors such as WSGI request info addition.
closes #3481
=> Fix _merge_scopes to work with PotelScope

tests/integrations/bottle/test_bottle.py
The logger test never actually worked as designed (`app.logger` was never a thing). The 500 error doesn't really test any Bottle-related functionality.
=> tests: Remove broken bottle tests

MIGRATION_GUIDE.md, sentry_sdk/integrations/grpc/aio/server.py, sentry_sdk/integrations/grpc/server.py, sentry_sdk/tracing.py
* use `ReadableSpan` checks for attribute and parent access (handles the `NonRecordingSpan` case as a result)
* deleted methods `continue_from_environ`, `continue_from_headers` and `from_traceparent` from `POTelSpan`, the new interface will not support them, but we might shim them later to not break code from outside the otel stuff
* replaced `continue_from_headers` with `continue_trace` in grpc
=> Fix some methods in POTelSpan

sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/tracing.py, tests/integrations/opentelemetry/test_potel.py
* add and track underlying root span in a hidden attr `_sentry_root_otel_span` in all subsequent children spans in the span processor on start
* wrap this underlying root otel span in a `POTelSpan` to act as a proxy
* make `POTelSpan` constructor work with explicitly passed in `otel_span`
* implement `__eq__` on `POTelSpan` to make sure proxies to the same underlying `_otel_span` are considered the same
=> Add root_span implementation

sentry_sdk/scope.py, sentry_sdk/utils.py, tests/test_basics.py
- ignore errors while breadcrumb sorting
- best-effort coerce string timestamps into datetimes before sorting
Fixes https://github.com/getsentry/sentry-python/issues/3508
=> Fix breadcrumb sorting

sentry_sdk/metrics.py, sentry_sdk/tracing.py
Raise a `DeprecationWarning` on import of the `sentry_sdk.metrics` module.
Closes #3502
=> ref(metrics): Deprecate `sentry_sdk.metrics`

.github/workflows/test-integrations-ai.yml, .github/workflows/test-integrations-aws-lambda.yml, .github/workflows/test-integrations-cloud-computing.yml, .github/workflows/test-integrations-common.yml, .github/workflows/test-integrations-data-processing.yml, .github/workflows/test-integrations-databases.yml, .github/workflows/test-integrations-graphql.yml, .github/workflows/test-integrations-miscellaneous.yml, .github/workflows/test-integrations-networking.yml, .github/workflows/test-integrations-web-frameworks-1.yml, .github/workflows/test-integrations-web-frameworks-2.yml, scripts/split-tox-gh-actions/templates/test_group.jinja
The Codecov plugins somehow changing our coverage reports, which lead to incorrect coverage measurements. 
This change will disable all Codecov plugins so our uploaded coverage reports will not be altered. According to Codecov engineers, this has no downsides.
=> Update Codecov config

scripts/init_serverless_sdk.py, sentry_sdk/_compat.py, sentry_sdk/client.py, sentry_sdk/integrations/aws_lambda.py, sentry_sdk/metrics.py, sentry_sdk/profiler/transaction_profiler.py, sentry_sdk/scope.py, sentry_sdk/tracing.py, sentry_sdk/utils.py, tests/test_metrics.py
Remove compat for Python < 3.7
=> Remove 3.6 compat

sentry_sdk/integrations/django/middleware.py, tests/integrations/django/test_middleware.py
Apparently, not having the [`sync_capable`](https://docs.djangoproject.com/en/5.1/topics/http/middleware/#asynchronous-support) on the `SentryWrappingMiddleware` sometimes breaks things when we have an async-only middleware, such as [ServeStatic](https://github.com/Archmonger/ServeStatic). 
Fixes #3506
=> fix(django): Add `sync_capable` to `SentryWrappingMiddleware`

sentry_sdk/api.py, sentry_sdk/integrations/threading.py, sentry_sdk/integrations/wsgi.py
Replace usages of `use_scope`, `use_isolation_scope` with the POTel-friendly variant.
=> Use POTel `use_scope`, `use_isolation_scope`

sentry_sdk/scope.py, sentry_sdk/tracing.py, tests/tracing/test_misc.py, tests/tracing/test_span_name.py
To align our API with OpenTelementry. In OTel a span has no `description` but a `name`.
This only changes to user facing API, under the hood there is still everything using the `description`. (This will then be changed with OTel)
Docs PR: https://github.com/getsentry/sentry-docs/pull/11332
Follow up PR that should be released at the same time: https://github.com/getsentry/sentry-python/pull/3525
Fixes #3520
=> Added `name` parameter to `start_span()` and deprecated `description` parameter.

.github/workflows/ci.yml
Supersedes https://github.com/getsentry/sentry-python/pull/3381 using artifacts/merge to merge together multiple artifacts from different jobs into the single one named github.sha that craft expects.
Summarily, upload-artifact v3 is deprecated but v4 doesn't support mutating an artifact with the name name by uploading different filepaths to the same artifact. Because we need a single artifact "github.sha", we have to use actions/merge to create it. Alternatively craft could be modified but this is the easiest way forward and I like the idea of a unified artifact, it makes craft simpler.
ref: https://github.com/getsentry/craft/issues/552
=> ci: update actions/upload-artifact to v4 with merge

sentry_sdk/integrations/cohere.py, sentry_sdk/scope.py, sentry_sdk/utils.py, tests/test_basics.py, tests/test_utils.py
These tests were failing for me locally as the timestamps were without `tzinfo` and all were assumed UTC whereas my local timezone is BST at the moment.
This patch fixes the tests along with faulty/incomplete breadcrumb timestamp parsing logic on py3.7 and py3.8.
=> fix: Fix breadcrumb timestamp casting and its tests

sentry_sdk/client.py, sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/anthropic.py, sentry_sdk/integrations/atexit.py, sentry_sdk/integrations/aws_lambda.py, sentry_sdk/integrations/bottle.py, sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/cohere.py, sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/fastapi.py, sentry_sdk/integrations/flask.py, sentry_sdk/integrations/gcp.py, sentry_sdk/integrations/huggingface_hub.py, sentry_sdk/integrations/langchain.py, sentry_sdk/integrations/openai.py, sentry_sdk/integrations/pyramid.py, sentry_sdk/integrations/sanic.py, sentry_sdk/integrations/starlette.py, sentry_sdk/integrations/strawberry.py, sentry_sdk/integrations/sys_exit.py, sentry_sdk/integrations/threading.py, tests/profiler/test_continuous_profiler.py
Improve `get_integration` typing to make it clear that we return an `Optional[Integration]`. Further, add overloads to specify that when called with some integration type `I` (i.e. `I` is a subclass of `Integration`), then `get_integration` guarantees a return value of `Optional[I]`.
These changes should enhance type safety by explicitly guaranteeing the existing behavior of `get_integration`.
=> ref(client): Improve `get_integration` typing

sentry_sdk/integrations/aiohttp.py, tests/integrations/aiohttp/test_aiohttp.py
`failed_request_status_codes` allows users to specify the status codes, whose corresponding `HTTPException` types, should be reported to Sentry. By default, these include 5xx statuses, which is a change from the previous default behavior, where no `HTTPException`s would be reported to Sentry.
The status codes are only captured as errors if they are returned by raising an `HTTPException`. If a response with one of the `failed_request_status_codes` is returned, we would not report this to Sentry, as there is no exception object we can send and no easy way to create one.
Closes #3535
=> feat(aiohttp): Add `failed_request_status_codes`

tests/integrations/fastapi/test_fastapi.py, tests/integrations/starlette/test_starlette.py
We use the same parametrization for testing FastAPI's and Starlette's `failed_request_status_codes` because the `FastApiIntegration`'s constructor is the same as `StarletteIntegration`'s constructor (the former is a subclass of the latter).
Here, we refactor the test cases to define the parametrization once, then use it in both tests. This change will make some future changes simpler, since we only need to change the parameters in one place to affect the test for both frameworks.
=> test(starlette): Refactor shared test parametrization

tests/integrations/starlette/test_starlette.py
The Starlette integration tests (as well as the FastAPI integration tests, which hit the same code path as the Starlette integration) include a test where the integrations' `failed_request_status_codes` parameter is set to `[None]`. However, since the parameter is typed as `Optional[list[HttpStatusCodeRange]]`, where `HttpStatusCodeRange = Union[int, Container[int]]`, passing `[None]` for this parameter should not be allowed, per the type hint. Thus, we should not test this input, since the behavior of passing `[None]` is not, and likely should not be, defined by the API.
Depends on #3562
=> test(starlette): Remove invalid `failed_request_status_code` tests

sentry_sdk/integrations/aiohttp.py
There is no reason this constant should be part of the public API. Since no release has included this constant yet, making this constant private does not require a major version bump.
=> ref(aiohttp): Make `DEFUALT_FAILED_REQUEST_STATUS_CODES` private

sentry_sdk/integrations/__init__.py, sentry_sdk/integrations/_wsgi_common.py, sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/starlette.py, tests/integrations/fastapi/test_fastapi.py, tests/integrations/starlette/test_starlette.py
Add support to Starlette and FastApi for the new `Set[int]` API for `failed_request_status_codes` that we are using in the AIOHttp integration
=> Support new failed request status codes API in Starlette

sentry_sdk/_types.py, sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/integrations/opentelemetry/sampler.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/integrations/opentelemetry/utils.py, sentry_sdk/tracing.py
* Add parsed baggage sentry items as items on the `sampling_context.trace_state` in `continue_trace`
* Fix sampler to propagate the `trace_state` to children in both sampled and dropped cases
* make `iter_headers` work
* make `get_trace_context` work
* add `dynamic_sampling_context` in `trace_context` so that it can be picked up by the client and added in the envelope header
closes #3478, #3565
---
[Example trace using JS -> Python -> Rails](https://sentry-sdks.sentry.io/performance/trace/bdf2c2df328c4254b233270740696c0a/?node=txn-49f5b05bea31490cabc29ecde1df4d49&node=txn-2c8f4dd512364e5fae14071594b14d81&node=txn-22a631acda6f46718bde8a528d597059&project=5434472&query=http.method%3AGET&referrer=performance-transaction-summary&showTransactions=recent&source=performance_transaction_summary&st …
=> Make DSC and trace_context work for outgoing traces

.github/workflows/test-integrations-ai.yml, .github/workflows/test-integrations-cloud-computing.yml, .github/workflows/test-integrations-data-processing.yml, .github/workflows/test-integrations-databases.yml, .github/workflows/test-integrations-graphql.yml, .github/workflows/test-integrations-miscellaneous.yml, .github/workflows/test-integrations-networking.yml, .github/workflows/test-integrations-web-frameworks-1.yml, .github/workflows/test-integrations-web-frameworks-2.yml, tox.ini
Test integrations on Python 3.13 as long as the framework/library supports it.
Follow up: https://github.com/getsentry/sentry-python/issues/3582
=> Test more integrations on 3.13

sentry_sdk/tracing.py, tests/test_propagationcontext.py
The PropagationContext does not have a `dynamic_sampling_context` parameter anymore, but instead takes a `baggage`.
=> Fix PropagationContext test

requirements-testing.txt, sentry_sdk/tracing.py, tests/integrations/asyncpg/test_asyncpg.py, tests/integrations/django/test_db_query_data.py, tests/integrations/sqlalchemy/test_sqlalchemy.py
Use freezegun to create spans of a certain time duration. (avoids monkey patching the underlying otel span)
=> Fix record sql queries tests

sentry_sdk/integrations/django/__init__.py
since we already have patched a request object (both ASGI/WSGI) before arriving, we should move patched-using logic closer to where it actually being used. for minimize impact and allow ASGI functionality.
---
=> allowing ASGI to use drf_request in DjangoRequestExtractor

tests/integrations/aws_lambda/test_aws.py
AWS Lambda has changed something in their environment and now our tests can not capture events in the init phase of the Lambda function.
Will skip the test for now.
=> Skip one of the Lambda tests

requirements-aws-lambda-layer.txt
For generating the lambda layer we have a separate requirements file (Because Lambda layers for Python 3.7 do not support modern `urllib3`)
So we need to add the new dependency of `opentelemetry-distro` to this file.
=> Fix `make aws lambda layer`

sentry_sdk/tracing_utils.py, tests/test_dsc.py
In the DSC send in the envelope header for envelopes containing errors the type of `sample_rate` was `float` instead of the correct `str` type.
Fixes #3601
=> Fix type of sample_rate in DSC (and add explanatory tests)

tox.ini
No need to specify the versions for a target one by one if it's literally all the versions we support.
=> Simplify tox version spec

sentry_sdk/integrations/django/asgi.py, tests/integrations/django/asgi/test_asgi.py
The ASGI middleware already supports this, we just weren't passing the option in.
=> Add http_methods_to_capture to ASGI Django

sentry_sdk/integrations/opentelemetry/consts.py, sentry_sdk/integrations/opentelemetry/sampler.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/integrations/opentelemetry/utils.py, sentry_sdk/tracing.py
* Populates a DSC with correct values when we don't have an incoming trace.
* We rely on `trace_state.add` only adding new keys to the tracestate so these values will be populated in the first samplign decision on the root and just be propagated further.
Note that transaction name is missing here for now and will be dealt with separately as part of the transaction name PRs.
closes #3479
=> Head SDK DSC population

sentry_sdk/client.py, sentry_sdk/spotlight.py
This fixes an issue with the recent SpotlightMiddleware patch where the error triggered the page was not highlighted/opened automatically. It changes the semapics of `capture_event` and methods depending on this a bit: we now return the event_id if the error is sent to spotlight even if it was not sent upstream to Sentry servers.
=> fix: Open relevant error when SpotlightMiddleware is on

sentry_sdk/utils.py, tests/test_basics.py
Supersedes #3056
Closes #3050
---
=> feat: Add `__notes__` support

requirements-testing.txt, sentry_sdk/consts.py, sentry_sdk/transport.py, tests/integrations/aiohttp/test_aiohttp.py, tests/test_transport.py
Brotli level 4 and 5 offer comparable or better compression to GZip
level 9 (which is our default) with better performance. This patch
adds opportunistic Brotli compression at level 4 (to be conservative)
when it detects the `brotli` module is available. It also provides some
escape hatches through `transport_compression_level` and
`transport_compression_algo` experiment configs to fine tune the behavior.
In the future, we may want to bump the default level from 4 to 5 for better
compression.
=> feat: Add opportunistic Brotli compression

sentry_sdk/integrations/bottle.py, tests/integrations/bottle/test_bottle.py
=> feat(bottle): Add `failed_request_status_codes`

tests/test_basics.py
The `test_auto_enabling_integrations_catches_import_error` test case tests the same scenario, and not just for Redis.
Fixes https://github.com/getsentry/sentry-python/issues/3624
=> Remove flaky test

sentry_sdk/integrations/opentelemetry/utils.py
Set the correct span `op` for database spans, instead of the generic `"db"`.
=> Fix database span `op`.

MIGRATION_GUIDE.md, sentry_sdk/integrations/redis/utils.py, tests/integrations/redis/asyncio/test_redis_asyncio.py, tests/integrations/redis/cluster/test_redis_cluster.py, tests/integrations/redis/cluster_asyncio/test_redis_cluster_asyncio.py, tests/integrations/redis/test_redis.py, tests/integrations/redis_py_cluster_legacy/test_redis_py_cluster_legacy.py
Otel `span.set_attribute()` does not allow `dict` values, thus we change the data to be compatible
=> Fix redis pipeline commands

sentry_sdk/utils.py, tests/test_utils.py
Removing `ensure_integration_enabled_async` since there are some unresolved issues with it.
This should be ok to just remove (as opposed to deprecate) since it's only meant to be used internally.
Closes https://github.com/getsentry/sentry-python/issues/2892
=> Remove `ensure_integration_enabled_async`

tox.ini
New falcon major coming out soon. Let's prepare.
=> feat(falcon): Run test suite with Falcon 4.0.0b3

sentry_sdk/integrations/opentelemetry/sampler.py
`trace_state.add` will never overwrite existing entries -- this is good. However, everytime it bails, it logs a warning, which then shows up in breadcrumbs in tests. 
```
WARNING  opentelemetry.trace.span:span.py:308 The provided key sentry-sampled already exists.
WARNING  opentelemetry.trace.span:span.py:308 The provided key sentry-sample_rate already exists.
WARNING  opentelemetry.trace.span:span.py:308 The provided key sentry-sampled already exists.
WARNING  opentelemetry.trace.span:span.py:308 The provided key sentry-sample_rate already exists.
WARNING  opentelemetry.trace.span:span.py:308 The provided key sentry-sampled already exists.
...
```
In this PR we explicitly check before `add`ing.
=> Only `add` to trace state if key does not exist

sentry_sdk/integrations/opentelemetry/consts.py, sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/integrations/opentelemetry/utils.py, sentry_sdk/scope.py, sentry_sdk/tracing.py, tests/integrations/flask/test_flask.py
* while sending the event in the final payload, the transaction name will be picked up from the attributes `sentry.name` or fallback to the `description` when we only have otel instrumentation
* for populating DSC in the head case, we are doing a best attempt solution and fetching the transaction name/source from the current and isolation scopes
* NOTE that there are cases where this will be inaccurate if we never set the transaction name on the scope in some integration, so we will go through and fix those cases separately.
=> Make transaction names work

tox.ini
=> Test with newer Falcon version

sentry_sdk/integrations/anthropic.py, tests/integrations/anthropic/test_anthropic.py
If you've initialized Sentry with Anthropic integration, streaming responses with [tool calls](https://docs.anthropic.com/en/docs/build-with-claude/tool-use) fail. 
The reason is quite simple, the API introduced a new data model for a `ContentBlockDeltaEvent`. This new refactor was made in `0.27.0` because json was needed to be streamed back (so arguments were returned as json for tool calls, I think this was the initial reason). This introduced a new data type [InputJsonDelta](https://github.com/anthropics/anthropic-sdk-python/blob/main/src/anthropic/types/raw_content_block_delta_event.py#L13) that had it's contents in `partial_json` instead of what is currently supported `text` ([reference](https://github.com/anthropics/anthropic-sdk-python/blob/v0.25.0/src/anthropic/types/content_block_ …
=> Fix Anthropic integration when using tool calls

tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/httpx/test_httpx.py, tests/integrations/stdlib/test_httplib.py
Instead of getting span from `._span_recorder` get it from envelope.
=> Fix tests using `_span_recorder`

sentry_sdk/integrations/langchain.py
It's possible for the parent span to not have been traced (or have been GCd) so a KeyError would be raised when trying to fetch the span for the parent run_id. Now we defensively `.get()` the parent span instead of subscripting it.
=> fix(langchain): handle case when parent span wasn't traced

sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/django/templates.py, tests/integrations/django/test_basic.py, tests/integrations/django/test_cache_module.py, tests/integrations/django/test_db_query_data.py, tests/integrations/django/test_transactions.py
fixes all django tests except profiling
=> Fix Django CI

sentry_sdk/integrations/asgi.py, tests/integrations/asgi/test_asgi.py
=> Allow custom transaction names in asgi

sentry_sdk/spotlight.py, tests/integrations/django/test_basic.py
Turns out `settings.MIDDLEWARE` does not have to be a `list`. This causes issues as not all iterables support appending items to them. This PR leverages `itertools.chain` along with `type(settings.MIDDLEWARE)` to extend the middleware list while keeping its original type. It also adds a try-except block around the injection code to make sure it doesn't block anything further down in the unexpected case that it fails.
=> fix(spotlight): More defensive Django spotlight middleware injection

sentry_sdk/_compat.py, tests/test_transport.py
The `test_transport_works` test is flaking ~7 our of 10 times after adding brotli, but only on 3.6 with gevent and only in CI.
=> Fix flaky transport test

README.md
Added more approachable language and technical examples to help developers understand how to install, configure, and use the Sentry SDK for Python. Clarified instructions around integrations, migration, and contributing. Included additional resources for further learning and support.
The previous README was more formal, and this update makes it more engaging while keeping all necessary technical information intact. This change improves the developer experience by making the documentation more accessible.
=> docs(sdk): Enhance README with improved clarity and developer-friendly examples

sentry_sdk/integrations/opentelemetry/integration.py, sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/tracing.py
=> Add sentry_meta object to Span and pass it through to ReadableSpan

sentry_sdk/integrations/strawberry.py, tests/integrations/strawberry/test_strawberry.py
As suggested by @szokeasaurusrex in https://github.com/strawberry-graphql/strawberry/issues/3590, Strawberry is preparing to fully remove its deprecated `SentryTracingExtension` in favor of the integration provided by the Sentry SDK.
This PR prepares the Sentry Strawberry integration for that removal by:
- fixing that the integration would assume Strawberry is not installed if the extension cannot be imported
- making sure tests with Strawberry versions before and after the removal still work
I also checked that removing the extension does not otherwise affect the integration: The extension's sync and async variants are imported to replace them and to guess whether sync or async code is used. Both still works if the imports are defaulted to `None`.
=> fix(strawberry): prepare for upstream extension removal

sentry_sdk/integrations/opentelemetry/integration.py, sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/integrations/opentelemetry/utils.py, sentry_sdk/tracing.py
also removed the `sentry_meta` property patching and added explicit helper methods since that broke a bunch of typing
=> Use root span transaction name in populated head DSC

sentry_sdk/integrations/redis/_async_common.py, sentry_sdk/integrations/redis/_sync_common.py, sentry_sdk/integrations/redis/modules/caches.py, sentry_sdk/integrations/redis/modules/queries.py, sentry_sdk/integrations/redis/rb.py, sentry_sdk/integrations/redis/redis.py, sentry_sdk/integrations/redis/redis_cluster.py, sentry_sdk/integrations/redis/redis_py_cluster_legacy.py, sentry_sdk/integrations/redis/utils.py, sentry_sdk/tracing_utils.py, tests/integrations/redis/test_redis.py, tests/integrations/redis/test_redis_cache_module.py, tests/integrations/redis/test_redis_cache_module_async.py
This moves the creation of `redis` breadcrumbs from the `maybe_create_breadcrumbs_from_span` into the integrations. And as well fixes some span related tests by using `render_span_tree`.
=> Fix breadcrumbs in redis

sentry_sdk/integrations/asyncpg.py, tests/integrations/asyncpg/test_asyncpg.py
We can't use data stored on the span because it might be a NonRecordingSpan that doesn't carry any data.
Fixes https://github.com/getsentry/sentry-python/issues/3681
=> Fix asyncpg breadcrumbs

MIGRATION_GUIDE.md, sentry_sdk/integrations/pymongo.py, sentry_sdk/tracing.py, tests/integrations/pymongo/test_pymongo.py
Fix pymongo spans/breadcrumbs.
❗ **Important:** With this PR we're now stripping commas and equals signs from all span names because they're [not supported](https://github.com/open-telemetry/opentelemetry-python/blob/5de1ccbfe296abeb79a46d3a895eaf34a758c62d/opentelemetry-api/src/opentelemetry/trace/span.py#L28-L37) in OTel tracestate values.
=> Fix pymongo

sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/boto3.py, sentry_sdk/integrations/httpx.py, sentry_sdk/integrations/redis/_async_common.py, sentry_sdk/integrations/redis/_sync_common.py, sentry_sdk/integrations/redis/modules/caches.py, sentry_sdk/integrations/redis/modules/queries.py, sentry_sdk/integrations/redis/redis_cluster.py, sentry_sdk/integrations/stdlib.py, sentry_sdk/tracing_utils.py, tests/integrations/boto3/test_s3.py, tests/integrations/redis/test_redis.py
This moves the creation of breadcrumbs for outgoing HTTP requests from the `maybe_create_breadcrumbs_from_span` into the integrations.
=> Fix breadcrumbs in HTTP clients

tox.ini
`fakeredis` `2.26.0` [broke on Python 3.6 and 3.7](https://github.com/cunla/fakeredis-py/issues/341). A fix should be available when the next version is available.
=> ci(tox): Exclude fakeredis 2.26.0 on py3.6 and 3.7

requirements-devenv.txt
The `pytest` pin in `requirements-devenv.txt` appears to be unnecessary. Our tests anyways do not seem to respect this pin; the actual pins are defined for each environment in `tox.ini`.
ref #3035
=> build: Remove `pytest` pin in `requirements-devenv.txt`

.github/workflows/codeql-analysis.yml
This action only is triggered on PRs to `master`, but the action is required. This becomes a problem when a PR is opened against a branch other than `master` (e.g. as part of a PR tree). When the parent branch is merged to `master`, the PR's base automatically changes to `master`, but this action does not get triggered. Instead, it blocks on "Expected" and can only be run by adding commits to the branch.
Running the action on PRs against any branch should fix this.
Also, add logic to cancel in-progress workflows on pull requests (logic taken from our other actions)
=> ci: Run CodeQL action on all PRs

tox.ini
This pin appears to be unnecessary on Python 3.8+.
ref #3035
=> test(tox): Unpin pytest for Python 3.8+ common tests

tox.ini
The pin appears to be unnecessary in Python 3.8+.
ref #3035
=> test(tox): Unpin `pytest` on Python 3.8+ `gevent` tests

tests/integrations/celery/test_celery.py, tox.ini
Unpin `pytest` for Celery tests. This requires adding a placeholder test to workaround a [bug with `pytest-forked`](https://github.com/pytest-dev/pytest-forked/issues/67#issuecomment-1964718720).
ref #3035
=> test(tox): Unpin `pytest` for `celery` tests

sentry_sdk/integrations/opentelemetry/potel_span_processor.py, sentry_sdk/integrations/opentelemetry/sampler.py, sentry_sdk/integrations/opentelemetry/utils.py, sentry_sdk/tracing.py
All profiling should work now except for the `profiles_sampler` config which will be handled separately.
=> Make profiling work with potel

tests/integrations/rq/test_rq.py
=> test: Disable broken RQ test in newly-released RQ 2.0

tests/integrations/rq/test_rq.py
#3708 got auto-merged before I had the chance to remove this print statement.
=> test(rq): Remove accidentally-committed print

tox.ini
Although we run the `redis` tests on Python 3.12 and 3.13, we don't install `pytest-asyncio` on these versions. We likely should.
=> test(redis): Install `pytest-asyncio` for `redis` tests (Python 3.12-13)

sentry_sdk/profiler/utils.py, tests/integrations/django/test_basic.py
When extract frame names, we should avoid accessing the `__class__` attribute as it can be overwritten in the class implementation. In this particular instance, the `SimpleLazyObject` class in django wraps `__class__` so when it is accessed, it can cause the underlying lazy object to be evaluation unexpectedly. To avoid this, use the `type()` builtin function which cannot be overwritten and will return the correct class.
Note that this does not work with old style classes but since dropping python 2 support, we only need to consider new style classes.
=> fix(profiling): Use `type()` instead when extracting frames

.github/workflows/test-integrations-miscellaneous.yml, requirements-linting.txt, requirements-testing.txt, scripts/split-tox-gh-actions/split-tox-gh-actions.py, sentry_sdk/flag_utils.py, sentry_sdk/integrations/launchdarkly.py, sentry_sdk/integrations/openfeature.py, setup.py, tests/integrations/launchdarkly/__init__.py, tests/integrations/launchdarkly/test_launchdarkly.py, tox.ini
Ref:
- https://github.com/getsentry/team-replay/issues/492
=> feat(flags): Add LaunchDarkly Integration

sentry_sdk/transport.py
The new `HTTP2Transport` needs `httpcore` _and_ `h2` and we only checked for `httpcore`. This caused runtime errors and dropping of all events during testing as the test platform had `httpcore` installed but not `h2`. This patch adds both as conditions for the new transport implementation. Ideally, when we switch out the old transport, we'd silently check for `h2` existence only and set the `http2` option accordingly.
=> fix(http2): Check for h2 existence

tests/test_utils.py
=> test: Fix UTC assuming test

sentry_sdk/integrations/stdlib.py, tests/integrations/stdlib/test_httplib.py
If the http request times out, the http client span never gets finished. So make sure to finish it no matter what.
=> fix(tracing): End http.client span on timeout

MIGRATION_GUIDE.md, sentry_sdk/_init_implementation.py, tests/test_api.py
BREAKING CHANGE: `sentry_sdk.init` now returns `None` instead of a context manager.
Closes #3727
=> Remove init context manager

sentry_sdk/integrations/anthropic.py, sentry_sdk/tracing.py, sentry_sdk/tracing_utils.py
So we never forget to serialize the span attribute.
=> Moved `_serialize_span_attribute` into `set_attribute`

sentry_sdk/spotlight.py
This came as user feedback (getsentry/spotlight#543). Intentionally not making this part of Sentry logging as I think if one is enabling Spotlight, they should be seeing this in their logs, regardless of their SENTRY_DEBUG setting, which tends to be noisy.
=> feat(spotlight): Add info logs when Sentry is enabled

sentry_sdk/integrations/arq.py, tests/integrations/arq/test_arq.py
Fix https://github.com/getsentry/sentry-python/issues/3741
=> Fix(Arq): fix integration with Worker settings as a dict

sentry_sdk/integrations/logging.py, tests/integrations/logging/test_logging.py
add capability for the logging integration to use the parameter 'stack_info' (added in Python 3.2). When set to True the stack trace will be retrieved and properly handled.
This feature is mapped in this [issue](https://github.com/getsentry/sentry-python/issues/2804).
---
=> [issue-2804] Handle the parameter `stack_info` for the `LoggingIntegration`

sentry_sdk/integrations/huey.py, sentry_sdk/tracing.py
=> Fix Huey tests 

tests/integrations/starlette/test_starlette.py
mainly some middleware span reordering
=> Fix starlette tests

sentry_sdk/integrations/arq.py, sentry_sdk/integrations/rq.py, tests/integrations/opentelemetry/test_utils.py, tests/integrations/rq/test_rq.py
One of the tests involves traces_sampler, have not fixed that one.
=> Fix rq tests

sentry_sdk/_init_implementation.py, tests/test_api.py
It is possible to use the return value of `sentry_sdk.init` as a context manager; however, this functionality has not been maintained for a long time, and it does not seem to be documented anywhere.
So, we are deprecating this functionality, and we will remove it in the next major release.
Closes #3282
=> ref(init): Deprecate `sentry_sdk.init` context manager

sentry_sdk/spotlight.py
This patch expands the `SpotlightMiddleware` for Django and injects the Spotlight button to all HTML responses when Spotlight is enabled and running. It requires Spotlight 2.6.0 to work this way.
Ref: getsentry/spotlight#543
=> feat(spotlight): Inject Spotlight button on Django

MIGRATION_GUIDE.md, sentry_sdk/api.py, sentry_sdk/integrations/opentelemetry/consts.py, sentry_sdk/integrations/opentelemetry/sampler.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/scope.py, sentry_sdk/tracing.py, tests/tracing/test_sampling.py
- Add support for the `sampled` flag for `start_span` and respect it when making sampling decisions.
- Rework `sampling_context` in `traces_sampler` to work with span attributes instead. Make sure we still have the same data accessible as now. 
We could go one step further and change the format of `sampling_context` to just be the actual span attributes without any postprocessing into the current format. I kept the format in line with what we have now to make it easier to update.
See https://github.com/getsentry/sentry-python/issues/3746
Closes https://github.com/getsentry/sentry-python/issues/3739
This is a breaking change since we're removing `custom_sampling_context`. It'll break multiple integrations until we fix them (see https://github.com/getsentry/sentry-python/issues/3746).
=> Remove custom_sampling_context

sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/integrations/rq.py, sentry_sdk/scope.py, sentry_sdk/tracing.py, tests/conftest.py
because of #3748  span can now be an `INVALID_SPAN` we have to cleanup the fallback cases for TWP to work properly.
also:
* better potel scope cleanup for tests
* rq was propagating only for the span case and not twp, fix this
=> Cleanup `span is not None` checks for TWP

tests/integrations/aws_lambda/test_aws.py
Our AWS Lambda tests rely on outputting our events as JSON to stdout and parsing this output. AWS Lambda limits the amount of stdout it returns. 
So by reducing the size of the events we can fix the tests, that where broken by printing to much data to stdout so the output is truncated and can not be parsed into actual JSON structures again.
=> Fix AWS Lambda tests

sentry_sdk/integrations/rust_tracing.py, tests/integrations/rust_tracing/test_rust_tracing.py
this PR introduces a new integration that allows traces to descend into code in Rust native extensions by hooking into Rust's popular `tracing` framework. it relies on the Rust native extension using [`pyo3-python-tracing-subscriber`](https://crates.io/crates/pyo3-python-tracing-subscriber), a crate i recently published under Sentry, to expose a way for the Python SDK to hook into `tracing`.
in this screenshot, the transaction was started in Python but the rest of the span tree reflects the structure and performance of a naive fibonacci generator in Rust.
i have [a `sentry-docs` branch with new docs for the integration](https://github.com/matt-codecov/sentry-docs/tree/matt/python-rust-tracing-integration) pretty much ready to go. just want to get this merged and then add a working example …
=> feat: introduce rust_tracing integration

MIGRATION_GUIDE.md, tests/integrations/aiohttp/test_aiohttp.py
Remove explicit trace_id passing
=> Fix aiohttp tests

sentry_sdk/integrations/rust_tracing.py, tests/integrations/rust_tracing/test_rust_tracing.py
implemented my suggestion from https://github.com/getsentry/sentry-python/pull/3778 so that if anton agrees we can merge this before the weekend
this PR renames the `send_sensitive_data` flag to `include_tracing_fields`. the data in question is generally data the user expects `tracing` to record or data they explicitly passed into a log statement to be recorded, so if we call it "sensitive" they may think we are referring to something else
also, this PR applies the same condition to both `on_record()` and `on_new_span()`. both callbacks set the same fields, so they should either both be redacted or both be allowed. previously only `on_record()` had the condition applied.
---
Thank you for contributing to `sentry-python`! Please add tests to validate your changes, and lint your code using …
=> fix: include_tracing_fields arg to control unvetted data in rust_tracing integration

MIGRATION_GUIDE.md, sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/opentelemetry/sampler.py, tests/integrations/aiohttp/test_aiohttp.py
* can't use objects in `sampling_context` anymore, so get rid of `aiohttp_request`
* pick out meaningful properties from the AIOHTTP request and set them as span attributes (following OTel's [semconv](https://opentelemetry.io/docs/specs/semconv/http/http-spans/))
Part of https://github.com/getsentry/sentry-python/issues/3746
=> Extract span attrs from AIOHTTP request

MIGRATION_GUIDE.md, sentry_sdk/integrations/tornado.py, tests/integrations/tornado/test_tornado.py
- remove `tornado_request` from sampling context
- add span attrs instead
=> Extract span attrs from Tornado request

sentry_sdk/_init_implementation.py, sentry_sdk/integrations/aiohttp.py, tests/test_api.py, tests/test_utils.py
Tiny PR with some flake8 fixes:
- some extra imports
- testing a removed util
- ignoring `sentry_sdk/integrations/aiohttp.py:393:33: E231 missing whitespace after ':'` on this line
```python
url = f"{request.scheme}://{request.host}{request.path}"
```
🙄 
Original output:
```
linters: commands[0]> flake8 tests sentry_sdk
tests/test_utils.py:109:12: F821 undefined name 'datetime_from_isoformat'
tests/test_api.py:4:1: F401 'sentry_sdk' imported but unused
sentry_sdk/_init_implementation.py:1:1: F401 'warnings' imported but unused
sentry_sdk/integrations/aiohttp.py:393:33: E231 missing whitespace after ':'
```
=> Fix flake8

setup.py
There's an issue with `pip==24.0` where extras with an underscore in the name can't be installed, so e.g. `pip install sentry-sdk[pure_eval]` will claim there is no `pure_eval` extra.
The issue is fixed in `pip>=24.1`. Some folks are stuck using older versions though. We can fix it for them by renaming the extra to `pure-eval` instead, which makes `pip install sentry-sdk[pure-eval]` work correctly in 24.0 too. 
(The underscore version `sentry-sdk[pure_eval]` will continue to work after this change. Tested with pip and uv.)
Closes https://github.com/getsentry/sentry-python/issues/3754
=> Make sentry-sdk[pure-eval] installable with pip==24.0

sentry_sdk/integrations/django/caching.py
This patch enables `cache_spans` in Django integration automatically when Spotlight is enabled and `DEBUG` is set in Django settings.
=> feat(spotlight): Auto enable cache_spans for Spotlight on DEBUG

sentry_sdk/integrations/rq.py, tests/integrations/rq/test_rq.py
Since https://github.com/rq/rq/pull/1964 the job status is set to Failed before the handler decides whether to capture or not the exception while `handle_job_failure ` has not yet been called so the job is not yet re-scheduled leading to all exceptions getting captured in RQ version >= 2.0.
Related to #1076
Fixes #3707
=> fix(integrations): Check retries_left before capturing exception

.github/workflows/test-integrations-dbs.yml, scripts/split-tox-gh-actions/templates/test_group.jinja
The docker image name of the official Clickhouse docker image changed, so I updated our GH action that starts that docker container and reference the new version here.
---
=> Use new clickhouse gh action

pytest.ini, tests/integrations/asyncio/test_asyncio.py, tests/integrations/grpc/test_grpc_aio.py
* default `asyncio_default_fixture_loop_scope` to `function` to get rid of deprecation messages
* Change `test_asyncio.py` event loop scopes to `module` to avoid that event loop bleeding into all other tests in the same `session`.
* Remove explicit `event_loop`s since `pytest-asyncio` takes care of those
=> Fix asyncio testing setup

sentry_sdk/integrations/opentelemetry/integration.py, sentry_sdk/integrations/opentelemetry/propagator.py, sentry_sdk/integrations/opentelemetry/scope.py, tests/conftest.py, tests/integrations/stdlib/test_subprocess.py
Instead of relying on fallback behaviour, it makes sense to populate the scopes on the first context during init.
This also fixes breadcrumb leakage between httplib and subprocess tests.
=> Fix initial scope handling

tests/integrations/ray/test_ray.py
… and show that actors are not supported
---
=> Improve ray tests

tests/integrations/cohere/test_cohere.py
A few weeks ago I changed this tests to assume the second event. We since have fixed the thing that was creating this event, so we can change the test back.
=> Fix Cohere tests in potel

MIGRATION_GUIDE.md, sentry_sdk/integrations/opentelemetry/contextvars_context.py, sentry_sdk/integrations/threading.py, sentry_sdk/scope.py, sentry_sdk/tracing.py, tests/integrations/threading/test_threading.py
Since the otel context span reference is the source of truth for the current active span, we need to explicitly pass the span reference on the scope through when we use `use_scope` since we are changing context variables in the other thread.
Also,
* remove deprecated `propagate_hub` completely
* fixes some typing in the original scope
* adds more types to the `contextvars_context` manager
=> Fix threading by carrying forward span reference in `use_scope`

MIGRATION_GUIDE.md, sentry_sdk/_init_implementation.py, sentry_sdk/integrations/opentelemetry/contextvars_context.py, sentry_sdk/integrations/opentelemetry/integration.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/integrations/threading.py, sentry_sdk/scope.py, sentry_sdk/tracing.py, tests/conftest.py, tests/integrations/threading/test_threading.py, tests/test_scope.py
The scope context management init cannot be inside the integration since that would not work when we use `default_integrations=False` and other such cases.
=> Move scope context init outside integration

sentry_sdk/integrations/django/caching.py
I was testing Spotlight with Sentry and realized things started to get slow and crashy. It looks like sometimes `args` is just an empty array on cache's `_instruments_call` causing lots of exceptions being thrown. This patch fixes that with explicit length checks and also adds a note for the missing instrumentation for `get_or_set` method. This might be related to #2122 and #3300.
=> fix(django): Fix errors when instrumenting Django cache

sentry_sdk/spotlight.py
Current Spotlight error handling logic gives up sending events to Spotlight after 3 errors. This doesn't make much sense because:
1. Since there is no back off or retry mechanism, even a very brief server hiccup or restart turns off Spotlight reporting
2. Once this shut off kicks in, there is no way to turn it back on except for a server restart
I added a note for future work for retries and some short buffer.
=> fix(spotlight): Don't give up on Spotlight on 3 errors

MIGRATION_GUIDE.md, sentry_sdk/integrations/_wsgi_common.py, sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/asgi.py, sentry_sdk/integrations/aws_lambda.py, sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/gcp.py, sentry_sdk/integrations/rq.py, sentry_sdk/integrations/tornado.py, sentry_sdk/integrations/wsgi.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/asgi/test_asgi.py, tests/integrations/aws_lambda/test_aws.py, tests/integrations/celery/test_celery.py, tests/integrations/gcp/test_gcp.py, tests/integrations/rq/test_rq.py, tests/integrations/tornado/test_tornado.py, tests/integrations/wsgi/test_wsgi.py
When using `_serialize_span_attribute`, it's not guaranteed that the same kind of object will be serialized the same way. E.g. lists are sometimes serialized as lists (if they only contain one element type) but can also be serialized as strings. This makes for a really bad user interface. So just use `str` everywhere when dealing with serializing task queue `args` and `kwargs`.
Sometimes we were just silencing errors with `try...except`. In cases where this can legitimately be an SDK issue, use `capture_internal_exceptions` instead.
GH research shows some folks use headers to make sampling decisions. Add headers to span attributes.
Closes https://github.com/getsentry/sentry-python/issues/3746
=> Sampling context improvements

sentry_sdk/_lru_cache.py, tests/test_lru_cache.py
@aliu39 discovered that under certain circumstances a process can get stuck in an infinite loop.  Andrew fixed this by using `deepcopy` which prevents the infinite loop and fixes a bug where the LRU returns incorrect results.  Additionally, I've added a terminating loop in case there are any future bugs we've missed.
Closes: https://github.com/getsentry/sentry-python/issues/3862
Out of precaution, we disabled flagpole evaluation tracking Sentry while we wait for this to be merged.
=> fix(LRUCache): copy using deepcopy, and ensure the get_all function always terminates

scripts/ready_yet/requirements.txt
`pathlib` has been part of the standard library for a long time, no need to use the pypi package.
Thanks @Tenzer for [spotting this](https://github.com/getsentry/sentry-python/pull/3425#discussion_r1872767671)!
=> Use stdlib pathlib in script

sentry_sdk/spotlight.py
When we inject spotlight, we don't set the correct sidecar URL. This is an issue when a user defines a custom sidecar URL where we are able to load Spotlight UI from the correct URL but don't tell it the correct sidecar URL, making it non-functional.
=> fix(spotlight): Use the spotlight_url passed into the SDK when loading Spotlight

sentry_sdk/integrations/arq.py, sentry_sdk/tracing.py, tests/integrations/opentelemetry/test_potel.py
Make sure OK status is set, only when there has not been a error status set before.
=> Fix arq tests in POTel

sentry_sdk/integrations/ray.py, tests/integrations/ray/test_ray.py
Make sure to set the transaction name.
=> Fix ray tests in POTel

.github/workflows/test-integrations-misc.yml, requirements-linting.txt, scripts/split-tox-gh-actions/split-tox-gh-actions.py, sentry_sdk/integrations/typer.py, tests/integrations/typer/__init__.py, tests/integrations/typer/test_typer.py, tox.ini
This PR adds an integration for [Typer](https://typer.tiangolo.com/)
The integration works by mocking `typer.main.except_hook`, I was chatting with Sebastian and he's willing to add a hook in typer to avoid mocking, but I think it's also fine to keep the code as is 😊
The code is inspired by the `ExcepthookIntegration`, same thing for the test, unfortunately there's no way to test a custom except_hook with pytest, so I'm running the CLI using subprocess.
Shall I add this to the default integrations? 😊
Closes #1612
Closes #1604
=> ✨ Add Typer integration

sentry_sdk/integrations/logging.py
Without this, internal otel logs (especially `logger.exception`s) will show up as events / breadcrumbs in the payload.
=> Ignore opentelemetry logger in logging integration

sentry_sdk/integrations/arq.py, sentry_sdk/integrations/logging.py, sentry_sdk/integrations/opentelemetry/span_processor.py, tests/tracing/test_misc.py
These limits are slightly different than before because they hold on each level of the span tree rather than on the whole transaction but I think that's fine since the main purpose of these limits are avoiding unbounded memory blowup.
=> Implement span limits on span processor

.github/workflows/release-comment-issues.yml
When a release is done the Changelog will be parsed for issue numbers. Then a comment will be added to those issues that a fix has been released.
This is taken from the Javascript SDK: https://github.com/getsentry/sentry-javascript/blob/develop/.github/workflows/release-comment-issues.yml
=> Add Github workflow to comment on issues when a fix was released

sentry_sdk/integrations/launchdarkly.py, tests/integrations/launchdarkly/test_launchdarkly.py
Refactors setup code and removes an error case from the [LaunchDarkly integration](https://docs.sentry.io/platforms/python/integrations/launchdarkly/)
> register LD hook in setup instead of init
IMO we should only hook into LD once, when this integration is setup by `sentry_sdk.init`. It's rare, but this class could be instantiated more than once, from user error, tests, etc. It's reasonable to expect Sentry `init` is only called once in prod.
> don't check for initialization
We shouldn't fail if LDClient hasn't initialized yet. Initialization is the async process of connecting to the LD server, and may take a moment. With the setup code from our docs, we configure LD right before calling Sentry `init`, and don't wait for initialization to complete. **This could lead to a lot of errors / …
=> ref(flags): register LD hook in setup instead of init, and don't check for initialization

sentry_sdk/_lru_cache.py, sentry_sdk/flag_utils.py, sentry_sdk/scope.py, tests/test_lru_cache.py
- Removes manual overrides of copy behavior and leaves it up to the caller.
- E.g. a future use case may require a non-deepcopy. If we override copy they would have to remove the dunder copy, update every implementation which relies copy, before finally creating their own copy implementation.
- Deepcopies the flag buffer.
- Though we do not cache mutable references yet we may soon and so this foot gun should be removed from possibility.
- Removes "copy" test coverage from `test_lru_cache.py`. We're no longer assuming copy usage and leave it up to the caller.
- The existing test in `tests/test_scope.py` covers the cache pollution case [originally mentioned here](https://github.com/getsentry/sentry-python/issues/3852).
- The mutable cache pollution case is not covered because we do not …
=> fix: Fix cache pollution when copying mutable references

tests/integrations/launchdarkly/test_launchdarkly.py
Fixes flakes ([example](https://github.com/getsentry/sentry-python/actions/runs/12465223145/job/34790658871?pr=3887)) caused by background processes in `LDClient` trying to connect to a non-existent server (we're mocking the flag data through `TestData`).
=> fix(flags): fix/refactor flaky launchdarkly tests

sentry_sdk/integrations/arq.py
Problem:
- The ARQ integration loses `__kwdefaults__` when patching the `enqueue_job` method
- This causes issues when filtering kwargs in custom implementations
Solution:
- Save original `__kwdefaults__` before patching
- Restore them in the patched function
---
=> fix: preserve ARQ enqueue_job __kwdefaults__ after patching

.github/workflows/test-integrations-web-2.yml, tests/integrations/launchdarkly/test_launchdarkly.py, tox.ini
=> Update test matrix for Sanic

sentry_sdk/integrations/feature_flags.py, tests/integrations/feature_flags/test_feature_flags.py
Follow-up to https://github.com/getsentry/sentry-python/pull/3860, which hasn't been released yet
=> ref(flags): underscore featureflags module and identifier

CONTRIBUTING.md
=> Small contribution docs update

sentry_sdk/integrations/__init__.py, sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/anthropic.py, sentry_sdk/integrations/ariadne.py, sentry_sdk/integrations/arq.py, sentry_sdk/integrations/asyncpg.py, sentry_sdk/integrations/boto3.py, sentry_sdk/integrations/bottle.py, sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/clickhouse_driver.py, sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/falcon.py, sentry_sdk/integrations/flask.py, sentry_sdk/integrations/gql.py, sentry_sdk/integrations/graphene.py, sentry_sdk/integrations/ray.py, sentry_sdk/integrations/rq.py, sentry_sdk/integrations/sanic.py, sentry_sdk/integrations/sqlalchemy.py, sentry_sdk/integrations/strawberry.py, sentry_sdk/integrations/tornado.py
For [populating tox automatically](https://github.com/getsentry/sentry-python/issues/3808), we need to store min versions of frameworks/libraries in a programmatically accessible place.
The obvious place for this would be in each integration; however, since integrations can't be imported unless the respective framework is installed, this couldn't be used from the script (unless we'd always install all requirements of all integrations prior to running it, which takes a non trivial amount of time). So instead I've opted for a central place within `sentry_sdk/integrations/__init__.py`.
Note: the min versions probably need updating. Not sure when this was last done, but some of them look quite ancient and we probably don't support them because we'd already dropped the last Python version …
=> Centralize minimum version checking

.github/workflows/ci.yml, .github/workflows/codeql-analysis.yml, .github/workflows/enforce-license-compliance.yml, .github/workflows/test-integrations-ai.yml, .github/workflows/test-integrations-aws.yml, .github/workflows/test-integrations-cloud.yml, .github/workflows/test-integrations-common.yml, .github/workflows/test-integrations-dbs.yml, .github/workflows/test-integrations-graphql.yml, .github/workflows/test-integrations-misc.yml, .github/workflows/test-integrations-network.yml, .github/workflows/test-integrations-tasks.yml, .github/workflows/test-integrations-web-1.yml, .github/workflows/test-integrations-web-2.yml, scripts/split_tox_gh_actions/templates/base.jinja
...and remove `sentry-sdk-2.0` from the CI yamls.
In the future it probably makes sense to have these long-running feature branches have a common prefix since then we can just say `common-prefix/**` in the yamls and don't have to update them for every new long-running feature branch. Maybe `major/` or `feature/`?
=> Treat potel-base as release branch in CI

.github/workflows/test-integrations-ai.yml, .github/workflows/test-integrations-aws.yml, .github/workflows/test-integrations-cloud.yml, .github/workflows/test-integrations-common.yml, .github/workflows/test-integrations-dbs.yml, .github/workflows/test-integrations-graphql.yml, .github/workflows/test-integrations-misc.yml, .github/workflows/test-integrations-network.yml, .github/workflows/test-integrations-tasks.yml, .github/workflows/test-integrations-web-1.yml, .github/workflows/test-integrations-web-2.yml, scripts/split_tox_gh_actions/templates/test_group.jinja
python 3.7 doesnt work on ubuntu 24.04
=> Pin ubuntu to 22.04

sentry_sdk/_init_implementation.py, tests/conftest.py
The newly added feature flags add an error processor to `current_scope` in their `setup_once`. This is actually an antipattern and shouldn't be encouraged.
Either way, this PR sets up the scopes first since the integrations get setup in the `Client` and require that scope to be correct.
=> Setup scopes before client

.github/workflows/test-integrations-flags.yml, scripts/split_tox_gh_actions/split_tox_gh_actions.py
Take feature flag tests out of Misc and into their own new Flags group.
Also move Tasks down in the `GROUPS` dict do that it's alphabetized (except for misc which is at the bottom)
=> tests: Create a separate group for feature flag suites

sentry_sdk/utils.py
Be more defensive in `get_source_context`.
The current check makes no sense as we first try to decrement `tb_lineno` and then check the result against `None`: 
```python
lineno = tb_lineno - 1
if lineno is not None and abs_path:
```
So it looks like this was an oversight/got broken at some point.
Closes https://github.com/getsentry/sentry-python/issues/3924
=> Handle `None` lineno in `get_source_context`

sentry_sdk/utils.py, tests/test_utils.py
=> fix(utils): Check that `__module__` is `str`

.craft.yml, tests/integrations/aws_lambda/test_aws.py
Its time to add support for newer versions of Python to our AWS Lambda integration. 
Fixes #3946
=> Add support for Python 3.12 and 3.13 to AWS Lambda integration.

.github/workflows/test-integrations-gevent.yml, .github/workflows/test-integrations-network.yml, scripts/split_tox_gh_actions/split_tox_gh_actions.py
Same as https://github.com/getsentry/sentry-python/pull/3962, but for master
=> Split gevent tests off

LICENSE
It's 2025 now.
#skip-changelog
=> chore: Increase date range for MIT licence

sentry_sdk/api.py, sentry_sdk/client.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/integrations/opentelemetry/utils.py, sentry_sdk/scope.py, sentry_sdk/tracing.py
=> Cleanup scopes types and no-op old scope tracing methods

sentry_sdk/client.py, tests/test_client.py
The option `enable_tracing` is deprecated in favor of using `traces_sample_rate`. 
Fixes #3918
=> Deprecate `enable_tracing` option

sentry_sdk/_queue.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/huggingface_hub/test_huggingface_hub.py, tests/integrations/pymongo/test_pymongo.py
- `black==25.1.0` changed some default styles
- `pytest-aiohttp==1.1.0` removed the `loop` fixture
- `huggingface-hub==0.28.0` deprecated `InferenceClient.post` to `InferenceClient._inner_post`
- `pymongo==4.11.0` required `maxWireVersion` to be `7`
=> fix(ci): Various errors on master

sentry_sdk/integrations/_wsgi_common.py
Handles an internal error in sentry_sdk if there is an issue with parsing request.POST. See attached stack trace of this internal error that we experienced in production.
It would be better to handle this exception without request data instead of crashing and not reporting anything.
```
[sentry] ERROR: Internal error in sentry_sdk
Traceback (most recent call last):
File "/usr/src/app/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py", line 588, in parsed_body
return self.request.data
^^^^^^^^^^^^^^^^^
AttributeError: 'WSGIRequest' object has no attribute 'data'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "/usr/src/app/.venv/lib/python3.13/site-packages/sentry_sdk/integrations/django/__init__.py", …
```
=> Handle MultiPartParserError to avoid internal sentry crash

sentry_sdk/consts.py, sentry_sdk/profiler/continuous_profiler.py, sentry_sdk/scope.py, tests/profiler/test_continuous_profiler.py
This introduces a new top level setting for the continuous profiling session sample rate. The sample rate is evaluated once at the beginning and is used to determine whether or not the profiler will be run for the remainder of the process.
=> feat(profiling): Continuous profiling sample rate

sentry_sdk/tracing.py, sentry_sdk/utils.py, tests/tracing/test_integration_tests.py
We set transaction status to `internal_error` if there is an exception exiting the `start_transaction` context manager. We don't check what kind of exception it was.
Some exceptions aren't a sign of anything wrong, like `SystemExit` with a value of 0, so we shouldn't mark the transaction as failed in that case.
Closes https://github.com/getsentry/sentry-python/issues/4024
=> Don't set transaction status to error on sys.exit(0)

sentry_sdk/tracing_utils.py, tests/conftest.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/httpx/test_httpx.py, tests/integrations/requests/test_requests.py, tests/integrations/stdlib/test_httplib.py
- add logic to `maybe_create_breadcrumbs_from_span` to set the `level` of the breadcrumb to `warning` for the client error range (4xx) and to `error` for server errors (5xx)
- add functionality to the simple HTTP server that we use in some tests to respond with a specific error code
- we were (and are) still "using" `responses` in multiple places, but they're not actually active (the `activate` decorator is missing) and we're making actual requests outside -- we should clean this up
- we also can't use `responses` for stdlib/requests tests since they patch something that we patch
- add `httpx`, `stdlib`, `requests`, `aiohttp` tests for the new behavior
- restrict the `requests` tests to 3.7+ since in 3.6, the span is finished before the HTTP status is set for some reason...
Closes …
=> Set level based on status code for HTTP client breadcrumbs

requirements-linting.txt, sentry_sdk/integrations/ariadne.py, sentry_sdk/integrations/gql.py, sentry_sdk/integrations/graphene.py, sentry_sdk/integrations/strawberry.py
Looks like the new release of strawberry (0.259.0) is not compatible with our integration. Fix it.
New Strawberry version removes the `execute` and `execute_sync` functions that we were monkeypatching in favor of integrating the code directly in `Schema.execute` and `Schema.execute_sync`.
We were previously patching `execute` instead of `Schema.execute` that's calling it because that way we had access to a populated `execution_context` which contains data that we wanted to put on the event via an event processor.
We have access to the `execution_context` directly in the extension hooks Strawberry provides, so we now add the event processor there instead of monkeypatching anything.
This should also work for older Strawberry versions, so shouldn't be necessary to keep the old implementation …
=> fix(integrations): Do not patch `execute`

sentry_sdk/tracing_utils.py, tests/test_tracing_utils.py
The default `__repr__` does not show what is in the `Baggage`, making it extremely difficult to debug code involving `Baggage` objects. Add a `__repr__` which includes the serialized `Baggage` to improve debuggability.
---
=> feat(tracing): Add `__repr__` to `Baggage`

sentry_sdk/scope.py, sentry_sdk/tracing.py, sentry_sdk/tracing_utils.py, tests/integrations/stdlib/test_httplib.py, tests/test_dsc.py, tests/tracing/test_integration_tests.py, tests/tracing/test_sampling.py
- update `sample_rate` in DSC after the initial sampling decision is made
- fix some typos
Part of https://github.com/getsentry/sentry-python/issues/3999
=> Update sample rate in DSC

.github/workflows/test-integrations-flags.yml, requirements-linting.txt, scripts/populate_tox/populate_tox.py, scripts/split_tox_gh_actions/split_tox_gh_actions.py, sentry_sdk/integrations/__init__.py, sentry_sdk/integrations/statsig.py, sentry_sdk/integrations/unleash.py, setup.py, tests/integrations/statsig/__init__.py, tests/integrations/statsig/test_statsig.py, tox.ini
New integration for tracking [Statsig](https://docs.statsig.com/server/pythonSDK) ([pypi](https://pypi.org/project/statsig/)) flag evaluations, specifically the checkGate method which is used for boolean release flags. Unlike JS, there's no support for event callbacks for Statsig's server SDKs. Instead we wrap the module-level `check_gate` function.
Ref https://develop.sentry.dev/sdk/expected-features/#feature-flags
Ref 
- https://github.com/getsentry/team-replay/issues/538
=> feat(flags): add Statsig integration

tests/profiler/test_continuous_profiler.py
Not too sure what the problem is exactly but my suspicion is that the profiler runs in a separate thread and needs time to flush the chunk, the test wasn't waiting long enough.
=> tests(profiling): Reduce continuous profiling test flakiness

tests/integrations/clickhouse_driver/test_clickhouse_driver.py
We're not interested in random breadcrumbs from random logs like
```
+     {
+         'category': 'tzlocal',
+         'data': {},
+         'level': 'warning',
+         'message': '/etc/timezone is deprecated on Debian, and no longer reliable. '
+         'Ignoring.',
+         'type': 'log',
},
```
=> Fix clickhouse test

tests/integrations/stdlib/test_httplib.py
Ideally this test shouldn't even make a request anywhere but this should make it a little more stable.
This test failed 3 times on the same PR
- https://github.com/getsentry/sentry-python/actions/runs/13337072005/job/37254546574?pr=4056
- https://github.com/getsentry/sentry-python/actions/runs/13337072005/job/37254551103?pr=4056
- https://github.com/getsentry/sentry-python/actions/runs/13337072011/job/37254546356?pr=4056
=> tests(httplib): Fix flakey https test

.github/workflows/test-integrations-ai.yml, .github/workflows/test-integrations-dbs.yml, .github/workflows/test-integrations-flags.yml, .github/workflows/test-integrations-gevent.yml, .github/workflows/test-integrations-graphql.yml, .github/workflows/test-integrations-misc.yml, .github/workflows/test-integrations-network.yml, .github/workflows/test-integrations-tasks.yml, .github/workflows/test-integrations-web-1.yml, .github/workflows/test-integrations-web-2.yml, scripts/populate_tox/tox.jinja, tox.ini
closes https://github.com/getsentry/sentry-python/issues/4064
=> Sync toxgen with master

sentry_sdk/profiler/continuous_profiler.py, tests/profiler/test_continuous_profiler.py
The `start_profiler` and `stop_profiler` functions were renamed to `start_profile_session` and `stop_profile_session` respectively.
=> feat(profiling): Add new functions to start/stop continuous profiler

requirements-docs.txt
Sphinx 8.2 (see [changelog](https://www.sphinx-doc.org/en/master/changes/index.html#release-8-2-0-released-feb-18-2025)) seems to have broken our CI. Looks like an incompatibility between it and the autodoc-typehints extension, so hopefully the two catch up with one another -- I'll pin sphinx to <8.2 for now.
=> ci: Fix API doc failure in CI

.github/workflows/ci.yml, scripts/populate_tox/populate_tox.py, scripts/populate_tox/tox.jinja, tox.ini
Add `fail_on_changes` to toxgen. The idea is that the script will now have two modes:
- **Normal mode** (when `fail_on_changes` is `False`) that is used to actually generate the `tox.ini` file. This [will be](https://github.com/getsentry/sentry-python/issues/4050) run in a cron job in CI and create a PR with the updated test setup.
- The newly added **fail-on-changes mode** (when `fail_on_changes` is `True`) that is used to detect manual changes to one of the affected files without updating the rest (e.g. making a manual change to `tox.ini` without updating the `tox.jinja` template). This will be run in CI similar to the `fail_on_changes` check of `split-tox-gh-actions`.
The problem with detecting manual changes is that if we just reran the script on each PR, chances are it would pull in …
=> tests: Add `fail_on_changes` to toxgen

scripts/populate_tox/README.md, scripts/populate_tox/config.py, scripts/populate_tox/populate_tox.py, tox.ini
If a package has a prerelease of a higher version than the highest released stable version, make sure to test it, too. We consider alpha, beta, and RC releases.
Also add an option to ignore specific releases (this is related to the above since the script now pulls in two irrelevant alpha releases of starlite).
Closes https://github.com/getsentry/sentry-python/issues/4030
=> tests: Test relevant prereleases and allow to ignore releases

sentry_sdk/profiler/__init__.py
Need to export these explicitly so it can be used.
=> feat(profiling): Export start/stop profile session

sentry_sdk/scope.py
The original type hint could be understood as a one-level `dict` of `str` to `Any`, when in fact, it's a two-level dict.
=> fix(scopes): Add more typing info to Scope.update_from_kwargs's "contexts"

.github/workflows/test-integrations-dbs.yml, scripts/split_tox_gh_actions/templates/test_group.jinja
Use new version of the ClickHouse Github action. This works with newest ClickHouse and also now prints ClickHouse details.
=> Fix ClickHouse in test suite

sentry_sdk/integrations/opentelemetry/span_processor.py, sentry_sdk/tracing.py, sentry_sdk/utils.py, tests/tracing/test_integration_tests.py
Also make sure, that the span status is not set as a tag on the span. SDKs should not set tags at all by default (only users are allowed to set tags)
Fixes #4065
=> Tread `SystemExit(0)` not as a span status of 'internal_error'

sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/httpx.py, sentry_sdk/integrations/stdlib.py, sentry_sdk/utils.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/httpx/test_httpx.py, tests/integrations/requests/test_requests.py, tests/integrations/stdlib/test_httplib.py
On potel-base, we got rid of the `maybe_create_breadcrumbs` function in favor of creating breadcrumbs manually, so the new breadcrumb level logic needs to go directly in the affected integrations.
Closes https://github.com/getsentry/sentry-python/issues/4066
=> Set HTTP client breadcrumb level based on status code

sentry_sdk/tracing.py, sentry_sdk/tracing_utils.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/celery/test_celery.py, tests/integrations/httpx/test_httpx.py, tests/integrations/stdlib/test_httplib.py, tests/test_api.py, tests/test_dsc.py, tests/test_monitor.py, tests/tracing/test_integration_tests.py, tests/tracing/test_sample_rand.py, tests/tracing/test_sampling.py
Use the `sample_rand` value from an incoming trace to make sampling decisions, rather than generating a random value. When we are the head SDK starting a new trace, save our randomly-generated value as the `sample_rand`, and also change the random generation logic so that the `sample_rand` is computed deterministically based on the `trace_id`.
Depends on:
- #4040 
- #4038 
Closes #3998
---
=> feat(tracing): Use `sample_rand` for sampling decisions

sentry_sdk/scope.py, sentry_sdk/tracing.py, sentry_sdk/tracing_utils.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/celery/test_celery.py, tests/integrations/httpx/test_httpx.py, tests/integrations/stdlib/test_httplib.py, tests/test_api.py, tests/test_dsc.py, tests/test_monitor.py, tests/tracing/test_integration_tests.py, tests/tracing/test_sample_rand.py, tests/tracing/test_sample_rand_propagation.py, tests/tracing/test_sampling.py
`continue_trace` now propagates incoming `sample_rand` values to the transaction's baggage. Also, in the case where `sample_rand` is missing from the incoming trace and needs to be backfilled, this change introduces a mechanism for the backfilled value from the scope's propagation context to be propagated to the transaction's baggage.
The transaction still does not use the `sample_rand` for making sampling decisions; this PR only enables propagation. A future PR will add support for reading the incoming/backfilled `sample_rand` and for using this value to make sampling decisions.
Depends on:
- #4038 
Ref #3998
---
Running the test suite on your PR might …
=> feat(tracing): Propagate sample_rand to transaction's baggage 

sentry_sdk/integrations/httpx.py
Oversight from https://github.com/getsentry/sentry-python/pull/4090 -- forgot to update the breadcrumb level created by the async httpx client
Makes all Network tests green.
=> Fix breadcrumb level for HTTP client breadcrumbs in POTel

sentry_sdk/integrations/arq.py
Handle `None` values in arq configuration gracefully. 
Fixes #3827
Unfortunately our test setup for arq does not allow for testing `None` values in the configuration because they are changed to `[]` in the arq init code in the test suite [here](https://github.com/getsentry/sentry-python/blob/master/tests/integrations/arq/test_arq.py#L50-L51) and [here](https://github.com/getsentry/sentry-python/blob/master/tests/integrations/arq/test_arq.py#L95-L96). 
This is why I have not added additional tests for this bug fix.
=> Fixed bug when `cron_jobs` is set to `None` in arq integration

sentry_sdk/integrations/opentelemetry/span_processor.py, tests/tracing/test_misc.py
Closes https://github.com/getsentry/sentry-python/issues/4067
Possible follow-up: https://github.com/getsentry/sentry-python/issues/4103
=> Record number of dropped spans in POTel

sentry_sdk/integrations/starlette.py, tests/integrations/starlette/test_starlette.py
=> Fix FastAPI/Starlette middleware with positional arguments. 

sentry_sdk/integrations/cloud_resource_context.py
The URL that works in EC2 does not work in ECS, this can lead to the HTTP request getting stuck. 
Fixes #2376
=> Added timeout to HTTP requests in CloudResourceContextIntegration

sentry_sdk/integrations/asyncio.py
Instrumenting asyncio projects can be confusing. Here are two improvements:
- If users try to init the Sentry SDK outside of an async loop, a warning message will now printed instructing them how to correctly call init() in async envrionments. Including a link to the docs. 
- During shutdown of Python unfinished async tasks emit an error `Task was destroyed but it is pending!`. This happens if you use Sentry or not. The error message is confusing and led people to believe the Sentry instrumentation caused this problem. This is now remediated by 
- The tasks is wrapped by Sentry, but we now **set the name of the wrapped task to include the original** and (and a hint that is has been wrapped by Sentry) to show that the original task is failing, not just some Sentry task unknown to the user. …
=> Improve asyncio integration error handling.

sentry_sdk/integrations/spark/spark_driver.py, tests/integrations/spark/test_spark.py
Closes https://github.com/getsentry/sentry-python/issues/1099
=> fix(pyspark): Grab `attemptId` more defensively

tests/integrations/arq/test_arq.py
Testing if I can reproduce the behavior from https://github.com/getsentry/sentry-python/issues/2608 in CI since the test passes locally.
=> tests: Add concurrency testcase for arq

sentry_sdk/__init__.py, tests/test_import.py
=> Fix import problem in release 2.23.0

sentry_sdk/integrations/starlette.py, tests/integrations/fastapi/test_fastapi.py
In Starlette/FastAPI you're able to create subapps. When using `transaction_style="url"` in our integration, this would throw an exception because we try to access `route.path` to determine the transaction name, but `Host` routes have no `path` attribute.
Closes https://github.com/getsentry/sentry-python/issues/2631
=> Support Starlette/FastAPI `app.host`

sentry_sdk/integrations/loguru.py, tests/integrations/loguru/test_loguru.py
Loguru has two message levels `TRACE` and `SUCCESS` that are not available in Sentry breadcrumbs. This PR maps `TRACE` to `debug` and `SUCCESS` to `info` in Sentry so those breadcrumbs do not show a confusing error message in the Sentry UI.
Fixes #2759
=> Handle loguru msg levels that are not supported by Sentry

sentry_sdk/integrations/logging.py
=> style(integrations): Fix captured typo

sentry_sdk/client.py, sentry_sdk/integrations/dedupe.py, tests/test_basics.py
Imagine an app throws an exception twice, from different places. The first exception is dropped in the user's `before_send`. The second exception is not. Should the second exception appear in Sentry?
The current state is that it won't, since `DedupeIntegration` will take the first, dropped exception into account. When encountering the second exception, it'll consider it a duplicate and will drop it, even though the first exception never made it to Sentry.
In this PR, we reset `DedupeIntegration`'s `last-seen` if an event has been dropped by `before_send`, ensuring that the next exception will be reported.
Closes https://github.com/getsentry/sentry-python/issues/371
=> Reset `DedupeIntegration`'s `last-seen` if `before_send` dropped the event

sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/django/asgi.py, sentry_sdk/integrations/django/signals_handlers.py, sentry_sdk/integrations/django/templates.py, sentry_sdk/integrations/django/views.py
We're not using `@functools.wraps` in a handful of places in the Django integration, leading to the wrapped functions reporting wrong (i.e., Sentry wrapper) names when inspected.
Closes https://github.com/getsentry/sentry-python/issues/4138
=> feat(django): Use `functools.wraps` in more places

sentry_sdk/profiler/__init__.py, sentry_sdk/profiler/continuous_profiler.py
Revert back to using `start_profiler` and `stop_profiler` function names and deprecate the `*_session` ones instead.
Prior PR that introduced the change we're undoing: https://github.com/getsentry/sentry-python/pull/4056
=> feat(profiling): reverse profile_session start/stop methods deprecation

sentry_sdk/profiler/__init__.py, sentry_sdk/profiler/continuous_profiler.py, tests/profiler/test_continuous_profiler.py
Closes https://github.com/getsentry/sentry-python/issues/4163
=> Remove start/stop_profile_session in favor of start/stop_profiler

sentry_sdk/profiler/continuous_profiler.py
We're deprecating the short-lived `start_profile_session` and `stop_profile_session` functions in favor of `start_profiler` and `stop_profiler`, respectively.
The functions will be dropped in 3.x, see https://github.com/getsentry/sentry-python/pull/4170
=> chore(profiler): Add deprecation warning for session functions

tests/integrations/stdlib/test_httplib.py
The URL www.squirrelchasers.com is actually existing, so we should not access it in our tests. Hope this make the test more stable.
=> Fixed flaky test

sentry_sdk/integrations/spark/spark_driver.py
We now clear all existing breadcrumbs when a job is started. If an error happens in a job, only breadcrumbs created in this job will be shown. 
Fixes #1245.
=> Fix memory leak by not piling up breadcrumbs forever in Spark workers. 

sentry_sdk/tracing_utils.py, tests/tracing/test_sample_rand.py
`InvalidOperation` can occur when using tracing if the `Decimal` class's global context has been modified to set the precision below 6. This change fixes this bug by setting a custom context for our `quantize` call.
Fixes #4177
=> fix(tracing): Fix `InvalidOperation`

MIGRATION_GUIDE.md, sentry_sdk/client.py, sentry_sdk/consts.py, sentry_sdk/debug.py, sentry_sdk/profiler/__init__.py, sentry_sdk/profiler/continuous_profiler.py, sentry_sdk/profiler/transaction_profiler.py, sentry_sdk/tracing_utils.py, sentry_sdk/transport.py, tests/conftest.py, tests/integrations/celery/test_celery.py, tests/integrations/celery/test_update_celery_task_headers.py, tests/integrations/graphene/test_graphene.py, tests/integrations/sqlalchemy/test_sqlalchemy.py, tests/profiler/test_transaction_profiler.py, tests/test_basics.py, tests/test_client.py, tests/test_scope.py
Remove the following deprecated stuff:
- `configure_debug_hub` from `debug.py`
- exported stuff in `profiler/__init__.py` that's not part of public API and was only exported for backwards compat reasons
- support for `_experiments['profiler_mode']` and `_experiments['profiles_sample_rate']` which both have non-experimental top-level options now
- `Transport.capture_event`
- `_FunctionTransport` and support for function transports in general
- `enable_tracing`
=> chore: Drop more deprecated stuff

sentry_sdk/consts.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/scope.py, sentry_sdk/tracing.py
=> Use `warnings` module for deprecation messagse. 

sentry_sdk/envelope.py, tests/profiler/test_continuous_profiler.py
We need to send the platform as part of the headers in the chunk item-type as this is the header that relay is checking to manage rate limiting.
=> feat(profiling): add platform header to the chunk item-type in the envelope

sentry_sdk/integrations/django/__init__.py
We are seeing internal errors in the Sentry SDK if `self.request.data` fails. Specifically, it recently failed with `rest_framework.exceptions.UnsupportedMediaType: Unsupported media type "" in request.`.
This exception should not prevent sentry from reporting the original error. 
Similar to a previous fix I made https://github.com/getsentry/sentry-python/pull/4001
=> Broader except in django parsed_body

sentry_sdk/spotlight.py
The conditional early exit in `SpotlightMiddleware` may cause attribute access errors when trying to check if `_spotlight_url` is set or not. This patch sets it to `None` explicitly at class level.
=> fix: Always set _spotlight_url

tests/test_utils.py
There's a test in `test_utils.py` that flakes very often, but only on Python 3.8 and only in CI (locally it's all fine). I've tried a couple of ways to fix it but at this point it's not worth the effort, so just skipping it on 3.8.
=> Fix flaky test

sentry_sdk/scope.py
The docstring for `Scope.user` says it's deprecated in favor of `Scope.set_user()`, but there is no user-facing warning. Add one so that we can [drop the property](https://github.com/getsentry/sentry-python/pull/4193) in the next major.
=> chore: Deprecate Scope.user

.github/workflows/test-integrations-web-2.yml, scripts/populate_tox/config.py, scripts/populate_tox/populate_tox.py, scripts/populate_tox/tox.jinja, tox.ini
Remove hardcoded Litestar entries from `tox.ini`/`tox.jinja` and let `toxgen` handle it.
(the pymongo update was pulled in by rerunning the script)
=> tests: Move Litestar under toxgen

scripts/populate_tox/populate_tox.py
...also, `cohere` was in the `IGNORE` list twice, apparently.
=> toxgen: Make it clearer which suites can be migrated

sentry_sdk/_experimental_logger.py, sentry_sdk/client.py, sentry_sdk/consts.py, sentry_sdk/integrations/logging.py, tests/test_logs.py
We have integrations that make the python logger create breadcrumbs and issues. This adds a third handler which creates Sentry logs on `logger.log` statements.
Enable the logger with:
```python
...
_experiments={
"enable_sentry_logs": True
}
)
some_logger = logging.Logger("some-logger")
some_logger.info('Finished sending answer! #chunks=%s', chunks)
```
Refs #4150
=> feat(logs): Make the `logging` integration send Sentry logs

sentry_sdk/_types.py, sentry_sdk/client.py, sentry_sdk/utils.py, tests/test_basics.py
=> fix: Don't hang when capturing long stacktrace

scripts/populate_tox/config.py, tox.ini
Looks like strawberry is not compatible with the latest pydantic release (2.11.0). Restrict the version of pydantic used in strawberry tests for now.
sqlalchemy apparently released a new version which made it in by rerunning toxgen.
=> ci: Fix GraphQL failures

sentry_sdk/client.py
This patch makes Spotlight easier to setup by turning all sampling to 100% when no DSN is set and Spotlight is enabled. I consider this a non-breaking and a safe change as these only apply when no DSN is set so it should have no production or billing implications.
=> feat: Sample everything 100% w/ Spotlight & no DSN set

.github/CODEOWNERS, scripts/populate_tox/tox.jinja, tox.ini
This is breaking our test suite right now. The eco system should stabilize in the next couple of days/weeks, then we can remove the pin.
=> Pin `fakeredis` until `rq` can work with the new version

sentry_sdk/spotlight.py
Sometimes one may have Spotlight turned on in the SDK but not have the sidecar running or reachable. In that case we spam the console with every event as they fail to reach Spotlight. This patch limits the fail warnings to 3: the first 2 are actual errors and the final one is a note about shutting up.
=> feat: Do not spam sentry_sdk.warnings logger w/ Spotlight

tests/integrations/wsgi/test_wsgi.py, tests/profiler/test_continuous_profiler.py, tests/test_client.py
- function transports have been removed. removing the related test
- `profiles_sample_rate` is not experimental anymore
- `continuous_profiling_mode` has been removed so only the top level `profiler_mode` exists. (so the if is not necessary anymore)
=> Fixed some tests

sentry_sdk/integrations/logging.py, tests/test_logs.py
Currently if you do something like
```
python_logger = logging.Logger("test-logger")
python_logger.error(Exception("test exc"))
```
It will error, because Exception is not JSON serializable.
=> fix(ourlogs): Use repr instead of json for message and arguments

sentry_sdk/integrations/anthropic.py
The old functionality wouldn't re-emit the `stop` message for streaming Anthropic calls.
=> fix(ai): Do not consume anthropic streaming stop

sentry_sdk/integrations/asyncio.py
Remove the shutdown handler from the asyncio integration. It's only purpose was to log a message, but it looks like it has [unintended side effects](https://github.com/getsentry/sentry-python/issues/4234).
Closes https://github.com/getsentry/sentry-python/issues/4234
=> fix(asyncio): Remove shutdown handler

sentry_sdk/integrations/starlette.py, tests/integrations/starlette/test_starlette.py
Previously, when encountering malformed JSON in request bodies, the json() method would raise a JSONDecodeError. This change updates the method to catch the exception and return None instead, providing more consistent behavior and preventing unexpected crashes.
Added a test case to verify this error handling behavior.
=> fix: Handle JSONDecodeError gracefully in StarletteRequestExtractor

sentry_sdk/integrations/logging.py, tests/test_logs.py
resolves https://linear.app/getsentry/issue/LOGS-13
Docs: https://develop-docs-git-abhi-logs-sdk-developer-documentation.sentry.dev/sdk/telemetry/logs/#default-attributes
> If a log is generated by an SDK integration, the SDK should also set the sentry.origin attribute, as per the [Trace Origin](https://develop-docs-git-abhi-logs-sdk-developer-documentation.sentry.dev/sdk/telemetry/logs/traces/trace-origin/) documentation. It is assumed that logs without a sentry.origin attribute are manually created by the user.
=> feat(logs): Add sentry.origin attribute for log handler

sentry_sdk/tracing.py
Preparing to remove this in https://github.com/getsentry/sentry-python/pull/4201
=> chore: Deprecate `same_process_as_parent`

sentry_sdk/api.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/scope.py, sentry_sdk/tracing.py
These classes were added so that `start_transaction`'s `kwargs` would be typed.
Now that that function is deprecated, these classes are no longer needed. The types have also now diverged from the actual signature of `Span.__init__`, making their continued presence confusing
---
=> ref: Remove `SpanKwargs` and `TransactionKwargs`

MIGRATION_GUIDE.md, sentry_sdk/ai/monitoring.py, sentry_sdk/ai/utils.py, sentry_sdk/integrations/aiohttp.py, sentry_sdk/integrations/anthropic.py, sentry_sdk/integrations/boto3.py, sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/django/caching.py, sentry_sdk/integrations/django/signals_handlers.py, sentry_sdk/integrations/django/templates.py, sentry_sdk/integrations/graphene.py, sentry_sdk/integrations/grpc/aio/client.py, sentry_sdk/integrations/grpc/client.py, sentry_sdk/integrations/httpx.py, sentry_sdk/integrations/langchain.py, sentry_sdk/integrations/redis/utils.py, sentry_sdk/integrations/rust_tracing.py, sentry_sdk/integrations/socket.py, sentry_sdk/integrations/sqlalchemy.py, sentry_sdk/integrations/stdlib.py, sentry_sdk/integrations/strawberry.py, sentry_sdk/tracing.py, sentry_sdk/tracing_utils.py, tests/integrations/opentelemetry/test_potel.py, tests/test_scrubber.py, tests/tracing/test_misc.py
=> Deprecate `Span.set_data()`

sentry_sdk/api.py, sentry_sdk/integrations/opentelemetry/scope.py, sentry_sdk/scope.py, sentry_sdk/tracing.py, tests/integrations/rust_tracing/test_rust_tracing.py
BREAKING CHANGE: Remove `Span.containing_transaction`. Use `Span.root_span` instead.
Closes #4253
---
=> feat(tracing): Remove `containing_transaction`

sentry_sdk/client.py, tests/test_logs.py
Docs: https://develop-docs-git-abhi-logs-sdk-developer-documentation.sentry.dev/sdk/telemetry/logs/#default-attributes
> [BACKEND SDKS ONLY] `server.address`: The address of the server that sent the log. Equivalent to server_name we attach to errors and transactions.
`server.address` convention docs: https://getsentry.github.io/sentry-conventions/generated/attributes/server.html#serveraddress
resolves https://linear.app/getsentry/issue/LOGS-33
=> feat(logs): Add server.address to logs

sentry_sdk/client.py, tests/test_logs.py
Docs: https://develop-docs-git-abhi-logs-sdk-developer-documentation.sentry.dev/sdk/telemetry/logs/#default-attributes
> sentry.sdk.name: The name of the SDK that sent the log
> sentry.sdk.version: The version of the SDK that sent the log
convention docs:
- `sentry.sdk.name`: https://getsentry.github.io/sentry-conventions/generated/attributes/sentry.html#sentrysdkname
- `sentry.sdk.version`: https://getsentry.github.io/sentry-conventions/generated/attributes/sentry.html#sentrysdkversion
resolves https://linear.app/getsentry/issue/PY-1/
=> feat(logs): Add sdk name and version as log attributes

sentry_sdk/tracing.py
A missing `import warnings` in `tracing` is causing our linter action to fail
=> fix: Import `warnings` in `tracing`

sentry_sdk/transport.py, tests/test_transport.py
For some reason, we don't define any timeouts in our default transport(s).
With this change:
- We add a 30s total timeout for the whole connect+read cycle in the default HTTP transport
- In the experimental HTTP/2 httpcore-based transport there is no way to set a single timeout, so we set 15s each for getting a connection from the pool, connecting, writing, and reading
Backend SDKs in general set wildly different timeouts, from 30s in Go to <5s in Ruby or PHP. I went for the higher end of the range here since this is mainly meant to prevent the SDK preventing process shutdown like described in https://github.com/getsentry/sentry-python/issues/4247 -- we don't want to cut off legitimate requests that are just taking a long time. (I was considering going even higher, maybe to 60s -- but I …
=> feat(transport): Add a timeout

MIGRATION_GUIDE.md, sentry_sdk/api.py, sentry_sdk/client.py, sentry_sdk/integrations/arq.py, sentry_sdk/integrations/django/asgi.py, sentry_sdk/integrations/django/views.py, sentry_sdk/integrations/fastapi.py, sentry_sdk/integrations/huey.py, sentry_sdk/integrations/quart.py, sentry_sdk/integrations/starlette.py, sentry_sdk/scope.py, tests/test_scope.py
=> feat(scope): Replace `transaction` with `root_span`

tests/test_basics.py
These tests were causing flakes where the mock method was being called more than once. The tests were also difficult to understand.
This change removes the need for mocking (hopefully increasing test stability) and also should hopefully make it easier to understand what these tests are meant to be checking
=> test(tracing): Simplify static/classmethod tracing tests

sentry_sdk/tracing.py
This reverts commit e05ed0aa62cfe2c992b26b07c64c3148f837a609.
`same_process_as_parent` is `True` by default, so we actually don't have a way of detecting whether this was set explicitly by the user or not.
Removing the deprecation altogether -- no one's using this.
Closes https://github.com/getsentry/sentry-python/issues/4289
=> Revert "chore: Deprecate `same_process_as_parent` (#4244)"

MIGRATION_GUIDE.md, sentry_sdk/integrations/logging.py, tests/integrations/flask/test_flask.py, tests/integrations/logging/test_logging.py, tests/integrations/starlette/test_starlette.py, tests/test_logs.py, tests/test_scrubber.py
=> feat(logging): Do not capture errors from `LoggingIntegration` to Sentry by default

.github/workflows/test-integrations-ai.yml, scripts/populate_tox/populate_tox.py, tests/integrations/huggingface_hub/test_huggingface_hub.py, tox.ini
Also fixes
```
Repository Not Found for url: https://huggingface.co/api/models/some-model.
Please make sure you specified the correct `repo_id` and `repo_type`.
If you are trying to access a private or gated repo, make sure you are authenticated. For more details, see https://huggingface.co/docs/huggingface_hub/authentication
Invalid username or password.
FAILED tests/integrations/huggingface_hub/test_huggingface_hub.py::test_span_origin - huggingface_hub.errors.RepositoryNotFoundError: 401 Client Error. (Request ID: Root=1-67fe4547-10b0ce8f541a41c37ead3b2a;afe45d5d-3af1-45cd-a39a-c8ef4a5211c3)
```
which started popping up on huggingface_hub 0.30.
=> toxgen: Add huggingface_hub

sentry_sdk/tracing.py, tests/integrations/logging/test_logging.py, tests/integrations/threading/test_threading.py, tests/opentelemetry/test_compat.py
Porting stuff from master and other fixes
* add correct `event_level` to new logging tests (on `potel-base`, we don't capture logging errors by default so this has to be set explicitly)
* add compat for `start_transaction`
* re-enable an old test
**Note:** This still leaves one failing threading test, will address that separately
=> (Partially) fix POTel CI

sentry_sdk/feature_flags.py, sentry_sdk/integrations/launchdarkly.py, sentry_sdk/integrations/openfeature.py, sentry_sdk/integrations/statsig.py, sentry_sdk/integrations/unleash.py, sentry_sdk/tracing.py, tests/integrations/launchdarkly/test_launchdarkly.py, tests/integrations/openfeature/test_openfeature.py, tests/integrations/statsig/test_statsig.py, tests/integrations/unleash/test_unleash.py, tests/test_feature_flags.py
Flags evaluated within a span are appended to the span as attributes.
=> feat(spans): Record flag evaluations as span attributes

sentry_sdk/_types.py, sentry_sdk/types.py
Make types that users can use when configuring the SDK public. 
Accompaniyng docs update: https://github.com/getsentry/sentry-docs/pull/13437
Fixes #4127
=> Make all relevant types public

sentry_sdk/integrations/asgi.py, tests/integrations/asgi/test_asgi.py
fix(integrations): ASGI integration not capture transactions in Websocket
In [ASGI Specs](https://github.com/django/asgiref/blob/main/specs/www.rst#websocket-connection-scope), `method` is not in Websocket Connection Scope.
=> fix(integrations): ASGI integration not capture transactions in Websocket

scripts/populate_tox/populate_tox.py, tox.ini
Toxgen should only consider the highest patch release of each `major.minor` version. For the most part this was working fine as long as the releases were ordered as expected in PyPI, but in cases where a lower patch version succeeded a higher patch version in the release list from PyPI, we would incorrectly consider the lower patch version as well, instead of ignoring it in favor of the higher patch.
Example:
- we pull releases `[1.2.3, 1.2.4, 1.2.5, 1.2.2]` from PyPI (in that order)
- we consolidate `1.2.3, 1.2.4, 1.2.5` into one version, `1.2.5`, as expected
- `1.2.2` will not disappear into `1.2.5` because of a faulty check in toxgen and will instead be considered as a new version
- our resulting list of releases eligible for testing will be `[1.2.5, 1.2.2]` instead of just `[1.2.5]`, …
=> tests: Fix version picking in toxgen

sentry_sdk/tracing.py, sentry_sdk/tracing_utils.py, tests/tracing/test_sample_rand.py
=> Make sure to use the default decimal context in our code

sentry_sdk/integrations/huey.py, sentry_sdk/scope.py
Currently, this property has type `Any`, but it can now be changed to `Optional[Span]`
Depends on:
- #4263
=> ref(scope): Properly type `Scope.root_span`

sentry_sdk/integrations/huey.py, sentry_sdk/scope.py
=> ref: Simplify `Scope.root_span` logic

sentry_sdk/consts.py, tests/integrations/aiohttp/test_aiohttp.py, tests/integrations/asgi/test_asgi.py, tests/integrations/django/asgi/test_asgi.py, tests/integrations/django/test_basic.py, tests/integrations/wsgi/test_wsgi.py, tests/opentelemetry/test_sampler.py, tests/test_dsc.py, tests/tracing/test_trace_propagation.py
Revert changing the default of `traces_sample_rate` done in https://github.com/getsentry/sentry-python/pull/4240
=> Traces sample rate default change

tests/test_basics.py
Sometimes I see the test failing because the event contains `extras`
with `sys.argv` key in addition to `exception`. There's probably some
state leaking between tests, but regardless this patch should make the
test case slightly more robust.
Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
=> tests: fix test_stacktrace_big_recursion failure due to argv

sentry_sdk/_log_batcher.py, sentry_sdk/envelope.py, tests/test_logs.py
We've added a more efficient transport for logs handling, use that.
Solves LOGS-60
=> chore(ourlogs): Use new transport

sentry_sdk/integrations/logging.py, tests/test_logs.py
We'd like to allow linking to the 'source code' line in the logs page - this canonicalizes the path relative to the project root (if one is defined)
Solves LOGS-58
=> feat(ourlogs): canonicalize paths from the logger integration

tests/test_basics.py
In some loaded environments, the test may take slightly longer than 1s
to extract the stacktrace. This was noticed in nixpkgs build system
where the load is generally high due to high build parallelism and
resource constraints. I was sometimes getting failures because the time
it took was e.g. ~1.2s (less than current timeout of 1s).
Disclosure: we'll probably end up disabling the test in nixpkgs anyway
because we try to avoid time sensitive tests. Regardless, this bump may
help someone else in a similar situation or environment.
Signed-off-by: Ihar Hrachyshka <ihar.hrachyshka@gmail.com>
=> tests: bump test timeout for recursion stacktrace extract to 2s

.github/workflows/test-integrations-ai.yml, .github/workflows/test-integrations-misc.yml, sentry_sdk/feature_flags.py, tests/integrations/fastapi/test_fastapi.py, tests/test_feature_flags.py
Store feature flags on the isolation scope, that is the correct place. 
I also checked back with Colton about the behavior of feature flags, and having the flags on the isolation scope (meaning: one set of flags per request-response cycle) is the expected behavior.
=> Fix feature flags in potel

sentry_sdk/opentelemetry/sampler.py, sentry_sdk/scope.py, sentry_sdk/tracing_utils.py
Since we don't automatically have unsampled spans running, this caused a change in behavior when an upstream sampling decision needs to be propagated further downstream.
When an incoming trace has `sampled` set to 0 (`trace_id-span_id-0`),
in the past we would propagate this since we would have an active span/transaction running but just not sampled, so downstream would also receive `trace_id-span_id-0` from that active span.
Now, we actually don't have an active span since we don't sample (just how otel works), so instead of sending the `trace_id-span_id-0`  as before, we would have sent `trace_id-other_span_id` from the `propagation_context`  instead.
This would cause the downstream service to not receive the `-0`  flag and would thus sample independently, which is a regression.
=> Respect parent_sampled decision in propagation_context sentry-trace header

sentry_sdk/utils.py, tests/test_exceptiongroup.py
In some cases FastAPI emits an exception that has as `__cause__` an ExceptionGroup that contains a single excpetion. That single exepction is the original exception. This PR prevents an infinite loop by trying to add this construct in the `exception.values` field. 
It also introduces an hard upper limit of chained/nested transaction, to never run into an infinite loop.
=> Fix FastAPI recursive exceptions

MIGRATION_GUIDE.md, docs/api.rst, sentry_sdk/__init__.py, sentry_sdk/api.py
This PR also needs an update of the docs to make sure people use the top level API. See this docs issue: https://github.com/getsentry/sentry-docs/issues/13592
=> Add top level API for `add_atttachment`.

docs/api.rst, sentry_sdk/__init__.py, sentry_sdk/api.py
Users should not need to get the Scope and add the attachment there, we can do it for them. This has been first [implemented in SDK 3.0](https://github.com/getsentry/sentry-python/pull/4360) and is now back ported to 2.x.
=> Add `add_attachment()` top level API

docs/api.rst, sentry_sdk/__init__.py, sentry_sdk/api.py, sentry_sdk/feature_flags.py, tests/integrations/fastapi/test_fastapi.py, tests/test_feature_flags.py
Feature flags should life on the isolation Scope. This has been first [implemented in SDK 3.0](https://github.com/getsentry/sentry-python/pull/4353) and is now back ported to 2.x.
=> Put feature flags on isolation scope

requirements-docs.txt
Make apidocs buildable again -- we can investigate later if we can update something instead without needing the pin, but this is now blocking merges
=> Pin snowballstemmer for now

sentry_sdk/ai/monitoring.py, sentry_sdk/consts.py, sentry_sdk/integrations/cohere.py, sentry_sdk/integrations/huggingface_hub.py, sentry_sdk/integrations/openai.py, tests/integrations/anthropic/test_anthropic.py, tests/integrations/cohere/test_cohere.py, tests/integrations/huggingface_hub/test_huggingface_hub.py, tests/integrations/langchain/test_langchain.py, tests/integrations/openai/test_openai.py
The AI integrations sometimes used plain strings for setting `SPANDATA` attributes. Changed to always use `SPANDATA`.
=> Make use of `SPANDATA` consistent

sentry_sdk/ai/monitoring.py, sentry_sdk/consts.py, tests/integrations/anthropic/test_anthropic.py, tests/integrations/cohere/test_cohere.py, tests/integrations/huggingface_hub/test_huggingface_hub.py, tests/integrations/langchain/test_langchain.py, tests/integrations/openai/test_openai.py
Not using plain strings, but always use `SPANDATA`. Follow up to this PR: https://github.com/getsentry/sentry-python/pull/4373
=> Make use of `SPANDATA` consistent in AI integrations.`

sentry_sdk/integrations/logging.py, tests/test_logs.py
resolves https://linear.app/getsentry/issue/LOGS-101
=> feat(logs): Forward extra from logger as attributes

sentry_sdk/integrations/logging.py, sentry_sdk/logger.py, tests/test_logs.py
As per https://develop.sentry.dev/sdk/telemetry/logs/#default-attributes we should be using `sentry.message.parameter` (singular) instead of `sentry.message.parameters`. This matches how we approach the other attributes in our conventions.
=> fix(logs): Make `sentry.message.parameters` singular as per spec

sentry_sdk/integrations/celery/__init__.py, sentry_sdk/integrations/celery/beat.py, tests/integrations/celery/test_celery_beat_crons.py
When using the RedBeatScheduler, we're sending an extra in-progress check-in at scheduler start. Since this is never followed by an ok or error check-in, the check-in is marked as timed out in Sentry.
We're patching the scheduler's `maybe_due`, which (as the name implies) [might not end up executing the task](https://github.com/sibson/redbeat/blob/bdefad23b47f75e2e85d45f46f9f16dd00a93d40/redbeat/schedulers.py#L506-L508). This is indeed what seems to be happening -- `maybe_due` is run when the scheduler starts, but without scheduling the task. We don't check whether `maybe_due` actually ended up scheduling anything and always fire an in-progress check-in.
Patching the [scheduler's `apply_async`](https://github.com/sibson/redbeat/blob/bdefad23b47f75e2e85d45f46f9f16dd00a93d40/redbeat/schedule …
=> fix(celery): Do not send extra check-in

sentry_sdk/integrations/loguru.py, tests/integrations/loguru/test_loguru.py
We shouldn't have setup code in an integration's `__init__`. This can be called an arbitrary amount of times. `setup_once` exists so that the code is only guaranteed to run once.
Having integration setup in `__init__` also means that the integration currently can't be disabled via `disabled_integrations`.
Fixes https://github.com/getsentry/sentry-python/issues/4398
=> fix(loguru): Move integration setup from `__init__` to `setup_once`

sentry_sdk/logger.py, tests/test_logs.py
We need to send `warn` as the `severity_text` for warning level logs, not `warning`.
If we send `warning` it will not be recognized by the backend and the severity will show up as `UNKNOWN` in the frontend.
See screenshot for comparison of after and before.
=> fix(logs): send `severity_text`: `warn` instead of `warning`

tests/test_logs.py
When (at least) one of integrations is enabled (because some dependencies
are installed in the environment), `sentry.sdk.name` is changed from
`sentry.python` to `sentry.python.[FIRST_ENABLED_INTEGRATION]` which
makes `test_logs_attributes` fail. Prevent failure by relaxing the check.
This change is beneficial not only for packaging (this patch was required
for packaging for Fedora), but also for running tests with `pytest`
directly.
See also: https://github.com/getsentry/sentry-python/pull/4316
---
=> tests(logs): avoid failures when running with integrations enabled

tests/test_basics.py, tests/test_utils.py, tests/utils/test_contextvars.py, tests/utils/test_general.py
Fixes GH-3515
Summary:
**Before**
**After**
=> Increase test coverage

sentry_sdk/integrations/redis/_sync_common.py, sentry_sdk/integrations/redis/utils.py
This [commit](https://github.com/redis/redis-py/commit/91be4a0ff39556d5e270897740369d0b1cf9e044) in `redis-py` moved away from using the Pipeline's `command_stack` and is now using `_execution_strategy.command_queue` instead. We need to adapt to use the new command source if present.
This fixes `redis-latest` in CI.
=> fix(redis): Use `command_queue` instead of `command_stack` if available

MIGRATION_GUIDE.md, sentry_sdk/scope.py, tests/test_scope.py
We don't use the `client` parameter in the `Scope`'s constructor, perhaps we can remove it and simplify the API. It is still possible to set the client with `Scope.set_client`.
BREAKING CHANGE: `sentry_sdk.Scope` no longer has a `client` parameter.
---
=> feat(scope): Remove `client` parameter

sentry_sdk/client.py, tests/test_logs.py
ref https://github.com/getsentry/sentry-docs/pull/13974
=> fix(logs): Don't gate user behind `send_default_pii`

sentry_sdk/opentelemetry/tracing.py, sentry_sdk/tracing.py, tests/conftest.py
If a `TracerProvider` already exists, patch it. `TracerProvider` is a singleton, so if we aren't the first ones setting it up, we need to use the existing one.
In tests, reset `TracerProvider` after each test so that we start with a clean slate and it gets set up anew on init.
=> Patch `TracerProvider` if it already exists

tox.ini
(Yeah I'll automate this at some point)
=> tests: Regenerate tox

scripts/populate_tox/tox.jinja, tox.ini
New release of `tracerite` (a transitive dependency in the sanic workflow) causes [this](https://github.com/getsentry/sentry-python/actions/runs/15735197921/job/44345942053?pr=4493) to happen.
Related `tracerite` bug report: https://github.com/sanic-org/tracerite/issues/20 Once this is fixed, we can unpin.
=> fix(ci): Do not install newest tracerite

sentry_sdk/profiler/continuous_profiler.py, tests/profiler/test_continuous_profiler.py
The soft exit wasn't properly shutting down the thread if another profiler started up too quickly. This ensures it is reused if possible but is properly shutdown if needed.
Specifically, the shutdown allowed the profiler 1 cycle before actually shutting down. If another profiler is started during this cycle, it's possible the old profiler never shuts down. Resulting in multiple profilers running.
Fixes #4489
=> fix(profiling): Ensure profiler thread exits when needed

MIGRATION_GUIDE.md, sentry_sdk/consts.py, sentry_sdk/integrations/asyncpg.py, sentry_sdk/integrations/clickhouse_driver.py, sentry_sdk/integrations/django/__init__.py, sentry_sdk/integrations/pymongo.py, sentry_sdk/opentelemetry/utils.py, sentry_sdk/tracing_utils.py, tests/integrations/clickhouse_driver/test_clickhouse_driver.py, tests/integrations/django/test_basic.py, tests/integrations/django/test_db_query_data.py, tests/integrations/pymongo/test_pymongo.py, tests/integrations/sqlalchemy/test_sqlalchemy.py, tests/opentelemetry/test_utils.py
- According to our [span ops](https://develop.sentry.dev/sdk/telemetry/traces/span-operations/#database) there is no op called just `db`, but we're emitting these from django, clickhouse, asyncpg and pymongo. Changing to `db.query` instead.
- There was also a breadcrumb with type `db` that's also [officially not a supported type](https://develop.sentry.dev/sdk/data-model/event-payloads/breadcrumbs/#breadcrumb-types), changed it to `query`.
This is intentionally just on `potel-base` since it's technically a breaking change.
=> fix: Rename op `db` to `db.query`

sentry_sdk/__init__.py, sentry_sdk/api.py, tests/test_sessions.py
=> feat(sessions): Add top-level start- and end session methods

sentry_sdk/integrations/langchain.py, tests/integrations/langchain/test_langchain.py
`span_map` should be an instance variable; otherwise, separate instances of the `SentryLangchainCallback` share the same `span_map` object, which is clearly not intended here.
Also, remove the `max_span_map_size` class variable, it is always set on the instance, and so not needed.
Ref #4443
=> fix(langchain): Make `span_map` an instance variable

sentry_sdk/integrations/ray.py, tests/integrations/ray/test_ray.py
Monkey-patched implementation was passing the provided keyword arguments incorrectly due to a typo - "*kwargs" was used instead of "**kwargs" twice.
Fixed integration started hitting an assert in the Ray codebase that requires for users to use "@ray.remote" decorator either with no arguments and no parentheses, or with some of the arguments provided.
An additional wrapper function was added to support both scenarios.
---
=> fix(integrations/ray): Correctly pass keyword arguments to ray.remote function

sentry_sdk/opentelemetry/contextvars_context.py, sentry_sdk/opentelemetry/propagator.py, sentry_sdk/opentelemetry/sampler.py, sentry_sdk/opentelemetry/scope.py, sentry_sdk/opentelemetry/span_processor.py, sentry_sdk/opentelemetry/tracing.py, sentry_sdk/opentelemetry/utils.py, sentry_sdk/profiler/transaction_profiler.py, sentry_sdk/tracing_utils.py, sentry_sdk/utils.py, tests/integrations/logging/test_logging.py, tests/test_utils.py
* remove casts
* generalize `is_valid_sample_rate` to return the validated float
* added a `validate_scopes` helper method to validate the scopes entry on the context and return the narrowed type
* added a `get_typed_attribute` helper method to narrow the type on getting attributes from otel
* fix a flaky test on gevent
=> Migrate typing for opentelemetry files

scripts/populate_tox/tox.jinja, tox.ini
zope.event [released](https://pypi.org/project/zope.event/#history) a new version recently that broke our gevent ci
=> Pin zope.event

sentry_sdk/tracing.py
We currently use an `if self._ctx_token` check to determine if a span has a `_ctx_token`. However, this check is incorrect, since `_ctx_token` is only sometimes set. Furthermore, when `_ctx_token` is set, we should always have a `_ctx_token`.
Therefore, using `hasattr` is what we want.
---
=> fix(tracing): Use `hasattr` for `_ctx_token`

tests/integrations/loguru/test_loguru.py
Use inspect to dynamically compute the correct line number instead of hard coding it.
Fixes GH-4454
https://github.com/getsentry/sentry-python/issues/4454
Changed the loguru test_just_log test to use inspection logic for the line number instead of hard coding it.
=> test(loguru): Remove hardcoded line number in test_just_log

.github/workflows/test-integrations-ai.yml, scripts/populate_tox/config.py, scripts/populate_tox/tox.jinja, scripts/split_tox_gh_actions/split_tox_gh_actions.py, sentry_sdk/integrations/__init__.py, sentry_sdk/integrations/openai_agents/__init__.py, sentry_sdk/integrations/openai_agents/consts.py, sentry_sdk/integrations/openai_agents/patches/__init__.py, sentry_sdk/integrations/openai_agents/patches/agent_run.py, sentry_sdk/integrations/openai_agents/patches/models.py, sentry_sdk/integrations/openai_agents/patches/runner.py, sentry_sdk/integrations/openai_agents/patches/tools.py, sentry_sdk/integrations/openai_agents/spans/__init__.py, sentry_sdk/integrations/openai_agents/spans/agent_workflow.py, sentry_sdk/integrations/openai_agents/spans/ai_client.py, sentry_sdk/integrations/openai_agents/spans/execute_tool.py, sentry_sdk/integrations/openai_agents/spans/handoff.py, sentry_sdk/integrations/openai_agents/spans/invoke_agent.py, sentry_sdk/integrations/openai_agents/utils.py, tests/integrations/openai_agents/__init__.py, tests/integrations/openai_agents/test_openai_agents.py, tox.ini
Port the `openai-agents` integration to `potel-base`.
=> Adapt AI Agent Monitoring for potel

sentry_sdk/ai/monitoring.py, tests/integrations/anthropic/test_anthropic.py, tests/integrations/cohere/test_cohere.py, tests/integrations/huggingface_hub/test_huggingface_hub.py, tests/integrations/langchain/test_langchain.py, tests/integrations/openai/test_openai.py
Store AI token usage in `span.data` instead of deprecated `measurements`. 
In `relay` there is already code in place that copies the data from the deprecated `span.measurements` to `span.data` and uses `span.data` for calculating the cost of token usage. So this PR can be deployed in a minor without risk.
See also `relay` PR: https://github.com/getsentry/relay/pull/4768
=> Use `span.data` instead of `measurements` for token usage

sentry_sdk/consts.py, sentry_sdk/tracing.py, sentry_sdk/tracing_utils.py, tests/tracing/test_span_origin.py
Allow to turn off span creation based on span origin.
This is a nice-to-have that's useful when you're double instrumenting a library with e.g. Sentry and OpenTelemetry and you want to turn off Sentry spans. (On the OTel side you can also disable specific instrumentation. By adding the possibility to do this on the Sentry side of things, we enable users to pick whichever they prefer.)
❗ **Caveats to consider before approving this:**
- Any child spans of ignored spans will be promoted to transactions unless they have `only_if_parent=True`. (This will need to be documented in the docs.)
- It can be (mis)used for filtering out any kind of spans outside of any dual OTel/Sentry scenario, basically as a workaround for the missing `ignore_spans` option that's been requested over and over again. …
=> feat(tracing): Add option to exclude specific span origins

sentry_sdk/integrations/langchain.py, tests/integrations/langchain/test_langchain.py
While implementing #4479, I noticed that our Langchain integration lacks support for the `local_callbacks` having type `BaseCallbackManager`, which according to the type hint is possible.
This change adds support for this case.
Fixes #4537
---
=> feat(langchain): Support `BaseCallbackManager`

tests/conftest.py, tests/test_gevent.py, tests/test_transport.py
* Move `CapturingServer` to `conftest` for reuse
* Make `capturing_server` in original non-forked transport tests to be module level for faster tests
* Move `gevent` based transport tests to separate file since they still need to be forked because of the global monkeypatch 
As a result, `test_transport` now takes 13 seconds instead of almost 3 minutes.
BEFORE
```
235 passed, 384 skipped in 173.78s (0:02:53)
```
AFTER
```
235 passed in 12.69s 
```
part of #4538
=> Remove forked from test_transport, separate gevent tests and generalize capturing_server to be module level

tests/test_utils.py
The test `test_installed_modules` appears to not be all that useful.
The test exists to verify the behavior of the [`_generate_installed_modules` function](https://github.com/getsentry/sentry-python/blob/9b66f3b51502ca600554c711bc3f599c18f8f18b/sentry_sdk/utils.py#L1689). However, all the test does is essentially check the output of `_generate_installed_modules` against a refactored version of the function call itself.
In short, in its current form, the test appears to not make too much sense. As the test recently started failing, let's just delete it.
---
=> test: Remove `test_installed_modules`

requirements-testing.txt
The `pyrsistent` dependency in `requirements-testing.txt` does not appear to be used anywhere, so I removed it.
In Fedora, I maintain the [`python-pyrsistent` package](https://src.fedoraproject.org/rpms/python-pyrsistent), and [`python-sentry-sdk`](https://src.fedoraproject.org/rpms/python-sentry-sdk) is the only thing that still depends on it. Since this dependency appears to be vestigial, my goal is to remove it both upstream and downstream and then orphan `python-pyrsistent` in Fedora as an unused leaf package.
=> Remove pyrsistent from test dependencies

sentry_sdk/integrations/threading.py
Since we're using `current_thread` for `self` explicitly, we need to remove the first argument from `*a`.
This actually doesn't matter since `*a, **kw` are actually both empty but since this is the way the patch is implemented (presumably for forward compat), I don't want to change the signature.
This fixes the following warning in CI since what actually happens is this:
* `Thread.run` is being patched at each `Thread.start` (and not just once as other patches do)
* So the current thread keeps getting accumulated in `*a` giving the `TypeError` for subsequent thread runs except the first
```python
TypeError: Thread.run() takes 1 positional argument but 5 were given
tests/integrations/redis/cluster_asyncio/test_redis_cluster_asyncio.py::test_async_span_origin …
```
=> Fix threading run patch

tests/integrations/socket/test_socket.py
=> Fix socket tests to not use example.com

sentry_sdk/consts.py, sentry_sdk/integrations/openai.py, sentry_sdk/integrations/openai_agents/utils.py, sentry_sdk/utils.py, tests/integrations/openai/test_openai.py
Make sure all OpenTelemetry semantic conventions for AI clients and also the Sentry Conventions are adhered to.
Also cleans up the code a bit for better readability/maintenance.
=> Make OpenAI span data OTel compatible

sentry_sdk/ai/monitoring.py, sentry_sdk/consts.py, sentry_sdk/integrations/openai.py, sentry_sdk/integrations/openai_agents/utils.py, sentry_sdk/utils.py, tests/integrations/openai/test_openai.py
Update our OpenAI integration to support new APIs and be OTel compatible.
Contains:
- https://github.com/getsentry/sentry-python/pull/4563
- https://github.com/getsentry/sentry-python/pull/4564
- https://github.com/getsentry/sentry-python/pull/4628
=> OpenAI integration update

sentry_sdk/consts.py, tests/integrations/bottle/test_bottle.py, tests/integrations/falcon/test_falcon.py, tests/integrations/flask/test_flask.py, tests/integrations/pyramid/test_pyramid.py, tests/integrations/sqlalchemy/test_sqlalchemy.py, tests/test_client.py, tests/test_serializer.py
AI prompts/messages are potentially huge.
* raise `DEFAULT_MAX_VALUE_LENGTH` (responsible for string trimming) from 1024 to 100 000
* adapt tests (and make them more generic, without hardcoded parts, where possible)
This does not seem to affect issue grouping, see e.g. https://sentry-sdks.sentry.io/issues/6774464781/events/latest/?project=4506716433416192&query=is%3Aunresolved&referrer=latest-event
=> Considerably raise `DEFAULT_MAX_VALUE_LENGTH`

sentry_sdk/client.py, sentry_sdk/consts.py, sentry_sdk/integrations/logging.py, sentry_sdk/integrations/loguru.py, sentry_sdk/logger.py, sentry_sdk/utils.py, tests/integrations/logging/test_logging.py, tests/integrations/loguru/test_loguru.py, tests/test_logs.py
Promote `enable_logs` and `before_send_log` to regular (non-experimental) SDK options. Keep supporting the experimental versions too, for backwards compat.
Closes https://github.com/getsentry/sentry-python/issues/4641
=> Add `enable_logs`, `before_send_log` as top-level options

scripts/build_aws_lambda_layer.py, scripts/init_serverless_sdk.py, sentry_sdk/api.py, sentry_sdk/integrations/django/__init__.py, sentry_sdk/serializer.py, sentry_sdk/utils.py, tests/integrations/chalice/test_chalice.py, tests/integrations/django/test_middleware.py, tests/integrations/langchain/test_langchain.py, tests/integrations/sanic/test_sanic.py, tests/profiler/test_transaction_profiler.py, tests/test_basics.py, tests/test_client.py, tests/test_logs.py, tests/test_tracing_utils.py, tests/test_transport.py, tests/test_utils.py
Unsure if the types in `tests` are any good, but might as well make them into annotations
=> Migrate more type comments to annotations

sentry_sdk/consts.py
All `ai.*` attributes are deprecated. I also added some missing `gen_ai.*` attributes from [Sentry Conventions](https://getsentry.github.io/sentry-conventions/generated/attributes/gen_ai.html).
=> Update `gen_ai.*` and `ai.*` attributes

docs/api.rst, sentry_sdk/__init__.py, sentry_sdk/api.py, tests/tracing/test_misc.py
Manually setting data on spans for our insights modules can be made easier. This PR introduces a convenience function.
Right now users need to do some like this:
```python
span = sentry_sdk.get_current_span()
if span is not None:
span.description = f"Some {dynamic} name"
span.set_attribute("key1", "value1")
span.set_attribute("key2", "value2")
```
With this new convenience function a user can do:
```python
sentry_sdk.update_current_span(
name=f"Some {dynamic} name",
attributes={
"key1": "value1",
"key2": "value2",
},
)
=> feat(tracing): Add convenience function `update_current_span`.

sentry_sdk/integrations/clickhouse_driver.py, tests/integrations/clickhouse_driver/test_clickhouse_driver.py
Currently, the Clickhouse integration consumes any data passed as a generator when reading it for insertion as `db_params`. Instead, since generators cannot be cloned, we need to wrap the generator to add the params as we iterate over it.
Fixes #4657
---
=> fix(clickhouse): Don't eat the generator data

sentry_sdk/ai/utils.py, sentry_sdk/integrations/anthropic.py, sentry_sdk/integrations/starlite.py, tests/integrations/anthropic/test_anthropic.py
Update `AnthropicIntegration` to support Otel and Sentry AI Agents module compatible span attributes of `gen_ai.*` family.
Closes https://linear.app/getsentry/issue/TET-996/improve-integration-for-anthropic-sdk
=> feat(anthropic) Update span attributes to use `gen_ai.*` namespace instead of `ai.*`

scripts/populate_tox/tox.jinja, tox.ini
A new version of fakeredis was released which [sets a new keyword arg](https://github.com/cunla/fakeredis-py/compare/v2.30.3..v2.31.0#diff-7d354eae970f35e5aa784b88fa4d0fb98ad887adb45b5a1cba5b8df4494c9561R183) that doesn't exist in older Redis versions
=> Fix Redis CI

sentry_sdk/integrations/langchain.py
should now have everything it needs.
=> updated tool span

sentry_sdk/integrations/langchain.py
response of chat will follow soon.
=> work on chat span

sentry_sdk/transport.py, sentry_sdk/worker.py, setup.py
Add async implementation of the abstract Transport class. This transport utilizes the async task worker as well as the httpcore async functionality. 
Thread Safety: As capture_envelope is registered by the client as a callback for several background threads in the sdk, which are not running the event loop, capture_envelope in the transport is made to be thread safe and allow for execution on the event loop from other threads. The same is currently not the case for flush, as there does not seem to be a usage from background threads, however if necessary, it can also be added.
HTTP2 support: Currently not activated, but from the looks of the [httpcore docs](https://www.encode.io/httpcore/http2/) it should be as simple as setting the http2 in the init of the pool to true. This likely makes …
=> Add async transport

requirements-testing.txt, scripts/populate_tox/config.py, scripts/populate_tox/tox.jinja, sentry_sdk/api.py, sentry_sdk/client.py, sentry_sdk/consts.py, sentry_sdk/integrations/asyncio.py, sentry_sdk/transport.py, sentry_sdk/worker.py, tests/integrations/asyncio/test_asyncio.py, tests/test_client.py, tests/test_transport.py, tox.ini
Integrate the async transport with the rest of the SDK. Provide a new experimental option `transport_async` that enables the async transport if an event loop is running. Otherwise, fall back to the sync transport.
Furthermore, adapt the client to work with the async transport. To this end, flush and close were changed to be non blocking and awaitable in an async context to avoid deadlocks, however close enforces a completed flush before shutdown. As there are to my knowledge no background threads running flush/close, these methods are currently not thread-safe/loop-aware for async, which can be changed if necessary.
Atexit issue: The atexit integration used by the SDK runs after the event loop has already closed if asyncio.run() is used. This makes it impossible for the async flush to …
=> Integrate async transport with SDK

sentry_sdk/client.py, tests/test_client.py
The `attach_stacktrace` option was attaching stack traces to transactions. This is an expensive operation but the results aren't used anywhere.
=> fix(tracing): Do not attach stacktrace to transaction

sentry_sdk/integrations/clickhouse_driver.py, tests/integrations/clickhouse_driver/test_clickhouse_driver.py
we need to call the original function first for `db_params` to be correctly populated in the generator case
(see diff without whitespace)
=> Fix clickhouse logic for generator case

requirements-testing.txt, scripts/populate_tox/config.py, scripts/populate_tox/tox.jinja, sentry_sdk/api.py, sentry_sdk/client.py, sentry_sdk/consts.py, sentry_sdk/integrations/asyncio.py, sentry_sdk/transport.py, sentry_sdk/utils.py, sentry_sdk/worker.py, setup.py, tests/integrations/asyncio/test_asyncio.py, tests/test_client.py, tests/test_transport.py, tox.ini
Includes:
* this PR: new shared base class for common sync/async logic
* https://github.com/getsentry/sentry-python/pull/4580
* https://github.com/getsentry/sentry-python/pull/4591
* https://github.com/getsentry/sentry-python/pull/4614
* https://github.com/getsentry/sentry-python/pull/4615
* https://github.com/getsentry/sentry-python/pull/4700
Fixes GH-4568
=> Add experimental async transport

sentry_sdk/integrations/openai.py
The function `_new_embeddings_create_common()` creates a span context with the `with` keyword, whereas `_new_responses_create_common()` and `_new_chat_completion_common()` manually call `__enter__` and set `finish_span=True`. Reusing the same `_capture_exception()` for all scenarios caused a double-exit in `_wrap_async_embeddings_create()`, which calls `_new_embeddings_create_common()`.
Context:
- Unraisable exceptions were present in our OpenAI tests. See https://github.com/getsentry/sentry-python/issues/4723.
- Tests fail in the (draft) unraisable exception integration because of unraisable exceptions in the the OpenAI integrations: https://github.com/getsentry/sentry-python/pull/4733
=> fix(openai): Avoid double exit causing an unraisable exception

scripts/populate_tox/config.py, tox.ini
A new version of `openai`, which is a dependency of `openai_agents`, [came out an hour ago](https://pypi.org/project/openai/#history), which [broke](https://github.com/getsentry/sentry-python/actions/runs/17405958869/job/49410259073) our CI. Pinning for now.
=> Fix `openai_agents` in CI

sentry_sdk/ai/monitoring.py
The following code snippet now fails mypy: https://github.com/getsentry/sentry-python/issues/4663#issuecomment-3224040493
I followed how other functions in the SDK are typed. For example, other wrappers have the signature `(F) -> F` for a type variable `F`, although here the function can be async as well.
Closes https://github.com/getsentry/sentry-python/issues/4663
=> fix: Constrain types of ai_track decorator

sentry_sdk/tracing.py
Ref https://github.com/getsentry/sentry-python/issues/4718
Does not solve the underlying issue and might leave things in an inconsistent state, but it's still preferable to letting an error bubble up to the user.
=> Wrap span restoration in `__exit__` in `capture_internal_exceptions`

sentry_sdk/integrations/__init__.py, sentry_sdk/integrations/unraisablehook.py, tests/integrations/unraisablehook/test_unraisablehook.py, tests/test_basics.py
Closes https://github.com/getsentry/sentry-python/issues/374
Adds an uncaught exception integration, enabled by default. The integration forwards the exception to Sentry only if the exception value and stacktrace are set.
The implementation and tests are adapted from `excepthook`. Sets `sys.unraisablehook` instead of`sys.excepthook`, and changes relevant signatures and types. Compared with the `excepthook` integration, there is no `always_run` parameter. As far as I can tell the option was added to avoid excessive errors in interactive shells, which does not apply to unraisable errors.
Unlike in the `excepthook` tests, the `unraisablehook` test does not check for the presence of the local variable in the pre-context. The local variable from the `excepthook` test is not captured in an …
=> feat(integrations): Add unraisable exception integration

scripts/split_tox_gh_actions/split_tox_gh_actions.py
- actually support dashes in integration names in `tox.ini`/toxgen
- make `split_tox_gh_actions.py` actually fail if it fails to parse `tox.ini`
Context: `split_tox_gh_actions.py` was actually failing because it assumed there can't be dashes in test suite names, but since it was just printing the error instead of actually exiting with an error code, we didn't notice this in CI.
=> tests: Support dashes in test suite names

scripts/populate_tox/config.py, scripts/populate_tox/populate_tox.py, scripts/populate_tox/tox.jinja, tox.ini
Remove hardcoded arq config, generate with toxgen instead.
=> tests: Move arq under toxgen

MIGRATION_GUIDE.md, sentry_sdk/consts.py, sentry_sdk/transport.py, tests/integrations/excepthook/test_excepthook.py, tests/integrations/typer/test_typer.py, tests/test_client.py, tests/test_transport.py
Making the HTTP2 transport the default when `h2` and `httpcore` packages are installed. We've been testing this on Sentry SaaS for a while without any issues.
We should promote installing the SDK as `sentry-sdk[http2]` for this to be picked up though. Since we still have to support Python 3.7 and `h2` not being supported there, we cannot install it by default and use HTTP2 directly.
---
EDIT: please merge after potel dogfooding
=> breaking(transport): Make HTTP2Transport the default

scripts/populate_tox/config.py, tox.ini
[v1.104.2](https://github.com/openai/openai-python/releases/tag/v1.104.2) of openai added back the missing export that was causing problems for `openai_agents`, so we can remove the version pin again.
=> tests: Remove openai pin and update tox

.github/workflows/test-integrations-tasks.yml, scripts/populate_tox/config.py, scripts/populate_tox/populate_tox.py, scripts/populate_tox/tox.jinja, tox.ini
- move beam under toxgen
- lower the waiting time between pypi requests
Ref https://github.com/getsentry/sentry-python/issues/4506
=> tests: Move beam under toxgen

.github/workflows/test-integrations-dbs.yml, scripts/populate_tox/config.py, scripts/populate_tox/populate_tox.py, scripts/populate_tox/tox.jinja, tests/integrations/asyncpg/test_asyncpg.py, tox.ini
- remove hardcoded asyncpg config, let toxgen take care of generating it
- isolate DB so that multiple asyncpg test suites for different envs can run at the same time without touching the same DB
- update instructions on running the test suite locally
Ref https://github.com/getsentry/sentry-python/issues/4506
=> tests: Move asyncpg under toxgen

.github/workflows/test-integrations-web-2.yml, scripts/populate_tox/config.py, scripts/populate_tox/populate_tox.py, scripts/populate_tox/tox.jinja, tox.ini
Other updates got pulled in when regenerating the test matrix; if we merge https://github.com/getsentry/sentry-python/pull/4777 before them I can rebase this to only contain quart.
Ref https://github.com/getsentry/sentry-python/issues/4506
=> tests: Move quart under toxgen

sentry_sdk/integrations/langchain.py, tests/integrations/langchain/test_langchain.py
- Catch ImportError for `langchain.agents` if langchain is not present and set AgentExecutor to None so the rest of the logic still keeps working
- Add test for recording new OTEL-compliant data for `langchain-core`
- Verified AI Agents functionality (span generation, token accounting, etc) with `langchain-core` and `langchain-openai`
Closes TET-1126
Closes PY-1833
Closes https://github.com/getsentry/sentry-python/issues/4776
=> fix(langchain): make new langchain integration work with just langchain-core

sentry_sdk/profiler/continuous_profiler.py, tests/profiler/test_continuous_profiler.py
Re-initializing the continuous profiler should use new settings.
=> fix(profiling): Re-init continuous profiler

sentry_sdk/integrations/gql.py
gql 4.0 [changed](https://github.com/graphql-python/gql/pull/556/files) the signature of the `execute` function which we were patching. Instead of a `DocumentNode` it now gets a `GraphQLRequest` (which contains the `document` attribute with the `DocumentNode`). This means we need to update the way we're extracting additional data in the event processor.
=> feat(integrations): Support gql 4.0-style execute

.github/workflows/update-tox.yml
The toxgen PR template contains links to files in the repo, but they were broken, fixing that here.
- Please add tests to validate your changes, and lint your code using `tox -e linters`.
- Add GH Issue ID _&_ Linear ID (if applicable)
- PR title should use [conventional commit](https://develop.sentry.dev/engineering-practices/commit-messages/#type) style (`feat:`, `fix:`, `ref:`, `meta:`)
- For external contributors: [CONTRIBUTING.md](../CONTRIBUTING.md), [Sentry SDK development docs](https://develop.sentry.dev/sdk/), [Discord community](https://discord.gg/Ww9hbqr)
=> fix: Fix links to files in toxgen PRs

scripts/populate_tox/config.py, scripts/populate_tox/populate_tox.py, scripts/populate_tox/tox.jinja, tox.ini
- moved pure_eval under toxgen
Ref https://github.com/getsentry/sentry-python/issues/4506
- Please add tests to validate your changes, and lint your code using `tox -e linters`.
- Add GH Issue ID _&_ Linear ID (if applicable)
- PR title should use [conventional commit](https://develop.sentry.dev/engineering-practices/commit-messages/#type) style (`feat:`, `fix:`, `ref:`, `meta:`)
- For external contributors: [CONTRIBUTING.md](https://github.com/getsentry/sentry-python/blob/master/CONTRIBUTING.md), [Sentry SDK development docs](https://develop.sentry.dev/sdk/), [Discord community](https://discord.gg/Ww9hbqr)
=> tests: Move pure_eval under toxgen

.github/workflows/test-integrations-ai.yml, .github/workflows/test-integrations-cloud.yml, .github/workflows/test-integrations-common.yml, .github/workflows/test-integrations-dbs.yml, .github/workflows/test-integrations-flags.yml, .github/workflows/test-integrations-gevent.yml, .github/workflows/test-integrations-graphql.yml, .github/workflows/test-integrations-misc.yml, .github/workflows/test-integrations-network.yml, .github/workflows/test-integrations-tasks.yml, .github/workflows/test-integrations-web-1.yml, .github/workflows/test-integrations-web-2.yml, scripts/populate_tox/populate_tox.py, scripts/runtox.sh, scripts/split_tox_gh_actions/split_tox_gh_actions.py, scripts/split_tox_gh_actions/templates/base.jinja, scripts/split_tox_gh_actions/templates/check_required.jinja, scripts/split_tox_gh_actions/templates/test_group.jinja, tox.ini
With all eligible test suites now moved to toxgen, we can remove our old way of testing for regressions in new versions of packages.
For context, before toxgen we had two groups of test targets for each test suite: pinned and latest. Pinned targets used to be a small selection of hand-picked pinned versions of the package to test. Latest always pulled the newest release, to check for incompatibilities. There was a lot of code to cater to having these two different categories.
With the switch to toxgen, all targets are now pinned, and we make sure we pick a representative sample of versions to test against, always including the latest available version to detect regressions. I'm removing the code dealing with the `latest` group entirely, and removing references to anything `pinned` as this …
=> tests: Remove old system for checking for regressions

sentry_sdk/integrations/langchain.py, tests/integrations/langchain/test_langchain.py
- This PR makes sure we don't record tool calls as outputs in `gen_ai.chat` spans in langchain when users deselect the option to include prompts / send pii
Closes TET-1181
=> fix(langchain): don't record tool call output if not include_prompt / should_send_default_pii

sentry_sdk/integrations/openai.py
* resolves: #4853
* resolves: PY-1865
=> Don't swallow userland exceptions in openai

tests/test_logs.py
Even though we try to figure out the current release automatically if it's not provided, it can still end up being `None`. If that's the case, it won't be attached to logs. The `test_logs_attributes` test assumes there always is a release, which is incorrect.
I opted for conditionally checking for `sentry.release` in the test instead of removing the check altogether, even though the test itself is supposed to test custom user provided attributes. The reason is that there is no other generic logs test testing `sentry.release`.
Closes https://github.com/getsentry/sentry-python/issues/4878
- Please add tests to validate your changes, and lint your code using `tox -e linters`.
- Add GH Issue ID _&_ Linear ID (if applicable)
- PR title should use [conventional …
=> fix(tests): Don't assume release is set
